입찰 엔티티 및 레포지토리 추가
woowacourse-teams/2023-3-ddang pull request #119
Opened 2023-07-25 08:24 UTC by JJ503

## 📄 작업 내용 요약

입찰 엔티티 및 레포지토리 추가

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

## 📎 Issue 번호

- closed #113

2023-07-25 08:53 UTC, apptie approved these changes
잘 해주셨네요 Approve 하도록 하겠습니다 
언급해주신 TODO는 저는 충분히 설득력 있는 것 같고 나중에 회의를 따로 하면 좋을 것 같습니다

2023-07-25 08:53 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
> +    // TODO: 2023/07/25 BaseTimeEntity 사용 고려, 단 createdTime만 필요함
TODO 좋습니다

2023-07-25 08:53 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
> +    @AttributeOverride(name = "value", column = @Column(name = "price"))
이 부분 트러블슈팅 나중에 기록하셨다가 블로그로 정리해주세요

2023-07-26 08:51 UTC, swonny approved these changes
저희 서비스에 입찰 기능이 생겨 기뻐요!
TODO에 대해서는 회의 잡고 이야기해보면 좋을 것 같습니다.
필드명에 대한 간단한 리뷰 하나 남겼습니다.
고생하셨습니다👍🏻

2023-07-26 08:51 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
> +    private User user;
`user`는 타입으로 지정되어 있으니 `buyer`와 같은 네이밍으로 변경하는 것은 어떤가 건의드려봅니다!

2023-07-26 08:51 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
> +    @AttributeOverride(name = "value", column = @Column(name = "price"))
어떤 이슈가 있었는지 궁금해요!

2023-07-26 08:51 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
> +    // TODO: 2023/07/25 BaseTimeEntity 사용 고려, 단 createdTime만 필요함
쪽지 기능에서도 createdTime만 필요한 상황입니다!
TODO에 대해 회의 잡고 이야기해보면 좋을 것 같습니다.

2023-07-26 14:19 UTC, kwonyj1022 requested changes
제이미 수고하셨습니다!
createdTime을 어떻게 할지에 대한 회의를 하고 코드 변경을 해야할 것 같아 approve는 다음에 진행하도록 하겠습니다!
createdTime을 분리한다면 Bid가 BaseTimeEntity 같은 엔티티를 상속하고 있어야 하고,
createdTime 분리 없이 지금처럼 사용한다면 Bid 생성을 builder로 변경해주어야 할 것 같아서요

2023-07-26 14:19 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
> +    private LocalDateTime createdTime;
이 부분이 있는 것은 BaseTimeEntity를 상속받으면 lastModifiedTime도 생기기 때문에 createdTime만 필드로 넣은 건가요?

2023-07-26 14:19 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
> +    }
createdTime을 필드로 갖고 이렇게 생성자를 작성하게 된다면 파라미터가 4개가 되니까 저희 컨벤션에 맞게 Builder를 써야할 것 같아요!

2023-07-26 14:23 UTC, kwonyj1022 requested changes

2023-07-27 01:38 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
> +    @AttributeOverride(name = "value", column = @Column(name = "price"))
앗.... 제가 제대로 몰라서 생긴 문제였어서 좀 부끄럽네요...
간단하게 설명을 하자면 제가 처음에 `@AttributeOverride(name = "value", column = @Column(name = "price"))`를 붙이지 않았었습니다.
그런데 `@Embedded`를 통해 Price 객체를 가져와 사용하게 될 때 제가 Price 객체에 붙인 변수 이름인 price가 DB 필드 명으로 반영되지 않음을 확인했습니다. price 대신 Price 객체 내 필드명인 value가 필드 네이밍으로 지정되어 버렸거든요 🥲
그래서 `AttributeOverride`를 통해 네이밍을 꼭 지정해줘야 한다는 문제였습니다..!

2023-07-27 01:39 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
> +    private User user;
오 좋습니다!
해당 객체 내에서 user가 정확히 어떤 역할인지 잘 알 수 있을 것 같네요 👍

2023-07-27 01:48 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
> +    private User user;
buyer 대신 bidder라고 수정했는데 어떨까요?

2023-07-27 02:17 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
> +    }
오늘 회의 결과 `BaseTimeEntity`에서 `createdTime`과 `lastModifiedTime`를 분리하기로 했고 이는 따로 이슈로 만들기로 했기에 수정은 진행하지 않겠습니다!

2023-07-27 03:26 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/bid/infrastructure/persistence/JpaBidRepositoryTest.java
> +                                       .build();
회의 결과 말씀해 주신 데이터들은 nullable 하지 못하도록 하기로 결정했습니다.
그래서 추후 Auction의 특정 필드들을 nullable false로 변경할 것이기에 해당 데이터들도 따로 수정하지 않도록 하겠습니다!

2023-07-27 03:29 UTC, kwonyj1022 approved these changes

2023-07-27 03:55 UTC, merged