채팅 기능 구현에 필요한 엔티티 생성
woowacourse-teams/2023-3-ddang pull request #122
Opened 2023-07-26 03:14 UTC by kwonyj1022

## 📄 작업 내용 요약

채팅 기능 구현에 필요한 엔티티 생성

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

## 📎 Issue 번호

 
- closed #118

2023-07-26 06:27 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/Message.java
> +    public Message(final ChatRoom chatRoom, final User writer, final User receiver, final String contents) {
저희...가 생성자 매개변수가 3개를 초과하는 경우 `@Builder`를 쓰기로 했던 것 같은데 이 부분은 좀 가물가물하네요 ㅎㅎ;

2023-07-26 06:28 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/Message.java
> +@ToString
해당 부분도 `ChatRoom`과 동일하게 제외해주시면 좋을 것 같습니다

2023-07-26 06:41 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/chat/domain/ChatRoomTest.java
> +@SpringBootTest
아니면 `Reflection`으로 직접 값을 세팅해줘도 되기는 하겠네요

2023-07-26 06:43 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/Message.java
> +    private String contents;
`VARCHAR` VS `LOB`? 어떤게 더 좋을지 같이 고민해봐야될거같네요

2023-07-26 06:45 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/ChatRoom.java
> +@ToString
조회하기 위함이 아니라 조회하기 때문이네요 ㅎㅎ;

2023-07-26 07:27 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/Message.java
> +    private String contents;
찾아보니 저희의 애플리케이션 상황에서는 `VARCHAR`가 조금 더 적합할 것 같네요 좋습니다 👍

2023-07-26 07:44 UTC, JJ503 requested changes
큰 수정사항은 없어 소소하게 몇 가지 리뷰 남깁니다!
페어로 진행하시느라 고생 많으셨습니다 ☺️👍👍

2023-07-26 07:44 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/ChatRoom.java
> +    private Auction auction;
Lazy를 설정하기만 해도 말씀해 주신 "Auction이 삭제되어도 ChatRoom은 삭제되지 않음"에 대한 설정이 되는 건가요?
해당 의도에 대한 설정 방법이 궁금합니다!

2023-07-26 07:44 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/domain/ChatRoomTest.java
> +@SpringBootTest
`@SpringBootTest`를 사용한 이유가 정확히 무엇인지 궁금합니다!

2023-07-26 08:03 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/chat/domain/ChatRoomTest.java
> +}
역시 제이미

2023-07-26 09:04 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/ChatRoom.java
> +    private Auction auction;
`casecade` 에 대해 아무것도 설정하지 않으면 강제 삭제가 안되기 때문에 해당 부분에 주석을 남겨놓은 것이었습니다. lazy 옵션에 대한 주석이 아닌 `@OneToOne` 어노테이션에 casecade 옵션을 넣지 않은 것에 대한 주석이었습니다.

2023-07-27 08:09 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/ChatRoom.java
> +    private Auction auction;
이해했습니다. 답변 감사합니다!

2023-07-27 08:10 UTC, apptie approved these changes
`@SpringBootTest`에서 모두 `@DataJpaTest`로 변경해주신 점도 좋고, 필드 명도 적절히 seller와 buyer로 변경해주셔서 저는 훌륭하게 작성해주신 것 같습니다!

나중에 단위 테스트에서도 `@DataJpaTest`를 사용해야하는지는 테스트 성능 측면에서 다같이 고민하거나 해야 할 거 같기도 하고요..?

일단 Approve 드리겠습니다 고생하셨습니다 👍

2023-07-28 03:11 UTC, JJ503 approved these changes
마지막까지 고생 많으셨습니다!
별다른 문제는 보이지 않아 또 한 번 approve 합니다!
그런데 궁금한 점이 하나 있어 해당 부분만 확인해주시면 감사하겠습니다!

2023-07-28 03:11 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/ChatRoom.java
> +@EqualsAndHashCode(callSuper = false, of = "id")
갑자기 궁금해져 여쭤봅니다.
callSuper false가 기본값으로 알고 있는데 이를 명시해 주는 것이 좋을까요?
만약 좋다면 저도 수정이 필요해 여쭤봅니다!

2023-07-28 03:15 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/ChatRoom.java
> +@EqualsAndHashCode(callSuper = false, of = "id")
오..! 다른 코드들에는 명시가 안되어있었네요
다른 코드에 맞춰 삭제해두겠습니다.

2023-07-28 03:16 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/ChatRoom.java
> +@EqualsAndHashCode(callSuper = false, of = "id")
이 부분...은 저는 굳이 명시해줄 필요는 없지 않을까 싶기는 하네요

2023-07-28 03:16 UTC, apptie approved these changes
저도 다시 한 번 approve를 드리도록 하겠습니다
고생하셨습니다

2023-07-28 03:26 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/ChatRoom.java
> +@EqualsAndHashCode(callSuper = false, of = "id")
Auction에 명시가 되어있어서 적용시켜 주었는데요, 저희 회의 결과 굳이 명시하지 않기로 결정되었습니다! 삭제하겠습니다. 나중에 추후 Auction 엔티티도 수정을 해주어야 할 것 같아요

2023-07-28 04:59 UTC, merged