지역 엔티티, 경매 엔티티 연동
woowacourse-teams/2023-3-ddang pull request #137
Opened 2023-07-27 07:30 UTC by apptie

## 📄 작업 내용 요약

지역 엔티티, 경매 엔티티 연동

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- 변경된 테스트 코드나 DTO는 컴파일 오류를 수정하기 위한 부분이라 무시하셔도 좋습니다.(전혀 중요하지 않습니다..)
- QuerydslAuctionRepositoryImpl
  - findAuctionWithRegionsById : 경매에 등록된 직거래 지역을 모두 fetch join하기 위한 메서드

## 📎 Issue 번호

- closed #116

2023-07-27 07:55 UTC, JJ503 approved these changes
수많은 dto 클래스와 테스트 코드에 눈물이 흐르네요...
리팩토링 하시느라 정말 고생 많으셨습니다...!! 👍
제 눈에는 수정 사항이 따로 보이지 않아 approve 합니다.

querydsl과 관련해 궁금한 점이 있어 해당 부분만 답변해 주시면 감사하겠습니다!

2023-07-27 07:55 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +                .where(auction.deleted.isFalse(), lessThanLastAuctionId(lastAuctionId))
쉼표(,)는 and의 역할과 동일하다고 보면 될까요?
만약 맞다면 and가 봤을 때 좀 더 명확해 보이는데 쉼표로 바꾼 이유가 있을까요?

2023-07-27 07:55 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +                .leftJoin(region.secondRegion).fetchJoin()
fetchJoin() 👍👍
덕분에 fetchJoin() 공부와 사용 방법을 알 수 있었네요!

2023-07-27 07:57 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +                .where(auction.deleted.isFalse(), lessThanLastAuctionId(lastAuctionId))
해당 부분은 제가 이전에 잘못된 정보를 말씀드려서 변경했습니다
where절에 null이면 무시된다고 말씀드렸는데 이 때 조건이 and가 아닌 `,` <- 얘로 나열해야지 null일 때 무시가 됩니다 

몰래 수정하려고 했는데...ㄲㅂ

2023-07-27 08:49 UTC, JJ503 requested changes
엇 그런데 `CreateAuctionDto` dto에 있는 region을 toEntity() 등을 수행할 때 region에 대한 정보는 없는 것 같습니다..!

2023-07-27 08:49 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +                .where(auction.deleted.isFalse(), lessThanLastAuctionId(lastAuctionId))
오 그렇군요!
덕분에 또 하나 배워갑니다 🫡

2023-07-27 23:36 UTC, JJ503 approved these changes
수정해 주신 부분 확인 완료했습니다!
한 가지 궁금한 사항이 있어 해당 부분만 답변해 주시면 감사하겠습니다.
지역 관련해서 마지막까지 고생 많으셨습니다!! 👍👍👍

2023-07-27 23:36 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/region/domain/AuctionRegion.java
> +@Table(name = "auction_region")
`users`의 경우 `@Table`의 위치가 클래스 바로 위에 있는데 해당 어노테이션도 위치를 동일하게 하는 것은 어떨까요?
또한, 해당 클래스 명은 이미 `AuctionRegion`인데 테이블명을 명시적으로 작성해 준 이유도 궁금합니다!

2023-07-27 23:42 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/region/domain/AuctionRegion.java
> +@Table(name = "auction_region")
위치 이슈...맞추도록 하겠습니다 감사합니다

Table 어노테이션으로 명시한 이유는 JPA가 AuctionRegion의 테이블명을 _를 빼먹은 AUCTIONREGION으로 인식하는 이슈가 있었기 때문이었습니다

2023-07-27 23:57 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/region/domain/AuctionRegion.java
> +@Table(name = "auction_region")
앗 그렇군요..!
답변 감사합니다 🫡

2023-07-28 06:12 UTC, kwonyj1022 approved these changes
지토 수고하셨어요! approve 하겠습니다! 다만 몇 가지 궁금한 사항이랑 메서드 분리 관련한 제안 사항이 있어서 관련된 코멘트 달았습니다.

2023-07-28 06:12 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +        }
이 부분 메서드 분리해도 좋을 것 같아요! create()가 개행 때문에 길어지기도 했고, 메서드 이름으로 이 로직이 어떤 로직인지 알고 세부 코드를 보면 더 이해가 쉬울 것 같습니다.

2023-07-28 06:21 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/DirectRegionResponse.java
>  }
이건 경매 상세 조회 API 응답에서 사용됩니다 
`category : {main: String, sub: String}` 이런 식으로 되어 있어서 그거에 맞추려고 한 부분이라고 봐 주시면 될 것 같습니다
근데 id는 제거를 해야겠네요..

2023-07-28 06:21 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/DirectRegionsResponse.java
> +}
이름 짱어렵네요 말씀하신대로 변경하겠습니다

2023-07-28 06:23 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +        }
말씀하신 방향이 좋아보이네요 분리하도록 하겠습니다

2023-07-28 06:37 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/DirectRegionResponse.java
>  }
그럼 결국 필요 없어지겠네요 삭제하도록 하겠습니다

2023-07-28 10:53 UTC, swonny approved these changes
고생 많으셨습니다 지토....................................
정말 어려운 작업을 하셨네요...... 역시 지토입니다.......👽

질문 두 가지 남겨두었습니다.
질문이어서 approve하겠습니다.

그리고 저는 다음과 같이 이해했는데 이해한 내용이 맞는지도 궁금합니다
경매 생성 시 세 번째 지역을 기준으로 경매 지역을 저장하고, 
조회 시에는 DB에 저장된 첫 번째, 두 번째 지역을 함께 불러오는 흐름으로 이해했는데 맞을까요???
그리고 지역 조회 시 객체들을 한 번에 생성하기 위해 fetch join을 사용하신 것도 맞을까요??

그리고 아까 잠깐 언급하셨던.. 두 번째 지역에서 전체를 선택한 경우(세 번째 지역이 입력되지 않은 경우)에 대한 문제는 해결이 된건지 궁금합니다. 이 부분에 대해 조금 생각해봤는데 세 번째 지역이 입력되지 않은 경우 두 번째 지역에 해당하는 모든 세 번째 지역을 저장하는 방식으로 해결할 수 있을까요??

2023-07-28 10:53 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +                .leftJoin(region.secondRegion).fetchJoin()
모든 지역을 한번에 조회해오기 위해 사용하신 게 맞나요?? N+1 어쩌구..문제를 해결하기 위해 사용하신건가요??

2023-07-28 10:53 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepository.java
> +    Optional<Auction> findAuctionWithRegionsById(final Long auctionId);
`AuctionService`에서 경매를 조회할 때는 항상 지역을 포함해 검색을 진행하게 되고, 
지정한 지역이 없는 경우 `auction`의 `auctionRegions`에는 null이 들어가는 게 맞나요??

Auction 조회시 항상 지역을 함께 조회하는거라면 `findAuctionWithRegions`에서 regions가 꼭 포함되어야 하는지 궁금합니다!

2023-07-28 12:04 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +                .leftJoin(region.secondRegion).fetchJoin()
@swonny 
넵 맞습니다
5개의 직거래 지역을 등록한 경매 글을 fetch join 없이 조회하는 예시를 든다면

1. (직거래 지역 정보를 제외한) 경매 글 조회 쿼리 1회
2. 각 직거래 지역의 정보를 getter로 꺼내올 때 마다 조회 쿼리 5회(N회)
해서 N+1 문제를 해결하기 위한 코드라고 봐주시면 될 것 같습니다

그래서 결론은 `모든 지역을 한번에 조회해오기 위해 사용한 것`입니다

2023-07-28 12:08 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepository.java
> +    Optional<Auction> findAuctionWithRegionsById(final Long auctionId);
`AuctionService에서 경매를 조회할 때는 항상 지역을 포함해 검색을 진행하게 되고` -> 넵 맞습니다 `findAuctionWithRegionsById`로 조회하면 항상 지역을 포함해 검색합니다 

`지정한 지역이 없는 경우 auction의 auctionRegions에는 null이 들어가는 게 맞나요??` -> 넵 맞습니다 없으면 null로 옵니다

`Auction 조회시 항상 지역을 함께 조회하는거라면 findAuctionWithRegions에서 regions가 꼭 포함되어야 하는지 궁금합니다!`
-> 이건 제가 잘 이해를 못했습니다 네이밍에 대한 질문이실까요?

2023-07-28 12:13 UTC, apptie commented
@swonny 

`경매 생성 시 세 번째 지역을 기준으로 경매 지역을 저장하고,` 
-> 넵 맞습니다 서울특별시 전체 강서구 전체 이런 조건을 제외했기 때문에 세 번째 지역이 무조건 존재하고, 세 번째 지역은 첫 번째와 두 번째 지역을 알고 있기 때문에 세 번째만 저장해주었습니다 (세 번째 지역 Region에서 firstRegion, secondRegion 조회 가능)

`조회 시에는 DB에 저장된 첫 번째, 두 번째 지역을 함께 불러오는 흐름으로 이해했는데 맞을까요???`
-> 음...이건 좀 애매한데
thridRegion이 Lazy라 평범한 쿼리로는 같이 조회가 되지 않습니다
그래서 fetch join을 사용해서 경매 조회 시 세 번째 지역도 같이 조회되도록 하고
이와 동일한 이유로 두 번째 지역, 첫 번째 지역도 같이 조회되도록 했습니다

`그리고 지역 조회 시 객체들을 한 번에 생성하기 위해 fetch join을 사용하신 것도 맞을까요??`
-> 넵 맞습니다 DB에서 지역 관련 정보들을 한 번에 조회해서 객체들을 쿼리 한 번으로 생성하기위해 사용했습니다

`두 번째 지역에서 전체를 선택한 경우(세 번째 지역이 입력되지 않은 경우)에 대한 문제는 해결이 된건지 궁금합니다.`
-> 이 부분은 오늘 둘리와의 대화?로 전체 지정 기능을 제외하도록 했습니다..`@ModelAttribute`는 `Nested Object`가 허용되지 않더라고요..

`이 부분에 대해 조금 생각해봤는데 세 번째 지역이 입력되지 않은 경우 두 번째 지역에 해당하는 모든 세 번째 지역을 저장하는 방식으로 해결할 수 있을까요??`
-> `@ModelAttribute`의 한계 상 세 번째 지역의 Id를 List로만 받아올 수 있어서 이 방법은 안타깝게도 불가능할 것 같습니다..

2023-07-28 12:48 UTC, merged