경매 이미지 엔티티, 카테고리 엔티티, 경매 엔티티 연동
woowacourse-teams/2023-3-ddang pull request #149
Opened 2023-07-29 04:58 UTC by apptie

## 📄 작업 내용 요약

- 경매 이미지 엔티티, 카테고리 엔티티, 경매 엔티티 연동
  - 연동 과정 중 컴파일 에러가 발생하는 프로덕션, 테스트 영역 코드 리펙토링
- API 명세 변경에 따른 프로덕션, 테스트 영역 코드 리펙토링

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- QuerydslSliceHelper
  - No-Offset 기반 목록 조회 시 반환 타입을 List에서 Slice로 변경하는 역할
- QuerydslAuctionRepositoryImpl.findAuctionsAllByLastAuctionId
  - List 대신 Slice 반환
  - Region, Category fetch join
- QuerydslAuctionRepositoryImpl.findAuctionWithRegionsById
  - Region, Category fetch join
- StoreImageProcessor
  - 이미지를 저장하는 것 자체는 도메인 기능이라고 판단, 인터페이스로 분리
  - 실제 로컬에 데이터를 저장하는 기능을 수행하는 대상은 LocalStoreImageProcessor

## 📎 Issue 번호

- closed #140

2023-07-30 11:27 UTC, kwonyj1022 requested changes
Files chaged와 Commits 수를 보니 지토가 얼마나 고생했는지 가늠이 가네요.. 정말 수고하셨습니다 👍
지토를 백엔드 회장으로~ ㅎㅎ
공부할 만한 코드가 많아서 리뷰하면서 많이 유익했습니다.
몇 가지 제안 사항이 있어서 코멘트 달았어용

MultipartResolver로 StandardServletMultipartResolver를 명시해 주는 것에 대해서는, 저도 이 부분을 처음 접해봐서 확실하진 않지만 MultipartResolver를 직접 커스텀해서 구현할 일이 있을 수 있기 때문에 명시해 놓는 것도 좋다고 생각합니다. 

![image](https://github.com/woowacourse-teams/2023-3-ddang/assets/96688810/b9001164-ec50-4172-a7ed-c1c72ec982b4)

2023-07-30 11:27 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/common/helper/QuerydslSliceHelper.java
> +}
이 부분도 처음 접해보는 개념이네요! 지토가 올려준 디스커션 참고해서 열심히 공부해 보겠습니다~ 👍

2023-07-30 11:27 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/region/domain/AuctionRegion.java
> -@Table(name = "auction_region")
테이블 이름에 언더바가 적용 안 되는 이슈가 잘 해결된 것인가요? 적용이 안 되었던 이유가 무엇이었나요?

2023-07-30 11:27 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/image/domain/AuctionImage.java
> +@Table(name = "auction_image")
해당 어노테이션이 없어도 테이블명이 auction_image로 잘 만들어지는데 명시해 주신 이유가 있을까요?

2023-07-30 11:27 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/image/domain/dto/StoreImageDto.java
> +}
사용하지 않는 dto인 것 같은데 삭제하는 건 어떨까요?

2023-07-30 11:32 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepository.java
>      Optional<Auction> findAuctionWithRegionsById(final Long auctionId);
좋은 네이밍이네요 👍 
여러 엔티티랑 연동하게 되면서 이것저것 다 fetch join으로 가지고 오다 보니 말씀하신대로 Region을 같이 조회한다는 사실을 굳이 메서드 이름에서 드러낼 필요가 없겠네요

2023-07-30 12:16 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +    }
`setter` 관련된 리뷰는 저랑 견해가 조금 다르신 것 같습니다.

예시로 들어주신 코드 중 `dto.toEntity(subCategory, auctionRegions, auctionImages);`가 있어서 
엔초가 제안해주신 방법이 `Auction 생성 시 필요한 필드를 초기화할 때 add~() 메소드가 아닌 생성자에서 모두 초기화하는 것`이라고 가정하고 제 의견을 말씀드리겠습니다.

---

말씀해주신대로 `addAuctionRegions()`, `addAuctionImages()`는 결과적으로는 `setter`와 동작이 유사하다고 볼 수 있기는 하지만 `Auction`을 영속화할 때 필요한 기능이라고 생각하고 구현했습니다.

제가 코드를 이렇게 작성한 이유는 다음과 같습니다.

1. 양방향 관계에서 객체의 관계를 서로 세팅해주기 위함
지금 당장은 `Auction` 생성 시 바로 `save()`를 호출하고 있지만 로직이 변경되면서, 언제 `AuctionRegion`에서 `Auction`이 필요할지, `Auction`에서 `AuctionRegion`이 필요할지 알지 못하는 상황입니다.
이러한 상황에서, 위와 같은 연관관계 편의 메서드가 존재하지 않는다면 `null`을 참조하게 되는 상황이 발생할 수 있습니다.
`NPE`는 최대한 피해야 한다고 생각하기 때문에, 이러한 연관관계 편의 메서드를 추가해 양쪽에서 객체 그래프를 자유롭게 탐색할 수 있도록 추가해줘야 한다고 생각했습니다.
2. 외부에서 연관관계를 세팅해주기 위해 `setter`와 유사한 메서드가 필수적
이러한 연관관계를 생성자에서도 추가할 수 있겠지만, `Region`이나 `Category`같이 `self join`이 아니라면 결국 외부 클래스이기 때문에 `setter`와 유사한 메서드가 필수가 됩니다.
`Auction`의 생성자에 `AuctionRegions`를 입력할 수 있지만, `Auction`의 생성자에서 `auctionRegions` 필드를 초기화해준다고 해서, `AuctionRegion`의 `auction` 필드는 초기화할 수 없게 됩니다. 
결국 `private`이기 때문에 `setter`와 유사한 메서드가 필수적이 됩니다. 
이 상황에서 어디서는 생성자, 어디서는 메서드로 초기화하기에는 일관성이 너무 없어 오히려 더 헷갈린다는 판단을 했습니다.
그래서 하나의 연관관게 편의 메서드를 통해 두 도메인 엔티티의 객체 그래프를 세팅해주고자 했습니다.
3. 가독성 향상
생성자에서 이러한 연관관계 세팅 작업을 수행한다면 생성자가 너무 복잡해질 것이라고 생각했습니다.
정팩메도 고려를 했었는데, 정팩메를 쓰는 것보다는 서비스에서 명시적으로 해당 연관관계 편의 메서드를 호출하는 것이 `Service의 Auction 생성 메서드`를 통해 어떠한 쿼리가 나갈지 더 수월하게 예측할 수 있을 것이라고 생각했습니다.
이는 굳이 dto에서 이러한 연관관계 편의 메서드를 호출하지 않은 이유이기도 합니다.
4. `setter`와 유사하지 `setter`가 아님
저는 `setter`를 쓸 경우 문제가 되는 이유 중 하나가 어디서나 호출해서 사용할 수 있기 때문이라고 생각합니다.
사실 엄격하게 객체 지향적으로 간다면 모든 도메인을 불변으로 선언해야겠지만 이는 `JPA`를 사용하면서 불가능하기 때문에 이러한 측면에서는 어느 정도 트레이드 오프를 해야 한다고 생각합니다.
이러한 측면에서 `연관관계를 세팅한다`는 기능을 수행하는 `add~()`나 `init~()`은 `setter`에 비해 사용할 수 있는 영역을 명시적으로 표현했다고 생각합니다.
다만 이러한 메서드 이름은 제 생각이기 때문에 네이밍의 경우 저희끼리 컨벤션을 정해서 `해당 메서드는 오로지 연관관계를 세팅하기 위해서만 호출해야한다`라고 정하면 충분할 것이라고 생각합니다.

혹시 제가 잘못 이해한 것이라면 말씀해주세요!

---

나머지 리뷰는 반영하겠습니다! 좋은 의견이네요 👍

2023-07-30 12:26 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +        final Auction persistAuction = auctionRepository.save(auction);
이거는 제 개인적인 취향..?같은 느낌입니다
개인적으로 객체 지향 프로그래밍에서 메서드의 매개변수로 넘겨준 값을 직접 변경해서 사용해서는 안 된다고 생각합니다.

예를 들어서 void 반환 타입의 메서드의 매개 변수에 List를 넘겨주고, List에 요소를 해당 메서드가 추가하는 등의 경우를 예시로 들 수 있을 것 같습니다.

```
public void addContent(final List<String> contents) {
    contents.add("1");
    ...
}
```

이는 객체의 불변성이나 순수 함수 측면에서 어울리지 않는다고 생각합니다.

```
public List<String> addContent(final List<String> contents) {
    contents.add("1");
    ...
    return contents;
}
```

이와 같이 메서드에서 결과가 똑같다고 하더라도, 반환을 해 주는 것이 불변성을 지키고(`contents`가 변경이 되기는 했지만 그래도 명시적으로 반환된 값을 사용) 메서드가 항상 동일한 출력(인자로 받은 컬렉션에 요소를 더한 뒤 반환)을 한다고 볼 수 있다고 생각합니다.

```
final Auction persistAuction = auctionRepository.save(auction);
```

해당 메서드 또한 동일하다고 생각합니다. 

`save()`를 호출하면 엔티티에 모든 값을 자연으로 세팅해주지만(매개변수로 입력한 객체에 값을 변경), `JPA`에서 `save()`한 엔티티 값 그 자체를 반환해주는 이유는 여러 이유가 있겠지만, 위에서 설명드린 이유도 포함된다고 추측하고 있습니다.

그래서 테스트같은 환경에서면 몰라도, 프로덕션 환경에서는 이러한 식으로 매개변수로 한 번 소모된 변수는 사용하지 않고, 반환받은 값을 사용하는 것을 선호합니다.
물론 테스트 환경에서는 대충 막 쓰기는 합니다..

2023-07-30 12:30 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/infrastructure/local/LocalStoreImageProcessor.java
> +            }
말씀해주신대로 분리하는 게 더 낫겠네요! 

그리고 `save` 대신 `store`라는 단어를 쓴 이유는 `DB에 저장`한다는 의미인 `save`와 `이미지를 어디인지는 모르지만 아무튼 외부에 저장`한다는 의미인 `store`로 단어를 분리하고 싶었기 때문이었습니다..만 이것도 그냥 바꾸는게 좋을까요?

2023-07-30 12:38 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/infrastructure/local/LocalStoreImageProcessor.java
`MalformedURLException`를 말씀해주신걸까요? 
해당 부분은 이름대로 `URL`이 잘못되었을 때 발생하는데, 앞에 `file:`만 명시하면 발생할 수가 없어서 굳이 처리할 필요가 있나 싶었습니다.
또한 이외의 다른 부분에서 발생할 가능성이 없다고 판단해서 저 예외를 그대로 `ControllerAdvice`에서 처리하고자 했습니다.

이미지 커스텀 예외의 같은 경우는 나중에 (제이미가 계층 구조로 커스텀 예외 작성하는 걸 보고) 맞춰서 하려고 합니다 ㅎㅎ; 
잘 감이 안와서...
해당 부분은 충돌날까봐 안해놓은 `ControllerAdvice`부분에 예외 핸들링 처리를 하면서 처리하도록 하겠습니다

2023-07-30 12:42 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/CreateAuctionDto.java
> +                calculateThirdRegionIds(request),
사실 엔초가 말씀해주신 부분이 맞기는 한데 저는 단순 조회가 아닌 모든 메서드에서는 최대한 getter 네이밍을 쓰지 않으려고 했었기 때문이었습니다 
메리가 작성해주신 코드를 봤을 때에도 엔초가 제안해주신 방식대로 작성하셨던데 내일 한 번 대화해보고 통일하는게 낫겠네요 
내일 백엔드 데일리 때 말씀드려보도록 하겠습니다

2023-07-30 12:42 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/CreateInfoAuctionDto.java
> +public record CreateInfoAuctionDto(
저는 진짜 네이밍에 자신이 없습니다...따르겠습니다..

2023-07-30 12:50 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/ReadAuctionDto.java
> +                convertImageUrls(auction),
이 부분도 취향의 차이?가 갈리는 것 같네요 

저는 메서드 네이밍만으로도 어떠한 기능을 수행하고, 어떠한 필드가 필요한지 판단할 수 있을 것이라고 생각했습니다
즉 메서드 네이밍만으로도 충분히 명확하다고 생각했었습니다 

그리고 `convertImageUrls(auction.getAuctionImages())`와 같이 너무 구체적으로 필드를 지정해주는 경우 가독성이나 유지보수에 좋지 않을 것이라고 생각했습니다

`convertImageUrls()` 메서드를 호출할 때, `auction`에 어떠한 필드가 해당 메서드에게 필요한지 구체적으로 알 필요는 없다고 생각했습니다 
`convertImageUrls()`를 호출하는 곳에서는 `경매 엔티티를 주면 아무튼 이미지 URL을 반환해주는구나` 정도면 충분하다고 생각했고, 이 편이 더 가독성이 좋다고 생각했습니다

그리고 `convertImageUrls()`에서 갑자기 추가적인 필드가 필요할 경우 제안해주신대로 구체적인 필드를 지정해주면 호출하는 쪽과 로직을 수행하는 메서드 모두가 수정되어야 하지만, `auction`만 넘겨준다면 이러한 변경 사항에 최대한 유연하게 처리할 수 있을 것이라고 생각했습니다

이 부분은 다른 분들의 의견도 궁금하네요

2023-07-30 12:51 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
> +        final CreateAuctionResponse response = CreateAuctionResponse.of(createInfoAuctionDto, baseUrl);
이 부분 분리할지 말지 고민 엄청했는데 그냥 분리해버릴까요 
사실 분리 안할 이유도 없는데 왜 고민했었는지 까먹었네요..

2023-07-30 12:52 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/category/infrastructure/persistence/JpaCategoryRepository.java
> +    List<Category> findSubAllByMainCategoryId(final Long mainCategoryId);
이건 제가 한거 아닌거같은데 인텔리제이가 해준거같아요 아무튼 개꿀

2023-07-30 12:55 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/category/infrastructure/persistence/JpaCategoryRepository.java
> +    Optional<Category> findSubCategoryById(final Long subCategoryId);
그러네요 말씀 해주신걸 보고나니 왜 붙였나 싶네요 감사합니다

2023-07-30 12:58 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/category/infrastructure/persistence/JpaCategoryRepository.java
> +    Optional<Category> findSubCategoryById(final Long subCategoryId);
저 떠올렸어요 

해당 메서드를 호출하는 경우가 새롭게 경매를 등록할 때 하위 카테고리 id만 입력하고 그걸 찾아서 `auction`에 세팅해주는 식인데 
이 때 하위 카테고리 id가 아니라 상위 카테고리 id를 입력할 수도 있기 때문에 이를 거르기 위해서 사용했었습니다

2023-07-30 12:59 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/region/domain/AuctionRegion.java
> -@Table(name = "auction_region")
네 그것은 제 실수였습니다

뭔가 제 로컬 환경 세팅이 잘못된건지 새로운 기능 추가하려고 새롭게 클론받은 다음에 그냥 한 번 삭제하고 돌려보니까 되더라고요 
그래서 그냥..뺐습니다 머쓱하네요

2023-07-30 12:59 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/domain/AuctionImage.java
> +@Table(name = "auction_image")
`@Table(name = "auction_region")`이건 빼고 `@Table(name = "auction_image")` 이건 넣었네요 매우 머쓱합니다 빼도록 하겠습니다

2023-07-30 13:01 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +        final Auction persistAuction = auctionRepository.save(auction);
그렇군요 역시 지토 👍 
그럼 이 부분에 대해서 내일 백엔드 데일리 때 이야기 나눠보고 모두 동의한다면 저희 컨벤션으로 추가하면 좋을 것 같습니다!

2023-07-30 13:02 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/domain/dto/StoreImageDto.java
> +}
이거는 `StoreImageProcessor`에서 사용합니다 파일 원본 이름과 경로를 포함한 저장된 파일 이름을 넘겨주기 위해서 사용하고 있습니다

`AuctionService.convertAuctionImages()`에서 그냥 바로 `stream` 돌려보여서 명시적으로 안보이기는 하네요...
게다가 `toEntity()`를 만들어놓고 안쓰고 있었네요 이 부분은 사용하도록 수정하겠습니다

2023-07-30 13:07 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/infrastructure/local/LocalStoreImageProcessor.java
> +            }
앗 이 부분은 그 `save()` 호출 시 반환 값으로 써먹는거랑 비슷한 이유로 분리를 안했었네요 일단 냅두겠습니다

2023-07-30 13:12 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/image/infrastructure/local/LocalStoreImageProcessor.java
> +            }
store를 동사로 사용하신 거고, save와 분리하고자 하는 지토의 네이밍 의도를 알고 나니 납득이 됐습니다. store도 괜찮은 것 같아요!

2023-07-30 13:15 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/image/infrastructure/local/LocalStoreImageProcessor.java
EmptyImageException 등과 같은 커스텀 예외를 의미한 것이었습니다!
혹시 까먹으셨을까봐 말씀드린 건데, 충돌이 날까 봐 처리를 안 한 것이었군요. ㅎㅎ

2023-07-30 13:19 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/ReadAuctionDto.java
> +                convertImageUrls(auction),
처음에 함께 작성했던 convertPrice()와 통일성이 있으면 좋겠다는 생각에서 제안드린 것이었는데요, 구체적으로 필드를 지정해 주는 경우 가독성이나 유지보수에 좋지 않을 것이라는 지토의 의견에 동의합니다! 그 부분을 생각 못했던 것 같아요. 저는 이대로 가도 좋을 것 같습니다!

2023-07-30 13:23 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +    }
근데 지금 보니까 `Category`만 다른 방식으로 했네요 과거의 저를 이해할 수가 없군요
결론 나면 통일하도록 하겠습니다

2023-07-30 13:35 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +    }
제가 처음 코멘트 작성할 때 말을 좀 생략한 것 같아 추가적으로 수정하였는데 혹시 보셨는지 모르겠네요ㅠ "setter와 유사하지만 연관관계 세팅의 기능이 있다는 점이 다르긴 하다"라는 말을 추가했습니다. 코멘트의 의도는 'auction을 생성할 때 Auction 생성자나 CreateAuctionDto의 toEntity() 내부에서 add~ 메서드를 이용해 연관관계를 세팅하는 것은 어떨까'였습니다.

1번과 2번에 대해서는 동의합니다. 4번도 저희 기존에 category와 region 만들 때 사용했던 네이밍이기 때문에 메서드 이름도 괜찮은 것 같아요. 그런데 혹시 서비스에서 명시적으로 해당 연관관계 편의 메서드를 호출하는 것이 Service의 Auction 생성 메서드를 통해 어떠한 쿼리가 나갈지 더 수월하게 예측할 수 있을 것이라고 생각했습니다.` 이 부분에 대해서 좀 더 자세하게 설명해 주실 수 있나요? 서비스에서 어떤 쿼리가 나갈지 예측할 수 있다는 게 구체적으로 어떤 말씀이신지, 서비스에서 예측이 필요한 이유가 궁금합니다.

2023-07-30 13:37 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
> +        final CreateAuctionResponse response = CreateAuctionResponse.of(createInfoAuctionDto, baseUrl);
이유가 있으셨던 것 같은데 궁금하네요! 생각나면 말씀해주세요!

2023-07-30 14:11 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +    }
3번의 경우는 저희 애플리케이션 기준으로 jpa를 사용하기 때문에 쿼리를 직접 만들고 실행하는 것이 아니라는 부분에서 설명드리자면

일단 저는 성능 최적화를 위해 쿼리 성능 개선이 필수라고 생각합니다 
근데 이제 앞서 적어놓은 부분처럼 저희가 쿼리를 직접 만드는게 아니다 보니 쿼리를 예측하는 것이 상당히 중요하다고 생각합니다
N+1같이 예상하지 못한 쿼리가 발생하는 경우를 예방하기만 해도 유의미한 성능 개선이 가능할 정도이기 때문입니다 

그리고 `auction`과 같이 비중이 매우 큰 도메인 엔티티의 경우 해당 도메인 엔티티와 관련된 서비스(`AuctionService`)가 아니라면 다른 서비스에서 직접 생성할 일은 없다고 생각합니다
그러다 보니 특정 엔티티를 생성하는 서비스를 보기만 했을 때 어떠한 쿼리가 나갈지 예측할 수 있도록 명확하게 한다면 후에 성능 개선을 진행할 때 수월하다고 생각하기 때문에 3번과 같이 설명드린 것이라고 보시면 좋을 것 같습니다

예시를 들어보자면 `auctionService.create()`를 보면 카테고리랑 직거래 지역들이랑 경매 이미지들의 연관관계를 세팅하고 있는데 
이를 통해서 쿼리가 최대 몇 번 나갈지를 예측하고(아마도 카테고리는 상관 없고 직거래 지역 auctionRegion이 직거래 개수만큼 insert 될 것이고 경매 이미지는 최대 10장이니 10번 insert된 이후에 auction insert가 1번 나갈 것 같습니다), 실행한 뒤 실행 결과가 일치하지 않는다면 불필요한 쿼리를 수정하고, 이후 별도의 쿼리 최적화를 적용(insert문이 많이 나가니 batch-fetch-size를 조절하는 등)할 것 같습니다

2023-07-30 14:12 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +    }
그리고 추가해주신 부분은 이제 봤네요 ㅎㅎ;

2023-07-30 14:34 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/category/infrastructure/persistence/JpaCategoryRepository.java
> +    Optional<Category> findSubCategoryById(final Long subCategoryId);
앗 그렇군요! 지토의 의견을 듣고 나니 해당 조건은 필요할 것 같습니다.

2023-07-31 07:44 UTC, kwonyj1022 approved these changes
일단 approve 합니다.

2023-07-31 07:46 UTC, merged

2023-07-31 12:56 UTC, JJ503 approved these changes
지토 이번 이슈 역시 엄청난 노력이 보이네요 🫡
몇 가지 궁금한 사항이 있어 해당 부분들만 확인해 주시면 될 것 같습니다.
수정해야 할 부분은 따로 보이지 않고 컨벤션 부분만 몇 개 있어 확인해주시면 감사하겠습니다!
이번에도 고생 많으셨습니다~!

2023-07-31 15:38 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +        final Auction persistAuction = auctionRepository.save(auction);
save()를 통해 반환되는 메서드 또한 영속성 컨텍스트 캐시에 저장이 됩니다
좀 더 정확히 말씀드리면 save() 매개변수를 넣은 엔티티나 save() 메서드가 반환한 엔티티나 모두 동일한 영속성 컨텍스트 내의 1차 캐싱된 키를 가리키고 있다고 볼 수 있을 것 같습니다 
마치 자바 컬렉션처럼 해당 컬렉션에 추가하기 전 요소를 변경해도, 요소를 컬렉션에서 찾아서 꺼내서 변경해도 동일한 요소라면 동일하게 모두 변경되는 것과 같다고 보시면 될 것 같습니다

create 시 id가 아닌 auction(CreateInfoAuctionDto라고 인식하겠습니다)을 반환한 이유는 클라이언트의 요구사항이었습니다 
생성 시 단순 id 뿐만 아니라 경매 목록 조회 시 보여주는 데이터들도 같이 반환해달라는 요청이 있어 그에 맞추기 위해 위와 같이 반환해주었다고 보시면 될 것 같습니다

2023-07-31 15:39 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/configuration/ImageConfiguration.java
> +        MultipartConfigFactory factory = new MultipartConfigFactory();
이런 실수를...수정하겠습니다

2023-07-31 15:44 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +                .limit(size + 1L)
`slice의 경우 +1을 해준다는 글을 보긴 했는데 이는 JpaRepository의 구현체를 사용할 때인 것이고 저희는 직접 쿼리를 생성하기에 직접 해준 걸까요?`
-> 넵 맞습니다 이거 querydsl에서는 안해줘서 +1을 해줬습니다

`그리고 이 이유가 slice에 대한 서로의 이해 때문인 걸까요? 혹은 꼭 해줘야만 하는 걸까요?`
-> 이건 제가 이해가 잘 안되는 것 같은데 `Slice를 쓸 때왜 +1을 해줘야하는지?`로 가정하고 답변드리겠습니다
일단 Slice는 페이징에 대한 정확한 데이터(현재 페이지가 몇, 다음 페이지 몇, 현재 페이지 사이즈 몇 등등)을 제공하지 않는 대신, 다음 페이지가 있는지 없는지 여부만을 반환해주는 친구입니다
그래서 Slice는 Page와는 다르게 별도의 count 쿼리가 나가지 않습니다
대신 지금 코드처럼 간단하게 요청한 size보다 1큰 값을 전달해서 단순하게 요청한 사이즈보다 결과가 많은지만 확인해서 다음 페이지가 있는지 없는지만 확인해줍니다 
그래서 +1하는 과정은 반드시 필요하다라고 볼 수 있을 것 같습니다

2023-07-31 15:44 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
>                  .leftJoin(auction.auctionRegions, auctionRegion).fetchJoin()
? 아뇨 이거는 제가 정신을 놓아버린 것 같습니다
개행을 안하는게 맞을 것 같아요 ㅎㅎ; 죄송합니다 제가 이렇게 정신을 놓고다닙니다

2023-07-31 15:46 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadAuctionResponse.java
> +        return baseUrl.concat(String.valueOf(dto.auctionImageIds().get(0)));
성능상 이점은 아무것도 없습니다 
가독성 때문에 선택했습니다
사실 가독성도 별 큰 이유는 없습니다
+은 뒤에 리터럴만 넣어서 지저분하다고 느껴졌습니다
StringBuilder는 new로 생성하고 append로 더해주고 toString으로 빼는게 지저분하게 느껴졌습니다

2023-07-31 15:46 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/infrastructure/local/LocalStoreImageProcessor.java
> +            for (MultipartFile imageFile : imageFiles) {
이런 끔찍한 실수를...수정하겠습니다

2023-07-31 15:47 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/infrastructure/local/LocalStoreImageProcessor.java
> +        } catch (IOException e) {
이번 PR은 끔찍한 실수가 많군요..반성하며 수정하겠습니다

2023-08-01 03:01 UTC, swonny reviewed
모르는 것과 궁금한 것들 위주로 코멘트 남겼습니다~!
고생많으셨습니다 지토 🤩👍🏻

2023-08-01 03:01 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/image/application/ImageServiceTest.java
> +        final Long invalidAuctionImageId = -999L;
7월 31일 월요일 기준으로 invalidId는 상수로 추출하기로 결정했던 부분이 생각나서 리마인드 코멘트 남깁니다.
나중에 리팩토링 시에 반영해주시면 좋을 것 같습니다!

2023-08-01 03:29 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepository.java
> +    Slice<Auction> findAuctionsAllByLastAuctionId(final Long lastAuctionId, final int size);
사실 무한 스크롤(정확히는 No-Offset 기반 페이징)에서 Slice가 적절하지는 않습니다
안드로이드 분들이 요청해주신 사항 때문에 이러한 부분을 추가했다고 볼 수 있을 것 같습니다

그리고 List가 아니라 Slice로 변경한 이유는 JPA에서 제공하는 자료구조이기 때문입니다 
사실 List로 반환하고 DTO에서 isLast를 계산해줄지 고민했지만 추후 Slice를 사용할 여지가 있을 경우, 반환 값을 통일하는 것이 좋다고 판단했습니다 
그래서 Slice를 반환해줬다고 봐 주시면 될 것 같습니다

2023-08-01 05:27 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/infrastructure/local/LocalStoreImageProcessor.java
> +        imageFile.transferTo(new File(fullPath));
넵 맞습니다 application-*.yml에 저장한 image.store.dir을 기준으로 이미지 저장 경로를 지정합니다

서버 환경에 따라 이미지를 저장할 경로가 변경될 가능성이 크기 때문에 외부 설정으로 분리했고, 이로 인해 외부 설정에 명시된 경로로 이미지 파일이 저장된다고 봐주시면 될 것 같습니다

2023-08-01 05:28 UTC, apptie commented on backend/ddang/src/main/resources/application-local.yml
> +    dir: ./
위에서 설명드린대로 이미지 파일이 저장될 경로를 의미합니다 
로컬에서는 그냥 애매해서 현재 위치를 상대경로를 통해 지정해주었습니다

2023-08-01 05:29 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/domain/AuctionTest.java
> +        final AuctionImage auctionImage = new AuctionImage("image.png", "image.png");
이거는 테스트라서 굳이 UUID를 통해 식별할 이유를 찾지 못했습니다

UUID를 사용한 이유는 이미지 파일 이름 중복을 방지하기 위함입니다
UUID가 아니어도 유니크한 이름이기만 하면 되지만 가장 간단한게 UUID라서 사용했다고 봐 주시면 될 것 같습니다

테스트 코드는 이미지 파일을 저장하지 않기 때문에 UUID를 지정해주지 않았습니다

2023-08-01 05:30 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/image/infrastructure/persistence/JpaAuctionImageRepositoryTest.java
> +        final Long invalidAuctionImageId = -999L;
어..저희 상수로 빼기로 했었나요? 필드로 기억하고 있었습니다

2023-08-01 05:31 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/image/infrastructure/persistence/JpaAuctionImageRepositoryTest.java
> +        final Long invalidAuctionImageId = -999L;
확인해보니 지역 변수로 빼기로 했던 것 같습니다