채팅 전송 API 추가
woowacourse-teams/2023-3-ddang pull request #155
Opened 2023-07-30 07:59 UTC by swonny

## 📄 작업 내용 요약

채팅 전송 API 추가

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- `userNotFoundException` 생성
    - 메시지 전송 시 메시지 수신자와 발신자 id를 함께 전달받습니다. 잘못된 user id가 전달된 경우 예외를 발생시키게 하기 위해 `UserNotFound`를 추가해두었습니다.
    
- POST `/chattings/{chatRoomId}/messages`
    - 채팅방 아이디를 request DTO에 포함시켜 전달받는 형태로 구현했다가 구현 예정인 채팅 메시지 조회 API 명세와 동일하게 path variable로 전달받도록 구현했습니다.

## 📎 Issue 번호

- closed #151

2023-07-30 10:24 UTC, apptie requested changes
주말 작업 고생하셨습니다
사실 별 거는 없고...개행같은 컨벤션 위주로 체크를 했습니다 ㅎㅎ; 
추가적으로 jacoco가 잡는 테스트 커버리지만 채워주시면 좋을 것 같습니다

2023-07-30 10:24 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +                             .orElseThrow(() -> new UserNotFoundException(message));
회원을 찾지 못하는 예외 케이스에 대한 테스트가 없는 것 같습니다

`Rule violated for method com.ddang.ddang.chat.application.MessageService.lambda$getUser$1(java.lang.String): lines covered ratio is 0.00, but expected minimum is 0.70`로 `jacoco`가 잡고 있네요

2023-07-30 10:24 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +                                         "지정한 아이디에 대한 채팅방을 찾을 수 없습니다."
채팅방을 찾지 못하는 예외 케이스에 대한 테스트가 없는 것 같습니다

`Rule violated for method com.ddang.ddang.chat.application.MessageService.lambda$getChatRoom$0(): lines covered ratio is 0.00, but expected minimum is 0.70`로 `jacoco`가 잡고 있네요

2023-07-30 10:24 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/exception/ChatRoomNotFoundException.java
> +    public ChatRoomNotFoundException(final String message) {
해당 부분 개행 부탁드립니다!

2023-07-30 10:24 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/MessageServiceTest.java
> +        final CreateMessageDto createMessageDto = new CreateMessageDto(chatRoom.getId(), writer.getId(), receiver.getId(), contents);
해당 라인의 글자 수가 120자가 넘는 것 같습니다!

2023-07-31 01:29 UTC, swonny reviewed
인텔리제이 설정을 안 해두어서 컨벤션이 엉망인 상태로 제출을 했네요....
다음 PR부터는 더 신경쓰겠습니다 😶‍🌫️...

2023-07-31 01:29 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +                                         "지정한 아이디에 대한 채팅방을 찾을 수 없습니다."
제 로컬에서 `jacoco`실행이 안되는 이슈가 있어서 확인을 못하고 제출했습니다 🥲 감사합니다 추가해두었어요!

2023-07-31 01:29 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +                             .orElseThrow(() -> new UserNotFoundException(message));
마찬가지로 추가해두었습니다

2023-07-31 01:29 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/exception/ChatRoomNotFoundException.java
> +    public ChatRoomNotFoundException(final String message) {
반영해두었습니다!

2023-07-31 01:29 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/MessageServiceTest.java
> +                                       .subCategory("subCategory")
넵 변경 사항 생기면 리팩토링 해두겠습니다!

2023-07-31 01:29 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
반영해두었습니다!

2023-07-31 01:29 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +                                 .alwaysDo(print()).build();
반영해두었습니다

2023-07-31 01:29 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +    }
반영해두었습니다!!

2023-07-31 01:29 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +               .andExpectAll(status().isNotFound(), jsonPath("$.message", is(userNotFoundException.getMessage())));
반영해두었습니다!

2023-07-31 01:49 UTC, JJ503 approved these changes
주말 동안 작업 고생 많으셨습니다! 👍👍👍
이미 컨벤션 관련해서는 해결이 된 것 같아 approve 합니다!
개행이 되지 않은 부분이 한 곳 있어 해당 부분만 수정해 주시면 감사하겠습니다.
또한, 궁금한 점 몇 가지가 있어 해당 부분들 확인해 주시면 감사하겠습니다!

2023-07-31 01:49 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/ChatRoomController.java
> +        return ResponseEntity.created(URI.create("/chattings/" + chatRoomId + "/messages/" + messageId))
`created()` 메서드의 파라미터 url은 location을 의미한다고 알고 있습니다.
메시지 생성을 성공했을 때 전달되는 url로 messageId가 포함되도록 하는 것이 좋을지 궁금합니다.
채팅을 보내고 해당 url로 이동할 수 있을까요?

url이 존재하지 않아도 생성된 객체의 id가 전달돼야 한다면 제 코드도 수정되어야 하기에 여쭤봅니다!

2023-07-31 01:49 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/dto/CreateMessageRequest.java
> +        String contents
`@NotNull`과 같은 어노테이션 사용 시 개행을 주기로 했었습니다!

```suggestion
        @NotNull(message = "메시지 발신자 아이디가 입력되지 않았습니다.")
        Long writerId,
        
        @NotNull(message = "메시지 수신자 아이디가 입력되지 않았습니다.")
        Long receiverId,
        
        @NotNull(message = "메시지 내용이 입력되지 않았습니다.")
        String contents
```

2023-07-31 01:49 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/MessageServiceTest.java
> +        final User receiver = createUser("수신자");
혹시 이렇게 메서드를 분리해서 생성하는 것에 대한 얘기를 한 적이 있었을까요?
기억이 나지 않아 여쭤봅니다.

만약 얘기를 하지 않았다고 해당 방법이 깔끔하다고 생각해 아예 컨벤션으로 두어도 좋지 않을까 생각합니다!

2023-07-31 06:44 UTC, kwonyj1022 requested changes
메리 수고하셨습니다. 저희 컨벤션 정해야 할 게 있는 것 같아서 회의 후 수정 해주시면 좋을 것 같아요!

2023-07-31 06:44 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +                                .getId();
이 부분 저희 컨벤션 회의해봐야 할 것 같아요. 지토의 경우 레포지토리에 save 한 후에 새로운 변수에 repository.save()의 반환값을 할당한 후 사용하더라고요.
```java
final Auction persistAuction = auctionRepository.save(auction);
```

2023-07-31 06:44 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +    public Long create(final CreateMessageDto dto) {
service에서 Long을 반환하도록 하신 이유가 있는지 궁금합니다.

제 개인적인 생각으로는 만약 클라이언트가 id 외의 다른 필드들도 응답에 필요로 할 경우 service 레이어까지 수정이 이루어져야 할 것 같아서 개인적으로는 dto를 반환하는 것을 선호합니다.

이 부분에 대해 다같이 컨벤션 회의 해보면 좋을 것 같아요!

2023-07-31 06:51 UTC, kwonyj1022 approved these changes

2023-08-01 06:46 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/dto/CreateMessageRequest.java
> +        String contents
수정해야겠다고 생각했었는데 그대로 제출했네요..... 제송함니다... 🙇🏻‍♀️

2023-08-01 06:47 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/ChatRoomController.java
> +        return ResponseEntity.created(URI.create("/chattings/" + chatRoomId + "/messages/" + messageId))
제이미가 말씀해주시고 이야기 나눴던 것처럼 유효한 uri를 전달해야 됩니다!
아직 조회 부분이 구현이 안 되었고 안드로이드와 명확한 API가 나오지 않아 추후 확정되면 반영하여 변경해두겠습니다

2023-08-01 06:57 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/MessageServiceTest.java
> +        final User receiver = createUser("수신자");
회의 때 이야기했던 방식으로 변경해두었습니다

2023-08-01 07:03 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +                                .getId();
오늘 정한 컨벤션에 맞춰 그대로 두었습니다!

2023-08-01 07:06 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +    public Long create(final CreateMessageDto dto) {
이 부분도 회의 결과에 따라 그대로 두었습니다 !!

2023-08-01 07:07 UTC, apptie approved these changes
고생하셨습니다!

2023-08-01 10:29 UTC, merged