입찰 api(등록) 추가
woowacourse-teams/2023-3-ddang pull request #156
Opened 2023-07-31 00:58 UTC by JJ503

## 📄 작업 내용 요약

입찰 api(등록) 추가

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- 몇 가지 고민 사항에 대해 todo를 통해 코드에 작성해 두었습니다. 해당 부분에 대해 확인해 주시면 감사하겠습니다.
- 추가적으로 Auction 엔티티에서 `lastBidPrice`를 가지고 있는 것이 더 좋은지 궁금합니다.
  일단 아래와 같이 생각해 auction의 lastBidPrice에 대한 업데이트를 수행하지 않았습니다.
  하지만, 두는 것이 더 좋다면 수정하도록 하겠습니다.

   - 할 수 있는 방법은 아래 두 가지
       - 마지막 lastBidPrice를 Bid 테이블에서 가져오기
       - 입찰에 성공할 때마다 Auction의 lastBidPrice 업데이트

    - 현재 선택
       - 마지막 lastBidPrice를 Bid 테이블에서 가져오기
       - 왜?
           - bid에 create를 수행했는데 Auction의 update가 이루어져도 괜찮은지 의문
           - 차라리 현재는 지금과 같이 조회를 하고 성능상 문제가 생긴다면 그때 redis 등 DB 외 메모리를 두는 편은 어떤가 싶음

- 등록 API 명세
   - requst
    
       **[ Header ]**
       `Authorization`: 2 (2 or 3이 구매자 아이디입니다.)
    
       **[ body ]**    
       `POST` /bids
    

   - response
    
       ```json
       201(CREATED)
    
       {
        	auctionId : Int(id),
        	bidPrice : Int
       }
       ```
    

   - 실패 케이스 (`400` Bad Request)
       - 종료된 경매인 경우
           - `이미 종료된 경매입니다`
       - 삭제된 경매인 경우
           - `삭제된 경매입니다`
       - 마지막 입찰 금액보다 낮은 금액을 입력한 경우
           - `마지막 입찰 금액보다 낮은 금액을 입력했습니다`
       - 잘못된 금액을 입찰한 경우 (기타)
           - `입찰 금액이 잘못되었습니다`
       - 마지막 입찰자가 다시 입찰한 경우
           - `이미 최고 입찰자입니다`

<br>

## 📎 Issue 번호

- closed #120

2023-07-31 04:05 UTC, apptie requested changes
고생하셨습니다!
request changes기는 하지만 바꿀거는 테스트 코드의 sout밖에 없고
컨벤션 관련해서 대화를 나눌만한 것들이 많아보이네요

2023-07-31 23:27 UTC, kwonyj1022 requested changes
제이미 수고하셨습니다!

lastBidPrice의 경우 경매 목록 조회나 경매 상세 정보 조회에 사용될 예정이기 때문에 그대로 두셔도 될 것 같아요!

2023-07-31 23:27 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
> +    }
이 부분도 입찰 하나를 나타내는 객체에 last bid, next bid 개념이 들어있어 약간 어색하게 느껴집니다

2023-07-31 23:27 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/presentation/BidController.java
> +        bidService.create(CreateUserDto.from(userRequest), CreateBidDto.from(bidRequest));
user를 생성하는 데 사용되는 dto가 아니라서 그런지 CreateUserDto라는 네이밍이 어색하게 느껴집니다.

2023-07-31 23:27 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java
> +    public void checkIsNotLastBidder(final Bid lastBid, final User bidder) {
클래스 내부에서만 쓰이는데 public으로 하신 이유가 궁금합니다

2023-08-01 00:58 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/bid/infrastructure/persistence/JpaBidRepositoryTest.java
> +        System.out.println(bid2.getCreatedTime());
허허... 몰래 사용했는데 들켜버렸네요... 😅

2023-08-01 01:04 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
> +    }
이 부분 저도 동의합니다 엔초의 리뷰를 보고 갑자기 보니까 생각이 났어요 

`isSmallerThanLastBidPrice`, `isSmallerThanNextBidPrice`보다는 `isSmallerThanPrice`로 통합하고 메서드의 호출 순서나 매개 변수로 넣는 값을 제어하면 좋을 것 같아요

2023-08-01 01:13 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/bid/presentation/BidControllerTest.java
> +    // TODO: 2023/07/30 [고민] 예외 상황들에 대해 모두 해주는 것이 좋을까요? 혹은 대표 예외 케이스(404, 400)에 대해서만 해줘도 괜찮을까요?
사실 목적 자체는 제 예외 처리가 제대로 되었는지 확인 용도이긴 했습니다 ㅎㅎ
어제 컨벤션 회의를 통해 해당 경우는 상위 exception 클래스가 존재하기에 넘어가기로 결정했습니다.
그래서 이번에는 넘어가고 다음부터는 모든 예외에 대해 처리를 진행하는 방향으로 가도록 하겠습니다!

2023-08-01 01:15 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/presentation/dto/CreateBidRequest.java
> +        @NotNull(message = "경매 아이디가 입력되지 않았습니다.")
오 `@Positive` 조건도 추가하면 더 좋겠네요! 👍
해당 부분 적용했습니다.

2023-08-01 01:18 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/presentation/dto/CreateBidRequest.java
> +        @NotNull(message = "입찰 금액이 입력되지 않았습니다.")
앗 notnull 동작을 안 하네요..!
Integer로 변경해두었습니다.

2023-08-01 02:30 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java
> +    private Price getPrice(final int value) {
컨벤션 회의를 통해 findPrice로 변경하기로 결정
수정하도록 하겠습니다.

2023-08-01 02:33 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
> +    // TODO: 2023/07/28 필드 관련 메서드 외 메서드 명에 getter 괜찮은가?
회의를 통해 getter를 사용하지 않기로 결정했기에 calculate로 수정하도록 하겠습니다!

2023-08-01 02:35 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java
> +        checkInvalidAuction(auction);
회의를 통해 현재 상태를 유지하기로 했기에 수정하지 않도록 하겠습니다!

2023-08-01 02:35 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
> +    public boolean isClosed() {
허허... 충돌 해결은 제 몫이 되어 버렸군요... 🥲

2023-08-01 02:36 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java
> +        }
이것도 동일하게 현상유지 하기로 했기에 수정하지 않도록 하겠습니다.

2023-08-01 02:40 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java
> +                            .getId();
save()에 대한 반환값을 사용하되 객체에 새로 할당은 하지 않기로 했기에 유지하도록 하겠습니다.
다만, dto의 엔티티 변환에 대한 객체만 만들기로 했기에 해당 부분만 수정했습니다.

2023-08-01 02:45 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
> +    }
확실히 Bid 자체에서는 `LastBidder`는 존재하지 않겠네요.. 너무 서비스 측면적인 이름...!
`isSmaeBidder`로 변경했습니다!

2023-08-01 02:52 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
> +    }
@apptie 통합하는 방식이 잘 이해가 되지 않네요..!
서로 비교 대상이 달라 분리를 한 것인데 분리하게 된다면 비교 대상을 어떻게 설정해 줄 수 있을까요?
파라미터로 받아야 할까요?

2023-08-01 02:56 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
> +    }
@kwonyj1022 @apptie 
last bid는 동의합니다. 해당 메서드 네이밍은 현재 bid와만 비교하기 위해 `isSmallerThanBidPrice()` 변경했습니다.
그런데 이도 썩 만족스럽지는 않네요...

그런데 nextBidPrice가 이상하다는 의견은 아직 와닿지 않습니다.
현재 bid를 기준으로 다음 가능한 입찰액을 의미하는 것인데 어떤 부분이 어색한 걸까요?

2023-08-01 02:59 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/presentation/BidController.java
> +        bidService.create(CreateUserDto.from(userRequest), CreateBidDto.from(bidRequest));
확실히 그렇네요..!
해당 부분은 삭제하고 다시 만들 예정이라 대충 짓기도 했고, createBidDto 만들면서 자연스럽게 그렇게 된듯합니다 😅
일단 혼란을 야기하지 않도록 LoginUser라고 수정했습니다.

2023-08-01 03:00 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java
> +    public void checkIsNotLastBidder(final Bid lastBid, final User bidder) {
메서드 위치를 계속 변경하다 생긴 문제인 듯합니다...ㅎ
private으로 수정했습니다!

2023-08-01 03:18 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/infrastructure/persistence/QuerydslBidRepositoryImpl.java
> +    // TODO: 2023/07/28 (고민) orderBy를 id와 createdTime 중 무엇으로 하는 것이 좋은가? (acution은 id임)
id가 시간 순서를 보장하지 않는다는 이야기가 있어 회의 결과를 통해 createTime으로 하기로 결정했습니다!

2023-08-01 04:55 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
> +    }
```
public boolean isSmallerThan(final Bid bid) {
    return this.price.isMoreThan(bid.price);
}

// A랑 B를 비교할 때, A가 B보다 작은지 확인해야 하는 경우
A.isSmallerThan(B);

// A랑 B를 비교할 때, B가 A보다 작은지 확인해야 하는 경우
B.isSmallerThan(A);
```

이런 방식을 말씀드리고 싶었습니다

2023-08-01 04:58 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
> +    }
근데 제가 위에 적은 내용은 제가 코드를 잘못 이해한 상황이네요
이건 무시해주셔도 될 것 같아요

2023-08-01 05:08 UTC, apptie approved these changes
고생하셨습니다
제가 코드를 잘못 이해한 이슈가 있었네요
Approve 하겠습니다

2023-08-01 06:32 UTC, swonny reviewed
제이미 이사 때문에 바쁘셨을텐데 고생 많으셨습니다 👍🏻
사소한 부분들 코멘트 달아두었는데 확인해주세요!!

2023-08-01 06:32 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/bid/infrastructure/persistence/JpaBidRepository.java
>      List<Bid> findByAuctionId(final Long id);
경매 조회의 경우 다양한 필터가 존재해 querydsl을 사용한 것으로 알고 있습니다.
입찰처럼 경매 아이디 하나만으로 조회하는 경우에는 단순하게 구현할 수 있을 것 같은데 querydsl을 사용하신 이유가 궁금합니다!

2023-08-01 06:32 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/auction/domain/AuctionTest.java
> +    void 첫_입찰자가_시작가_낮은_금액으로_입찰하는_참을_반환한다() {
오타 발견했습니다 !!!
```suggestion
    void 첫_입찰자가_시작가_보다_낮은_금액으로_입찰하는_경우_참을_반환한다() {
```

2023-08-01 06:47 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
> +        return LocalDateTime.now().isAfter(closingTime);
해당 부분을 놓쳤는데 감사합니다!
LocalDateTime.now()를 주입받는 형식으로 바뀌며 자연스럽게 해결되었습니다.

2023-08-01 07:03 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/infrastructure/persistence/JpaBidRepository.java
>      List<Bid> findByAuctionId(final Long id);
이전에는 입찰 시간으로 정렬을 진행했기에 추가적으로 들어가는 코드가 생길 수도 있기에 설정을 보다 편하게 하려고 처음부터 querydsl로 작성했습니다.
그런데 메리 말대로 id로 바뀐 이상 크게 쿼리문이 바뀌진 않을 것 같네요!
jpql로 수정했습니다!

2023-08-01 07:04 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/domain/AuctionTest.java
> +    void 첫_입찰자가_시작가_낮은_금액으로_입찰하는_참을_반환한다() {
먼산.. 🙄

2023-08-01 07:09 UTC, swonny approved these changes
제이미 멋집니다

2023-08-01 07:12 UTC, kwonyj1022 approved these changes
수고하셨습니다.

2023-08-01 07:13 UTC, merged