경매 엔티티에 판매자 필드 추가
woowacourse-teams/2023-3-ddang pull request #187
Opened 2023-08-01 12:35 UTC by apptie

## 📄 작업 내용 요약

- 경매 엔티티에 판매자 필드 추가
- DTO 일부 수정
- 테스트 일부 수정
- flyway V3 스크립트 작성
- AuctionApplication 일부 수정
  - sellter 주입 로직 추가
  - category 초기화 방식 변경 (생성자 초기화 -> 연관관계 세팅 메서드를 활용한 초기화)
## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

AuctionController.create에서 고정된 회원 1번(판매자)를 입력하도록 한 상태입니다
추후 로그인 기능이 추가되면 컨트롤러나 CreateAuctionDto등이 전반적으로 변경될 예정입니다

추가로 이전에 변경 사항이 너무 많았던 것은 제가 이상한 코드를 수정하고 있었기 때문이었습니다
처음부터 하니 비교적 금방 끝나네요 
## 📎 Issue 번호

- closed #185

2023-08-01 14:45 UTC, swonny approved these changes
경매 엔티티에 추가되어야 하지만 정작 경매에는 당장 필요하지 않은,, 필드를 만들어주시느라 고생 많으셨습니다~! 감사해요!
코드 열심히 살펴봤는데 코멘트 할 부분이 없어 approve합니다
어노테이션 질문 하나만 확인 부탁드립니다

2023-08-01 14:45 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImplTest.java
> +@IsolateDatabase
이제 레포지토리 테스트에는 해당 어노테이션을 사용하면 될까요??

2023-08-01 15:01 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImplTest.java
> +@IsolateDatabase
앗..아닙니다 이 부분은 제가 헷갈렸습니다
저 `@IsolateDatabase`는 `@SpringBootTest` 랜덤 포트 사용할 때만 쓰는거라서...
수정하도록 하겠습니다 감사합니다

2023-08-01 22:50 UTC, JJ503 approved these changes
따로 수정 사항이 보이지 않아 approve 합니다!
고생 많으셨습니다~!

2023-08-01 23:25 UTC, kwonyj1022 approved these changes
완벽하네요 역시 지토 👍

2023-08-02 00:36 UTC, kwonyj1022 requested changes
경매 삭제 시에 판매자인지 확인하는 로직이 없습니다.

2023-08-02 02:06 UTC, kwonyj1022 approved these changes

2023-08-02 02:06 UTC, merged