채팅방 목록 조회 api 추가
woowacourse-teams/2023-3-ddang pull request #197
Opened 2023-08-02 13:47 UTC by kwonyj1022

## 📄 작업 내용 요약

채팅방 목록 조회 api 추가
- 요청한 사람이 참여한 채팅방들을 조회해 옵니다.
    - 요청한 사람이  판매자인 경우
    - 요청한 사람이 구매자인 경우
## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

## 📎 Issue 번호

 
- closed #144

2023-08-02 15:04 UTC, apptie approved these changes
컨벤션 관련 하나 제외하고는 모두 좋은 것 같습니다 
고생하셨습니다

2023-08-02 15:04 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/dto/response/ReadChatPartnerResponse.java
> +
이것만 없애주시면 될 것 같습니다

2023-08-02 15:49 UTC, swonny requested changes
🍫🤎고생하셨습니다 엔쵸🍫🤎
역시 엔초는 코드도 잘 짜네요..
🍫🤎리뷰 몇 가지 남겨서 request change할게요!🍫🤎

2023-08-02 15:52 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/auth/UserIdArgumentResolver.java
> +
해당 클래스 메서드 파라미터에 `final`이 다 안 붙어 있는데 이것도 확인 부탁드립니다 🤎

2023-08-02 16:08 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/dto/response/ReadAuctionResponse.java
> +    public static ReadAuctionResponse of(ReadAuctionDto dto, String baseUrl) {
헉.. 이럴수가

2023-08-02 16:09 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/dto/response/ReadChatPartnerResponse.java
> +public record ReadChatPartnerResponse(Long id, String name, String profileImage) {
파라미터 말씀하시는 건가요? 120자가 넘지 않는다면 그냥 두어도 되지 않나요?

2023-08-02 16:11 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/ChatRoomServiceTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
넵 그렇다면 메리의 코드도 변경이 필요하겠네요! 내일 확인해보고 적용하겠습니다!

2023-08-02 16:21 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +        final List<ChatRoom> chatRooms = chatRoomRepository.findAllParticipatingChatRoomByUserId(findUser.getId());
가능성이 적긴 하지만 권한 상관없이 모든 채팅방을 조회하는 경우랑 구분시켜 주기 위해 ParticipatingChatRoom을 넣어주었는데요, 빼는 게 나을까요? 아니면 readAllParticipatingsByUserId() 이런 식으로 ChatRoom이라는 단어의 중복만 제거해도 되나요?

2023-08-03 00:58 UTC, JJ503 approved these changes
확인 완료했습니다!
별다른 수정 사항은 없어 approve 합니다.
그런데 간단하게 수정하면 좋을 것 같은 사항이 있어 해당 코멘트만 확인해주시면 감사하겠습니다.

2023-08-03 00:58 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/auth/UserIdArgumentResolver.java
> +                parameter.hasParameterAnnotation(com.ddang.ddang.chat.presentation.auth.AuthenticateUser.class);
해당 클래스에 대해 패키지 위치를 모두 작성해 줘야 인식이 되는 걸까요?

2023-08-03 00:58 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/dto/response/ReadAuctionResponse.java
> +        return new ReadAuctionResponse(dto.id(), dto.title(), imageUrl, dto.lastBidPrice());
한 번 개행해 주면 좋을 것 같아요!

2023-08-03 00:58 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/ChatRoomServiceTest.java
> +    com.ddang.ddang.chat.application.ChatRoomService chatRoomService;
클래스 외의 패키지 경로들은 지우면 좋을 것 같습니다~

2023-08-03 01:03 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/auth/UserIdArgumentResolver.java
> +                parameter.hasParameterAnnotation(com.ddang.ddang.chat.presentation.auth.AuthenticateUser.class);
다른 파일에 작성했다가 복붙했더니 이렇게 됐네요.. 수정하였습니다!

2023-08-03 01:07 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +        final List<ChatRoom> chatRooms = chatRoomRepository.findAllParticipatingChatRoomByUserId(findUser.getId());
`findAllByUserId()` 정도로 하면 유저에 따라 참여하는 방 조회하는 메서드라는 것이 드러나지 않을까 생각하는데 엔초 생각은 어떠신가요?

2023-08-03 01:09 UTC, apptie commented
`ReadUserDto가 현재는 chat/application/dto 패키지에 있습니다. 이걸 user 패키지로 옮기는 게 좋을지 일단은 chat 패키지에 있는 게 좋을지 궁금합니다.`
-> 이러한 DTO는 지금 당장은 필드가 일치하더라도 사용하는 곳에 따라서 분리하는 것이 바람직하다고 생각합니다 
그래서 전 지금 구조가 좋은 것 같습니다
나중에 user 패키지에서 뭔가 서비스에서 조회할 일이 있다면 그건 별도로 user를 작업하시는 분이 user 패키지에 새롭게 DTO를 만드는 것이 자연스러울 것 같아요 (관심사에 따라서 User 엔티티에서 조회해야하는 데이터가 달라질 가능성이 있기 때문)

2023-08-03 01:59 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +        final List<ChatRoom> chatRooms = chatRoomRepository.findAllParticipatingChatRoomByUserId(findUser.getId());
앗 그러네요 좋습니다! 수정할게용

2023-08-03 04:38 UTC, swonny approved these changes
approve 합니다.

2023-08-03 04:51 UTC, merged