경매 관련 예외 핸들링, 테스트 케이스, 문서 추가
woowacourse-teams/2023-3-ddang pull request #198
Opened 2023-08-02 14:58 UTC by apptie

## 📄 작업 내용 요약

경매 관련 예외 핸들링, 테스트 케이스, 문서 추가
## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- GlobalExceptionHandler
  - UserNotFoundException이 2개(bid, chat 패키지)가 있기 때문에 두 가지 예외에 대해 모두 핸들러를 등록했습니다
- RestDocsConfiguration
  - deprecated 된 메서드가 있어 수정했습니다
## 📎 Issue 번호

- closed #189

2023-08-02 15:18 UTC, kwonyj1022 requested changes
지토 고생하셨습니다!
`RegionApiException`, `ImageNotFoundException` 핸들링이 안 되어 있는데 이유가 있을까요?
그리고 `InvalidImagePathException`은 사용하지 않는 클래스이니 삭제하면 좋을 것 같습니다!

2023-08-02 17:47 UTC, JJ503 approved these changes
고생 많으셨습니다!
엔초가 이야기한 부분 외에 수정해야 할 부분은 따로 보이지 않아 approve 합니다.

그런데 궁금한 점이 하나 있는데 에러와 관련해서는 문서화를 굳이 하지 않아도 되는지 궁금합니다.

2023-08-03 00:55 UTC, apptie commented
@kwonyj1022 
ImageNotFoundException는 제가 놓친 부분입니다 ㅎㅎ; 추가하겠습니다
InvalidImagePathException 이것도 안쓰는군요..삭제하겠습니다

RegionApiException는 의도적으로 핸들링에서 제외했습니다
그 이유는 해당 예외는 클라이언트 측에서 요청하는 api가 아니라 애플리케이션 실행 시 단 한 번만 호출되고, 외부 설정으로 인해 아예 실행되지 않을 수 있기 때문입니다
그리고 RegionApiException이 발생했다는 것은 애플리케이션을 사용할 수 있는 최소한의 데이터조차 세팅하지 못하는 상황이라고 판단했기 때문에 GlobalControllerAdvice에서 핸들링하는 것은 자연스럽지 않다 판단했으며 이 경우 그냥 애플리케이션 실행조차 되지 않도록 하는게 맞다고 판단했기 때문이었습니다

2023-08-03 00:57 UTC, apptie commented
@JJ503 
사실 예외 상황까지 문서화하는걸 선호하기는 합니다
서로가 이해하고 있는 상태 코드가 다를 수 있다 보니..특정 상황의 요청(입력이나 기타 등등 그런것들)에 따라 어떤 상태 코드를 반환하고 어떤 메세지를 반환하는지를 다 클라이언트측에 알려줘야 한다고 생각합니다
다만 아직 저희가 커스텀 예외 쪽 정리도 안되고(대표적으로 UserNotFoundException이 여러 개 있다거나) 예외 상황까지 문서화하는 것은 너무 비용이 크다고 생각해서 그냥 정상 흐름에 대해서만 문서화를 진행했습니다

2023-08-03 01:01 UTC, JJ503 commented
@apptie 
답변 감사합니다!
예외에 대해서도 문서화를 해야 할까에 대해 계속 고민 중이었는데 지토 덕분에 해결됐네요!
예외 문서화는 하되 커스텀 예외를 모두 정리한 후에 issue를 만들어 작업하도록 하죠!

2023-08-03 01:53 UTC, swonny approved these changes
import문 관련해서 간단한 리뷰 남겼습니다!
고생하셨습니다 지토🛸

2023-08-03 01:53 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(com.ddang.ddang.bid.application.exception.UserNotFoundException.class)
패키지명이 모두 들어가있습니다!

2023-08-03 01:53 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<ExceptionResponse> handleUserNotFoundException(final com.ddang.ddang.bid.application.exception.UserNotFoundException ex) {
여기도 ..! 확인부탁드립니당

2023-08-03 02:01 UTC, kwonyj1022 approved these changes
수정 사항과 코멘트 확인 완료했습니다. 수고하셨습니다 지토

2023-08-03 04:28 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(com.ddang.ddang.bid.application.exception.UserNotFoundException.class)
해당 부분은..UserNotFoundException이 두 개라서 어쩔 수 없었습니다..
나중에 리펙토링을 해야 할 것 같아요

2023-08-03 04:28 UTC, merged