입찰 시 판매자 검증 로직 추가
woowacourse-teams/2023-3-ddang pull request #199
Opened 2023-08-02 16:55 UTC by JJ503

## 📄 작업 내용 요약

입찰 시 판매자 검증 로직 추가

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- `bidService`에서 판매자인지 확인하는 검증로직 추가
- 기존 `Bid`의 `Price`를 `BidPrice`로 변경
    - 해당 변경으로 인해 수정된 부분이 많아 대충 봐도 괜찮습니다 ㅎㅎ
- 메서드 명이 적절한지 살펴봐 주시면 감사하겠습니다!

## 📎 Issue 번호

- closed #186

2023-08-02 23:32 UTC, kwonyj1022 approved these changes
approve 하겠습니다. 수고하셨습니다!

2023-08-02 23:38 UTC, kwonyj1022 requested changes
사소하지만 단위테스트 누락된 메서드가 하나 있어서 리뷰 남겼습니다!

2023-08-02 23:38 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
>      }
`isSeller()` 에 대한 단위 테스트가 없습니다!

2023-08-03 01:01 UTC, apptie approved these changes
고생하셨습니다
사소한 건의 사항이 있지만 사소해서 approve를 하도록 하겠습니다

2023-08-03 01:01 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/BidPrice.java
> +            throw new InvalidBidPriceException(String.format("가격은 %d원 이상이어야 합니다.", MINIMUM_PRICE));
`String.format("가격은 %d원 이상이어야 합니다.", MINIMUM_PRICE)` 이 부분이 중복되니 별도의 메서드로 분리하는건 어떨까요

calculateExceptionMessage() 대충 뭐 이런식으로 네이밍하고 내부에 예외 메세지 포맷은 상수로 안빼면 충분히 가독성이 있을 것 같은 그런 느낌도 들 수 있을 것 같기도 하고요 ㅎㅎ;

2023-08-03 01:38 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
>      }
역시 꼼꼼한 엔초네요!
그런데 `isSeller()`와 중복된 코드가 존재해 `isSeller()`는 `isOwner()`와 통합했습니다.
`isOwner()`는 이미 테스트가 존재해 테스트 추가는 생략했습니다.

2023-08-03 01:51 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/BidPrice.java
> +            throw new InvalidBidPriceException(String.format("가격은 %d원 이상이어야 합니다.", MINIMUM_PRICE));
해당 부분이 중복된다는 것이 무슨 의미일까요?
하나는 `이상`, 다른 하나는 `이하`인데 메서드로 분리해도 결국 메시지와 값을 파라미터러 넣어줘야 하지 않나요?
그렇다면 달라지는 게 없어 보이는 데 구체적으로 말씀해 주시면 감사하겠습니다!

2023-08-03 01:54 UTC, kwonyj1022 approved these changes

2023-08-03 01:59 UTC, swonny requested changes
💚간단한 리뷰 남겼습니다 확인해주세요💚

2023-08-03 01:59 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/BidPrice.java
> +@ToString
`@ToString`에 of를 추가해주세요~!

2023-08-03 01:59 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/bid/domain/BidPriceTest.java
> +}
개행 추가해주세요~~

2023-08-03 02:11 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/BidPrice.java
> +@ToString
엔티티가 아닌 값 객체인데도 필요한 걸까요?

2023-08-03 04:04 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/bid/domain/BidPriceTest.java
> +}
오!
개행했습니다~

2023-08-03 04:14 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/BidPrice.java
> +            throw new InvalidBidPriceException(String.format("가격은 %d원 이상이어야 합니다.", MINIMUM_PRICE));
메세지가 같은 줄 알았습니다 죄송합니다

2023-08-03 04:17 UTC, apptie approved these changes
Approve는 그대로 유지하겠습니다
테스트에 있는거랑 flyway 스크립트가 안보여서 만약 스크립트가 없다면 추가 부탁드립니다

2023-08-03 04:17 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
> +import org.assertj.core.api.*;
별이 있습니다

2023-08-03 04:17 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/domain/AuctionTest.java
> +import org.assertj.core.api.*;
별이 생겼습니다

2023-08-03 04:17 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/bid/application/BidServiceTest.java
>  import org.assertj.core.api.*;
별이 있었습니다

2023-08-03 04:35 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/bid/domain/BidPrice.java
> +@ToString
맞네요 죄송..해요..👽

2023-08-03 04:36 UTC, swonny approved these changes
💚🎄 멜이 approve 합니다💚🎄

2023-08-03 04:40 UTC, merged