채팅방 상세 정보 조회 api 추가
woowacourse-teams/2023-3-ddang pull request #212
Opened 2023-08-05 07:13 UTC by kwonyj1022

채팅방 상세 정보 조회 api 추가
## 📄 작업 내용 요약

채팅방 목록 조회랑 거의 비슷해서 가볍게 봐주시면 될 것 같아요!
## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

## 📎 Issue 번호

- closed #145

2023-08-05 07:20 UTC, apptie approved these changes
고생하셨습니다
소소한 건의사항과 함께 approve를 하겠습니다

2023-08-05 07:20 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/ChatRoomServiceTest.java
> +        final User buyer = new User("구매자", "", 5.0);
저는 테스트 코드만 봤을 때 중간에 null string이 무슨 의미인지 몰라서 결국 User를 봐야 이해가 되었습니다
간단하게 "profile.png" 이런 식으로 이미지라는 의미를 표현해주시는건 어떨까 건의드려봅니다

2023-08-05 08:55 UTC, JJ503 requested changes
크게 수정사항은 없긴 하지만, `CharRoomController`에서 `message`와 `chatRoom`에 대한 구분이 필요하지 않을까 싶어 다른 분들의 의견이 궁금합니다!
추가적으로 컨벤션과 관련해 간단한 수정 사항 작서해두었습니다.

2023-08-05 08:55 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +            throw new UserNotAuthorizationException("권한이 없습니다.");
`User`보다는 `ChatRoom`에 권한이 없는 것이니 해당 방향으로 바꾸는 건 어떨까 싶습니다.
추후 로그인, 회원가입 등에 대한 기능이 생겼을 때 실제 계정이 없는 상태로 로그인을 하는 등에서 권한이 없는 예외와 헷갈리지 않을까 해서요.

2023-08-05 08:55 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/ChatRoom.java
> +        return isBuyer(user);
개행 추가해 주면 좋을 듯합니다!

2023-08-05 08:55 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/ChatRoomController.java
>      public ResponseEntity<CreateMessageResponse> create(
컨트롤러에서 메서드 순서가 CRUD 순서였던 것으로 기억하는데 아닐까요?
그냥 제가 혼자 그렇게 생각한 것일 수도...
만약 맞다면 `create` -> `read` -> `readAllParticipatingChatRooms` 순으로 두면 좋을 것 같습니다.

2023-08-05 08:55 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/ChatRoomController.java
>      public ResponseEntity<CreateMessageResponse> create(
제가 잘못 봤네요 `create`의 경우 chatRoom이 아닌 message에 대한 생성이었군요.
메서드 순서는 read -> readAllParticipatingChatRooms 순으로만 바꾸되 `create` 메서드 명으로 `createMessage`로 바꾸고  `read`도 `readChatRoomById`와 같이 구분이 되게 작성하는 건 어떨까 싶어요.
해당 컨트롤러에서는 예외적으로 두 서비스를 쓰는 만큼 구분이 되면 더 이해하기 쉬울 것 같습니다.
추후 채팅 방을 만드는 `create` 메서드 혹은 메시지를 `read`하는 메서드도 필요하지 않을까 싶고요.

해당 부분은 메리의 코드도 있는 만큼 메리 의견도 주시면 좋을 것 같습니다!

2023-08-06 09:43 UTC, swonny requested changes
고생하셨습니당 엔초!
몇 가지 리뷰 남겨두었습니다
확인 부탁드려요!

2023-08-06 09:43 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +    private static void checkAccessible(final User findUser, final ChatRoom chatRoom) {
`static`은 지워도 될 것 같아요!

2023-08-06 09:43 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/ChatRoom.java
> +        return isBuyer(user);
```suggestion
        return isBuyer(user) || isSeller(user)
```

이런식으로 줄일 수 있지 않을까요?!

2023-08-06 09:43 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/ChatRoom.java
> +        return auction.getSeller().equals(user);
비즈니스 로직에서 getter가 사용된 느낌이라
`auction.isSeller(user)` 로 변경해주면 어떨까 싶습니다!

2023-08-06 09:43 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/ChatRoomController.java
>      public ResponseEntity<CreateMessageResponse> create(
제이미의 의견에 동의합니다!
같은 컨트롤러를 사용한다면 네이밍으로 chatRoom과 message에 대한 CRUD임을 구분해주는 게 좋을 것 같네요.
추가적으로 지난번에 이 부분에 대해서 컨트롤러를 나누는 것에 대해서도 의견을 주셨던 것 같은데 내일 엔초랑 한 번 이야기 해보고 변경해보겠습니다

2023-08-06 09:52 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/ChatRoomServiceTest.java
> +        final User buyer = new User("구매자", "", 5.0);
좋은 의견입니다! 반영하였습니다

2023-08-06 10:36 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +    private static void checkAccessible(final User findUser, final ChatRoom chatRoom) {
오잉 static이 언제 붙었지.. 감사합니다!

2023-08-06 10:37 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +            throw new UserNotAuthorizationException("권한이 없습니다.");
좋은 의견입니다. 새로운 커스텀 예외 만들어서 적용하였고 handler에서도 상태 코드를 forbidden으로 반환하도록 수정했습니다!

2023-08-06 10:39 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/ChatRoom.java
> +        return isBuyer(user);
그러네요! 왜 이렇게 적었지? 레벨 1 다시 해야겠네요 ㅠㅠ

2023-08-06 10:40 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/ChatRoom.java
> +        return auction.getSeller().equals(user);
auction에 `isOwner()` 가 있어서 그거 사용해서 수정했습니다~

2023-08-07 09:10 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/ChatRoomController.java
>      public ResponseEntity<CreateMessageResponse> create(
메리와의 회의 결과 메시지 또한 하나의 채팅방에 대한 정보들이기 때문에 일단은 분리하지 않고 나중에 컨트롤러가 비대해진다면 분리하기로 했습니다.

2023-08-07 11:37 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +            throw new UserNotAuthorizationException("권한이 없습니다.");
오 상태코드까지! 좋습니다~!

2023-08-07 11:51 UTC, JJ503 approved these changes
수정 사항이 따로 보이지 않고 리뷰에 대한 적용도 잘 확인했습니다!
고생 많으셨습니다.

그런데 api와 관련해 궁금한 점이 있어 해당 코멘트 확인해주시면 감사하겠습니다.

2023-08-07 11:51 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/dto/ReadParticipatingChatRoomDto.java
>                  ReadAuctionDto.from(chatRoom.getAuction()),
이번 수정 사항은 아니긴 한데 궁금한 점이 있어 여쭤봅니다.
노션에 있는 api의 경우 auctin에 대한 정보로 `id`, `title`, `image`, `price`만 넘겨주고 있습니다.
그런데 `ReadAuctionDto`에는 경매 상세 정보와 동일한 정보가 들어가 모든 정보가 넘어가고 있는 것으로 보이는데 api에서 문제가 발생하지 않을까요?

아래는 노션에 올라와있는 api 명세입니다.
``` 
200(OK)

Body
{
    id: Long,
    auction: {id: Long, title: String, image: String, price: Int },
    chatPartner: {id: Long, name: String, profileImage: String},
    isChatAvailable: boolean
}
```

2023-08-07 11:59 UTC, swonny approved these changes
특별한 코멘트는 없습니다!
하나 제안드린 내용은 알고계신 방법이 있다면 반영해주시면 좋고,
그렇지 않으면 그냥 넘기셔도 될 것 같습니다

지금은 저도 방법이 떠오르지 않아서 혹시 좋은 아이디어 있으신가 의견 묻고자 코멘트 남겼습니당
고생많으셨어요 approve합니다!

2023-08-07 11:59 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +    }
이 코드를 보고 한 가지 제안 드리고 싶은 게 생각나 코멘트 남깁니당
레벨1, 2 때 배웠던 내용을 적용시켜서 checkAccessible이 chatRoom 생성자 내부에서 체크되면 좋을 것 같다는 생각이 드는데,
jpa 레포지토리를 사용하다보니 어떻게 적용할 수 있을지 잘 떠오르지 않네요..!
혹시 관련해서 좋은 방법이 있으시다면 적용해주셔도 좋고, 없다면 그냥 넘겨주셔도 좋습니다!

2023-08-07 11:59 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/ChatRoomController.java
> +    public ResponseEntity<CreateMessageResponse> createMessage(
감사합니다 엔쵸👍🏻

2023-08-07 14:52 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/dto/ReadParticipatingChatRoomDto.java
>                  ReadAuctionDto.from(chatRoom.getAuction()),
해당 부분은 service에서 controller로 넘어가는 dto이고, 컨트롤러에서 사용하는 response dto에는 api 명세와 같게 필드가 정해져 있습니다. service에서 controller로 넘어가는 dto를 모든 정보를 나타내도록 설계한 이유는 나중에 응답 값이 변하더라도 response dto만 수정하면 되도록 하고 싶어서였습니다.

이와 같은 설계를 유지한다고 했을 때 고민이 되는 점은 지금은 auction 패키지에 있는 dto를 사용하고 있는데, auction의 모든 정보를 dto에 담아서 전달하기 때문에 새로 dto를 만들지 않고 auction의 dto를 재사용했습니다. 만약 재사용하지 않고 chat 패키지에서 auction의 모든 정보를 넘겨준다는 의미의 dto를 새로 만든다면 auction 엔티티 변경으로 인해 dto의 수정이 필요할 경우 chat 패키지에 있는 dto도 수정해주어야 한다는 단점이 있을 것 같습니다. 

이런 상황에서 chatService에서 chatController로 넘어가는 chat 패키지 하위에 새로 만드는 것이 좋을지, auction 패키지에 있는 dto를 재사용하는 것이 좋을지 고민이 되는데 제이미의 의견은 어떠신가요?

2023-08-07 15:16 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +    }
chatRoom을 생성해서 auction 정보와 buyer 정보가 모두 존재하는 상태에서만 접근 권한을 따질 수 있을 것 같아서 아직은 딱히 좋은 방법이 떠오르지 않습니다. 일단은 이대로 하고 나중에 방법이 생각난다면 새로 이슈 파서 리팩토링하는 것은 어떤가요?

2023-08-08 01:02 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/dto/ReadParticipatingChatRoomDto.java
>                  ReadAuctionDto.from(chatRoom.getAuction()),
해당 부분은 제가 response로 착각해서 여쭤봤네요!
그런데 엔초가 말씀해 주신 문제점에 앞서 필요한 auction의 경우 region도 없고 이미지도 한 개만 가져오는 등 경매의 모든 정보를 가져올 필요가 없는데 경매 상세와 동일한 쿼리를 날리는 것이 좋을지 궁금합니다.
하나의 경매만 불러오므로 성능상 큰 문제는 없을까요?

2023-08-08 01:37 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/dto/ReadParticipatingChatRoomDto.java
>                  ReadAuctionDto.from(chatRoom.getAuction()),
의견 나눠본 결과 service에서 controller로 넘어가는 dto는 일단 경매의 모든 정보를 넘겨주고 나중에 성능 테스트 시 유의미한 성능 저하가 있다면 리팩토링 하는 방향으로 결정하였습니다.

현재 auction 패키지에 있는 dto를 재사용하지 않고, chat 패키지에 dto를 따로 만드는 쪽으로 수정하고 머지하겠습니다!

2023-08-08 03:10 UTC, merged