채팅방 생성 api 추가
woowacourse-teams/2023-3-ddang pull request #234
Opened 2023-08-08 14:14 UTC by kwonyj1022

## 📄 작업 내용 요약

채팅방 생성 api 추가

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

채팅방 생성 시 
- 요청 시 auction은 closed 상태여야 한다. deleted여도 안 된다.
- 요청 유저가 판매자이거나 낙찰자(lastBid의 bidder)여야 한다.
- 요청 시 이미 채팅방이 존재하는지 여부 체크한다.

## 📎 Issue 번호

- closed #228

2023-08-08 14:57 UTC, apptie requested changes
고생하셨습니다 엔초
컨벤션이랑 건의사항 몇 개 남겼는데 건의사항은 제가 코드를 잘못이해한거일수도 있으니 굳이 고칠 필요 없이 설명만 해주셔도 충분할 것 같습니다
하지만 일단 엔초의 의도가 궁금하기 때문에 request changes를 드리도록 하겠습니다

2023-08-08 14:57 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +        }
이러한 경우는 find를 통해 존재 여부를 확인하는 것보다는 chatRoomRepository에 existsByAuctionId() 메서드를 추가하고 이를 통해 존재 여부를 boolean으로 반환받아서 처리해주는것이 더 자연스러울 것 같습니다

2023-08-08 14:57 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +                        .map(chatRoom -> toDto(findUser, chatRoom))
해당 PR에는 없어서 여기에다가 남깁니다...

toDto() 메서드에서 보면 ReadParticipatingChatRoomDto.of()를 통해서 dto로 변환하고 있는데
해당 메서드의 작업을 Dto.of() 메서드로 옮겨도 될 것 같습니다
toDto()에서 findUser, chatRoom이 어떠한 작업을 통해 결과를 반환받고 이를 dto로 생성하는지 굳이 서비스에서 알 필요는 없을 것 같습니다

그래서 ReadParticipatingChatRoomDto.of(findUser, chatRoom) 혹은 시간 테스트를 조금 더 편하게 하기 위해 ReadParticipatingChatRoomDto.of(findUser, chatRoom, targetTime)으로 하고 of() 내부에 chatRoom.calculateChatPartnerOf() 이런 메서드를 호출하는건 어떨까 건의드려봅니다

2023-08-08 14:57 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +            throw new InvalidAuctionToChatException("삭제된 경매입니다.");
여기에서는 서비스에서 예외를 처리해주고 있었네요

Auction.checkWinnerExist()랑 이거랑 통일성을 지켜주는 방향은 어떨까 건의드려봅니다

2023-08-08 14:57 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/domain/AuctionTest.java
> +        User winner = new User("낙찰자", "profileImage.png", 5.0);
final이 빠진 것 같습니다

그리고 5.0보다는 double형임을 표현할 수 있게 5.0d가 좋을 것 같아요

2023-08-08 14:57 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/chat/infrastructure/persistence/JpaChatRoomRepositoryTest.java
> +            softAssertions.assertThat(actual.get().getId()).isEqualTo(chatRoom.getId());
equals()를 항상 재정의하므로 getId()로 id를 꺼내서 비교할 필요 없이 바로 객체끼리 비교하면 될 것 같습니다

2023-08-09 04:27 UTC, JJ503 approved these changes
지토가 이미 꼼꼼하게 확인해 주어 다른 수정 사항은 보이지 않네요.
그래서 저는 approve하고 지토의 판단을 믿기로 하겠습니다.
이번에도 고생 많으셨습니다 엔초! 👍👍

2023-08-09 05:25 UTC, swonny requested changes
좀전에 채팅방 생성 API에 대해 변경된 사항이 있어서 request change합니다!
나머지 부분들은 간단한 리뷰입니당
고생많으셨어요 엔초!

2023-08-09 05:25 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +    private void checkAlreadyExist(final Auction findAuction) {
변경된 부분 리마인드 차원에서 코멘트 남깁니다!

`findOrCreateChatRoomByAuction(final Auction findAuction)`이런식의 메서드로 바꾸고, 없으면 채팅방 생성해서 아이디 반환해주면 될 것 같습니다~!

지토가 말씀해주신 의견도 좋은데 boolean과 chatRoomId 조회를 위해 두 번 조회하게 될 것 같아 의견 남겨요!

2023-08-09 05:25 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/auction/domain/AuctionTest.java
> +        User winner = new User("낙찰자", "profileImage.png", 5.0);
아래 테스트에도 User 변수에는 final이 빠져있습니다!!

2023-08-09 05:25 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/auction/domain/AuctionTest.java
> +    void 경매가_종료되지_않았다면_최종_낙찰자를_구할_떄_예외가_발생한다() {
소소한 한글 오타.. 
```suggestion
    void 경매가_종료되지_않았다면_최종_낙찰자를_구할_때_예외가_발생한다() {
```

구할_떄 → 구할_때 로 변경해주시면 될 것 같습니다

2023-08-09 05:25 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/ChatRoomServiceTest.java
> +    void 해당_경매에_대한_채팅이_이미_존재할_경우_예외가_발생한다() {
이것도 리마인드 차원에서 코멘트 달아둡니당

예외 발생 대신 생성된 채팅방 아이디를 반환하도록 하면 될 것 같아요!

2023-08-09 05:25 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +    void 해당_경매에_대한_채팅이_이미_존재할_경우_400을_반환한다() throws Exception {
이것도 리마인드입니다!

채팅방 참여 가능한 유저 중
직접 채팅방을 생성하지 않은 유저가 채팅방을 조회했을 때 이미 생성된 아이디가 잘 넘어오는지에 대한 테스트도 추가되면 좋을 것 같아요!

2023-08-09 06:36 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +                        .map(chatRoom -> toDto(findUser, chatRoom))
좋습니다. 반영하겠습니다!

2023-08-09 06:41 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
> +    }
이 부분에 대해서 저도 뭔가 이상하긴 했습니다. 
우선 낙찰자를 판단하는 것은 auction 도메인에 있는 것이 적절하다고 생각했습니다.

그런데 findWinner()를 호출했는데 낙찰자가 없어서 null이 들어가게 되는 경우를 만들지 않고 싶었고,
그러려면 findWinner() 전에 낙찰자가 존재하는지 확인해야 했고,
그 findWinner()를 호출했을 때 무조건 낙찰자 존재 여부를 확인하는 것을 강제하고 싶었습니다.
그러다보니 도메인에서 예외를 터뜨리게 되었습니다.

이 부분을 어떻게 하면 잘 해결할 수 있을까요? 저도 궁금합니다..ㅠㅠ

2023-08-09 06:42 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +        if (!findAuction.isOwner(findUser) && !findAuction.isWinner(findUser, LocalDateTime.now())) {
좋은 생각입니다. 메서드가 너무 잘게 분리되어 있어서 불편하지 않을까 하는 생각에 그냥 두었는데 가독성이 안좋아졌군요..

2023-08-09 06:42 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +        }
맞네요 적용하겠습니다!

2023-08-09 06:44 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +        checkAlreadyExist(findAuction);
맞아요 아마 이 부분 경매 목록 조회 시에도 필요한 기능입니다. 경매 목록 조회 같은 경우에도 저번에 임시로 하는 바람에 dto에서 변환하고 있는 것으로 알고 있어요. 다른 분들과 이야기하고 결정하겠습니다!

2023-08-09 06:46 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/domain/AuctionTest.java
> +    void 경매가_종료되지_않았다면_최종_낙찰자를_구할_떄_예외가_발생한다() {
꼼꼼하시군요👍

2023-08-09 06:46 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +    private void checkAlreadyExist(final Auction findAuction) {
친절하네요 메..리... 👍

2023-08-09 07:20 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
> +    }
일단 findWinner() 내부에서 낙찰자가 있는지 확인하고 findWinner()는 Optional<User>를 반환하도록 수정하였습니다!

2023-08-10 03:33 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
> +    }
@kwonyj1022 확실히 좀 애매하기는 하네요 
도메인에서 낙찰자가 존재하는지 확인하는 boolean 반환 메서드와 실제 낙찰자를 반환하는 User 반환 메서드로 분리하거나
엔초가 말씀해신대로 Optional로 반환하는 방식 두 가지로 할 것 같은데

전 엔초가 지금 작성해주신 방식이 더 좋은 것 같습니다

2023-08-10 03:47 UTC, apptie requested changes
정말 고생하셨습니다..
고생하셨지만...Optional 관련해서 수정을 부탁드리고 싶은 부분이 있어서 다시..request changes를..
고생하신게 느껴져서 좀 죄책감이 느껴지네요..

2023-08-10 03:47 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
> +                             .isPresent();
```suggestion
                return this.findWinner(targetTime)
                                 .filter(user::equals)
                                 .isPresent();
```

이거는 합치는 것이 더 자연스러울 것 같습니다

2023-08-10 03:47 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +    }
이름을 경매 참여자인지? 정도로 바꿔도 좋을 것 같습니다
isAuctionParticipants() 뭐 이런식으로..?
아니면 isSellerOrWinner()로 변경해도 괜찮을 것 같기도 하고요..?

근데 이건 단순 건의사항이라 지금도 괜찮습니다 판단은 엔초에게 맡기도록 하겠습니다

2023-08-10 03:47 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/dto/CreateChatRoomDto.java
> +        return new ChatRoom(auction, nullableWinner.get());
```suggestion
        final User winner = auction.findWinner(LocalDateTime.now())
                                           .orElseThrow(() -> new WinnerNotFoundException("낙찰자가 존재하지 않습니다"));

        return new ChatRoom(auction, winner);
```

Optional이 null 체크를 수월하게 하기 위한거라서 위처럼 코드를 작성하신 것은 

```
final User nullableWinner = auction.findWinner(LocalDateTime.now()); // null 반환 가능

if (nullableWinner == null) {
    throw new WinnerNotFoundException("낙찰자가 존재하지 않습니다");
}

return new ChatRoom(auction, nullableWinner);
```

위 코드처럼 그냥 null을 반환하는 것보다 비효율적인 코드인 것 같습니다

2023-08-10 03:47 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +    void 채팅방_생성을_요청한_사용자가_경매의_판매자_또는_최종_낙찰자가_아니라면_400을_반환한다() throws Exception {
Forbidden은 403이라서 수정이 필요할 것 같습니다

2023-08-10 03:47 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
> +        return isClosed(targetTime);
```suggestion
        return auctioneerCount != 0 && isClosed(targetTime);
```

합칠 수 있을 것 같습니다 복잡하지는 않은 조건식이라 굳이 분기처리를 할 필요는 없을 것 같아서..

2023-08-10 03:50 UTC, JJ503 approved these changes
지토가 이야기해 준 부분 외에는 개행 관련 수정 사항밖에 보이지 않아 남겨두었습니다.
저는 더 이상 수정 사항이 보이지 않아 이번에도 approve하고 지토를 믿도록 하겠습니다 ㅎㅎ
고생하셨습니다!

2023-08-10 03:50 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/domain/AuctionTest.java
> +
개행 제거해 주세요!

2023-08-10 03:51 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/domain/AuctionTest.java
> +
@JJ503 어케하면 이런 코드 컨벤션? 스타일을 잘 찾으실 수 있는거죠...전 안보이는데..

2023-08-10 03:53 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +    }
isSellerOrWinner()로 하겠습니다.
처음에 participants라는 단어도 고려하였는데 결과적으로 participants라는 단어를 쓰지 않은 이유는 낙찰자 말고도 이전에 다른 입찰자들도 경매의 참여자이기 때문에 혼동의 여지가 있을 것 같아서 participants는 사용하지 않았습니다.

2023-08-10 03:56 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +    }
@kwonyj1022 아 그렇군요 이해했습니다 의견 공유해주셔서 감사합니다

2023-08-10 03:59 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/domain/AuctionTest.java
> +
충돌 해결.. 정말 어렵네요. 몇 개 있어서 제가 수정했었는데 미처 못한 게 남았었군요ㅠㅠ

2023-08-10 04:03 UTC, apptie approved these changes
정말로 고생하셨습니다...

2023-08-10 04:46 UTC, swonny approved these changes
어제 이야기했던 POST 요청 시 채팅방 아이디 반환 로직 추가된 부분과 다른 수정사항 확인했습니다!
고생 많으셨어요 엔쵸..🍫
approve합니당

2023-08-10 04:51 UTC, JJ503 requested changes
엔초 죄송해요...
갑자기 궁금해진 점이 있어 request change 해두었습니다 ㅎㅎ

2023-08-10 04:51 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +                                .orElseThrow(() -> new AuctionNotFoundException("해당 경매를 찾을 수 없습니다."));
해당 부분과 관련해 궁금한 점이 있습니다.
`find~()`에 대해 예외 메시지가 바뀔 수 있으니 모두 분리하기로 하지 않았나요?
기억이 아니지 않아 확인차 여쭤봅니다.

2023-08-10 04:51 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
>          final ChatRoom chatRoom = chatRoomRepository.findById(chatRoomId)
해당 부분과 관련해 갑자기 궁금해진 부분이 있어 여쭤봅니다.
채팅룸을 조회한 후 바로 판매자와 구매자인지에 대해 확인하는 메서드가 존재합니다.
이 경우 판매자는 auction에 존재하기에 auction을 조회하는 쿼리를 날려야 됩니다.
그래서 차라리 fetch join을 통해 채팅룸을 조회할 때 auction도 함께 가져오도록 하면 어떨지 의견을 묻고 싶습니다.

2023-08-10 06:15 UTC, JJ503 requested changes
궁금한 점이 있어 코멘트 남겨두었습니다.
해당 부분만 확인해 주시면 감사하겠습니다!

2023-08-10 06:15 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslChatRoomRepositoryImpl.java
> +    }
목록을 조회할 때도 auction관련 검증이나 필요한 정보가 있는지 궁금합니다.
api만 봤을 때는 필요가 없어 보이는데 fetch join한 이유가 궁금합니다.
제가 놓친 코드가 있는 걸까요?

2023-08-10 06:19 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslChatRoomRepositoryImpl.java
> +    }
아! 동일한 dto를 사용하기 위함일까요??

2023-08-10 06:29 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslChatRoomRepositoryImpl.java
> +    }
chatRoom에는 seller가 없고 buyer만 존재하기 때문에 auction에 있는 seller까지 함께 가져오기 위해 fetchJoin을 사용했습니다!

2023-08-10 06:30 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslChatRoomRepositoryImpl.java
> +    }
앗 제가 chatRoom에 seller가 없는 것을 잠시 간과했네요..!
확인했습니다. 답변 감사합니다!

2023-08-10 06:31 UTC, JJ503 approved these changes
답변 확인해 approve로 수정했습니다.
고생 많으셨습니다!! 👍👍👍

2023-08-10 06:49 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/dto/CreateChatRoomDto.java
> +    public ChatRoom toEntity(final Auction auction) {
해당 메서드는 테스트에서만 사용되는 메서드인 것 같아요!

그리고 dto에는 비즈니스 로직을 최대한 빼는 것이 좋을 것 같다고 생각하는데, 예외를 던지는 부분은 비즈니스 로직이라고 생각해서 dto가 아닌 다른 도메인이나 서비스에서 수행되는 것이 좋아보입니다.
만약 `toEntity()`가 다른 비즈니스 로직에서 사용된다고 한다면 winner가 없는 경우에는 null을 가지고 있던지 Optional.empty를 그대로 가지고 있게 하는 것이 좋을 것 같다는 의견입니다!

2023-08-10 06:53 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/dto/CreateChatRoomDto.java
> +    public ChatRoom toEntity(final Auction auction) {
아 그렇네요! 제거하였습니다~

2023-08-10 06:57 UTC, merged