경매 상세 조회 시 채팅방 아이디와 채팅 가능 유저 여부 함께 전송하도록 수정
woowacourse-teams/2023-3-ddang pull request #265
Opened 2023-08-10 10:30 UTC by kwonyj1022

## 📄 작업 내용 요약

경매 상세 조회 시 채팅방 아이디와 채팅 가능 유저 여부 함께 전송하는 기능 추가

고치다 보니 연관된 게 많아서 한 번에 커밋하게 됐네요ㅠㅠ

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

## 📎 Issue 번호

 
- closed #260

2023-08-10 11:16 UTC, apptie requested changes
고생하셨습니다
로직 상 반드시 수정해야 하는 부분은 AuctionService.readAuctionById()이랑 ReadChatRoomDto.of() 부분이고 나머지는 컨벤션 파트라서 개행만 없애주시면 될 것 같습니다

수정을 부탁드립니다

2023-08-10 11:16 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/ReadChatRoomDto.java
> +    public static ReadChatRoomDto of(final Optional<ChatRoom> nullableChatRoom, boolean isChatParticipant) {
메서드 매개변수로 Optional을 전달하는 것은 안티 패턴이라고 보시면 될 것 같습니다
해당 부분은 수정을 부탁드리고 싶습니다

2023-08-10 11:16 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +        final Optional<ChatRoom> nullableChatRoom = chatRoomRepository.findByAuctionId(findAuction.getId());
```suggestion
        final Long chatRoomId = chatRoomRepository.findByAuctionId(findAuction.getId())
                                          .map(auction -> auction.getId())
                                          .orElse(null);
```

Optional을 매개변수로 전달하는 것은 최대한 지양하고 Optional에서 제공해주는 메서드로 Auction을 id로 변환하는 것이 좋을 것 같습니다

2023-08-10 11:16 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +        final Optional<ChatRoom> nullableChatRoom = chatRoomRepository.findByAuctionId(findAuction.getId());
저 위에서 null을 상수로 DEFAULT_CHAT_ROOM_ID나 NOT_EXISTS_CHAT_ROOM_ID같은걸로 변경하면 조금 더 의미를 부여해줄 수 있을 것 같습니다

2023-08-10 11:16 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
> +                                                                       .description("경매 참여자 수")
이 부분 개행을 없애주시면 좋을 것 같습니다

2023-08-10 11:16 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
> +                                                                          .description("시작가"),
여기 개행이 있네요 인텔리제이 자동 정렬의 흔적..

2023-08-10 13:20 UTC, swonny approved these changes
저는 간단한 리뷰라 approve하겠습니다!
고생하셨습니다 엔초!

2023-08-10 13:20 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/ReadChatRoomDto.java
> +    public static ReadChatRoomDto of(final Optional<ChatRoom> nullableChatRoom, boolean isChatParticipant) {
boolean 파라미터에 `final`이 빠졌습니다!

2023-08-10 13:20 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
> +            @PathVariable final Long auctionId) {
해당 부분 개행이 다른 메서드들과 조금 달라서 수정 부탁드립니다

2023-08-10 19:44 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +        final Optional<ChatRoom> nullableChatRoom = chatRoomRepository.findByAuctionId(findAuction.getId());
왜 저는 이런 생각이 안날까요..😢
코드 제안 감사합니다 지토!

2023-08-10 23:24 UTC, JJ503 requested changes
몇 가지 수정 사항과 의견을 묻고 싶어 일단 rquest changes 합니다.
확인해 주시면 감사하겠습니다.
이번에도 고생 많으셨습니다~!

2023-08-10 23:24 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
> +        return isOwner(user) || isWinner(user, LocalDateTime.now());
시간의 경우 대부분 테스트가 어려다는 이유 등으로 인해 서비스에서 주입받는 것으로 알고 있는데 해당 부분은 그렇지 않아도 괜찮을까요?

2023-08-10 23:24 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
> +    public ResponseEntity<CreateAuctionResponse> create(@AuthenticateUser AuthenticationUserInfo userInfo, @RequestPart final List<MultipartFile> images, @RequestPart @Valid final CreateAuctionReques
오잉 해당 파일에 개행이 다 사라졌어요..!

2023-08-10 23:24 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +                                 .orElseThrow(() -> new CategoryNotFoundException("지정한 하위 카테고리가 없거나 하위 카테고리가 아닙니다."));
굳이 개행을 제거한 이유가 있을까요?

2023-08-10 23:24 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
> +    public ResponseEntity<CreateAuctionResponse> create(@AuthenticateUser AuthenticationUserInfo userInfo, @RequestPart final List<MultipartFile> images, @RequestPart @Valid final CreateAuctionReques
추가적으로 엔초의 configuration과 auth 패키지 내의 파일들은 삭제하고 지토 코드를 사용하면 좋을 것 같네요

2023-08-10 23:24 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ChatRoomResponse.java
> +public record ChatRoomResponse(Long id, boolean isChatParticipant) {
저희가 정한 다른 패키지의 도메인과 관련된 dto 네이밍을 따르면 좋을 것 같아요.
이 경우 `ChatRoomInAuctionResponse`가 되겠네요.

추가적으로 `Read~`에 해당하는 dto인데 `Read`를 안 붙여도 괜찮을까요?
`auction`에 있는 dto들은 대부분 엔초 방식이고, 다른 패키지들의 response dto는 컨트롤러에서 직접적으로 사용하지 않아도 `Read~`로 시작하고 있어 통일하면 좋을 것 같아 언급합니다!

2023-08-10 23:24 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
> +        mockMvc.perform(RestDocumentationRequestBuilders.get("/auctions/{auctionId}", auction.id())
엔초가 짠 코드가 아닌 걸 알긴 하지만, 해당 부분을 지금 확인해 여기에 코멘트 남깁니다.
혹시 `RestDocumentationRequestBuilders`를 제거할 수 있을까요?
또한, 다른 컨트롤러들에서는 `MockMvcRequestBuilders`를 사용했는데 다른 것에 대한 문제는 없을까요?

2023-08-10 23:24 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
> +                                                        .header(HttpHeaders.AUTHORIZATION, "Bearer accessToken"))
엔초가 짠 코드가 아니란 것을 알지만... 이것도 까먹을까 봐 남깁니다.
괄호 하나만 개행해 주세요..

2023-08-10 23:24 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
> +                                        .queryParam("size", "10")
엔초가 짠 코드가 아니란 것을 알지만... 22 이것도 까먹을까 봐 남깁니다.
`contentType()` 개행 부탁드립니다.

2023-08-11 00:55 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
> +        return isOwner(user) || isWinner(user, LocalDateTime.now());
수정하였습니다!

2023-08-11 01:24 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
> +    public ResponseEntity<CreateAuctionResponse> create(@AuthenticateUser AuthenticationUserInfo userInfo, @RequestPart final List<MultipartFile> images, @RequestPart @Valid final CreateAuctionReques
넵 시간이 오래 걸릴 것 같아 미뤄두었습니다. 오늘 안에 구현하겠습니다.

2023-08-11 01:25 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +                                 .orElseThrow(() -> new CategoryNotFoundException("지정한 하위 카테고리가 없거나 하위 카테고리가 아닙니다."));
모르겠어요. 왜 되어있는지..

2023-08-11 01:36 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
> +        mockMvc.perform(RestDocumentationRequestBuilders.get("/auctions/{auctionId}", auction.id())
@JJ503 이 부분은 제가 답변을 드려야 될 것 같습니다 제가 작성한거라..
RestDocumentationRequestBuilders는 pathvariable에 대한 명세를 작성할 때 사용해줘야 합니다 
아니면 rest docs에서 예외가 발생합니다 
그래서 주로 get으로 api 요청할 때 자주 사용되는 편입니다 (/auctions/{id} 같은 식으로 조회를 해서...)

근데 pathvariable이 없는 get 요청 시에도 RestDocumentationRequestBuilders를 사용하는 것은 부적합하다고 생각해서 pathvariable을 사용하는 곳에서만 RestDocumentationRequestBuilders을 사용하도록 했고 나머지는 MockMvcRequestBuilders으로 유지하도록 했습니다

그리고 RestDocumentationRequestBuilders이랑 MockMvcRequestBuilders은 메서드 이름이 똑같아서 둘 중 하나는 import static이 되지 않기 때문에 덜 사용하는 RestDocumentationRequestBuilders을 명시하는 식으로 진행했습니다

2023-08-11 01:37 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ChatRoomResponse.java
> +public record ChatRoomResponse(Long id, boolean isChatParticipant) {
ChatRoomInAuctionResponse 로 수정하겠습니다.

저도 Read 붙여야 하나 생각했었는데 기존 코드를 보면 controller에서 반환에 사용되는 response dto만 read를 붙인 것 같더라구요.
AuctionDetailResponse, CategoryResponse, DirectRegionResponse, SellerResponse 들은 controller에서 반환하는 response dto 안에 필드로 존재하고 있고 Read도 안 붙어 있어서, ChatRoomResponse도 controller에서 반환하는 response dto 내부 필드로 사용되는 dto이기 때문에 read를 붙이지 않았습니다.

2023-08-11 01:39 UTC, apptie approved these changes
제가 요청드렸던 부분이 모두 적용해주셔서 approve 하도록 하겠습니다
고생하셨습니다

2023-08-11 03:35 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
> +    public ResponseEntity<CreateAuctionResponse> create(@AuthenticateUser AuthenticationUserInfo userInfo, @RequestPart final List<MultipartFile> images, @RequestPart @Valid final CreateAuctionReques
auth 관련해서는 메리 pr에서 메리가 해주셨다고 해서 머지할 때 확인하겠습니다.

2023-08-11 03:52 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ChatRoomResponse.java
> +public record ChatRoomResponse(Long id, boolean isChatParticipant) {
앗 제 의견은 `auction`에 있는 response dto 외의 나머지 패키지에서는 모두 `read~` 붙이기 때문에 얘기해 보았습니다.
해당 부분은 4명이 모두 이야기해보고 정하는 것이 좋을 듯합니다.

2023-08-11 06:56 UTC, JJ503 approved these changes
해줄게요

2023-08-11 07:08 UTC, merged