채팅 메시지 조회 API 추가
woowacourse-teams/2023-3-ddang pull request #272
Opened 2023-08-10 14:36 UTC by swonny

## 📄 작업 내용 요약

채팅 메시지 조회 API 추가

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

지난 PR 리팩토링 반영한거라 반영한 부분만 봐주시면 될 것 같습니다!

### ReadMessageDto

- 메시지 조회 시 MessageService에서 ChatRoomController로 반환하는 ReadMessageDto 필드(User와 ChatRoom) 도메인 → DTO

### QuerydslMessageRepository

- user가 receiver와 일치한 경우도 메시지를 가져올 수 있도록 변경
- BooleanBuilder → BooleanExpression 으로 변경
- 메시지 조회 user가 receiver인 경우에도 메시지를 조회할 수 있는 로직 테스트 코드 추가

### ChatRoomController

- null이 대입될 수 있는 PathVariable을 RequestParam으로 변경

### MessageService

- `findXX()` 메서드 레포지토리 직접 조회하도록 변경
- 메시지 생성 시 반환하는 redirect URI 유효한 URI로 변경

## 📎 Issue 번호

 
- closed #152

2023-08-10 15:06 UTC, apptie requested changes
고생하셨습니다 메리...

lastMessageId쪽 로직이 이해가 잘 안되는데 해당 부분 설명을 부탁드리고 싶습니다
저는 request.lastMessageId()와 messageRepository.findById(request.lastMessageId).getId()가 같은 값이 나올 것 같은데 해당 부분을 repository를 거치신 이유가 궁금합니다

소소하게 Optional 메서드 관련해서 부탁드리고 싶은 부분도 있어서 일단 request changes로 하겠습니다

2023-08-10 15:06 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslMessageRepositoryImpl.java
> +            final Long lastMessageId
아 이미 querydsl을 통해서 lastMessageId를 사용하고 있다면 MessageService.readAllByLastMessageId()에서 lastMessageId를 찾아주기보다는 해당 메서드에서 찾아주는것이 더 자연스러울 것 같습니다

또한 lastMessageId가 null이 아니라면 request.lastMessageId()의 값을 그냥 그대로 써도 되지 않을까 싶은데 이건 제가 코드를 잘못 이해한 것일 수도 있습니다..ㅎㅎ;

2023-08-10 15:06 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
> +                                                                       .description("경매 참여자 수")
해당 부분 개행 제거 부탁드립니다

2023-08-10 15:06 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
> +                                                                          .description("시작가"),
여기도 뭔가 자동 개행의 흔적이...저랑 다른 분들이랑 설정이 다른가 싶네요 전 이러지않던데 음

2023-08-10 16:04 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +                                             .getId();
와우 그러네요
lastMessageId를 레포지토리에서 찾아오는 계산 로직을 추가했던 이유는 lastMessageId가 잘못된 아이디가 아닌지를 검증하는 로직이 필요했고, `findById()` 메서드를 통해 검증하려는 과정에서 생각을 잘못했었나봅니다ㅠ

`validateLastMessageId()` 메서드를 추가해 검증 로직을 대체하고, 말씀해주신 것처럼 request에서 받아온 lastMessageId를 사용하도록 변경했습니다

2023-08-10 16:06 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslMessageRepositoryImpl.java
> +            final Long lastMessageId
위 코멘트와 동일한 내용입니다!
말씀하신 것처럼 null이 아니라면 request.lastMessageId()의 값을 그대로 사용하는 것이 더 자연스럽다고 생각해 반영해두었습니다

2023-08-10 16:13 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
> +                                                                       .description("경매 참여자 수")
ㅠㅠ 이런.. 반영해두었습니다

2023-08-10 16:13 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
> +                                                                          .description("시작가"),
이것도 반영해두었습니다

2023-08-10 19:05 UTC, kwonyj1022 requested changes
수고하셨습니다 메리!
그런데 왜 메리가 작성하지 않은 코드도 file changes에 있는 거죠? 😥

2023-08-10 19:05 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslMessageRepositoryTest.java
> +        }
작성해주신 테스트만으로는 `user가 receiver와 일치한 경우도 메시지를 가져올 수 있도록 변경` 이 제대로 잘 이루어졌는지 확인이 어려울 것 같습니다.

```suggestion
        final int messagesCount = 5;
        for (int count = 0; count < messagesCount; count++) {
            final Message message1 = Message.builder()
                                           .chatRoom(chatRoom)
                                           .writer(seller)
                                           .receiver(buyer)
                                           .contents("안녕하세요")
                                           .build();
           final Message message2 = Message.builder()
                                           .chatRoom(chatRoom)
                                           .writer(buyer)
                                           .receiver(seller)
                                           .contents("반갑습니다")
                                           .build();

            messageRepository.save(message1);
            messageRepository.save(message2);
        }
```

2023-08-11 00:02 UTC, JJ503 approved these changes
제 경우 간단한 수정 사항들이기에 approve 합니다!
코드 수정 후 슬랙으로 지토 엔초와 함께 멘션만 걸어주시면 감사하겠습니다!
이번에도 고생 많으셨습니다 메리! 👍

p.s. 그런데 엔초 말대로 왜 제가 작성한 코드들도 여기에 있는 걸까요..? 😥

2023-08-11 01:26 UTC, apptie commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +name: "\U0001F41E Bug Report"
충돌 해결 과정 중 main 브랜치쪽에서 새로운 브랜치를 만드는 방식으로 작업을 해주셔서 그런게 아닐까 추측..?해봅니다

2023-08-11 01:27 UTC, apptie approved these changes
제가 말씀드렸던 부분은 다 적용해주셔서 approve로 하도록 하겠습니다
고생하셨습니다

2023-08-11 01:48 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslMessageRepositoryTest.java
> +    void 상대방이_메시지를_추가한_경우_마지막으로_읽은_메시지_이후의_메시지를_조회한다() {
### 마지막으로_읽은_메시지_이후에_추가된_메시지를_조회한다

```java
  final List<Message> messages = messageRepository.findMessagesAllByLastMessageId(
          receiver.getId(),
          chatRoom.getId(),
          lastMessageId
  );
```

### 상대방이_메시지를_추가한_경우_마지막으로_읽은_메시지_이후의_메시지를_조회한다

```java
final Long lastMessageId = 3L;
final List<Message> messages = messageRepository.findMessagesAllByLastMessageId(
        seller.getId(),
        chatRoom.getId(),
        lastMessageId
);
```

messages를 생성할 때 조회하는 userId를 seller의 아이디로 조회하는지, receiver의 아이디로 조회하는지가 다릅니다!
유저를 저장하고 저장한 아이디로 처리해야하기 때문에 `@Parameterized`를 사용하지 않았는데, 중복제거에 좋은 아이디어가 있으시다면 말씀해주시면 감사하겠습니당

2023-08-11 01:49 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslMessageRepositoryTest.java
> +        }
이 부분도 마찬가지로 message를 조회하는 유저 id가 receiver인지, writer인지로 구분해주었습니다

2023-08-11 02:02 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslMessageRepositoryImpl.java
> +    }
ChatRoom과 User를 모두 fetchJoin 할 수 없어서 ChatRoom만 fetchJoin하도록 수정했습니다!

2023-08-11 05:14 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +
맞아요....
이것도 제가 잘못 생각한 것 같슴다
반영해두었습니다!

2023-08-11 05:15 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslMessageRepositoryImpl.java
> +    }
이 부분 이유는 잘 모르겠는데 우선 chatroom만 적용해둔 상태입니다! 이 부분은 해당 PR 리팩토링 이슈 새로 파서 진행하도록 하겠습니다!

2023-08-11 05:15 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/ChatRoomController.java
> +    }
그러네요! 반영해두었습니다

2023-08-11 05:16 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +                                                            "지정한 아이디에 대한 채팅방을 찾을 수 없습니다."));
이 부분 개행 방식이 다 다른 것 같아서..! 나중에 한번 이야기해봐도 좋을 것 같아요
우선 말씀해주신 방식대로 수정해두었습니다

2023-08-11 05:16 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/ChatRoomController.java
> +            @AuthenticateUser final AuthenticateUserInfo userInfo,
바꿔두었습니다!!

2023-08-11 05:16 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/ChatRoomController.java
> +                                                                           )))
반영했습니당

2023-08-11 05:16 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/dto/request/CreateMessageRequest.java
> +@Builder
지난번에 삭제한다는걸 잊었나봅니다.. 추가했습니다!

2023-08-11 05:16 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
> +                                                                   .description("조회한 단일 경매 정보"),
ㅠㅠ 왜 개행이... 반영해두었습니다

2023-08-11 05:16 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/ChatRoomServiceTest.java
> +        final Auction auction = Auction.builder().title("경매")
반영해두었습니다

2023-08-11 05:22 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +                                                            "지정한 아이디에 대한 채팅방을 찾을 수 없습니다."));
엇 그렇군요..!
저는 지금까지 아래 형식 고정인 줄 알았네요..

2023-08-11 05:23 UTC, JJ503 commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +name: "\U0001F41E Bug Report"
😭

2023-08-11 05:46 UTC, kwonyj1022 approved these changes
메리 수고하셨습니다!

2023-08-11 05:57 UTC, merged