채팅 api 문서화
woowacourse-teams/2023-3-ddang pull request #296
Opened 2023-08-12 15:42 UTC by kwonyj1022

## 📄 작업 내용 요약

채팅 api 문서화
## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

## 📎 Issue 번호

- closed #293

2023-08-12 15:56 UTC, apptie approved these changes
고생하셨습니다
나중에 문서화쪽 충돌이 두려워지네요

2023-08-13 01:20 UTC, JJ503 requested changes
확인 완료했습니다.
내용이 많아 귀찮으셨을 텐데 문서화 고생 많으셨습니다!
몇 가지 수정하면 좋을 것 같은 부분들이 있어 해당 부분들 확인해 주시면 감사하겠습니다.

2023-08-13 01:20 UTC, JJ503 commented on backend/ddang/src/docs/asciidoc/docs.adoc
> +include::{snippets}/chat-room-controller-test/채팅방을_생성한다/request-fields.adoc[]
테스트의 restdocs 문서를 확인해 보니 request headers에 대해서도 설정을 한 것으로 보이네요.
그렇다면 아래 내용을 219줄 아래 추가해야 할 것 같습니다!
아래 다른 요청에 대해서도 부탁드립니다.

```suggestion
include::{snippets}/chat-room-controller-test/채팅방을_생성한다/http-request.adoc[]
include::{snippets}/chat-room-controller-test/채팅방을_생성한다/request-headers.adoc[]
include::{snippets}/chat-room-controller-test/채팅방을_생성한다/request-fields.adoc[]
```

2023-08-13 01:20 UTC, JJ503 commented on backend/ddang/src/docs/asciidoc/docs.adoc
> +== 채팅 API
채팅 api가 신고 관련한 api보다 중요하다고 생각해서 신고 api 위로 올라가도 좋을 것 같아요!

2023-08-13 01:20 UTC, JJ503 commented on backend/ddang/src/docs/asciidoc/docs.adoc
> +include::{snippets}/chat-room-controller-test/마지막_조회_메시지_이후_메시지를_조회한다/response-fields.adoc[]
현재 docs.html에서 해당 부분이 아래와 같이만 보이는 상태입니다.
아무래도 수정 후 build를 다시 하지 않았기 때문이 아닌가라고 생각하는데 한번 확인해 주시면 감사하겠습니다.

![image](https://github.com/woowacourse-teams/2023-3-ddang/assets/63184334/0d7b3feb-aab3-4f37-8ba0-f9708ed30e5e)

2023-08-14 09:56 UTC, swonny approved these changes
역시 엔쵸..👍🏻

2023-08-16 07:33 UTC, JJ503 approved these changes
완벽하네요!!
고생 많았어요 엔초!

2023-08-16 07:43 UTC, merged