채팅 메시지 조회 리팩토링
woowacourse-teams/2023-3-ddang pull request #322
Opened 2023-08-16 13:15 UTC by swonny

## 📄 작업 내용 요약

지난번 엔초가 달아주신 리뷰를 추후에 리팩토링으로 진행하겠다고 말씀드렸었는데, 해당 부분 적용했습니다.

- 관련 리뷰: [fetch join 관련 엔초 리뷰](https://github.com/woowacourse-teams/2023-3-ddang/pull/272#discussion_r1290540382)

문제 상황
- `ReadMessageDto` 에서 불필요한 필드(`ChatRoomDto`, `UserDto`(`writerDto`, `receiverDto`)로 인한 추가 쿼리 발생
- 비즈니스 로직이나 view 둘 다 사용되지 않는 Dto 필드 생성을 위해 조회 쿼리가 추가적으로 발생하는 상황이었습니다.

1. fetch join을 사용하여 message 조회
2. 엔티티를 변환한 Dto 대신 id를 갖도록 변경

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- chatRoom 엔티티나 user에 대한 정보가 현재 사용되지 않는다는 이유로 해당 필드를 id로 대체하는 것이 올바른지에 대해서 고민이 되어 코멘트 남깁니다. view에서 사용될 정보를 서비스에서 미리 알고 선별해주는 느낌이라 고민이 되었습니다.

## 📎 Issue 번호

 
- #321

2023-08-16 15:33 UTC, apptie requested changes
고생하셨습니다
궁금한 점이 있어서 request changes를 달도록 하겠습니다

2023-08-16 15:33 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +               );
개행 이슈가...

2023-08-16 15:33 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslMessageRepositoryImpl.java
> +                .leftJoin(message.writer).fetchJoin()
이렇게 chatRoomID, receiver, writer를 fetch join하고 있기 때문에 추가 쿼리를 피하기 위해서 fetch join을 추가한 거는 상충되는 것 같습니다 

이전 상태로 롤백하고 실행시켜보니 bidder 관련해서 추가 쿼리가 하나 발생하는 것 같은데, fetch join으로 처리하고자 하신다면 bidder를 제외한 나머지를 dto로 전달하는 것이 더 자연스러워 보입니다

2023-08-16 15:33 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslMessageRepositoryImpl.java
> +                .leftJoin(message.writer).fetchJoin()
그리고 MessageService.readAllByLastMessageId()에서 findUser(사실상 receiver)와 chatRoom을 findById를 통해 조회하는데 굳이 message를 조회할 때 추가적으로 join을 할 필요는 없어 보입니다

2023-08-16 15:33 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslMessageRepositoryImpl.java
> +                .leftJoin(message.writer).fetchJoin()
현재 dto 상태(id만 전달)에서 chatRoom, receiver, writer에 대한 fetch join을 제외해도 추가적인 쿼리는 발생하지 않아서 굳이 추가할 필요는 없어 보입니다

2023-08-16 15:33 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/dto/ReadMessageDto.java
> +                message.getReceiver().getId(),
질문하신 부분에 대한 답변은 여기다가 적어놓도록 하겠습니다 

`view에서 사용될 정보를 서비스에서 미리 알고 선별해주는 느낌이라 고민이 되었습니다.`이라고 말씀해주셨는데, 살짝 관점을 달리 해보시면 될 것 같습니다 

현재 코드를 보면 public static ReadMessageDto from(final Message message)로 Service에서 from() 메서드를 호출해줄 때 Message 도메인 엔티티를 그대로 전달합니다 
즉 서비스는 반환 타입인 ReadMesageDto에 필드가 ReadUserInChatRoomDto인지 Long인지 알지 못한다는 의미입니다
DTO 내부에서 변환 로직을 처리하다보니 서비스는 무슨 데이터가 필요한지 알 필요가 없이 단순하게 Message만 전달해 주기 때문이입니다
실제로 PR 올리신 부분에는 서비스 코드에 대한 변경사항이 단 하나도 없는 것을 확인하실 수 있습니다 
응답 타입의 변환(ReadUserInChatRoomDto -> Long)의 여파가 서비스까지 미치지 않고 DTO에서 끝나기 때문입니다 

그래서 서비스가 view에 대한 내용을 선별한다라기보다는 dto가 view에 대한 내용을 선별한다고 보시면 될 것 같습니다 
그리고 이러한 환경이 각 레이어별로 DTO를 분리한 이유이기도 합니다 

---

그래서 제 입장을 말씀드리면 `view에서 사용될 정보를 DTO에서 미리 알고 선별해주는 느낌`이라면 괜찮다고 생각하고, ` view에서 사용될 정보를 서비스에서 미리 알고 선별해주는 느낌`이라면 안 된다고 생각합니다

그리고 지금 코드 상황은 `view에서 사용될 정보를 DTO에서 미리 알고 선별해주는 느낌`이라고 생각하므로 괜찮다고 생각합니다

2023-08-16 15:33 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslMessageRepositoryImpl.java
> +                .leftJoin(message.writer).fetchJoin()
그리고 서비스에서는 안달려서...뒤늦게 관련 리뷰를 추가해보겠습니다 ㅎㅎ;

만약 receiver(findUser)가 id만 필요하다면, 인가 과정을 거쳤기 때문에 무조건 유효한 회원(탈퇴한 회원은 인가처리가 안 됨)이라고 볼 수 있을 것 같습니다

그래서 추가적인 조회가 없어도 될 것 같고, 혹은 existsBy() 정도로 검증할 수 있을 것 같습니다

2023-08-31 12:28 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +               );
해당 부분은 다른 테스트코드 개행과 동일하게 적용되어 있는 것 같은데 혹시 어떤 개행인지 알 수 있을까요?

2023-08-31 12:35 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/dto/ReadMessageDto.java
> +                message.getReceiver().getId(),
지난번에도 확인하고 동의한다는 의견인데, 전달드렸었는지 기억이 안 나네요......ㅎㅎ...
의견 감사합니다! 말씀하신 것처럼 DTO를 레이어별로 분리해주었고, 따라서 DTO에서 데이터를 선별해주는 것만으로 서비스와 프레젠테이션 레이어의 분리가 된 것 같네요

2023-08-31 13:04 UTC, kwonyj1022 approved these changes

2023-08-31 13:05 UTC, kwonyj1022 approved these changes
수고하셨습니다!

2023-08-31 18:54 UTC, JJ503 approved these changes
지토가 리뷰해 주신 부분만 수정진행하면 될 것 같아 저는 지토에게 맡기도 approve 하겠습니다!
고생 많으셨어요 메리!! 😆

2023-08-31 22:09 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +               );
제가 뭔가 이상한 곳에 리뷰를 달아버린 것 같은데 동일한 클래스 하단쯤에 rest docs 관련 responseFields() 개행에 이슈가 있었습니다

2023-09-05 06:54 UTC, apptie approved these changes
제가 말씀드린 부분은 다 적용된 것 같아서 approve 하겠습니다
고생하셨습니다

2023-09-05 07:41 UTC, merged