채팅방 관련 코드 리팩토링
woowacourse-teams/2023-3-ddang pull request #347
Opened 2023-09-07 02:33 UTC by kwonyj1022

## 📄 작업 내용 요약

채팅방 관련 코드 리팩토링
- 방학 중에 리뷰 남겨놨던 것 중 채팅방 관련된 자잘한 리팩토링 사항은 [첫 번째 커밋](https://github.com/woowacourse-teams/2023-3-ddang/commit/4b5a3cb9b7debea1b85f075b63c73fbfc96e423c)에 한 번에 반영했습니다.
- AuctionService 내의 ChatRoomService 의존성 분리 [리뷰 링크](https://github.com/woowacourse-teams/2023-3-ddang/pull/329#discussion_r1306472557)
- 마지막 메시지가 최근인 순으로 정렬하는 과정을 서비스 내에서 하지 않고 db 조회 시 정렬해서 가지고 오도록 리팩토링 [리뷰 링크 1](https://github.com/woowacourse-teams/2023-3-ddang/pull/329#discussion_r1301840003), [리뷰 링크 2](https://github.com/woowacourse-teams/2023-3-ddang/pull/329#discussion_r1301840488)

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- 관련 내용 discussion에 정리해 두었습니다. [링크](https://github.com/woowacourse-teams/2023-3-ddang/discussions/346)
- repository에서 반환하는 dto 이름을 현재 `ChatRoomWithLastMessageDto` 로 했는데요, repository에서 dto 반환하는 경우는 이번이 처음이라 네이밍 컨벤션이 없어서 대충 지었습니다. 의견 부탁드립니다.
- querydsl 사용하면서 dto 반환할 때 방법이 여러가지 있는데, 생성자 사용하는 방식이랑 `@QueryProjection` 사용하는 방식 중에 고민을 했습니다. 각 방식에 대한 설명도 [discussion](https://github.com/woowacourse-teams/2023-3-ddang/discussions/346)에 작성해 두었습니다. 둘 중 어느 방식이 더 좋을지 고민이 되는데 의견 부탁드립니다.
- 저번에 지토가 디비에서 정렬해오는 방식을 이야기해주셔서 적용하였는데, 디비에서 정렬하는 작업은 리소스가 많이 든다는 이야기를 들었습니다. 그래서 디비에서 정렬해서 가져오는 것이 맞는 것인지, 정렬을 비즈니스 로직으로 보고 서비스 계층에서 정렬하는 것이 맞는 것인지 결론이 잘 안나는데 이것도 의견 부탁드립니다.

## 📎 Issue 번호

- closed #341

2023-09-07 06:25 UTC, apptie approved these changes
고생하셨습니다! 말씀드릴 부분은 모두 팀 회의때 말씀드려서 해당 부분만 처리해주시면 될 것 같아 approve 드리도록 하겠습니다

2023-09-08 01:52 UTC, JJ503 requested changes
고생 많으셨습니다 엔초!! 
리팩토링 많이 힘들었을 텐데 확실히 코드가 정말 깨끗해졌네요 👍
그리고 코드와 디스커션을 통해 엔초가 고민한 내용들이 잘 보여 더 이해가 잘 되었습니다.
데일리 때 이야기한 내용(지토 리뷰)와 아~주 간단한 개행 이슈 하나만 있는 상태인데 수정한 내용을 확인하고 싶어 request changes로 해두겠습니다.
지토 코드 적용 후 함께 멘션해주시면 감사하겠습니다!

2023-09-08 01:52 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/dto/ReadChatRoomWithLastMessageDto.java
> +            ) {
미... 미묘하게 어긋난...

2023-09-08 01:56 UTC, JJ503 approved these changes

2023-09-08 03:13 UTC, apptie commented
앗 추가로 그 부분에 대해서도 여기다가 적어보도록 하겠습니다

`repository에서 반환하는 dto 이름을 현재 ChatRoomWithLastMessageDto 로 했는데요, repository에서 dto 반환하는 경우는 이번이 처음이라 네이밍 컨벤션이 없어서 대충 지었습니다. 의견 부탁드립니다.`
-> 네이밍은 저도 자신이 없어서 패스합니다 다만 도메인 엔티티처럼 `WithLastMessage` 같은걸 붙이는게 아닌 좀 더 명확한 표현을 하면 좋지 않을까 생각합니다 

`querydsl 사용하면서 dto 반환할 때 방법이 여러가지 있는데, 생성자 사용하는 방식이랑 @QueryProjection 사용하는 방식 중에 고민을 했습니다. 각 방식에 대한 설명도 https://github.com/woowacourse-teams/2023-3-ddang/discussions/346에 작성해 두었습니다. 둘 중 어느 방식이 더 좋을지 고민이 되는데 의견 부탁드립니다.`
-> 이건 팀 회의 때 정한 것 같습니다 

`저번에 지토가 디비에서 정렬해오는 방식을 이야기해주셔서 적용하였는데, 디비에서 정렬하는 작업은 리소스가 많이 든다는 이야기를 들었습니다. 그래서 디비에서 정렬해서 가져오는 것이 맞는 것인지, 정렬을 비즈니스 로직으로 보고 서비스 계층에서 정렬하는 것이 맞는 것인지 결론이 잘 안나는데 이것도 의견 부탁드립니다.`
-> 페이징 처리가 없다면 애플리케이션에서 정렬하는게 맞다고 생각합니다
그리고 이 역할은 서비스가 아니라 리포지토리에서 해야 할 것 같습니다 
페이징 처리를 해야한다면 강제적으로 DB에서 해야 할 수 밖에 없을 것 같습니다

2023-09-11 03:22 UTC, swonny approved these changes
엔초... 리뷰가 너무 늦어버렸네요.....
왜 했다고 생각했을까요...
고생하셨습니다!! approve합니다!

2023-09-12 05:37 UTC, apptie approved these changes
고생하셨습니다

소소한 리뷰를 남겼으므로 Approve를 유지하도록 하겠습니다

2023-09-12 05:37 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +        if (isNotSellerAndWinner(findUser, findAuction)) {
`!`랑 `i`랑 비슷해서 눈에 잘 안보였는데 `Not` 붙여서 잘 보이는 것 같습니다 👍

2023-09-12 05:37 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +            throw new UserCannotAccessChatRoomException("경매의 판매자 또는 최종 낙찰자만 채팅이 가능합니다.");
`Cannot`보다는 `Invalid`같은게 더 자연스러울 것 같은데 음....그렇습니다
전 제 네이밍에 신뢰가 없기 때문에 음 아무튼 그렇습니다

2023-09-12 05:37 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +        return !findAuction.isOwner(findUser) && !findAuction.isWinner(findUser, LocalDateTime.now());
```suggestion
        return !(findAuction.isOwner(findUser) || findAuction.isWinner(findUser, LocalDateTime.now()));
```

하나로 묶어서 앞에 !로 부정을 해주는게 더 가독성이 좋지 않을까 생각합니다 
물론 이것도 제 개인적인 의견일 뿐입니다

2023-09-12 05:37 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/ChatRoomAndMessageRepository.java
> +public interface ChatRoomAndMessageRepository {
DTO 반환용 레포지토리 분리하신거 좋네요 👍

2023-09-12 05:37 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslChatRoomRepositoryImpl.java
> +                                                  .fetchFirst();
```suggestion
        final Long findChatRoomId = queryFactory.select(chatRoom.id)
                                                  .from(chatRoom)
                                                  .where(chatRoom.auction.id.eq(auctionId))
                                                  .fetchFirst();
```

id만 찾는 것 같은데 굳이 ChatRoom 전체를 조회할 필요는 없을 것 같습니다

2023-09-12 05:37 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/dto/ChatRoomAndMessageQueryProjectionDto.java
> +    @QueryProjection
아마도 여기 개행하기로 했었던 것 같은데 확신은 없네요 다른 분들도 확인해주시리라 믿습니다

2023-09-12 06:37 UTC, JJ503 approved these changes
빠른 수정 멋지네요 엔초!
그런데 클래스 네이밍에 있어 수정한 방향은 좋지만 해당 pr에서 모두 수정하지 않는 이상 당장의 통일성이 우선이라고 생각합니다.
그리고 아주 자그마한 컨벤션 피드백 해두었습니다.
해당 부분 확인해 주시면 감사하겠습니다.
정말 고생 많으셨어요~!

2023-09-12 06:37 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/ChatRoomAndMessageRepository.java
> +public interface ChatRoomAndMessageRepository {
해당 이름으로 하게 된 이유(인터페이스로 인한 추상화)를 듣기는 했지만 이번 pr에서는 `Querydsl`을 붙여줌으로써 통일성을 위해 맞춰주는 것이 좋을 것 같습니다.
이후에 수정하는 것으로 결정이 된다면 리팩토링 이슈를 하나 만들어 한 번에 바꾸는 것이 더 좋지 않을까 생각합니다.

2023-09-12 22:15 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
> +            throw new UserCannotAccessChatRoomException("경매의 판매자 또는 최종 낙찰자만 채팅이 가능합니다.");
`InvalidUserToChat`으로 변경하였습니다!

2023-09-12 22:22 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslChatRoomAndMessageRepository.java
> +                            .fetchJoin()
왜 이렇게 되어있지요.. 이유를 모르겠네요ㅠㅠ

2023-09-13 10:54 UTC, merged