경매 목록 검색 시 제목 기반의 검색 기능 추가
woowacourse-teams/2023-3-ddang pull request #350
Opened 2023-09-07 07:38 UTC by apptie

## 📄 작업 내용 요약

경매 목록 검색 시 제목 기반의 검색 기능 추가
## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- [08.31 - 09.01 백엔드 레벨 4 계획](https://www.notion.so/08-31-09-01-93b7ab36e362461a824359b5d7677742) 기준 경매 검색 기능이 `제목`에 한정되어 있어 일단 제목만 가장 간단한 방식으로 구현했습니다
- 그래서 딱히 주의 깊은 코드는 없고 쿼리 개선 시 리펙토링 할 예정입니다 
## 📎 Issue 번호

- closed #349

2023-09-07 23:22 UTC, kwonyj1022 approved these changes
수고하셨어요 지토!
궁금한 사항 하나만 질문했습니다.

2023-09-07 23:22 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
> +            final SearchCondition searchCondition
search condition은 어떻게 받는 건지 궁금합니다. 쿼리파라미터도 아니고, `@RequestBody`도 안 붙어있어서요! 
또 홈 화면에서의 경매 목록 조회 시(검색이 아닐 시)에는 어떤 값이 들어오는 건가요?

2023-09-07 23:30 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
> +            final SearchCondition searchCondition
어노테이션을 생략한 경우 ModelAttribute로 돗작하는걸로 알고 있습니다

그래서 아무 검색도 하지 않으면 SearchCondition의 title은 null이 되고
querydsl에서 null 처리를 해주는 식으로 진행합니다

2023-09-08 01:02 UTC, JJ503 requested changes
지토 이번에도 고생 많으셨습니다!
그런데 의문점이 드는 부분이 있어 해당 부분 확인해주시면 감사하겠습니다.
또한, 지난 번에 정렬 로직을 이해하기에 바빠 테스트를 제대로 보지 못했는데 정렬과 키워드 검색의 여러 경우에 대한 테스트가 있다면 이해에 더 좋을 것 같습니다!

2023-09-08 01:08 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImplTest.java
> +                PageRequest.of(1, 1, Sort.by(Order.desc("closingTime"))),
매우매우 슬프네요 테스트 귀찮아요

2023-09-08 01:18 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +                                                              lessThanLastAuctionId(lastAuctionId),
어 그러네요 너무 간단하게 생각한거같네요 
이 부분은 좀 더 고민해보도록 하겠습니다 감사합니다

2023-09-08 01:22 UTC, swonny approved these changes
고생하셨습니다 지토!
저는 approve 하겠습니다~!

2023-09-08 01:22 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +                                                              lessThanLastAuctionId(lastAuctionId),
제이미 진짜 예리하시네요....

2023-09-08 01:27 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +                                                              lessThanLastAuctionId(lastAuctionId),
일단 그 뭐지 경매 제목 검색 쪽 검증 로직 추가 & 테스트 추가하고 
새로 이슈를 파서 경매 정렬을 처리하고 
최종적으로 경매 목록 + 경매 검색 테스트를 추가하는 식으로 진행하겠습니다

2023-09-08 07:08 UTC, JJ503 approved these changes
확인했습니다 지토!
테스트를 부탁드리긴 했지만, 해당 기능에 대한 경우의 수가 엄청 많을 것으로 예상되어 저도 벌써 무섭네요...ㅎㅎ
고생 많으셨습니다~

2023-09-08 07:52 UTC, merged