경매 목록 조회 시 정렬 기능 버그 수정
woowacourse-teams/2023-3-ddang pull request #359
Opened 2023-09-09 13:24 UTC by apptie

## 📄 작업 내용 요약

- 경매 목록 조회 시 정렬 기능 버그 수정
- 관련된 테스트 케이스 추가 (단일 제목 검색, 단일 기준 정렬, 검색 + 정렬)
  - 동일한 조건이 페이지 크기보다 크도록 더미 데이터 추가 
- no-offset에서 offset 방식의 조회 방식으로 변경 
## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- SearchTitleQueryTest / SortQueryTest / SearchAndSortQueryTest에 다양한 조건에 대한 테스트를 진행했습니다 어떤 식으로 정렬되는지 확인하실 때 보시면 될 것 같습니다 
- no-offset을 할 때 where절의 조건은 id와 같이 유니크한 컬럼이어야 했습니다...될 줄 알았는데 안되네요...
  - 이로 인해 offset 기반으로 가면서 Pageable 기반의 페이징 처리를 하게 되었습니다 
- 조건은 대충 다음과 같습니다 
  - 경매 참여자 수 기반 정렬 -> 마지막으로 조회한 경매 참여자 수 (lastAuctioneerCount)
  - 마감 임박순 기반 정렬 -> 마지막으로 조회한 마감 임박 시간 (lastClosingTime)
  - 신뢰도 기반 정렬 -> 마지막으로 조회한 신뢰도 (lastReliability)
## 📎 Issue 번호

- closed #352

2023-09-10 06:12 UTC, kwonyj1022 requested changes
수고하셨습니다 지토! 그렇지만 또 버그를 발견해 버렸습니다..

2023-09-10 06:12 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/SearchAndSortQueryTest.java
> +         */
위에 말씀드린 대로 페이지 조회 후 경매 데이터가 추가되고 난 후에 다음 페이지를 조회했을 경우를 테스트해 보기 위해 아래와 같은 테스트 케이스를 추가해 보았습니다. (틀린 경우를 더 잘 파악하기 위해 id만으로 비교하도록 했고, searchCondition이 "맥북"이어서 title을 "맥북"으로 하였습니다.)
```java
            @Test
            void 두번째_페이지_조회_후_경매_추가_후_세번째_페이지_조회_테스트() {
                // given
                final PageRequest pageRequest1 = PageRequest.of(1, 3, Sort.by(Order.desc("reliability")));
                final PageRequest pageRequest2 = PageRequest.of(2, 3, Sort.by(Order.desc("reliability")));

                // when
                final Slice<Auction> actual1 = querydslAuctionRepository.findAuctionsAllByCondition(
                        pageRequest1,
                        searchCondition
                );
                final Auction auction17 = Auction.builder()
                                               .title("맥북")
                                               .description("추가된 경매")
                                               .bidUnit(new BidUnit(1_000))
                                               .startPrice(new Price(1_000))
                                               .closingTime(LocalDateTime.now().plusDays(2))
                                               .seller(seller4)
                                               .build();
                auctionRepository.save(auction17);
                final Slice<Auction> actual2 = querydslAuctionRepository.findAuctionsAllByCondition(
                        pageRequest2,
                        searchCondition
                );

                // then
                SoftAssertions.assertSoftly(softAssertions -> {
                    softAssertions.assertThat(actual1).hasSize(3);
                    softAssertions.assertThat(actual1.getContent().get(0).getId()).isEqualTo(auction16.getId());
                    softAssertions.assertThat(actual1.getContent().get(1).getId()).isEqualTo(auction15.getId());
                    softAssertions.assertThat(actual1.getContent().get(2).getId()).isEqualTo(auction14.getId());
                    softAssertions.assertThat(actual1.hasNext()).isTrue();
                    softAssertions.assertThat(actual2).hasSize(3);
                    softAssertions.assertThat(actual2.getContent().get(0).getId()).isEqualTo(auction13.getId());
                    softAssertions.assertThat(actual2.getContent().get(1).getId()).isEqualTo(auction12.getId());
                    softAssertions.assertThat(actual2.getContent().get(2).getId()).isEqualTo(auction11.getId());
                    softAssertions.assertThat(actual2.hasNext()).isTrue();
                });
            }
```
실제로 경매 데이터 추가 후에 조회한 페이지에서는 추가한 경매 데이터 수만큼 이전에 조회됐던 데이터가 중복되어 나오게 됩니다.

2023-09-10 06:15 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/SearchAndSortQueryTest.java
> +                final PageRequest pageRequest = PageRequest.of(5, 3, Sort.by(Order.desc("reliability")));
이런 복붙의 흔적이..
다행히도 마지막 페이지 이후 요청이라 테스트 자체의 내용은 큰 이상이 없네요

2023-09-10 06:16 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/SearchAndSortQueryTest.java
> +                final PageRequest pageRequest = PageRequest.of(5, 3, Sort.by(Order.desc("reliability")));
위에랑 동일하게 마지막 페이지 이후의 요청이라 테스트 자체에는 큰 문제가 없네요 그나마 다행입니다

2023-09-10 06:31 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +                                                      .offset(pageable.getOffset())
`이 offset은 이전까지 봤던 id를 의미하는 것인가요? 개수를 의미하는 것인가요?`
-> 개수를 의미합니다  

`그 값은 알아서 측정해 주는 것인가요?`
-> 이 부분은 Spring data jpa가 자동으로 계산해준다고 보시면 될 것 같습니다 

`이게 궁금했던 이유는 만약 개수를 의미하는 경우 버그가 발생할 것 같았기 때문입니다.`
-> 이 부분은 실시간으로 페이징 처리를 하지 않는 이상 어쩔 수 없이 발생하는 문제라고 보시면 될 것 같습니다 

데이터를 추가하는 상황이 아니더라도 데이터가 변경되면 어쩔 수 없이 조회한 시점에서의 문제는 발생할 수 밖에 없다고 생각합니다 

만약 사용자가 신뢰도를 기반으로 정렬하고 이후에 조회해서 5번(5.0d), 4번(4.0d), 3번(3.0d), 2번(2.0d), 1번(1.0d)이 나왔다고 가정하겠습니다
그리고 조회 이후에 3번 상품을 올린 판매자가 다른 판매를 성사시켜 신뢰도가 4.5d로 변경되었다고 가정하겠습니다
그러면 이후 조회되는 순서는 5번(5.0d),  3번(4.5d), 4번(4.0d), 2번(2.0d), 1번(1.0d)가 되어야겠지만 이미 조회한 사용자의 화면에서는 이전과 그대로 5번(5.0d), 4번(4.0d), 3번(3.0d), 2번(2.0d), 1번(1.0d)이 출력될 것입니다 

삭제의 경우에도 마찬가지 입니다

사용자의 화면에서는 5번(5.0d), 4번(4.0d), 3번(3.0d), 2번(2.0d), 1번(1.0d)이 조회된 상태에서 3번이 마약거래를 할려고 해서 3번 글을 삭제했다고 가정하겠습니다 
그러면 실질적으로는 5번(5.0d), 4번(4.0d), 2번(2.0d), 1번(1.0d)이 되어야겠지만 사용자의 화면에서는 여전히 그대로 노출이 될 것입니다

2023-09-10 06:37 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/configuration/DescendingSortPageableArgumentResolver.java
> +    }
paegable은 0부터 시작합니다 
하지만 사용자와 클라이언트 입장에서는 페이지는 1페이지부터 시작하는게 자연스러울 것입니다 
그래서 1부터 시작하도록 입력을 받고 이를 1을 빼준 것이라고 보면 될 것 같습니다 

---

`.limit(pageable.getPageSize() + SLICE_OFFSET)    // SLICE_OFFSET  = 1L` 
-> 이 부분은 Slice를 구하기 위해서 수행하는 과정이라고 보시면 될 것 같습니다 
Slice는 다음 페이지가 존재하는지 여부를 판단하는 필드가 존재합니다 
Querydsl을 사용하지 않고 JpaRepository에서 반환값을 Slice로 두면 spring data jpa가 알아서 처리해주는데 그 과정은 지금 코드와 똑같다고 보시면 될 것 같습니다 
만약 페이지의 size가 10이라면 실제 요청하는 size에 1을 더한 11을 더하고, 이 크기가 요청한 size인 10보다 큰지 여부를 판단해주는 식으로 판단하게 됩니다 

---

정리하자면

`.limit(pageable.getPageSize() + SLICE_OFFSET)    // SLICE_OFFSET  = 1L`
-> 이 과정은 페이지에서 1을 더해주는게 아닌 페이지'사이즈'에서 1을 더해주는 과정입니다 
즉 3페이지를 요청했는데, 이 페이지 하나하나의 크기가 10이라면 11을 요청하는 과정입니다 

`return Integer.parseInt(pageParameter) - 1;`
->  ArgumentResolver에서는 페이지를 클라이언트 입장에서 0페이지부터 시작하지 않고 1페이지부터 시작하도록 OFFSET을 처리해준 것입니다

2023-09-10 06:47 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/SearchAndSortQueryTest.java
> +         */
이 과정은 실시간으로 페이징을 처리하지 않아서 생기는 자연스러운 문제라고 봐주시면 될 것 같습니다

`Slice<Auction> actual1`를 요청한 것이 오후 4시라고 가정하겠습니다 
그럼 오후 4시에는 auction16, auction15, auction14가 나오는게 당연하고 자연스러운 값일 것입니다

그리고 `auction17 `를 저장한건 오후 4시 5분이라고 가정하겠습니다
그럼 데이터에는 auction1 ~ auction16까지의 값이 아니라 auction1 ~ auction17까지의 데이터가 존재할 것입니다 
즉 `actual1`을 요청할 때의 시간인 오후 4시에는 유효한 데이터가 16개였는데, auction17을 추가한 오후 4시 5분에는 유효한 데이터가 17개가 되는 것입니다 

그래서 페이지에서의 상태가 차이가 날 수 밖에 없다고 보시면 될 것 같습니다 

다른 예시로 페이지의 크기가 5개이며 최신 순으로 정렬된 게시판이 있다고 가정하겠습니다 
만약 현재 작성된 글이 정확하게 5개라면, 순서대로 5, 4, 3, 2, 1이 1페이지에 조회될 것입니다

이후에 글을 하나 추가했다면 데이터는 6, 5, 4, 3, 2, 1이 있을 것입니다
이를 페이징 처리를 한다면은 6, 5, 4, 3, 2는 1페이지, 1은 2페이지에 있을 것입니다

이처럼 조회를 호출한 그 시점에서만 유효성을 계산해야지, 조회를 호출한 이후 데이터가 변경되었음에도 불구하고 이전 조회 결과가 일치하지 않는다는걸 버그라고 볼 수는 없을 것 같습니다 

현재 저희 앱처럼 무한 스크롤 방식이 아니라 밑에 페이징 번호가 있는 커뮤니티에서 3페이지쯤 중간 페이지로 이동하시고 계속 새로고침을 하시다보면 3페이지의 맨 위의 글이 계속 변경될 것입니다(추가된 글만큼 자리가 밀리게 될 것 같습니다)

---

이와는 별개로 작성해주신 테스트 코드는 제가 이해를 하지 못했습니다 
then절에서 16, 15, 14는 auction1, 13, 12, 11은 auction2에서 검증하고 있는데 데이터가 중복되었다는거랑 어떠한 연관이 있는지 잘 이해가 되지 않았습니다..

2023-09-10 07:06 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/SearchAndSortQueryTest.java
> +         */
actual2에는 auction13, 12, 11이 나와야 하는데, 테스트를 돌려보면 auctual1에서 이미 조회가 되었던 14를 포함해서 14, 13, 12가 나온다는 의미의 테스트였습니다.

2023-09-10 07:13 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +                                                      .offset(pageable.getOffset())
뭔가 사용자 입장에서 스크롤을 내렸는데 봤던 게시글이 다시 나오는 경우 불편할 것 같다고 생각해서 작성한 코멘트였습니다.
현재는 사용자가 많지 않으니 고려할 필요가 없을 수도 있지만 사용자가 많다는 가정하에서는 사용자가 조회하는 와중에도 수많은 경매글이 추가될 것입니다. 지금 디폴트 사이즈는 10이라 10개씩 조회하고 있는데 페이지를 내리는 와중에 10개의 경매글이 상위에 추가된다면 이미 봤던 10개가 밑에 스크롤에 나오게 된다면 불편하지 않을까요?

lastAuctionId를 추가로 받아서 정렬에 활용하는 방식은 너무 복잡할까요?
지금 상태에서 추가로 조회할(다음 페이지에서 보여줄) 데이터 중 첫 번째 데이터를 기준으로 쭉 밑으로 내려가면서 lastAuctionId와 일치하는 row 이후의 row부터 조회하는 방식으로 한다면 어느 정도 해결이 가능할 것 같은데 구현이 좀 복잡해질 것 같기도 하네요..

2023-09-10 07:15 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/configuration/DescendingSortPageableArgumentResolver.java
> +    }
그렇군요 이해가 되었습니다! 답변 감사합니다!!

2023-09-10 07:41 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +                                                      .offset(pageable.getOffset())
lastAuctionId를 추가로 받아서 정렬에 활용하는 방식은 불가능합니다 
정렬의 대상이 되는 컬럼이 중복되어서는 안되기 때문입니다

신뢰도가 4.5d인게 여러 개 있을 때 lastAuctionId도 같이 사용한다면 문제가 생기는 상황은 다음과 같습니다
하나 당 페이지 크기는 2개라고 가정하겠습니다

lastAuctionId도 내림차순 정렬하는 경우 : id < lastAuctionId

정렬된 데이터의 순서는 다음과 같다고 가정하겠습니다

16번, 15번, 21번, 1번, 14번, 13번, 27번, 26번

그럼 조회 결과는 다음과 같을 것입니다 
1페이지 -> 조건 : 아무 조건없음 / 출력 결과 : 16번, 15번 / lastAuctionId : 15번 
2페이지 -> 조건 : lastAuctionId : 15번 / 출력 결과 : 21번, 1번 / lastAuctionId : 1번
3페이지 -> 조건 : lastAuctionId : 1번 / 출력 결과 : x / lastAuctionId : x 

와 같이 문제가 발생할 수 있습니다 
반대의 경우도 동일합니다 

즉 id는 불변하고, 순서를 항상 보장하고, 중복되지 않기 때문에 no-offset을 활용해 사용할 수 있었지만
신뢰도와 같은 나머지 정렬 조건은 불변하지도, 순서를 보장하지도, 중복되기 때문에 이러한 방법이 불가능하며 
이러한 정렬 조건으로 인해 pk까지 영향을 받아서 사실상 불가능합니다 

---

정리하자면 이러한 문제가 발생한 이유는 
1. pk와 동일한 unique를 갖지 못하는 컬럼을 기준으로 정렬하려고 했기 때문
2. 일반적인 페이징의 게시글 형식이 아닌 무한 스크롤 방식으로 UI를 사용했기 때문

이라고 보시면 될 것 같습니다 

---

`뭔가 사용자 입장에서 스크롤을 내렸는데 봤던 게시글이 다시 나오는 경우 불편할 것 같다`라는 의견은 동의합니다

다만 저는 이게 버그라기보다는 UI의 장단점을 택했다고 생각했습니다 
밑에 페이지 번호 있고 이걸 누르는 방식이라면 페이지 번호에 따라서 누르면 되니까 말씀하신 문제는 최대한으로 해소할 수 있겠지만 앱이라는 특성상 스크롤을 쭉 내리는 방식이 아니라 페이지 번호를 눌러야한다는 문제점, 스크롤이 위로갔다 아래로갔다 하는 불편함 대신 

스크롤을 밑으로 쭉 내리면서 페이지를 누를 필요는 없지만 중간중간 데이터의 중복이 발생할 수 있는 방법을 선택했다고 판단했습니다

2023-09-10 08:08 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +                                                      .offset(pageable.getOffset())
지금 당장 생각나는 개선 방식은 대충

결국 중복된 데이터를 방지할 수 있도록 후처리를 해야 한다는 것인데
서버에서 어떤 데이터를 전송했는지 알 수 없기 때문에(stateless)

1. 클라이언트에서 여태까지 받은 정보를 요청할 때 마다 다시 전송
2. 서버 메모리가 아닌 다른 공간에서 보낸 데이터를 캐싱처리해 보관 

하는 방식으로 어떤 데이터를 보냈는지 확인하고 그에 맞는 조건이 될 때 까지 반복해서 필터링하는건데 

첫 번째 방식의 경우 뒤에 있는 페이지를 요청할 때 마다 요청으로 포함해야 하는, 여태까지 조회한 모든 데이터를 전달해야 한다는 문제점이 있을 것이고
두 번째 방식의 경우 각 요청마다 어떤 데이터를 보냈는지를 항상 관리해야한다는 점, 그리고 캐싱된 데이터를 경매 목록 조회라는 변경되기 매우 쉬운 데이터를 항상 캐싱처리해야한다는 점이 있겠고

둘 모두의 문제점이라면은 조회 쿼리가 유효할때까지 결과를 비교하고 재실행해야한다는 점이 있겠네요 

그 외에는 떠오르지가 않는데 음 어케해야할지 모르겠네요

2023-09-10 16:24 UTC, swonny approved these changes
특별한 점은 찾지 못해 approve합니다!
엔초의 날카로운 리뷰에 대한 해결방법은 저도 한번 열심히 생각해볼게요.....
고생하셨습니다 지토

2023-09-11 03:43 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/configuration/DescendingSortPageableArgumentResolver.java
> +    }
아무래도 잏를 돕기 위해선 매직 넘버에 대한 상수 처리가 필요할 것 같습니다. (이름을 뭐라고 해야 할지 애매하긴 하지만...)
원래 우테코 컨벤션 처럼 매직 넘버는 모두 상수로 관리해주면 어떨까요?

2023-09-11 03:46 UTC, JJ503 approved these changes
저도 엔초가 말한 부분으로 대부분 이해되어 추가적으로 문제가 되는 부분은 발견하지 못했네요!
고생 많으셨습니다 지토!

2023-09-11 07:32 UTC, kwonyj1022 approved these changes
수고하셨습니다 지토!

2023-09-11 07:59 UTC, merged