사용자 정보 수정 기능 추가
woowacourse-teams/2023-3-ddang pull request #361
Opened 2023-09-09 14:16 UTC by JJ503

## 📄 작업 내용 요약

사용자 정보 수정 기능 추가

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- TODO를 이용해 [고민]이라고 작성해 둔 부분이 있습니다. 해당 부분들에 대한 의견을 주시면 감사하겠습니다.
- dto 중 baseUrl로 인해 파라미터가 2개 이상이라 of 였던 정팩메를 baseUrl이 없어짐에 따라 from으로 변경했습니다.
- 테스트 전체적으로 많은 수정이 일어났습니다. 오류는 발생하지 않지만, 확인해 주시면 감사하겠습니다.

## 📎 Issue 번호

- closed #353

2023-09-09 15:58 UTC, apptie requested changes
고생하셨습니다
(제가 만들어버린) 레거시 코드 개선을 해주셔서 감사합니다 
하지만 이름...ImageUrlBuilder의 이름을 다른걸로 바꿔주시면 좋겠어서 request  changes를 하도록 하겠습니다 

TODO쪽은 해당 주석쪽에 제 의견을 남겼습니다
다른 분들의 의견이 많이 궁금한 PR이네요

2023-09-09 15:58 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/ReadAuctionDto.java
> +    private static List<Long> convertImageIds(final Auction auction) {
전 변경하신 지금의 네이밍이 좋은 것 같습니다
제 네이밍 센스가 부족함을 다시 한 번 깨닫네요 슬픕니다...

2023-09-09 15:58 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/CreateAuctionResponse.java
> +                getAuctionImageUrl(dto.auctionImageId()),
네이밍은 get()이라서 단순 조회라는 생각이 드는데 실제 수행하는건 `calculate()`라 살짝 어색한 것 같습니다 
물론 전 제 네이밍을 믿지 않기때문에 다른 분들의 의견도 궁금하네요

2023-09-09 15:58 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadAuctionDetailResponse.java
> +        final SellerResponse sellerResponse = SellerResponse.from(dto.auctionDto());
👍

2023-09-09 15:58 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/domain/Image.java
> +// TODO: 2023/09/08 [고민] 아니면 AuctionIamge가 Image를 상속받는 형태는 어떻게 생각하시나요?
`현재는 프로필 이미지만 담당하지만, 추후 Q&A, 채팅에 이미지가 사용될 수 있을 것 같아 Image로만 이름을 지었는데 의견 부탁드립니다.`
-> 이 부분 좀 애매하네요...
단순하게 DB 관계를 생각하면 Q&A나 채팅이나 하나만 쓰기 때문에 하나로 통일할 수 있겠지만 
이미지 리소스를 어떤 식으로 관리할지를 고려하면 하나의 Image 엔티티로 프로필 이미지, Q&A, 채팅 등의 이미지 리소스를 모두 관리하는, 동일한 라이프사이클을 가지게 할지 좀 고민이 되긴 합니다

결국 이미지도 어딘가에 저장을 해야 하니 비용이 발생해서 언젠가는 지울 것 같은데
제가 생각한 내용은 
경매 관련 이미지(경매 이미지 / Q&A 이미지)는 모두가 볼 수 있기도 하고 중요한 내용이니 최대한 오래 가져가거나 지우지 않고 압축하는 방법을 사용할 것 같고 
사용자 프로필 이미지는 어처피 바꿀 때마다 업로드 할 테니까 안쓰는건 즉각즉각 삭제할 수 있을 것 같습니다 
채팅에 올린 사진 또한 경매가 종료되면 잘 안볼테니까 경매보다는 짧게 가져가지만 사용자 프로필보다는 길게 가져갈 것 같기는 하고...

그래서 이런걸 고려한다면 각 이미지의 정책이 달라질 수 있어서 하나로 묶어서 관리하는게 맞을지 모르겠습니다
상관없나 싶기도 하고요...다른 분들의 의견이 궁금하네요 

`아니면 AuctionIamge가 Image를 상속받는 형태는 어떻게 생각하시나요?` 
-> 상속은 좋을 것 같습니다 
BaseTimeEntity처럼 이미지가 무조건 가져야 하는 속성인 `uploadName`과 `storeName`은 어떤 이미지 엔티티가 들어오든지 저장은 해야하니까 좋은 방향인 것 같습니다 
다만 Embedded로 할지 상속으로 할지만 결정하면 되겠네요 
Embedded가 조금 더 간단할 것 같기도 하고 저는 개인적으로 상속보다는 Embedded가 나아 보이기는 합니다만 이것도 다른 분들의 의견이 궁금하네요

2023-09-09 15:58 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/domain/StoreImageProcessor.java
> +import java.util.List;
?? 무슨 차이일까요 이건

2023-09-09 15:58 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/infrastructure/local/LocalStoreImageProcessor.java
> +// TODO: 2023/09/08 [고민] 제가 지토 코드 맘대로 수정했는데 괜찮을까요?
당연히 괜찮습니다
레거시 코드 잘 개선해주신 것 같습니다

지금 보면 제가 왜 이렇게 괴상하게 메서드를 분리했는지 모르겠네요 
과거의 저는 참...그렇습니다

2023-09-09 15:58 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/util/ImageUrlBuilder.java
> +// TODO: 2023/09/08 [고민] 이미지 util의 패키지 위치는?
이미지...관련 쪽이니까 일단 image 패키지 쪽에 두신 것은 자연스러운 것 같습니다
다만 이게 응답 쪽 유틸이니까 presentation이나 presentation 내부에 response 패키지 추가하고 여기에 util 패키지에 놓는게 저는 좀 더 자연스러울 것 같습니다

다른 분들의 의견도 궁금하네요

2023-09-09 15:58 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/util/ImageUrlBuilder.java
> +public class ImageUrlBuilder {
이름이 Builder면 사실 디자인 패턴 중 Builder를 쓴걸로 연상되기 심해서 다른 이름이었으면 좋겠습니다

calculate니 ImageUrlCalculator 같은거 어떠신가요
아니면 다른것도 괜찮고 아무튼 Builder만 아니었으면 좋겠습니다

2023-09-09 15:58 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/util/ImageBaseUrl.java
> +package com.ddang.ddang.image.util;
해당 enum은 ServletUriComponentsBuilder에 의존하고 있으니 presentation 패키지 쪽으로 옮기는게 조금 더 자연스럽지 않을까 생각합니다

2023-09-10 07:57 UTC, kwonyj1022 requested changes
엄청난 files changed를 보니 제이미의 노고가 느껴지네요..
머지 시 충돌이 두렵습니다.. ㅎㅎ

2023-09-10 07:57 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +                             .map(StoreImageDto::toAuctionEntity)
해당 toAuctionEntity는 Auction이 아니라 AuctionImage를 반환하고 있으므로 메서드 이름을  toAuctionImageEntity로 하는 것은 어떨까요? 처음 메서드를 봤을 때 Auction을 반환할 거라는 생각이 들었습니다.

2023-09-10 07:57 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/ReadAuctionDto.java
> +    private static List<Long> convertImageIds(final Auction auction) {
저도 id를 반환하기 때문에 바뀐 네이밍이 더 명확하다고 생각합니다! 감사합니다~

2023-09-10 07:57 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/CreateAuctionResponse.java
> +                getAuctionImageUrl(dto.auctionImageId()),
저도 단순 getter 말고는 calculate나 process 같은 네이밍을 사용하기로 했던 저희 컨벤션에 따라 수정하면 좋을 것 같다고 생각합니다!

2023-09-10 07:57 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/configuration/initialization/InitializationUserConfiguration.java
> +                                 .profileImage(new Image("upload.png", "updateImage.png"))
서버에도 해당 이름의 이미지가 저장되어 있는 상태인가요?

2023-09-10 07:57 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/image/domain/Image.java
> +// TODO: 2023/09/08 [고민] 아니면 AuctionIamge가 Image를 상속받는 형태는 어떻게 생각하시나요?
auction image와 profile image 등 image별로 서로 다른 엔티티를 만드는 것이 좋을 것 같습니다. 잘 생각은 나지 않지만,, 이미지에 도메인 로직이 생길 수도 있지 않을까 해서요. 예를 들어 경매 이미지의 경우 앱 카메라를 통해 찍은 사진이라던가 뭐 그런거..
embedded와 상속 중에서 뭐가 좋을지는 모르겠네요. 좀 더 공부해보겠습니다.

2023-09-10 07:57 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/image/util/ImageUrlBuilder.java
> +// TODO: 2023/09/08 [고민] 이미지 util의 패키지 위치는?
저도 response 패키지에 있어도 좋고 그냥 response 패키지 따로 안 만들고 presentation 패키지 내에 있어도 상관없을 것 같아요.

2023-09-10 07:57 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/user/application/UserService.java
> +
updateById를 호출하는 controller는 없는 건가요?
또, 닉네임만 수정하는 경우에도 imageProcessor.storeImageFile()이 호출되는 것이라면 비효율적일 것 같습니다..

2023-09-10 15:18 UTC, swonny requested changes
바쁘실텐데 고생하셨습니다 제이미ㅠ..ㅠ
리뷰가 늦어져 죄송해요 ...🥲
제가 남긴 리뷰는 간단한 부분인데 다른 분들이 남긴 리뷰 반영된 것도 확인해보고싶어 request changes 하겠습니다!

2023-09-10 15:18 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/image/application/ImageService.java
> +        return new UrlResource("file:" + fullPath);
해당 메서드와 아래 readAuctionImage() 메서드 모두 `"file:"`을 String으로 생성해주고 있는데, 이 부분을 `findFullPath()` 메서드가 함께 생성해서 반환해주는건 어떤가요..?

그리고 findFullPath() 메서드 파라미터에 final이 누락되었슴당

2023-09-10 15:18 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/ImageController.java
> +        HttpHeaders headers = new HttpHeaders();
`final`이 누락된 것을 발견해버렸습니다.... 

아래 메서드에도 동일하게 `headers` 변수에 final이 누락되어 있네요!

2023-09-10 15:18 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/CreateAuctionResponse.java
> +                getAuctionImageUrl(dto.auctionImageId()),
저도 동의합니다!

2023-09-11 07:38 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/CreateAuctionResponse.java
> +                getAuctionImageUrl(dto.auctionImageId()),
`convert`로 변경하겠습니다!

2023-09-15 00:49 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/domain/Image.java
> +// TODO: 2023/09/08 [고민] 아니면 AuctionIamge가 Image를 상속받는 형태는 어떻게 생각하시나요?
회의에서 이야기했던 대로 `embedded`를 적용해 두었습니다.

그리고 예시라고 하긴 하지만, profile과 auction은 이미 다르다고 가정을 했기에 신경 쓰지 않고 profile과 q&a의 이미지, 채팅의 이미지와 비교가 적절하다고 생각합니다.
auctioin의 경우는 생명주기와 상관없이 이미 필드가 다르기에 다른 이미지로 생각해야 하기 때문에 예시로 적절하지 않은 것 같아 처음에 이해가 어려웠습니다.
그래서 서로의 이해를 위해 한번 언급합니다!

2023-09-15 00:53 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/domain/StoreImageProcessor.java
> +import java.util.List;
그냥 각 Intellij의 import 정렬 설정이 다른 듯합니다.
해당 부분 외에도 정렬하면 항상 import 순서가 변경되더라고요...

2023-09-15 01:40 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/util/ImageUrlBuilder.java
> +public class ImageUrlBuilder {
ImageUrlCalculator로 수정했습니다!

2023-09-15 01:43 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +                             .map(StoreImageDto::toAuctionEntity)
해당 방식으로 수정해보았습니다.
그렇다면 Entity의 경우는 잘 이해되는지 궁금합니다.

2023-09-15 01:56 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/configuration/initialization/InitializationUserConfiguration.java
> +                                 .profileImage(new Image("upload.png", "updateImage.png"))
헉...! 아닌 것 같아요.
엇 그런데 필요한가요??

2023-09-15 01:58 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/user/application/UserService.java
> +
> updateById를 호출하는 controller는 없는 건가요?

-> ㅎㅎ 컨트롤러를 까먹었지 뭡니까? 컨트롤러는 추가해 두었습니다.

> updateById를 호출하는 controller는 없는 건가요?
또, 닉네임만 수정하는 경우에도 imageProcessor.storeImageFile()이 호출되는 것이라면 비효율적일 것 같습니다..

-> 그런데 어떻게 구별할 수 있을지에 대한 아이디어가 떠오르지 적용하지 못했는데 않는데 혹시 생각나는 아이디어가 있을까요?

2023-09-15 01:59 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/util/ImageBaseUrl.java
> +        return ServletUriComponentsBuilder.fromCurrentContextPath().build().toUriString()
앗 왜 그렇게 되었을까요 수정해 두었습니다!

2023-09-15 02:07 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/infrastructure/local/LocalStoreImageProcessor.java
> +        } catch (IOException e) {
미션 때문에 e가 갑자기 익숙해져 버렸네요...ㅎㅎ
수정해 두었습니다!

2023-09-15 02:08 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/application/ImageService.java
> +        return new UrlResource("file:" + fullPath);
제가 작성한 코드가 아니라 메서드 분리만 해서 꼼꼼하게 보지 못했네요..!

2023-09-15 02:08 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/ImageController.java
> +        HttpHeaders headers = new HttpHeaders();
제가 작성한 코드가 아니라 메서드 분리만 해서 꼼꼼하게 보지 못했네요..!22

2023-09-15 03:02 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/application/ImageService.java
> +        return new UrlResource("file:" + fullPath);
@JJ503 @swonny 
`file:`은 FTP 프로토콜임을 명시하기 위해서 적은 접두사이고
`findFullPath()`는 로컬에 저장되어있는 이미지의 절대 경로를 의미합니다 

그래서 이건 용도가 다른거라 분리가 되어야 할 것 같습니다 
혹은 `calculateProtocolUrl()`같이 프로토콜의 전체 url을 구하는 메서드로 분리하고 `calculateProcotolUrl()` 내부에서 `findFullPath()`를 호출하거나 해야할 것 같습니다 

final은....전 컨벤션이 뭔지 모르는게 틀림없는거 같습니다

2023-09-15 03:02 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/ImageController.java
> +        HttpHeaders headers = new HttpHeaders();
죄송합니다

2023-09-15 03:06 UTC, JJ503 commented
### API도 한번 확인 부탁드립니다!
**Request**

`PATHCH` /users

```java
{
		name: String
		profileImage: MultipartFile
}
```

**Response**

```java
200 OK

{
		name: "updateName" (String),
		profileImage: "updateIamge" (String)
		reliability: double
}
```

2023-09-15 03:23 UTC, apptie commented
API의 response의 각 항목이 조금 헷갈리는데 
updateName은 회원 닉네임(별명?)이고 profieImage는 이미지 url인가요?

2023-09-15 03:29 UTC, apptie approved these changes
일단 제가 언급한 부분에 대해서는 다 개선이 된 것 같다고 생각해 approve로 하겠습니다

2023-09-15 03:36 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +                             .map(StoreImageDto::toAuctionEntity)
네 좋은 것 같아요! 감사합니다!

2023-09-15 03:39 UTC, kwonyj1022 requested changes
반영해주신 부분 확인했습니다. 그런데 저번 리뷰에서 놓친 부분이 있어서요! 혹시 image 엔티티가 변경되었고 AuctionImage, ProfileImage 등이 추가되었는데 관련해서 flyway 스크립트도 추가되어야할 것 같아요..!

2023-09-15 07:15 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/application/ImageService.java
> +        return new UrlResource("file:" + fullPath);
`file:`은 따로 상수로 뺀 후 원래대로 두었습니다.
메서드는 오히려 혼란을 가중시킬 것 같아 그대로 두었습니다.
추후 중복 코드가 심하다 느껴지면 수정하도록 하겠습니다.

2023-09-15 08:45 UTC, apptie commented on backend/ddang/src/main/resources/db/migration/V11__create_profile_image_tables.sql
> +alter table profile_image drop users;
이 부분에 문법이 맞는지 궁금합니다

2023-09-15 08:46 UTC, swonny approved these changes
충돌 해결 고생하셨습니다 제이미👍🏻

2023-09-15 08:51 UTC, kwonyj1022 approved these changes
제이미 수고했어요 정말...ㅠ

2023-09-15 08:52 UTC, merged