새로운 메시지 생성 시 알림 기능 추가
woowacourse-teams/2023-3-ddang pull request #367
Opened 2023-09-12 15:53 UTC by swonny

## 📄 작업 내용 요약

새로운 메시지 생성 시 알림 기능 추가

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- 테스트 실행 시 슬랙 > 백엔드-중요-정보에 등록해둔 `땅땅땅 Firebase Admin SDK`가 없으면 테스트가 실패합니다. 해당 파일을 resources/firebase/ 하위에 저장한 뒤 테스트를 실행해야 합니다.
- 알림 전송 서비스인 `FcmNotificationService`에 transactional 관련해서 send() 메서드 호출 시 새로운 트랜잭션으로 시작하도록 설정하고자 했는데, 이렇게 설정하면 테스트가 깨지는 문제가 있습니다ㅠ 그래서 시간이 없어서 일단 새로운 트랜잭션으로 하지 않은 상태로 pr을 올려두고 문제 해결한 뒤 다시 push 하도록 하겠습니다.

## 📎 Issue 번호

- closed #355

2023-09-12 16:06 UTC, kwonyj1022 commented
알림 전송하는 것을 새로운 트랜잭션으로 하지 않고 호출하는 곳에서 try-catch를 통해 예외를 잡는 방법에 대해서 어떻게 생각하시나요?

2023-09-12 18:56 UTC, kwonyj1022 commented
private-key.json 파일이 없으면 FirebaseMessging 빈을 만들 수 없어서 생기는 문제를 해결했고 그 과정을 디스커션에 올려두었습니다. 별 내용 없어요 [디스커션 링크](https://github.com/woowacourse-teams/2023-3-ddang/discussions/371)

2023-09-13 06:10 UTC, apptie requested changes
고생하셨습니다
equals랑 hashcode를 롬복이 아니라 직접 구현하신 부분이 있어서 이 부분으로 인해 rc를 드리도록 하겠습니다...
이것만 변경해주시면 될 것 같아요

2023-09-13 06:10 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/configuration/fcm/MockGoogleCredentials.java
> +    }
롬복을 사용하지 않고 이렇게 코드로 직접 구현하신 이유가 있으실까요?

2023-09-13 06:10 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/device/application/DeviceTokenService.java
> +    // TODO 메서드 이름이랑 반환값 어떻게 하는게 좋을까요?
해당 값은 void도 둬도 될 것 같습니다 
해당 api의 성공 여부는 상태 코드로 표현할 수 있을 것이니 굳이 쓰지도 않을 값을 고려할 필요는 없을 것 같습니다 
만약 다른 타입을 반환한다고 하더라도 List.add()와 같이 사용하지 않을 반환값이 될 것 같습니다

2023-09-13 06:10 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/device/application/DeviceTokenService.java
> +    // TODO 메서드 이름이랑 반환값 어떻게 하는게 좋을까요?
이름은 어렵네요 
processToken() 뭐 이런식으로 하면 되지 않을까요? persistToken()이나..?

2023-09-13 06:10 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/device/application/dto/UpdateDeviceTokenDto.java
> +public record UpdateDeviceTokenDto(String deviceToken) {
저는 개인적으로 Process나 Create..로 할 것 같아요 
다만 다른 분들의 센스를 믿겠습니다

2023-09-13 06:10 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/device/presentation/DeviceTokenController.java
> +    @PutMapping
이거 제이미...도 그 사용자 정보 변경할 때 Patch로 했으니까 그냥 맞춤용으로 Patch로 하는건 어떨까요 
토큰값만 추가하거나 변경하는 api니까 Put보다는 Patch가 더 자연스러운 것 같기도 합니다

2023-09-13 06:10 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/FcmNotificationService.java
> +        }
이런 식이라면 getter를 안쓰고 Optional을 반환하는 별도의 메서드를 만드는 것은 어떨까 건의를 드려봅니다

2023-09-13 06:10 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/FcmNotificationService.java
> +        }
매직넘버 상수처리 👍

2023-09-13 08:05 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/authentication/presentation/dto/request/LoginTokenRequest.java
> +        @NotEmpty(message = "AccessToken을 입력해주세요.") String accessToken,
여기 개행을 추가해야겠네욤,,

2023-09-14 03:45 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/configuration/fcm/MockGoogleCredentials.java
> +    }
요새 미션하다보니.. 미션에서는 롬복을 안 써서.. 수정했습니다!

2023-09-14 04:18 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/FcmNotificationService.java
> +        }
엔티티 필드에 `nullable=false` 설정을 해서 애초에 null이 올 수 없도록 변경하였습니다~

2023-09-14 04:19 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/authentication/presentation/dto/request/LoginTokenRequest.java
> +        @NotEmpty(message = "AccessToken을 입력해주세요.") String accessToken,
클래스 필드가 아니라 레코드의 파라미터라서 괜찮을 것 같아요!

2023-09-14 06:03 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/device/application/DeviceTokenService.java
> +    // TODO 메서드 이름이랑 반환값 어떻게 하는게 좋을까요?
process는 뭔가 토큰 문자열을 만들어주는 느낌이라 persist로 했습니다! 네이밍 추천 감사해요 지토

2023-09-14 06:06 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/device/application/dto/UpdateDeviceTokenDto.java
> +public record UpdateDeviceTokenDto(String deviceToken) {
요것도 persist로 했어요~

2023-09-14 09:58 UTC, JJ503 requested changes
고생 많으셨습니다 메리 엔초!
fcm 전혀 몰라서 어려워 보이기만 하네요... 대단해...
그런데 의견을 묻고 싶은 부분과 몇 가지 컨벤션 수정이 있어 일단 request chages합니다!

2023-09-14 09:58 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/authentication/application/AuthenticationService.java
> +        deviceTokenService.persist(persistUser.getId(), persistDeviceTokenDto);
별다른 설정이 없더라도 transaction은 하나로 진행되게 되는 걸까요?

2023-09-14 09:58 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/authentication/presentation/dto/request/LoginTokenRequest.java
> +        String deviceToken
deviceToken은 accessToken처럼의 처리는 따로 하지 않아도 괜찮은지 궁금합니다.

2023-09-14 09:58 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/configuration/fcm/FcmConfiguration.java
> +                                                                       .setProjectId("test-project")
120줄이 넘네요...
근데 지금 구조가 더 좋아보여서 그냥 알려만 드립니다 ㅎㅎ

2023-09-14 09:58 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/configuration/fcm/FcmConfiguration.java
> +                           .map(FirebaseMessaging::getInstance).orElse(null);
`orElse()` 개행 부탁드립니다!
또한, null이 반환되어도 괜찮은 것인지 궁금합니다.
그리고 반환된다면 `Optional`로 묶어주어야 하지 않을까도 싶네요..!

2023-09-14 09:58 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/device/application/DeviceTokenService.java
> +                                        .orElseThrow(() -> new UserNotFoundException("해당 사용자를 찾을 수 없습니다."));
체이닝이..! 체이닝이...!

2023-09-14 09:58 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/device/domain/DeviceToken.java
> +@ToString
User는 lazy인데 toString을 하게 된다면..?!

2023-09-14 09:58 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/util/NotificationProperty.java
> +    ;
원래 enum을 이런식으로 쓰나요??

2023-09-14 18:12 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/authentication/presentation/dto/request/LoginTokenRequest.java
> +        String deviceToken
이 부분은 안드로이드 분들과 논의 후 결정된 내용입니다!
accessToken은 항상 존재해야 하는데, deviceToken은 없는 경우가 있을 수 있다고 판단했습니다.
deviceToken이 없는 경우는 사실상 거의 없는 수준이겠지만
혹시나 그런 상황이 있더라도 기기 토큰의 부재가 로그인을 못하게 막을 정도는 아니라고 생각해 빈 값이 들어와도 된다고 결론이 나서 기기토큰에 대한 빈 값 검증 로직은 추가하지 않았습니다!

2023-09-14 18:28 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/configuration/fcm/FcmConfiguration.java
> +                           .map(FirebaseMessaging::getInstance).orElse(null);
null이 반환되는 경우는 등록된 firebase app이 없는 경우입니다.
말씀해주신 것처럼 null이 반환되는 것이 괜찮은지에 대해 고민해봤는데 아래와 같은 방법이 있다고 생각했습니다.

1. `@Conditional` 어노테이션으로 분기 처리 후 빈 등록 여부 결정
2. 예외 발생

그리고 저는 앱이 등록되어 있지 않으면 알림에 문제가 발생할 수 있어 예외를 던지는 것이 적절한 흐름이라고 생각해 예외를 던져두게 변경했는데, 이 부분은 엔초와 다시 상의해본 뒤 반영하겠습니다.

2023-09-14 18:31 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/util/NotificationProperty.java
> +    ;
저는 enum 사용할 때 새로운 값을 추가할 때의 편의성을 위해 이렇게 많이 사용했었고 
이렇게 사용하는 케이스를 몇 번 봤어서 엔초한테 이렇게 하자고 했는데 다른 코드 enum보니까 개행 없이 구현하셨네요..@
이건 기존 코드에 맞춰 바꿔두겠습니다!

2023-09-14 23:17 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/authentication/application/AuthenticationService.java
> +    public TokenDto login(final Oauth2Type oauth2Type, final String oauth2AccessToken, final String deviceToken) {
화이팅.. 충돌 해결할 때 같이 하시죠

2023-09-14 23:20 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/authentication/application/AuthenticationService.java
> +        deviceTokenService.persist(persistUser.getId(), persistDeviceTokenDto);
넵 deviceTokenService의 트랜잭션이 AuthenticationService의 트랜잭션에 속하게 되어서 DeviceTokenService에서 예외가 발생하면 login도 실패하게 됩니다. 또한, DeviceTokenService에서 예외가 발생하는 경우는 userRepository에서 회원을 찾을 수  없는 경우인데, login 수행 시 회원을 먼저 저장하고 난 후 기기 토큰을 저장하는 로직이 실행되기 때문에 현재 상태에서는 deviceTokenService에서 예외가 발생할 사항이 없긴 합니다.

2023-09-14 23:24 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/configuration/fcm/FcmConfiguration.java
> +                           .map(FirebaseMessaging::getInstance).orElse(null);
맞습니다. null이 반환되는 경우 빈 등록에 실패하기 때문에 서버 시작 시에 예외가 발생하게 됩니다. 만약 빈 등록이 되지 않았음에도 서버가 시작되도록 한다면 그 문제를 바로 인지하지 못할 수 있다고 생각했습니다.

2023-09-15 05:33 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/configuration/fcm/FcmConfiguration.java
> +                           .map(FirebaseMessaging::getInstance).orElse(null);
저도 이 부분은 null이 반환되는게 자연스럽다고 생각합니다

2023-09-15 05:39 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/configuration/fcm/FcmConfiguration.java
> +                           .orElseThrow(FcmNotFoundException::new);
이것도 음...나쁘지 않은 방식인 것 같네요

2023-09-15 05:39 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/device/presentation/DeviceTokenController.java
> +@RequestMapping("/deviceToken")
`/deviceToken`? `/device-token`?

2023-09-15 05:44 UTC, apptie approved these changes
고생하셨습니다!
제가 말씀드린 부분은 다 적용이 된 것 같아서 approve를 드리도록 하겠습니다 

나중에 언젠가 Configuration에서 테스트쪽도 분리했으면 좋겠네요...ㅎ하

2023-09-15 05:54 UTC, JJ503 approved these changes
수정 사항 모두 확인해 approve 합니다~

2023-09-15 07:10 UTC, merged