사용자 관련 경매 목록 조회 기능 추가
woowacourse-teams/2023-3-ddang pull request #368
Opened 2023-09-12 16:46 UTC by apptie

## 📄 작업 내용 요약

- 사용자 관련 경매 목록 조회 기능 추가
  - 내가 어쩌구 경매 목록 시리즈입니다 

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- `QuerydslAuctionRepositoryImpl`에 querydsl 코드가 반복되어 메서드로 분리했습니다
  - 이것이 querydsl의 장점이 아닐까 느꼈습니다 
- `QuerydslAuctionRepositoryImpl.findAuctionsAllByBidderId()`는 DB에서 정렬을 진행하지 않고 애플리케이션에서 정렬을 진행합니다
  - 로그인한 사용자가 같은 상품에 여러 번 입찰할 수도 있다보니 중복된 `auction`이 나올 수 있어 이를 `bid.auction`으로 `group by`를 진행해주었습니다
  - 정렬은 로그인한 사용자가 최근에 입찰한 목록 순입니다 
  - 이러한 정렬로 인해 `auction` 테이블만으로는 정렬이 불가능했습니다 (`bid.id`로 정렬 필요)
  - 그래서 DB에서 `auction + bid`를 join한 임시 테이블로 정렬 / 애플리케이션에서 정렬 중 애플리케이션 정렬을 선택했습니다
  - 페이지 크기가 10이므로 11개만 애플리케이션 메모리에 올려서 이미 정렬된 결과와 비교하는 식으로 비교하기 때문에 DB에서 정렬하는 것보다는 낫다고 느꼈습니다 
## 📎 Issue 번호

- closed #366

2023-09-14 09:20 UTC, JJ503 requested changes
지토 이번에도 역시 고생 많으셨습니다!!
쿼리 역시 어려워....
그런데 api 관련해서 적절한지에 대한 의견이 궁금해 일단 request changes 후 의견 듣고 approve 해드리도록 하겠습니다 ㅎㅎ

2023-09-14 09:20 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +                                                      .groupBy(bid.auction.id)
기능 얘기 듣자마자 이거 처리 없으면 지적해야지 생각했는데 처리 되어 있어서 속상해요...

2023-09-14 09:20 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +
헉 개행이 두개..?

2023-09-14 09:20 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
> +    @GetMapping("/mines")
api의 적절성이 그냥 궁금합니다!
user 관련 기능들은 모두 `user/~`로 진행될텐데 `mines`와 `bids`만 이렇게 분리되어 있으면 헷갈리지 않을까가 걱정되네요..!

2023-09-14 09:20 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/AuctionQueryByBidderIdTest.java
> + * 사용하는 더미 데이터 (제목 키워드 / ID / 신뢰도 / 경매 참여자 수 / 경매 마감일 / 판매자)
오 이렇게 주석으로 체크해주셔 감사합니다.
이전에도 해주시긴 했지만 세삼 보기 더 편함을 느끼네요!

2023-09-14 09:24 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +
헉...죽었다

2023-09-14 09:24 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +
변경하겠습니다..

2023-09-14 09:28 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
> +    @GetMapping("/mines")
`내 경매 목록 조회`는 `내`가 아니라 `경매 목록 조회`가 핵심이라고 생각해서 이렇게 작성했습니다 
`/users`로 시작하는 api의 경우 사용자 정보와 관련된 내용을 수행해야 한다고 생각했습니다

그래서 저는 제이미가 말씀해주신 내용의 반대로 경매 목록 조회는 /auctions~인데 /users로 시작하면 헷갈릴것이라고 생각했었습니다

2023-09-14 09:28 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/AuctionQueryByBidderIdTest.java
> + * 사용하는 더미 데이터 (제목 키워드 / ID / 신뢰도 / 경매 참여자 수 / 경매 마감일 / 판매자)
노림수가 먹혔군요 굳

2023-09-14 10:11 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
> +    @GetMapping("/mines")
아무래도 저는 접근 방법이 중요하다고 생각해요.
`/auctions/~`로 시작하게 된다면 경매 목록에서 살펴보는 등에 대한 이해가 명확할 것입니다.
그런데 `내 경매 목록 조회`의 경우 내 페이지로 이동 -> 내 경매 목록 클릭 이기 때문에 `/users`에서 파생된 페이지가 아닐까 하는 생각입니다.
만약 웹 url이었다면? 을 생각해 보니 어색함이 느껴져 의견 남겨보았습니다.

예를 들어 네이버 웹툰의 웹툰 목록이 존재하고 이때, 화요일 웹툰만 조회하는 경우의 url입니다. 해당 url은 아래와 같습니다.
https://comic.naver.com/webtoon?tab=tue

하지만, 내가 최근 본 웹툰의 url의 경우 아래와 같습니다.
https://comic.naver.com/mypage/recently

위와 같은 느낌으로 말씀드리게 되었습니다.

다른 분들에 대한 의견도 궁금하네요!

2023-09-14 12:04 UTC, kwonyj1022 approved these changes
수정할 사항이 보이지 않네요.. 완벽합니다 지토

2023-09-14 15:43 UTC, swonny approved these changes
지토 고생 많으셨습니다!
querydsl 관련해서 질문 남긴 부분이 몇 가지 있는데, 이 부분은 질문이기도 하고 변경되더라도 리팩토링의 영역이 될 것 같아 approve 하겠습니다!

그리고 메서드 순서만 바꿔주시면 감사하겠습니다👍🏻

2023-09-14 15:43 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
> +    @GetMapping("/mines")
저도 `mines`만으로는 의미 전달이 충분하지 않은 것 같다는 생각입니다!
 제이미가 예시와 함께 제시해준 섬세한 의견 ..👍🏻
개인적으로 `my-auctions` 정도로 하면 괜찮지 않을까 생각합니다

2023-09-14 15:43 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +                                                      .groupBy(bid.auction.id)
여기에서 `groupBy()`를 사용해주신 이유는 한 명의 사용자가 같은 경매에서 여러번 입찰할 수 있기 때문이 맞을까요?

groupBy가 어떤 역할을 하는지 잘 몰라서 찾아봤는데 groupBy로 통계를 내야하는 경우에 많이 사용된다는걸 알게됐습니다.
해당 쿼리에서는 groupBy로 통계치를 구하기보다는 auctionId의 중복을 제거하기 위해 사용된 것이라고 이해했는데,
distinct 대신 groupBy를 사용하신 이유가 궁금합니다!

그리고 distinct로 정상 동작하는지 보려고 distinct로 바꿔서 실행시켜봤는데 `SQLGrammarException`이 뜨더라구요..
제가 잘못 알거나 사용한건지 아니면 distinct로 대체될 수 있는 쿼리인지 궁금해 코멘트 남깁니다

2023-09-14 15:43 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +        findAuctions.sort((firstAuction, secondAuction) -> {
바로 위에서는 orderSpecifiers에 emptyList를 전달하고 아래에서 다시 sort를 진행하는 이유가 잘 이해가 안됩니다...
`findAuctionsByIdsAndOrderSpecifiers()`를 호출할 때 정렬을 함께 진행하면 안되는 이유가 뭔가요??

2023-09-14 15:52 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +        final BooleanExpression titleBooleanExpression = convertTitleSearchCondition(searchCondition);
앗...수정하겠습니다

2023-09-14 16:06 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
> +                                                      .groupBy(bid.auction.id)
distinct의 경우 쿼리의 핵심 테이블의 데이터가 중복되는 경우에만 사용할 수 있기 때문에 사용하지 않았다고 봐 주시면 될 것 같습니다

저는 치열한 하나의 경매에 사용자가 여러 번 경매를 하는 케이스를 고려했었습니다 
대충 다음과 같습니다(회원1이 경매를 한 목록이라고 가정하겠습니다)

```
Bid1(PK : 1, AuctionId : 5, Bidder: 회원1)
Bid2(PK : 2, AuctionId : 5, Bidder: 회원1)
Bid3(PK : 3, AuctionId : 5, Bidder: 회원1)
Bid4(PK : 4, AuctionId : 5, Bidder: 회원1)
Bid5(PK : 5, AuctionId : 5, Bidder: 회원1)
```

여기서 distinct를 사용하려면 기준이 되는(from의 대상 테이블) Bid의 기준으로 조회를 해야하는데 
select를 보시면 bid가 아니라 bid.auction.id로 auction 테이블의 데이터를 조회하고 있습니다 
querydsl이 distinct를 쓰려면 bid 테이블과 관련된 그 무언가를 조회해야 하는데 bid 테이블에 존재하지 않는 컬럼인 auction 테이블의 id를 조회해서 불가능하다고 봐주시면 될 것 같습니다

2023-09-15 05:47 UTC, JJ503 approved these changes
수정 사항 모두 확인해 approve 합니다!

2023-09-15 06:25 UTC, merged