서버로 디바이스 토큰을 전송하는 기능 추가
woowacourse-teams/2023-3-ddang pull request #375
Opened 2023-09-13 12:21 UTC by ippnsj

## 📄 작업 내용 요약
- 카카오 로그인 시 디바이스 토큰도 함께 전송하도록 api 수정
- 디바이스 토큰이 새로 발급되면 서버로 전송하는 기능 추가

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드
### 카카오 로그인 시 디바이스 토큰도 함께 전송하도록 api 수정
- 카카오 로그인 시 fcm으로부터 디바이스 토큰을 가져와야 하는데 그러기 위해서는 리스너를 추가해주어야 하고 해당 리스너에서 콜백이 호출되면 디바이스 토큰을 확인하여 서버로 전송 가능합니다.
- 콜백을 기다려야 하기 때문에 콜백이 올때까지 코루틴을 suspend하고 콜백이 오면 resume하도록 해야 했습니다.
- 그래서 드로이드 나이츠 때 배운 [suspendCancellableCoroutine](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/suspend-cancellable-coroutine.html)을 이용하여 구현하게 되었습니다!
- suspendCancellableCoroutine 함수를 실행하면 사용자가 resume하기 전까지 코루틴을 멈출 수 있습니다. 그래서 suspendCancellableCoroutine 내부에 fcm으로부터 디바이스 토큰을 가져오는 콜백을 정의하고 콜백이 호출되면 resume하도록 하였습니다.
- 처음 사용하는 함수이기에 suspendCancellableCoroutine이 원하는대로 잘 동작하는지 테스트도 진행했습니다.

### 디바이스 토큰이 새로 발급되면 서버로 전송하는 기능 추가
- fcm으로부터 새로운 디바이스 토큰이 발급되면 userRepository를 통해 서버로 디바이스 토큰을 전송하였습니다.
- AuctionRetrofit에 정의된 Interceptor에서 자체적으로 토큰을 검증하기 때문에 외부에서 토큰 존재 여부나 유효 여부를 따로 확인하지는 않았습니다.

## 📎 Issue 번호
- close: #374

2023-09-14 02:46 UTC, hyemdooly requested changes
안녕하세요 글로! 추가된 부분이 그렇게 많지 않았네요!
리뷰 하나만 확인해주시면 좋을 것 같습니다!

2023-09-14 02:46 UTC, hyemdooly commented on android/app/src/main/java/com/ddangddangddang/android/feature/login/LoginViewModel.kt
>                  else -> _event.value = LoginEvent.FailureLoginEvent
서버에서 날아오는 메시지를 담아 토스트를 띄운다든지의 예외처리를 할 수 있지 않을까요??

2023-09-14 02:46 UTC, hyemdooly commented on android/data/src/main/java/com/ddangddangddang/data/repository/AuthRepositoryImpl.kt
> +
suspendCancellableCoroutine을 사용한 점이 참 좋습니다!

2023-09-15 06:33 UTC, ippnsj commented on android/data/src/main/java/com/ddangddangddang/data/repository/AuthRepositoryImpl.kt
> +
suspendCoroutine은 부모 코루틴이 취소되더라도 함께 종료되지 않아서 suspendCancellableCoroutine을 사용했습니다!

2023-09-15 06:37 UTC, rhthrhrl0 reviewed
고생하셨습니다. 리뷰 남긴 것만 확인 부탁드립니다.

2023-09-15 06:37 UTC, rhthrhrl0 commented on android/data/src/main/java/com/ddangddangddang/data/repository/AuthRepositoryImpl.kt
> +                    continuation.resume(null)
로그인시 디바이스 토큰의 유무를 강제할지 고민해봐야할 것 같습니다!

2023-09-15 08:00 UTC, hyemdooly approved these changes
수고하셨습니다~!

2023-09-15 09:40 UTC, rhthrhrl0 approved these changes
고생많으셨습니다~

2023-09-15 09:40 UTC, rhthrhrl0 commented on android/data/src/main/java/com/ddangddangddang/data/remote/AuctionCall.kt
> +                        }
좋은 개선 코드인 것 같습니다~

2023-09-15 10:08 UTC, ippnsj commented on android/data/src/main/java/com/ddangddangddang/data/repository/AuthRepositoryImpl.kt
> +                    continuation.resume(null)
디바이스 토큰이 없으면 로그인이 불가하도록 수정했어요~ 😉

2023-09-15 12:38 UTC, merged