회원 정보 수정 기능 및 마이페이지 목록 UI 구성
woowacourse-teams/2023-3-ddang pull request #391
Opened 2023-09-15 17:45 UTC by rhthrhrl0

## 📄 작업 내용 요약
회원 정보 수정 기능입니다.

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드
회원 정보 수정 페이지를 위해, MyPageFragment에서 ProfileModel을 ProfileChangeActivity로 보냄.
ProfileChangeActivity에서는 처음 화면에 보여줄 값으로 마이페이지 프래그먼트 쪽에서 받은 ProfileModel을 사용함.
이후 사용자가 수정한 다음에, 확인 버튼을 누르면 submitProfile 함수가 실행되고, 여기서 이미지 uri의 최적화 과정을 거치고, 레포지토리에게 보낸 후, 멀티파트 요청을 수행함. 요청을 성공하면, ProfileFragment에게 수정한 정보를 반환해서 줌.

여기서, 제가 만든 멀티 파트 요청이 올바른지만 확인 부탁드립니다.. 지금, 개발 서버에서는 405 에러가 돌아와서, 해당 메소드가 제공되지 않는 것 같네요.

추가적으로 한 작업)
- 기존의 Uri 최적화 로직을 UriOptimizeUtil.kt 로 분리. 만약 파일명 수정원하시면 적어주세요.

## 📎 Issue 번호
- Close: #365

2023-09-16 04:39 UTC, hyemdooly requested changes
고생하셨습니다!
간단한 리뷰 몇개만 확인해주세요!!
멀티파트는 제가 폰으로 확인해서 안보이는건지 문제는 없어보이네요..🥲

2023-09-16 04:39 UTC, hyemdooly commented on android/app/src/main/java/com/ddangddangddang/android/feature/mypage/MyPageViewModel.kt
> +        object ShowMyAuctions : MyPageEvent()
기존에 이런 이벤트들은 NavigateTo로 네이밍했던 것 같은데 확인 한번 부탁드립니다!
Show라고 짓지 않았던 것 같아서요!

2023-09-16 04:39 UTC, hyemdooly commented on android/data/src/main/java/com/ddangddangddang/data/remote/AuctionService.kt
> +        @Part("request") name: RequestBody,
마이페이지는 이름 외에도 다른 요소가 추후에 생길 수 있을 것 같아요! 사용자의 정보를 의미하는, 포괄적인 다른 네이밍은 어떨까요?

2023-09-16 04:39 UTC, hyemdooly commented on android/app/src/main/res/layout/fragment_my_page.xml
> +                    bind:categoryName="@{@string/mypage_user_info_change_button}" />
오 이런 것도 있군여! include는 잘 안써서 몰랐네요 ㅋㅋㅋ

2023-09-16 15:26 UTC, ippnsj reviewed
수고하셨어요~
프로필 사진 수정할 때 기본 이미지로 변경 기능도 추가되면 좋을 것 같아요!
기존에 등록한 사진을 내리고 싶은 경우도 있을 것 같아서요~ㅎㅎ

2023-09-16 15:26 UTC, ippnsj commented on android/app/src/main/java/com/ddangddangddang/android/feature/profile/ProfileChangeActivity.kt
> +                finish()
함수 분리 해줘도 좋을 것 같아요~

2023-09-16 15:26 UTC, ippnsj commented on android/app/src/main/res/layout/view_my_page_feature_category.xml
> +            android:id="@+id/view_privacy_policy_divider"
id가 예전 id인 것 같아요ㅋㅋ 🤣

2023-09-16 15:26 UTC, ippnsj commented on android/data/src/main/java/com/ddangddangddang/data/model/request/ProfileUpdateRequest.kt
> +)
```kotlin
{
		request: {name: string},
		profileImage: MultipartFile
}
```
현재 api가 이런 구조인데 이 구조면 request라는 키를 가진 객체로 한번 더 감싸줘야 할거에요!
서버와 논의해보시고 아래와 같이 api를 수정하면 지금 구현하신대로 동작할 겁니다~
```kotlin
{
		name: string,
		profileImage: MultipartFile
}
```

2023-09-16 15:26 UTC, ippnsj commented on android/data/src/main/java/com/ddangddangddang/data/model/request/ProfileUpdateRequest.kt
> +)
서버와 얘기할 때 경매 등록 api를 참고하시면 좋을 것 같아요~ 👍

2023-09-16 17:43 UTC, rhthrhrl0 commented on android/app/src/main/java/com/ddangddangddang/android/feature/mypage/MyPageFragment.kt
> +        if (hidden.not() && viewModel.profile.value == null) viewModel.loadProfile()
엇 그것 때문은 아니였습니다. onViewCreated는 일반적으로 한 번만 호출되는데, 만약 여기서 실패했을때를 생각하고 작성한 로직이였습니다.
생각을 해봤는데, 만약 처음에 불러오는 과정에서 실패했으면, 마이페이지의 내정보는 영원히 안보여야 하는것인가?를 고민했습니다.  다른 탭을 다녀오면, 다시 불러오도록 시도라도 해주려고 이렇게 해놨습니다. 
마이페이지 탭을 누를 때마다 갱신을 해야할 필요가 있는가? 에 대한 고민을 했었는데, 그냥 양쪽에서 다 호출하면 되겠네요. 
onViewCreated는 맨 처음 마이페이지 탭을 클릭했을때만 일어나고, 이때는 onHiddenChanged가 발생하지 않고(맨처음 프래그먼트를 생성하므로),
이후에 다른 탭을 다녀올 때는 onHiddenChanged로 갱신해주고,
회원정보 수정 탭을 다녀올 때는 콜백으로 updateProfile 해주는 식으로 하면 되겠네요.

2023-09-16 17:43 UTC, rhthrhrl0 commented on android/data/src/main/java/com/ddangddangddang/data/model/request/ProfileUpdateRequest.kt
> +)
![image](https://github.com/woowacourse-teams/2023-3-ddang/assets/67176829/bb6e2628-df40-4862-82e5-dc1682b5dca0)
지금 이렇게 해주고, 
![image](https://github.com/woowacourse-teams/2023-3-ddang/assets/67176829/35158e23-1aa7-4304-851e-c120a3b30bb0)
이렇게 해주고 있으면, 문제 없는거 맞을까요?

2023-09-16 18:25 UTC, ippnsj commented on android/app/src/main/java/com/ddangddangddang/android/feature/mypage/MyPageFragment.kt
> +        if (hidden.not() && viewModel.profile.value == null) viewModel.loadProfile()
아 그러면 이전 코드대로 한다는 말씀이신가요? 🧐

2023-09-16 19:02 UTC, ippnsj commented on android/data/src/main/java/com/ddangddangddang/data/model/request/ProfileUpdateRequest.kt
> +)
이렇게 해도 잘 전달되는 것 같네요!

다른 문제를 발견했는데요! 수정 페이지 프로필 사진 url로부터 이미지를 가져오지 못한 경우에는 어떤 이미지를 보여줘야 할까요?
프로필 페이지에서는 디폴트 사진을 보여주는데 수정 페이지에서는 하얀 이미지를 보여줘서 논의가 필요할 것 같아요!

또 다른 문제는 기존 이미지 uri는 file로 변환이 잘 이루어지지 않고 있습니다! 그리고 서버와 논의하여 기존 이미지 그대로 수정 요청을 보내면 동일한 사진이 새로 저장되지 않도록 조치를 취해야 할 것 같아요~!

또 다른 문제는 프로필 수정에 성공했을 때 매번 imageUrl 값이 null로 온다는 점입니다! 이건 서버와 얘기해봐야 할 것 같아요!

2023-09-17 03:02 UTC, rhthrhrl0 commented on android/app/src/main/java/com/ddangddangddang/android/feature/mypage/MyPageFragment.kt
> +        if (hidden.not() && viewModel.profile.value == null) viewModel.loadProfile()
맞습니다

2023-09-17 07:08 UTC, ippnsj commented on android/data/src/main/java/com/ddangddangddang/data/model/request/ProfileUpdateRequest.kt
> +)
- 맞아요! 아래처럼 처리하게 되면 기존 이미지에서 수정하지 않은 경우에는 서버로 요청 자체가 가지 않더라구요.
근데 사용자 입장에서는 사진 변경 없이 닉네임만 수정하고 싶을 수 있으니까 서버에 요청은 가도록 해야할 것 같아서 말씀드린 거였어요.
- 만약 다수의 사용자가 기존 이미지는 그대로 두고 아이디값만 변경한다고 한다면 서버에 불필요하게 중복 저장된 이미지가 많아질 것 같아서 말씀드린 거였습니다! 서버에서는 이미지 파일을 저장하고 url값을 클라이언트에 보내주는데 저장 공간이 낭비되는건 아닌가 하는 우려가 들어서요.
- 위 우려와 비슷한 우려인데 현재 코드에서는 이미지가 존재하지 않는 사용자의 경우 디폴트 이미지를 uri로 변환하여 가지고 있다가 요청 시 서버에 함께 파일로 보내고 있는 것 같습니다. 그렇게 되면 디폴트 이미지를 서버에 여러번 저장하는 일이 발생할수도 있을 것 같아요. 디폴트 이미지의 경우 file값을 null로 전송하여 서버에서 해당 사용자는 프로필 사진이 없다고 인지하고 이후 클라이언트 요청 시 빈 스트링 값을 프로필 사진 url로 보내주는 것이 더 낫다고 생각합니다.

2023-09-17 07:44 UTC, ippnsj approved these changes
현재 문제인 부분은 서버와의 논의가 필요하니 일단 다음 작업 하면서 천천히 수정해 나가도록 해요!
수고하셨습니다~!!!

2023-09-17 07:47 UTC, hyemdooly commented
수고하셨습니다!

2023-09-17 07:47 UTC, hyemdooly approved these changes
수고하셨습니다!!!

2023-09-17 07:55 UTC, merged