나의 경매 목록 기능
woowacourse-teams/2023-3-ddang pull request #396
Opened 2023-09-17 10:40 UTC by rhthrhrl0

## 📄 작업 내용 요약
나의 경매 목록을 볼 수 있는 기능을 추가했습니다.

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드
<img width="701" alt="image" src="https://github.com/woowacourse-teams/2023-3-ddang/assets/67176829/83772cbb-381d-4a45-96b1-13c75f025df1">
만약 응답 성공시, 요청했던 페이지가 1이라면, 이전 정보는 빼고 새로 리스트를 설정했습니다.

<img width="640" alt="image" src="https://github.com/woowacourse-teams/2023-3-ddang/assets/67176829/471e57c8-849c-410d-a306-701d8b673fd2">
상품을 성공적으로 불러왔는데, 상품이 1개도 없을 경우 텍스트를 화면에 보여주기 위해 isLast를 라이브데이터로 했습니다.

### 현재 상황
- 내 경매 목록에서 상세 상품으로 들어가서 상품을 삭제하고 다시 돌아왔을때, 목록에서 제거되지 않습니다. 일단 기본적으로 서버에서 지금 내 경매 목록에 대해서는 삭제된 상품도 같이 보내주고 있습니다.
만약 서버에서 정책을 바꿔서, 삭제한 상품도 나의 경매 목록에서 보여주지 않도록 된다면, 상세 페이지에서 추가적인 작업이 필요할 것 같습니다. (삭제한 상품의 id정보를 돌려주지 않기 때문에, 만약 필요하다면, 상세 페이지에서 삭제시 상품의 정보를 종료 결과로 보내줘야 할 수도 있을 것 같습니다. 지금 아마 검색쪽에서도 같은 문제가 있을 것 같네요)

## 📎 Issue 번호
- close: #395

2023-09-17 11:19 UTC, hyemdooly requested changes
고생하셨습니다! 제 코드와 비슷하네요 ㅎㅎ
저도 리뷰 받았던 부분 두 가지만 피드백 남겼습니다. 확인 부탁해요~!

2023-09-17 11:19 UTC, hyemdooly commented on android/app/src/main/java/com/ddangddangddang/android/feature/myAuction/MyAuctionActivity.kt
> +            }
글로가 만들었던 ErrorType 클래스를 활용하면 어떨까요?

2023-09-17 11:19 UTC, hyemdooly commented on android/app/src/main/java/com/ddangddangddang/android/feature/myAuction/MyAuctionViewModel.kt
> +        }
response.auctions.map을 한번만 사용할 수 있을 것 같아요!
따로 변수로 빼서, new items를 value에 넣어줄지 기존 items에 더해서 넣어줄지를 결정하면 어떨까요?

2023-09-17 12:28 UTC, hyemdooly requested changes

2023-09-17 12:28 UTC, hyemdooly commented on android/app/src/main/java/com/ddangddangddang/android/feature/myAuction/MyAuctionActivity.kt
>              }
ErrorType 내부에 messageId가 있습니다! 다시 string을 꺼내써주지 않아도 괜찮아요!

2023-09-17 13:18 UTC, rhthrhrl0 commented on android/app/src/main/java/com/ddangddangddang/android/feature/myAuction/MyAuctionActivity.kt
>              }
이건 몰랐네요 ㅋㅋㅋ 감사합니다

2023-09-18 03:19 UTC, hyemdooly approved these changes
수고하셨습니다!!

2023-09-18 06:34 UTC, ippnsj approved these changes
주말동안 정말 수고하셨습니다~👍

2023-09-18 06:38 UTC, merged