경매 등록 글 EditText Text 옆에 '원' 단위 붙이기
woowacourse-teams/2023-3-ddang pull request #416
Opened 2023-09-19 06:37 UTC by hyemdooly

## 📄 작업 내용 요약
경매 입찰 때처럼 EditText에서 '원' 단위를 붙일 수 있게 했습니다.

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드
1. EditText 변경 시 TextWatcher 작동
2. TextWatcher에서 onChanged 함수 실행 (이번 코드에서는 viewModel의 setXXX 함수 실행)
3. viewModel의 setXXX 함수에서 LiveData value 변경 (price 변경)
4. 이 LiveData를 옵저빙하고 있는 액티비티에서, 뷰에서 텍스트가 화폐 단위로 보여질 수 있게 setPrice 실행

TextWatcher를 클래스로 분리하여, TextChanged 시 실행할 함수를 넣어주도록 했습니다!
```Kotlin
    private val startPriceWatcher by lazy { PriceTextWatcher(viewModel::setStartPrice) }
    private val bidUnitWatcher by lazy { PriceTextWatcher(viewModel::setBidUnit) }
```
이렇게 함수가 달라도 같은 클래스를 활용하여 재활용할 수 있습니다.
```kotlin
    private fun setPrice(editText: EditText, watcher: PriceTextWatcher, price: Int) {
        val displayPrice = getString(R.string.detail_auction_bid_dialog_input_price, price)
        editText.removeTextChangedListener(watcher)
        editText.setText(displayPrice)
        editText.setSelection(getCursorPositionFrontSuffix(displayPrice)) // " 원" 앞으로 커서 이동
        editText.addTextChangedListener(watcher)
    }
```
내용은 똑같은데 들어가는 값만 바뀌는 코드라, editText, watcher, price를 받는 함수로 만들었습니다.
```kotlin
    private fun setupStartPriceTextWatcher() {
        binding.etStartPrice.addTextChangedListener(startPriceWatcher)
        binding.etStartPrice.setOnClickListener {
            binding.etStartPrice.setSelection(getCursorPositionFrontSuffix(binding.etStartPrice.text.toString()))
        }
    }

    private fun setupBidUnitTextWatcher() {
        binding.etBidUnit.addTextChangedListener(bidUnitWatcher)
        binding.etBidUnit.setOnClickListener {
            binding.etBidUnit.setSelection(getCursorPositionFrontSuffix(binding.etBidUnit.text.toString()))
        }
    }
```
이 코드도 하나의 함수로 합칠 수 있을 것 같은데, 너무 함수로 뭉개뜨려서 의미가 잘 안보이는 것은 아닐까 싶어 두었습니다. 합칠지 둘지 의견 부탁드립니다!

### 추가 사항
기존 멘델의 코드에서 버그를 하나 발견했는데요! 금액을 입력한 후 다른 뷰로 포커싱을 바꿨다가 다시 EditText를 누른 후에 delete를 누르면 0원으로 바뀝니다. 예를 들어, '50,000 원'이 입력되어있다고 했을 때 delete를 누르면 '원'만 지워져서 함수에 들어가고 있었습니다. 맨 뒤에 공백이 남아 `.toInt()`가 불가능한 문자열로 인식하고 ZERO를 리턴하는 상황이었어요.
제 코드에서는 이 문제를 `trim()`을 적용해서 해결했습니다!
입찰 페이지에서는 다른 뷰로 포커싱되는 상황이 없어서 문제 없습니다!

## 📎 Issue 번호

- closed : #415

2023-09-19 12:22 UTC, rhthrhrl0 reviewed
헉 입찰 쪽에서 확인하지 못했던 버그네요. trim 처리 확인했습니다~ 
함수는 저는 지금처럼 분리 하는게 더 나을 것 같네요.

2023-09-19 12:22 UTC, rhthrhrl0 commented on android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionViewModel.kt
> +        val convertedPrice = convertStringPriceToInt(text)
입찰쪽도 이런 반환 구조로 수정해야겠네요

2023-09-19 12:25 UTC, rhthrhrl0 commented on android/app/src/main/java/com/ddangddangddang/android/feature/register/PriceTextWatcher.kt
> +class PriceTextWatcher(private val onChanged: (String) -> Unit) : TextWatcher {
사실 얘가 가격 입력 처리를 위한 Watcher 클래스로는 보이지 않네요. 불필요한 중복 코드를 방지하려면, 필요할 것 같긴한데, 클래스명이 적절한지는 고민해봐야할 것 같네요.. DefaultTextWatcher?

2023-09-19 14:04 UTC, ippnsj requested changes
수고했어요~
금액 수정과 관련하여 사용자가 불편을 느낄 수 있는 부분이 있다고 생각하여 리뷰 남겼는데 둘리는 어떻게 생각하시나요? 🤔

2023-09-19 14:04 UTC, ippnsj commented on android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionActivity.kt
> +        editText.setSelection(getCursorPositionFrontSuffix(displayPrice)) // " 원" 앞으로 커서 이동
이 경우에는 중간에서 금액을 지우고 바꾸고 싶을 때 지우는 순간 커서 유지가 안돼서 힘들더라구요ㅠㅠ
예를 들어 400을 500으로 바꾸고자 4를 지우고 5로 바꾸려고 했을 때 커서가 뒤로 이동해서 5를 입력하려면 커서를 다시 이동해야 하더라구요 ㅠㅠ

2023-09-19 14:04 UTC, ippnsj commented on android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionViewModel.kt
> +        val priceValue = originalValue.substringBefore(SUFFIX_INPUT_PRICE).trim() // " 원"
이 경우 SUFFIX_INPUT_PRICE가 " 원"이어서 원 앞의 공백을 지우면 멘델의 코드처럼 금액이 0으로 바뀌어요!
아마 SUFFIX_INPUT_PRICE.trim()으로 바꿔주면 해결되기 할 겁니다!

2023-09-19 16:06 UTC, hyemdooly commented on android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionViewModel.kt
> +        val priceValue = originalValue.substringBefore(SUFFIX_INPUT_PRICE).trim() // " 원"
그 문제를 이제 trim()처리를 함으로서 0으로 바뀌지 않게 처리했던건데 지금 코드도 같은 문제가 있었나요?

2023-09-19 16:12 UTC, hyemdooly commented on android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionActivity.kt
> +        editText.setSelection(getCursorPositionFrontSuffix(displayPrice)) // " 원" 앞으로 커서 이동
원을 못지우게 해야하는데🤔
if문 걸어서 한번 시도해볼게요~

2023-09-20 00:55 UTC, hyemdooly commented on android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionViewModel.kt
> +        val priceValue = originalValue.substringBefore(SUFFIX_INPUT_PRICE).trim() // " 원"
생각해보니 원 앞에 공백이 지워질 일이 없어서 그랬던 것 같네요! 확실하게 trim을 한번 더 처리해줬습니다

2023-09-20 02:36 UTC, hyemdooly commented on android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionActivity.kt
> +        editText.setSelection(getCursorPositionFrontSuffix(displayPrice)) // " 원" 앞으로 커서 이동
이것저것 시도를 해봤는데... 일단 TextWatcher는 무조건 적용해야하는 상황이구
removeTextChangedListener -> addTextChangedListener 하는 과정에서 커서가 맨 앞으로 갑니다.
따라서 setSelection을 풀면 계속해서 문자의 맨 앞으로 가게 돼요. -> setSelection은 필요하다!

그래서 현재의 커서 위치를 저장하고 TextWatcher 적용 후에 그 위치를 setSelection으로 옮겨주려고 했는데, 콤마가 문제가 되었어요. 예를 들어 210원에서 커서가 1뒤에 있을 때 위치는 1인데요, 0을 추가해서 2,100원이 되는 경우 위치가 1이 아니라 2가 되어야만 합니다.
따라서 현재 Formatting하기 전 EditText의 length와 Formatting 후 length를 비교해서 콤마가 추가됐는지 안됐는지 계산하여 커서 위치를 +1, -1해봤어요. 그리고 TextWatcher 적용 후 setSelection으로 옮겨줬습니다.

여기서 문제는 커서를 첫번째 0뒤에 두고 삭제해서 2,100 원 -> 210원으로 갔을 때 커서의 위치가 1 뒤가 아니라 맨 뒤로 간다는 버그가 있었어요. 이렇게 커서를 임의로 계산해서 위치를 지정해주는건 더 복잡한 로직이 필요하겠다고 판단했습니다. 특히, 하나씩 지우는게 아니라 범위를 지정해서 지우는 경우의 로직도 추가로 필요해요 ㅠㅠ

2시간동안 만져봤는데 지금 당장 바로 해결할 수 있는 문제가 아니라고 생각해서 selection은 그대로 두었습니당...🥲

2023-09-20 06:36 UTC, ippnsj approved these changes
수고했어요~! 제가 남긴 리뷰는 다음에 반영해보아요!

2023-09-20 06:39 UTC, ippnsj commented on android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionActivity.kt
> +        editText.setSelection(getCursorPositionFrontSuffix(displayPrice)) // " 원" 앞으로 커서 이동
`beforeTextChanged` 에서 다음과 같은 로직을 통해 커서 뒤에 있는 문장의 길이를 구할 수 있어요!
```kotiln
val positionFromEnd = if (s == null) 0 else (s.length - (start + count))
```
setSelection할 때 위에서 구한 값을 사용하여 커서 위치를 바꾸면 될 것 같아요!

2023-09-20 06:39 UTC, rhthrhrl0 approved these changes
고생하셨습니다~

2023-09-20 06:40 UTC, merged