쪽지 전송과 알림 전송 트랜잭션 분리
woowacourse-teams/2023-3-ddang pull request #445
Opened 2023-09-25 01:54 UTC by swonny

## 📄 작업 내용 요약

쪽지 전송과 알림 전송 트랜잭션 분리

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- NotificationService의 send() 메서드에 `@Transactional(propagation = Propagation.REQUIRES_NEW)`를 통해 트랜잭션을 분리했습니다.
- 새로운 트랜잭션에서 롤백 여부는 기존 트랜잭션에 영향을 미치지 않지만, 새로운 트랜잭션에서 예외가 발생하는 것은 영향을 미치기 때문에 `NotificationService.send()` 로직에서 발생할 수 있는 예외(`DeviceTokenNotFound`, `FcmMessagingException`)는 별도의 예외를 던지지 않고, 예외가 발생할 경우 전송 실패 메시지만 전달할 수 있도록 변경했습니다.

- [트랜잭션과 테스트 관련 트러블 슈팅]
    -  `@Transactional(propagation = Propagation.REQUIRES_NEW)` 옵션으로 인해 테스트 메서드에서 `NotificationService.send()` 호출 시 테스트 메서드와 분리되는 새로운 트랜잭션이 생성되고, 따라서 `NotificationService.send()`에서는 기존 트랜잭션에서 저장했던 기기 토큰을 찾을 수 없는 이슈가 있었습니다. (jpa 너무 어려워요😭) 따라서 불가피하게 NotificationService에서 사용되는 `DeviceTokenRepository`는 모킹하여 사용하도록 수정했습니다.
 
## 📎 Issue 번호

 
- closed #431

2023-09-25 06:47 UTC, apptie requested changes
안녕하세요 메리
반갑습니다
코드 작성하시느라 고생하셨네요 
하지만 안타깝게도 스포할 뻔 했던 것처럼 RC를 드리도록 하겠습니다

그 `트랜잭션과 테스트 관련 트러블 슈팅` 파트를 제외하고는 단순 확인이나 팀 단위의 컨벤션이 필요한 파트라고 생각해서 `FcmNotificationServiceTest`에서 `JpaDeviceTokenRepository`에서 `mocking`하는 부분만 수정해주시면 될 것 같습니다 

---

하나 더 있었네요 `FcmNotificationService`에서 `catch` 파트도 각 예외마다 추가하거나 `Exception`말고 발생하는 예외들을 `|`로 나열하는 식으로 변경해주셨으면 좋겠습니다

2023-09-25 06:47 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/FcmNotificationService.java
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
지금 봤는데 성공 유무를 문자열로 보내줄 필요가 있을까요?
성공 유무는 true / false로 보내는게 직관적이지 않을까요?

응답값을 반환해주는 것은 Service의 책임이 아닌 Controller의 책임이 아닐까 싶습니다

2023-09-25 06:47 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/notification/application/FcmNotificationServiceTest.java
> +        assertThat(actual).isEqualTo("알림 전송에 실패했습니다.");
해당 파트가 적어주셨던 `트랜잭션과 테스트 관련 트러블 슈팅` 파트 같네요 

이거는 `@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)`과 `@Transactional`이 같이 묶여서 발생한 이슈라고 생각됩니다 
`@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)`로 인해서 `given`절로 데이터를 넣어주는 트랜잭션과 `then`절에서 조회하는 트랜잭션이 서로 달라서(별도의 스레드) 발생하는 것 같네요 
`given`절에서 저장하기 전(트랜잭션이 끝나기 전)에 `then`절에서 조회하는 스레드의 트랜잭션이 조회하면서 값이 없다고 떠서 발생한 것 같습니다 

그렇다면 `then`절에서 스레드가 트랜잭션에 참여하면서 데이터를 조회하는 시점을 `given`절을 수행하는 스레드가 트랜잭션에 참여해서 데이터를 저장하고 트랜잭션을 커밋하기 전까지 기다리게 하면 되지 않을까요?

```suggestion
TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization() {
    @Override
    public void afterCommit() {
        final String actual = notificationService.send(createNotificationDto);

        assertThat(actual).isEqualTo("알림 전송 성공");
    }
});
```

이렇게 한 번 해보시면 좋을 것 같습니다

2023-09-25 06:47 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/notification/application/FcmNotificationServiceTest.java
> +        assertThat(actual).isEqualTo("알림 전송에 실패했습니다.");
추가적으로 통합 테스트에서는 `mocking`하는 과정을 최대한 지양했으면 좋겠습니다
외부 서비스는 별도로 두고 말이죠 
사실 외부 서비스는 아예 별도로 테스트용 `Stub`이나 `Fake` 등으로 작업하면 좋기는 하겠는데 이건 추후로 리펙토링을 하던가 팀단위로 정해야 할 것 같고..아무튼 그렇습니다

2023-09-25 08:48 UTC, kwonyj1022 approved these changes
컨벤션 관련 요청 사항 하나 작성했습니다. 지토 믿고 approve 드리겠습니다. 수고하셨어요 메리

2023-09-25 09:10 UTC, JJ503 requested changes
궁금한 점이 있기도 하고, 지토가 질문 남겨준 부분들에 대한 답변과 결과도 확인하고 싶어 일단 request changes합니다.
고생 많으셨습니다 메리~🎄

2023-09-25 09:10 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/FcmNotificationService.java
> +            return NOTIFICATION_SEND_FAIL;
`send()`에서 반환하는 값을 사용하지 않는 것으로 보이는데 반환해야 할 이유가 있는지 궁금합니다.
또한, 이때, 문제가 발생한 경우 문자열을 반환하는 것도 어색하게 느껴집니다.

2023-09-29 14:28 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +        final NotificationStatus notificationStatus = notificationService.send(CreateNotificationDto.from(messageDto));
`notificationService.send()` 메서드에서 알림 성공/실패 여부를 반환해주어야 하는지와 관련된 고민입니다.

현재 PR에서 `MessageService.create()`에서 `notificationService.send()` 메서드를 호출하고, 해당 메서드의 알림 전송 실패/성공 여부에 관계 없이 create()는 정상적으로 수행하도록 리팩토링을 진행했습니다. 따라서 알림 전송이 최소한 수행되었는지에 대한 여부를 messageService에서도 알아야 한다고 생각해 notificationService에서 성공/실패 여부를 반환하도록 구현해둔 상태입니다.

그런데 지토가 작업해주신 로그를 찍는 부분에서는 `messageService.create()`가 호출되는 경우에 대한 로그가 찍힐 것이고,
`notificationService.send()`를 수행하면서도 로그가 찍힐 것이기 때문에 굳이 messageService에서 알림 전송 성공/실패 여부에 대한 로그를 찍는 과정이 없어도 될 것 같다는 생각도 들어 이 부분에 대한 여러분의 의견이 필요합니다..!

2023-09-29 17:20 UTC, apptie approved these changes
고생하셨습니다
테스트 코드를 제외하면 제가 언급한 내용은 모두 수정이 된 것 같고
추가적인 사항은 없는 것 같아서 Approve를 드리도록 하겠습니다

다만 테스트 코드는 해당 PR...에서 작성하는거가 아닌거 같은 느낌인데 어떤 식으로 테스트 코드를 리펙토링하실 것인지 말씀해주셨으면 좋겠습니다

2023-09-29 17:20 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +        final NotificationStatus notificationStatus = notificationService.send(CreateNotificationDto.from(messageDto));
### 선택 

해당 부분의 경우 요청을 처리하는 모든 과정을 출력하는 로그가 있지만, 편의성을 위해서 예외 발생 시 log.error로 찍을만하다고생각합니다 
성공의 경우에는 별 필요가 없을 것 같은데, 실패의 경우에는 빠르게 실패의 원인을 찾아야 하므로 여러 로그 파일에 남기게 되면서 발행하는 비용을 감당할만하다고 생각합니다

2023-09-29 17:20 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/FcmNotificationService.java
> +        return firebaseMessaging.send(message);
### 질문

messageId는 무엇인지 혼동이 오는데, Long 타입이 아니라 String 타입인걸 보면 FCM이 지정해주는 message 식별자인가요? 어렵네요...

2023-09-29 17:20 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/dto/CreateNotificationDto.java
> +                // TODO: 2023/09/29 여기 user의 profile이미지를 반환하는 부분인데 merge하는 과정에서 누락이 된건지 원래 이 상태였던건지 잘 모르겠어서 수정해둔 상태입니다. 확인 한 번만 부탁드리겠습니다.
### 질문

일단 로직상으로는 맞는 것 같은데..? 확신은 안드네요

ImageRelativeUrl를 컨트롤러에서부터 받아서 -> MessageService.create()에서  MessageDto.from()으로 전달 -> 쪽지 알림 받는 수신자의 프로필 이미지 id랑 합쳐서 완전한 url 만들기...니까 맞지 않을까요?

확신이 없으니 이건 질문으로 남기겠습니다

2023-09-29 17:40 UTC, JJ503 requested changes
몇 가지 질문 사항과 수정 사항이 보여 다시 rc로 해두도록 하겠습니다.
해당 부분 답변 확인 후 approve로 수정하도록 하겠습니다.

2023-09-29 17:40 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/dto/CreateNotificationDto.java
> +                // TODO: 2023/09/29 여기 user의 profile이미지를 반환하는 부분인데 merge하는 과정에서 누락이 된건지 원래 이 상태였던건지 잘 모르겠어서 수정해둔 상태입니다. 확인 한 번만 부탁드리겠습니다.
### 질문
잘 모르겠는 부분이 있는 데 해당 레코드에서 `redirectUrl`과 `image`를 모두 받는 이유가 궁금합니다.
정확히는 `FcmNotificationService`에서 `IMAGE.getKeyName()`와 `REDIRECT_URL.getKeyName()`의 차이가 무엇인지 궁금합니다.
그리고 image가 이미지 url을 의미하는 것이라면 iamge url로 수정한다면 더 좋을 것이라 생각합니다.

2023-09-30 08:30 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +        final NotificationStatus notificationStatus = notificationService.send(CreateNotificationDto.from(messageDto));
의견 감사합니다.
반영해두었습니다.

2023-09-30 09:02 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/dto/CreateNotificationDto.java
> +    public static CreateNotificationDto from(final MessageDto messageDto) {
이 부분은 bidService 부분이라 우선은 건드리지 않고 의견을 여쭤본 이후에 반영하려고 했습니다!
저는 알림과 관련해서 MessageService와 BidService가 모두 분리되어야 한다고 생각했습니다.
따라서 MessageService에서 DTO를 생성할 때 `CreateNotificationDto`의 정팩메를 사용하도록 수정해두었습니다. 

그런데 정팩메를 생성하게 되면 redirect url을 생성하거나 이미지 url을 생성하는 등의 추가적인 작업을 진행해야 하므로 이런 부분까지 DTO의 역할로 두어도 괜찮은지 궁금해 todo에 의견을 남겨둔 것이었는데, 제대로 전달을 못한 것 같네요ㅠ 

아무튼 기존에 BidService에서 `CreateNotificationDto`를 생성하는 로직을 MessageService에서처럼 정팩메로 대체하는 것이 괜찮을까요? 괜찮다면 통일시키도록 하고, 다른 의견이 있다면 말씀해주시면 감사하겠습니다.

2023-09-30 09:05 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/dto/MessageDto.java
> +    public static MessageDto from(
어엇.. 감사합니다... 머쓱.. 죄송..

2023-09-30 09:15 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/FcmNotificationService.java
> +        return firebaseMessaging.send(message);
네 맞습니다! FCM에서 알림 전송에 성공할 경우 전송한 알림에 대한 식별자를 생성해 반환해주고, 메시지 전송에 실패한 경우 null을 반환해주는 것으로 알고 있습니다. 따라서 null이 반환되는 경우 NotificationStatus를 FAIL로 반환할 수 있도록 했습니다.

2023-09-30 09:21 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/dto/CreateNotificationDto.java
> +                // TODO: 2023/09/29 여기 user의 profile이미지를 반환하는 부분인데 merge하는 과정에서 누락이 된건지 원래 이 상태였던건지 잘 모르겠어서 수정해둔 상태입니다. 확인 한 번만 부탁드리겠습니다.
`redirectUrl`은 알림을 클릭한 경우 요청하게 되는 url입니다.
이미지에 대한 요청과는 무관한 url로 알고있습니다.

`FcmNotificationService`에서 알림 전송을 위한 `Message` DTO를 생성하기 위해 Map에 {Key, Value}와 같이 알림 전송에 필요한 데이터를 세팅합니다. 
이때 `IMAGE.getKeyName()`는 `imageUrl`을 담기 위해 "image"라는 key에 `imageUrl`을 담아주는 것이고,
`REDIRECT_URL.getKeyName()`는 사용자가 알림을 클릭한 경우 이동할 redirectUrl을 담아주기 위해 필요한 key와 value를 세팅해주는 과정이라고 생각해주시면 될 것 같습니다!

> 그리고 image가 이미지 url을 의미하는 것이라면 iamge url로 수정한다면 더 좋을 것이라 생각합니다.
→ 이 부분은 반영해두었습니다!

2023-09-30 09:23 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/dto/CreateNotificationDto.java
> +    public static CreateNotificationDto from(final MessageDto messageDto) {
그렇군요! 만약 그런 것이라면 todo를 사용해 추후 할 예정임을 암시해 준다면 더 좋을 것 같아요!
저는 두 가지의 알림 dto가 서로 다른 방식으로 만들어지는 것이 걸렸던 것이기에 메리가 이야기해 주신 부분이라면 괜찮다고 생각합니다!
그런데 redriect url 등과 관련해 궁금한 내용이 있는데 해당 부분은 [지난번에 작성한 코멘트](https://github.com/woowacourse-teams/2023-3-ddang/pull/445/files/9bb64bd5f8a99833175424f656dabcb55af794ac#r1341645691)에 답변해 주시면 감사하겠습니다!

2023-09-30 09:34 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/dto/CreateNotificationDto.java
> +    public static CreateNotificationDto from(final MessageDto messageDto) {
답변 작성해두었습니다. [링크](https://github.com/woowacourse-teams/2023-3-ddang/pull/445/files/9bb64bd5f8a99833175424f656dabcb55af794ac#r1341935507)

그리고 bidService도 messageService와 같이 통일시켜주도록 리팩토링 진행했습니다.

2023-09-30 09:58 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/notification/application/FcmNotificationServiceTest.java
> +        TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization() {
### 칭찬

칭찬해요!!!!!!!!!!!!!!!!!!!!!!!!!!@@@@@@@@@@#!

이제 서비스에서 mocking을 최소화하고 테스트가 가능하겠네요

2023-10-01 01:46 UTC, JJ503 approved these changes
해당 pr을 다시 확인하지 못해 리뷰가 늦었네요..! 죄송합니다.
로직에서 헷갈린 부분이 있었는데 메리의 자세한 설명 덕분에 잘 이해했습니다!
고생 많으셨습니다~!

2023-10-01 01:46 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/dto/CreateNotificationDto.java
> +                // TODO: 2023/09/29 여기 user의 profile이미지를 반환하는 부분인데 merge하는 과정에서 누락이 된건지 원래 이 상태였던건지 잘 모르겠어서 수정해둔 상태입니다. 확인 한 번만 부탁드리겠습니다.
아하 그렇군요!
해당 로직을 이해함에 있어 헷갈린 듯하네요..!
자세한 설명 감사합니다.

2023-10-01 01:46 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/dto/CreateNotificationDto.java
> +    public static CreateNotificationDto from(final MessageDto messageDto) {
확인했습니다. 감사합니다!

2023-10-01 01:59 UTC, merged