이미지 url 관련 네이밍 수정
woowacourse-teams/2023-3-ddang pull request #470
Opened 2023-09-28 02:02 UTC by JJ503

## 📄 작업 내용 요약

이미지 url 관련 네이밍 수정

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- 네이밍 관련해 수정을 진행하며 추가적으로 진행한 내용은 아래와 같습니다.
  해당 부분에 대해서도 확인해주시면 감사하겠습니다.

1. ImageUrlCaclulator의 비슷한 메서드 통합
2. UserAuctionController에서 Util을 사용하도록 수정

## 📎 Issue 번호

- clsoed #469

2023-09-28 04:17 UTC, kwonyj1022 requested changes
제이미 수고하셨습니다!
jacoco 성공하는 거 보고 approve 드릴게요~

2023-09-28 04:17 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java
> +    public Long create(final CreateBidDto bidDto, final String absoluteUrl) {
### 선택
controller 입장에서 어떤 url이 필요한지 파라미터 명으로 알 수 있도록 `absoluteAuctionImageUrl`로 파라미터 이름을 변경하면 좋을 것 같습니다.

2023-09-28 04:17 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +    public Long create(final CreateMessageDto dto, final String absoluteUrl) {
### 선택
여기도 BidService에 제안드린 내용과 같이, 컨트롤러에서 이 메서드 호출 시 어떤 url이 필요한지 알 수 있도록 `absoluteProfileImageUrl`로 파라미터 이름을 변경하면 좋을 것 같아요!

2023-09-28 04:17 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/ImageController.java
> +        headers.setContentType(MediaType.IMAGE_JPEG);
### 칭찬
이미지 타입 변경 👍

2023-09-28 09:15 UTC, apptie approved these changes
고생하셨습니다
Approve와 함께 질문 무더기를 드리도록 하겠습니다

2023-09-28 09:15 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageUrlCalculator.java
> +    public static String calculateBy(final ImageRelativeUrl imageRelativeUrl, final Long id) {
### 질문

calculate에서 calculateBy로 변경하신 이유가 궁금합니다 
개인적으로 calculateBy와 같이 By라는 네이밍을 사용한다면 JPA쪽 메서드와 이름을 맞춰서 calculateByUrlAndId 뭐 이런식을 생각했는데 제 생각이랑 좀 달라서 아리송하네요 
메서드 파라미터 명으로 인해 By 이후의 명칭을 제외했다면 By 또한 생략해서 큰 문제가 없을 것이라고 생각합니다 
그래서 네이밍의 의도가 궁금합니다

2023-09-28 09:15 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageUrlCalculator.java
> +        }
### 선택

위에 있는 calculateBy에도 포함될 것 같은 내용입니다

이 부분에서 return null의 null이 무슨 의미인지 상수로 명시한다면 가독성이 더 좋아질 것 같습니다

2023-09-28 09:15 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/user/presentation/UserAuctionController.java
> +        final ReadAuctionsResponse response = ReadAuctionsResponse.from(readAuctionsDto);
### 칭찬

칭찬해요!!!!!!!!!!!!!
이 부분 제가 작성했던 것 같은데 정신을 놓고 코딩해서 그런지 util 사용을 빼먹었던 것 같네요
 
사실 이 때 util이 있었는지 없었는지 기억조차 안나지만 어쨌든 정말 감사합니다

2023-09-28 09:15 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/AuctionDetailResponse.java
> +    private static List<String> convertImageFullUrls(final ReadAuctionDto dto) {
### 질문

저는 이런 경우 이름을 짓는게 상당히 헷갈렸는데 갑자기 떠올라서 질문을 드립니다 

이거는 
`이미지`가 여러 개 / `이미지 url`이 여러 개
중 어떤 식으로 봐야 할지 항상 고민했습니다

지금 코드로 예시를 들면 `convertImagesFullUrl`이 자연스러운지 `convertImageFullUrls`가 자연스러운지 항상 고민되더라고요 

그래서 이렇게 네이밍을 해주신 이유가 궁금합니다

2023-09-28 09:15 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadAuctionResponse.java
> +                convertImageFullUrl(dto.auctionImageIds().get(0)),
### 질문

이 부분에 대해서 엔초가 제안해주셨던 이미지에 대표 이미지인지 여부에 대한 값을 지정해주는지 여부가 생각났는데

만약 나중에 리펙토링을 하기로 했다면 이 부분에 대한 TODO를 남겨놓는 것이 좋을까요?

2023-09-28 09:15 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/user/presentation/dto/response/ReadAuctionsResponse.java
> -                                                                              ))
### 칭찬

칭찬해요!!!!!!!!!!!!!!!!!!!!!1

이 과정 귀찮으셨을텐데 정말 감사합니다

2023-09-28 09:15 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageUrlCalculator.java
> +        }
### 질문

그리고 갑자기 생각난건데 id가 null인 경우라면 이는 요청에서 문제가 발생한 것이 아닐까라는 생각이 들었습니다

프로필 이미지는 가입할 때 저희가 무조건 기본값(store_name이 default_뭐시기.png)인걸로 설정하고 있고
경매 이미지는 무조건 1장 이상인데 이 경우라면 id가 null인 경우가 있을지 궁금하고 

id가 null인 경우를 고려한다면 id가 0 이하인 경우도 고려해야하지 않을까하는 궁금증도 생겼습니다

알려주세요 제이미!!@#!@#!@#!@#!@#

2023-09-28 12:19 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java
> +    public Long create(final CreateBidDto bidDto, final String absoluteUrl) {
### 선택

저도 엔초 의견에 동의합니다!

2023-09-28 13:11 UTC, swonny approved these changes
제이미 연휴 첫 날부터 고생 많으셨습니다!!
저도 approve와 함께 질문 몇 가지 남겨두었어요!

2023-09-28 13:11 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadAuctionResponse.java
> +    private static String convertImageFullUrl(final Long id) {
### 선택

단순히 ImageUrlCalculator의 메서드만 호출하고 있는데, 메서드 분리가 필요할까요??
이 부분도 어떻게할지 논의하는 게 좋을까요?

2023-09-28 15:47 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/ImageController.java
> +        headers.setContentType(MediaType.IMAGE_JPEG);
1. 이미지 저장 자체를 jpg로만 하고 있다고 들어 바꾸게 되었는데 아니었을까요? 글로와 이야기를 하다 그렇다 이야기를 듣게 되어 변경하게 되었습니다. 현재 대부분의 이미지 데이터가 jpg였기 때문이기도 하고요. 그런데, png도 가능한 형태라면 확장자 확인을 통해 content-type 정해주는 것이 좋을 것 같습니다.
아직까지 문제는 없었지만, 굳이 찝찝한 상황을 만들 필요는 없을 것이라 생각하기도 하고요!

2. 해당 부분은 굳이 미리 하지 않아도 된다고 생각합니다. 그에 대한 것은 확장성 때문일 수도 있지만, 결국 S3가 도입된다가 가정이기에 해당 부분을 할 때 리팩토링하는 방식이 더 적절하다고 생각하기 때문입니다. 개인적으로 S3 파트가 궁금하긴 해서 고민해보도록 하겠습니다.

2023-09-28 15:48 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadAuctionResponse.java
> +    private static String convertImageFullUrl(final Long id) {
저도 이 생각이 들기는 했습니다. 아마 맨 처음에는 ImageUrlCalculator가 없었어서 메서드 분리가 있었고, 그다음부터는 이전 코드가 메서드 분리가 되어 있어서 계속 저 상태가 된 것 같습니다. 제 개인적으로는 이미지 url 관련 역할이 분리되어 있는 만큼 이제는 합쳐도 될 것 같다고 생각합니다. 지토 의견도 궁금하군요.

제이미만 괜찮다면 논의 결과에 따라 이 pr에서 같이 작업해 주시면 감사하겠습니다!

2023-09-28 15:51 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageRelativeUrl.java
> +// TODO: 2023-09-28 [고민] ImageRelativeUrl vs RelativeImageUrl
개인적인 의견으로는 ImageUrl로만 되어 있다면 해당 enum의 값들이 어떤 것을 의미하는지 의문이 들 것 같아 최대한 명확하게 진행했습니다.
그런데 해당 부분은 다른 두분의 의견도 궁금하네요!

2023-09-28 15:52 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadAuctionResponse.java
> +    private static String convertImageFullUrl(final Long id) {
생각해보니 그러네요 굳이 한 줄인데 분리할 필요는 없어 보이기는 합니다

2023-09-28 15:52 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageUrlCalculator.java
> +        return absoluteUrl.concat(String.valueOf(id));
결론이 나지 않아 그냥 변동 없이 진행하게 되었습니다.
이참에 정하는 것도 좋고요!

2023-09-28 15:55 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageRelativeUrl.java
> +// TODO: 2023-09-28 [고민] ImageRelativeUrl vs RelativeImageUrl
허거걱 이 todo를 못 봤네요ㅠ 저는 enum이 어떤 값인지 명시하는 게 좋을 것 같고, 둘 중에 고르자면 지토의 의견대로 다른 메서드들과 비슷한 구조인 ImageRelativeUrl이 좋은 것 같습니다.

2023-09-28 15:56 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageUrlCalculator.java
> +    public static String calculateBy(final ImageRelativeUrl imageRelativeUrl, final Long id) {
개인적으로 메서드 명은 동일하지만, 파라미터의 타입 등이 다른 경우 짓던 네이밍 방식입니다.
기존 메서드 명은 `calculate()` 이었는데, 이보다는 `By`를 붙이는 것이 여러 방식이 있다는 측면에서 보다 명확할 것이라 생각했기 때문입니다.
`By` 뒤에 굳이 추가적인 네이밍을 붙이지 않은 이유는 파라미터로 충분히 의미 전달이 가능하다고 생각했기 때문입니다.
이때, JPA와 다른 점은 JPA 메서드는 메서드 네이밍 만으로 쿼리를 생성해야 하기에 일종의 규칙이라 생각하였고, 쿼리와 관련 없는 클래스에서 굳이 이를 따르지 않아도 괜찮다고 생각했기 때문입니다.

하지만, Util 클래스인 만큼 다 같이 사용해야 하는 메서드이기에 다른 분들의 의견이 궁금합니다!

2023-09-28 15:56 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageUrlCalculator.java
> +        }
> 이 부분에서 return null의 null이 무슨 의미인지 상수로 명시한다면 가독성이 더 좋아질 것 같습니다

좋습니다! null보다는 그 편이 어떤 값을 전달하려는 지 보다 명확하겠네요!

2023-09-28 16:07 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageUrlCalculator.java
> +        }
> 그리고 갑자기 생각난건데 id가 null인 경우라면 이는 요청에서 문제가 발생한 것이 아닐까라는 생각이 들었습니다
프로필 이미지는 가입할 때 저희가 무조건 기본값(store_name이 default_뭐시기.png)인걸로 설정하고 있고
경매 이미지는 무조건 1장 이상인데 이 경우라면 id가 null인 경우가 있을지 궁금하고

알람 이미지를 위해 만들었던 메서드의 경우 id가 아닌 도메인을 받아 처리하는 데, 이때, 이미지가 null인 경우 id를 가져올 때 문제가 생기기에 만들었던 로직입니다...
아무 생각 없이 메서드들을 통합하는 바람에 필요 없는 로직이 들어가 버렸네요... 허허
해당 로직은 삭제하도록 하겠습니다!

> id가 null인 경우를 고려한다면 id가 0 이하인 경우도 고려해야하지 않을까하는 궁금증도 생겼습니다

null을 고려하는 로직은 삭제할 거기도 하고, 0 이하는 이미지를 찾는 과정에서 고려해도 충분할 것이라 생각합니다.
어떻게 생각하시나요?

2023-09-28 16:15 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/AuctionDetailResponse.java
> +    private static List<String> convertImageFullUrls(final ReadAuctionDto dto) {
이유는 두 가지입니다.
1. 기존 메서드가 그러했음 + 이미지 아이디를 가져오는 메서드도 `auctionImageIds()`임
2. 이미지를 각각 url로 calculate 해 이미지들을 List로 모으기 때문

2023-09-28 16:17 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadAuctionResponse.java
> +                convertImageFullUrl(dto.auctionImageIds().get(0)),
아하
까먹을 것 같다면 todo를 해두는 것이 좋을 것 같습니다.
그런데 해당 부분보다는 auction image 도메인에 todo로 남겨두는 것이 명확할 것 같은 데 어떻게 생각하시나요?

2023-09-28 16:18 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageUrlCalculator.java
>              return null;
null을 반환해줘야 할 이유도 없어져 해당 로직은 삭제했습니다.

2023-09-28 16:20 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadAuctionResponse.java
> +    private static String convertImageFullUrl(final Long id) {
오 확인했습니다!
해당 부분들은 수정해두도록 하겠습니다!

2023-09-28 16:58 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/ImageController.java
> +        headers.setContentType(MediaType.IMAGE_JPEG);
1. 지금은 클라이언트에서 jpg로 오고 있기는 하지만 백엔드 서버에서는 jpg, jpeg, png가 모두 허용되는 상황이라...
클라이언트에 맞춰서 LocalStoreImageProcessor가 jpg만을 저장할 수 있도록 리펙토링하는게 더 낫겠네요 

2. 제이미가 해주신 답변 보니 지금은 굳이스럽기는 하네요 감사합니다

2023-09-28 16:59 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageUrlCalculator.java
> +        return absoluteUrl.concat(String.valueOf(id));
저는 `concat`보다는 `+`가 더 가독성이 좋다고 생각하는 편입니다

`Objects.isNull(target)`과 `target == null` 중 후자가 더 가독성이 좋은 느낌과 유사한 느낌입니다

2023-09-28 17:01 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/AuctionDetailResponse.java
> +    private static List<String> convertImageFullUrls(final ReadAuctionDto dto) {
> 기존 메서드가 그러했음 + 이미지 아이디를 가져오는 메서드도 auctionImageIds()임

Auction이면 제가 지었을 것 같은데 전 제 네이밍을 믿지 않습니다...

> 이미지를 각각 url로 calculate 해 이미지들을 List로 모으기 때문
이건 상당히 설득력 있는 주장이로군요 감사합니다

2023-09-28 17:02 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadAuctionResponse.java
> +                convertImageFullUrl(dto.auctionImageIds().get(0)),
AuctionImage 쪽을 수정해도 DTO 로직은 동일하게 수행이 가능할 것 같아서 음...그냥 둘 다 TODO 하는건 어떨까요

2023-09-28 17:09 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageUrlCalculator.java
> +        }
### 질문
파라미터를 long으로 받는다면 해당 파라미터에 null이 들어갈 때 NPE가 발생하지 않나요?

2023-09-28 17:11 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/ImageController.java
> +        headers.setContentType(MediaType.IMAGE_JPEG);
이 부분.. 프로필 기본 이미지는 png로 되어있어서 jpg로 강제한다면 서버 측 수정도 필요할 것 같네요.

2023-09-28 17:11 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageUrlCalculator.java
> +        return absoluteUrl.concat(String.valueOf(id));
저도 +가 더 좋아요~

2023-09-28 17:13 UTC, kwonyj1022 approved these changes
자코코  성공하는거 봤으니 approve로 바꿨어요!

2023-09-29 02:03 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageUrlCalculator.java
> +        }
id가 null인 경우는 없을 것이라 생각합니다. 이미지 객체가 null이라면 id를 가져오는 과정에서 이미 오류가 발생했을 것이기 때문입니다.
그래서 이미지에 대해 util클래스를 통해 url로 변환하기 전에 이에대한 처리가 필요할 것이리 생각합니다.
이는 util 클래스의 역할 밖이라 생각해 객체가 아닌 id를 받도록 했습니다.
이에 대한 다른 분들의 의견이 궁금합니다!

2023-09-29 03:00 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/ImageController.java
> +        headers.setContentType(MediaType.IMAGE_JPEG);
그렇다면 일단, jpeg와 jpg는 동일하기 때문에 jpeg 타입으로 두도록 하겠습니다.
추석 이후에 혹시 모르니 기본 이미지를 jpeg로 변환한 뒤에 LocalStoreImageProcessor에서 jpeg, jpg로만 받을 수 있도록 리팩토링 진행하도록 하겠습니다.

2023-09-29 03:01 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/ImageController.java
> +        headers.setContentType(MediaType.IMAGE_JPEG);
일단은 현재 상태 그대로 진행하도록 하겠습니다.

2023-09-29 03:02 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageUrlCalculator.java
> +        return absoluteUrl.concat(String.valueOf(id));
좋습니다! 그러면 하는 김에 모든 `concat`을 `+`로 변환해 두도록 하겠습니다!

2023-09-29 03:03 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadAuctionResponse.java
> +                convertImageFullUrl(dto.auctionImageIds().get(0)),
좋습니다! 두 부분 모두 TODO 처리해두도록 하겠습니다.

2023-09-29 03:20 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadAuctionResponse.java
> +// TODO: 9/29/23 추후 대표 이미지 관련 필드 추가
### 칭찬

칭찬해요!@#!@#!@#!@#!@#!@#
의견 반영 감사합니다

2023-09-29 03:21 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/authentication/infrastructure/oauth2/Oauth2Type.java
> +                             .toLowerCase(Locale.ENGLISH);
### 선택 

요거 뭔가 삐딱선..?
`.` 위치가 살짝 안맞는거같아서 살짝 불편하기는 하네요

2023-09-29 03:24 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/authentication/infrastructure/oauth2/Oauth2Type.java
> +                             .toLowerCase(Locale.ENGLISH);
으아닛 바로 수정했습니다.
감사합니다!

2023-09-29 03:39 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageUrlCalculator.java
> +        }
이러한 이슈가 있었군요
저는 제이미의 의견에 동의합니다 
차라리 NPE가 발생하는게 오히려 예외 잡기에는 더 좋을지도 모르겠네요

2023-09-29 04:58 UTC, kwonyj1022 requested changes
수정하시기로 한 부분 중에 하나 안된 것이 있네요~

2023-09-29 04:58 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +    public Long create(final CreateMessageDto dto, final String absoluteUrl) {
### 필수
이 부분 수정이 안되어 있습니다!

2023-09-29 04:59 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageUrlCalculator.java
> +        }
### 질문
이 부분은 수정을 안하기로 하신건가요? 어떻게 하기로 결정했는지 궁금합니다.

2023-09-29 07:38 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +    public Long create(final CreateMessageDto dto, final String absoluteUrl) {
억 아래 `send()`의 파라미터 이름만 수정하고 수정했다고 생각했네요... 감사합니다 엔초!

2023-09-29 07:42 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageUrlCalculator.java
> +        }
메리 의견도 들어보고 싶어 아직 진행하지 않았습니다.
그런데 개인적으로는 long으로 처리하는 게 보다 명확할 것이라 생각해 수정 진행하도록 하겠습니다!

2023-09-29 09:49 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageUrlCalculator.java
> +        }
의견을 나눠본 결과 long으로 바꾸는 과정은 현재 pr 및 이슈와 관련이 없다고 생각해 다시 Long으로 돌려두었습니다.
다만, 이 과정은 모두 필요하다고 해주셨기에 따로 이슈를 만들도록 하겠습니다.

2023-09-29 09:59 UTC, kwonyj1022 approved these changes
제이미 수고하셨습니다!!!

2023-09-29 10:00 UTC, merged