카테고리 관련 테스트 코드 리펙토링
woowacourse-teams/2023-3-ddang pull request #472
Opened 2023-09-28 11:13 UTC by apptie

## 📄 작업 내용 요약

카테고리 관련 테스트 코드 리펙토링
## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- 특이사항이 있습니다 
  - JpaCategoryRepositoryTest 테스트의 경우 Category는 직접 DB에서 insert로 저장하기 때문에 save() 관련된 모든 로직을 사용하지 않습니다
  - 이로 인해 픽스처에서 모든 도메인을 저장해주는 상황이 발생했습니다 
## 📎 Issue 번호

2023-09-28 13:19 UTC, kwonyj1022 requested changes
지토 수고하셨어요! 테스트 리팩토링 첫 pr 작성자가 되셨군요 ㅎㅎ 필수 사항은 없지만 제안드린 내용이 많고 질문 남긴 것도 있어서 request change 해놓았습니다.

2023-09-28 13:19 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/fixture/JpaCategoryRepositoryFixture.java
> +public class JpaCategoryRepositoryFixture {
### 질문
저번에 컨벤션 관련 회의할 때는 생각하지 못했는데, 궁금한 점이 생겨서 이곳에 질문 남깁니다.
레포지토리 테스트에서든, 서비스 테스트에서든 `@DataJpaTest`, `@Import`, `@IsolateDatabase` 같은 테스트에 필요한 어노테이션들이  픽스처 클래스에 있는 것보다는 테스트 클래스에 명시되어 있는 게 가독성 면에서 좋지 않을까? 오히려 `@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)`나 `@SuppressWarnings("NonAsciiCharacters")`는 테스트에 직접적인 영향이 있는 어노테이션이 아니라 편의를 위한 어노테이션이기 때문에 이 두 어노테이션이 픽스처 클래스에 있는 편이 좋을 것 같다. 라는 생각이 들었습니다.

`@DataJpaTest`, `@Import`, `@IsolateDatabase` 같은 어노테이션들을 테스트 클래스로 옮기게 되면 픽스처 클래스의 `@Autowired`에 빨간 줄이 생기기는 하지만  테스트를 돌렸을 때 성공하기는 하는데, 혹시 보이지 않는 다른 문제가 생기는지 궁금합니다.

2023-09-28 13:19 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/category/application/fixture/CategoryServiceFixture.java
> +    JpaCategoryRepository categoryRepository;
### 선택
픽스처가 아닌 필드의 접근 지정자는 private로 하기로 했던 것 같습니다!

2023-09-28 13:19 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/category/application/fixture/CategoryServiceFixture.java
> +@IsolateDatabase
`@IsolateDatabase` 에 `@Transactional` 어노테이션을 제거하고 `DatabaseCleanListener.class`도 수정되었는데, 물론 저번 회의 때 임시로 만들어 놓은 브랜치 가서 제가 복사해 올 수도 있지만, 해당 수정 사항을 지토가 수정해 주신 만큼 지토가 pr 만들어주시면 좋을 것 같아요~~

2023-09-28 13:24 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/fixture/JpaCategoryRepositoryFixture.java
> +public class JpaCategoryRepositoryFixture {
오 지난번엔 생각 못했었는데 저도 테스트에 필요한 어노테이션은 픽스처 클래스보다 테스트에 명시하는 것이 좋다는 엔초의 의견에 동의합니다!

2023-09-28 13:26 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/category/domain/CategoryTest.java
> +            softAssertions.assertThat(sub.getMainCategory()).isNotNull();
이 부분도 엔초 의견에 동의합니다!

2023-09-28 13:27 UTC, swonny approved these changes
저는 엔초가 남겨준 부분 말고는 추가적인 리뷰는 없습니다!
테스트 코드 리팩토링 PR 진행하시느라 고생많으셨습니다!!

2023-09-28 13:47 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/category/application/fixture/CategoryServiceFixture.java
> +@IsolateDatabase
@IsolateDatabase의 경우 별도의 이슈를 올려서 처리하도록 하겠습니다 

할일이 늘었군요

2023-09-28 13:54 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/fixture/JpaCategoryRepositoryFixture.java
> +public class JpaCategoryRepositoryFixture {
엔초와 메리가 말씀해주신 가독성 측면에서는 동의를 하지만
문제는 `JpaCategoryRepositoryFixture`에서 `@DataJpaTest`를 누락한다면 `EntityManager`나 `JpaCategoryRepository`를 `@Autowired`로 주입받을 수 없습니다
`@DataJpaTest`는 내부적으로 `@Transactional`을 가지고 있으므로 이는 `@Transactional` 설정이 없어진다는 의미와 동일하므로 `JPA`를 사용하기 때문에  `Fixture`로 만들 도메인 엔티티를 테스트 DB에 저장할 수 없다는 의미가 됩니다  

`@DataJpaRepository`를 `Fixture`에도 `Test`에도 건다면 `@Transactional`이 이중으로 붙어서 어떤 문제가 발생할지 모르기 때문에 피하고 싶네요 

위와 같은 이유로 저는 `Fixture` 클래스에 어노테이션을 부득이하게 추가해야 한다고 생각하며, 추가해야한다면 다른 `Fixutre` 클래스에도 통일하는게 좋다고 생각합니다

2023-09-28 13:54 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/JpaCategoryRepositoryTest.java
>      void 하위_카테고리가_아닌_아이디를_전달하면_빈_Optional을_반환한다() {
네이밍 어렵네요 감사합니다

2023-09-28 13:56 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/JpaCategoryRepositoryTest.java
> +        });
순서가 별로 중요하지 않은 로직이라서 대충 contains로 퉁치고 넘어간 것 같습니다 
개인적으로 List 비교는 선호하지 않아서 (컬렉션 비교는 비용이 비싼 것으로 알고 있습니다) 
해당 부분의 순서를 검증하는 것으로 변경하겠습니다

2023-09-28 13:58 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/category/application/CategoryServiceTest.java
> +        });
해당 부분의 actual은 ReadCategoryDto이고 Fixture는 Category이므로 isEqualTo 비교가 불가능합니다

2023-09-28 13:59 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/category/application/CategoryServiceTest.java
> +        });
해당 부분의 actual은 ReadCategoryDto이고 Fixture는 Category이므로 isEqualTo 비교가 불가능합니다 22

2023-09-28 14:01 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/category/domain/CategoryTest.java
> +            softAssertions.assertThat(sub.getMainCategory()).isNotNull();
노션에는 `테스트하려는 도메인 객체 외에는 모두 픽스처 생성`이라고 명시가 되어 있어서 픽스쳐를 사용하지 않았습니다 

저는 Category에 대한 도메인을 테스트하기 때문에 생성하는 과정은 직접적인 연관이 없어도 Fixture로 분리하지는 않았었는데 
`CategoryTest`라는 도메인 단위 테스트에서도 `인스턴스를 생성하는 행위`는 테스트 케이스에서 필요하지 않으므로 이것도 Fixture로 가는게 맞나요? 이 부분이 계속 헷갈리네요

2023-09-28 14:02 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/category/application/fixture/CategoryServiceFixture.java
> +    protected Category 가구_하위_책상_카테고리;
👍

2023-09-28 14:05 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/category/domain/CategoryTest.java
> +            softAssertions.assertThat(sub.getMainCategory()).isNotNull();
Category가 테스트하려는 도메인이기 때문에 fixture를 생성하지는 않지만 id는 세팅해야 하지 않을까 해서 질문드렸습니다.

2023-09-28 14:06 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/category/application/CategoryServiceTest.java
> +        });
아 맞네요 죄송합니다ㅠ

2023-09-28 14:06 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/category/application/CategoryServiceTest.java
> +        });
이 부분도 죄송합니다..ㅠㅠ

2023-09-28 14:08 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/category/application/fixture/CategoryServiceFixture.java
> +@IsolateDatabase
감사합니다 지토 🙇

2023-09-28 14:52 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/fixture/JpaCategoryRepositoryFixture.java
> +public class JpaCategoryRepositoryFixture {
(뭔가 현재 트랜잭션을 출력해보고 싶어서 이것저것 해보다가 안돼서 이렇게라도 질문 남깁니다.)

제가 상속의 세부적인 동작 원리를 잘 몰라서 생긴 질문인 것 같습니다.

테스트 실행 시에 성공하는 것은 최종적으로는 주입받는 것을 성공했기 때문에 테스트가 성공하는 것이 아닌가요? 
fixture 클래스 혼자서는 주입을 받을 수 없겠지만 해당 클래스를 확장하는 자식 클래스가 존재하기 때문에 주입이 된 게 아닌가 라는 생각을 했습니다. 실제로 아래와 같이 fixture 클래스를 상속하는 클래스에 아무런 어노테이션을 추가하지 않으면 빈 주입에 실패해서 에러가 발생하게 됩니다.
```java
public class TestTest extends JpaCategoryRepositoryFixture {

    @Test
    void asdf() {
        final Category category = new Category("임시");
        assertThat(category).isNotNull();
    }
}
```

2023-09-28 15:05 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/fixture/JpaCategoryRepositoryFixture.java
> +public class JpaCategoryRepositoryFixture {
조금 다른 이야기인데, `@SuppressWarnings("NonAsciiCharacters")`는 한글에 대한 경고 때문이라도 픽스처 서블릿에 있으면 좋을 것이라 생각합니다.
하지만, `@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)`는 테스트에 있어야 하지 않나 싶습니다.
테스트에 직접적인 영향을 주지 않는다고 하지만, Fixture 클래스에 있어야 하는 이유를 잘 모르겠습니다.
해당 어노테이션은 테스트 메서드 네이밍을 위한 어노테이션이기에 현재로서는 픽스처와는 관계없는 어노테이션이라는 생각이 드는데 테스트 클래스에 있는 것이 더 적절하지 않을까요?

2023-09-28 15:15 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/category/domain/CategoryTest.java
> +            softAssertions.assertThat(sub.getMainCategory()).isNotNull();
조금 헷갈리는 부분이 있습니다.
당시 reflection을 사용하더라도 id를 세팅해 주기로 했던 이유는 로직상 id를 통해 동등성 비교를 하는 과정이 있기 때문이라 기억하고 있습니다.
그래서 해당 도메인을 테스트하기 위해 굳이 id를 세팅해줘야 할 이유가 궁금합니다.

2023-09-28 15:19 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/fixture/JpaCategoryRepositoryFixture.java
> +public class JpaCategoryRepositoryFixture {
아 이거 제가 헷갈렸네요 `@BeforeEach`가 Fixture 클래스에서 별개로 동작하는걸로 인지해버렸습니다 
이 부분에 대해서는 엔초와 메리의 의견이 맞네요 
혼동을 드려 죄송합니다 

다만 저도 `@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)`는 테스트 메서드의 `_`를 ` `로 변경해주는 것이니 제이미의 의견과 동일하게 테스트 클래스에 있어야 한다고 생각합니다 

그리고 `@SuppressWarnings("NonAsciiCharacters")`는 Fixture에도 테스트에도 있어야겠네요

2023-09-28 15:24 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/fixture/JpaCategoryRepositoryFixture.java
> +public class JpaCategoryRepositoryFixture {
### 질문
`@SuppressWarnings("NonAsciiCharacters")`을 fixture와 테스트 둘 다에 두는 이유는 무엇인지 궁금합니다.

2023-09-28 15:28 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/category/domain/CategoryTest.java
> +            softAssertions.assertThat(sub.getMainCategory()).isNotNull();
그것도 그러네요
단순히 동등성 비교를 하기 위해 id를 리플렉션해줘야하는가? 는 잘 모르겠군요...

2023-09-28 15:28 UTC, JJ503 requested changes
지토 고생 많으셨습니다!
그런데 엔초가 질문해준 부분에 대한 코멘트들을 보다보니 헷갈리는 부분이 있어 일단 해당 부분이 해결되면 다시 approve로 수정하도록 하겠습니다.
추가적으로 변수 명과 관련해 의견을 제안해 보았는데 해당 부분은 지토가 편하신대로 해주세요!

2023-09-28 15:28 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/category/application/fixture/CategoryServiceFixture.java
> +    protected Category 가구_하위_책상_카테고리;
### 선택
메서드에서 `하위`가 아닌 `서브`카테고리로 진행할 것이라면, 해당 픽스처 네이밍도 `서브`로 진행하는 것이 어떨까요?

2023-09-28 15:33 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/fixture/JpaCategoryRepositoryFixture.java
> +public class JpaCategoryRepositoryFixture {
`@SuppressWarnings("NonAsciiCharacters")`의 경우 인텔리제이 경고 억제입니다 
그래서 상속이 의미가 없다고 보면 될 것 같습니다 

Fixture에서 `@SuppressWarnings("NonAsciiCharacters")`를 명시하고 이를 상속한다고 하더라도 테스트에서는 여전히 인텔리제이가 경고를 발생시키게 됩니다

2023-09-28 15:34 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/category/application/fixture/CategoryServiceFixture.java
> +    protected Category 가구_하위_책상_카테고리;
동의합니다 통일해야겠네요

2023-09-28 15:37 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/category/domain/CategoryTest.java
> +            softAssertions.assertThat(sub.getMainCategory()).isNotNull();
답변들을 보고 다시 생각해 보았을 때 뭔가 도메인을 보지 않고 저 테스트코드만 봤을 때 null이 아니라는 이유로 원하는 서브카테고리가 잘 세팅이 되었다는 것을 정확하게 나타낼 수 있는가?라는 생각이 들었습니다. 

만약 카테고리 생성 시 디폴트로 서브 카테고리(예를 들면 '기타')를 하나 생성하는 코드가 존재하는 상황이고, 
Category의 addCategory 메서드가 제대로 동작하지 않는 상황을 가정해 본다면, 
실패해야 하는 테스트가 성공하게 됩니다. 

따라서 단순히 null이 아니라는 것이 addCategory()가 정상적이라는 것을 보장할 수 없다고 생각합니다.

리플렉션 관련해서 말씀드리자면,
리플렉션 얘기가 나온 발단은 제이미가 말씀해 주신 그 상황이 맞습니다. 다만 이곳에서도 리플렉션을 말씀드린 이유는 그냥 다른 도메인과의 통일성을 위해 말씀드렸던 것입니다. id를 세팅하지 않는다면 name으로라도 비교하는 것이 더 좋을 것 같습니다.

2023-09-28 15:43 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/category/domain/CategoryTest.java
> +            softAssertions.assertThat(sub.getMainCategory()).isNotNull();
name으로 비교는 괜찮아보이네요 다른분들 의견은 어떠신가요

2023-09-28 15:48 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/category/domain/CategoryTest.java
> +            softAssertions.assertThat(sub.getMainCategory()).isNotNull();
저는 name으로 비교 좋습니다!

2023-09-28 16:13 UTC, JJ503 approved these changes
확인 완료했습니다!
실제로 하는 첫 리팩토링이다보니 여러 이야기를 나눌 수 있었군요 허허
고생 많으셨습니다 지토!

p.s. 테스트를 한 번에 리팩토링할까 생각했는데, 오히려 이렇게 도메인 별로 하니 확인이 편해 더 좋을 것 같네요!

2023-09-28 16:19 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/category/domain/CategoryTest.java
> +            softAssertions.assertThat(sub.getMainCategory()).isNotNull();
그러네요 동등성 비교를 위해 리플렉션으로 id를 부여하는 게 어색하네요!

근데 헷갈리는 점은 도메인 동등성 비교를 할 때는 id 대신 name과 같이 대표성을 띄는 속성으로 비교하게 되는걸까요?
그리고 id가 동일하면 동일성을 보장한다는 가정 하에 모든 로직이 수행되고 있는데, 임의로 name만 지정해서 name이 같으면 동일성을 보장한다고 판단해도 괜찮은지 잘 판단이 서지 않네요..!

2023-09-28 16:37 UTC, kwonyj1022 requested changes
지토 수고하셨습니다. 그런데 수정하시겠다고 하신 부분 중에 누락된 부분이 있어서 rc 유지하겠습니다..

2023-09-28 16:37 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/category/domain/CategoryTest.java
> +            softAssertions.assertThat(sub.getMainCategory().getName()).isEqualTo(main.getName());
### 질문
main 카테고리를 굳이 검증할 필요가 있나요?

2023-09-28 16:37 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/JpaCategoryRepositoryTest.java
>      JpaCategoryRepository categoryRepository;
### 질문
이 부분도 갑자기 이제와서야 궁금하네요..
JpaCategoryRepository는 픽스처에서 `@Autowired`로 빈 주입을 받고 있고, 빈의 경우 처음 생성된 것이 계속 재사용되기 때문에 여기서도 동일한 빈을 주입받게 됩니다. 따라서 중복된 코드(?)라고 볼 수 있을 것 같은데 테스트 클래스에 추가적으로 선언해도 괜찮은지 궁금합니다.

2023-09-28 16:37 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/JpaCategoryRepositoryTest.java
> +        });
### 필수
이 부분 수정이 안된 것 같습니다!

2023-09-28 16:37 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/fixture/JpaCategoryRepositoryFixture.java
> +        가구_하위_책상_카테고리 = new Category("책상");
### 선택
CategoryServiceFixture에서 '서브'를 키워드를 사용했으므로 여기서도 동일하게 '서브' 키워드를 사용하는 것이 좋을 것 같습니다!

2023-09-28 16:48 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/category/domain/CategoryTest.java
> +            softAssertions.assertThat(sub.getMainCategory().getName()).isEqualTo(main.getName());
연관관계 세팅인만큼 main -> sub와 sub -> main 모두 체크해야 한다고 생각했었습니다

2023-09-28 16:50 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/JpaCategoryRepositoryTest.java
>      JpaCategoryRepository categoryRepository;
저도 이 부분이 좀 애매하더라고요....

상위 클래스와 하위 클래스에서 동일한 필드를 가진 경우 하위 클래스가 우선권을 갖는 뭐 그런거 때문에 문제는 없기는 합니다
다만 이걸 Fixture에는 어울리지 않는 것 같아서 이렇게 두기는 했는데...어찌할지 좀 고민이 되네요

2023-09-28 16:51 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/fixture/JpaCategoryRepositoryFixture.java
> +        가구_하위_책상_카테고리 = new Category("책상");
이거 제이미가 말씀해주신거 처리하면서 했던 것 같은데 안했었나 싶고 헷갈리네요 적용하겠습니다

2023-09-28 16:54 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/category/domain/CategoryTest.java
> +            softAssertions.assertThat(sub.getMainCategory()).isNotNull();
해당 테스트의 특이성이라고 생각하면 될 것 같기는 합니다

카테고리는 id를 통한 동일성 관련 로직을 수행하는 곳이 없어서 이 경우에만 예외적으로 사용하는 느낌..?
User나 Auction 같은 곳에서는 id를 리플렉션으로 해야 할 것 같네요

2023-09-28 17:14 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/fixture/JpaCategoryRepositoryFixture.java
> +        가구_하위_책상_카테고리 = new Category("책상");
ServiceFixture에는 했는데 여기는 안하셨더라구요~ 했는데 안했습니다(?)

2023-09-28 17:16 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/JpaCategoryRepositoryTest.java
>      JpaCategoryRepository categoryRepository;
근데 또 그렇다고 fixture에서 저 `@Autowired`를 없애면 컴파일이 안되니 좀 애매하긴 하네요. 근데 또 repository가 픽스처는 아니라서 테스트에서 픽스처의 repository를 가져다가 쓰는것도 뭔가 모양새가 이상하구요. 일단 이렇게 두고 나중에 나중에(?) 생각해보도록 하죠..

2023-09-28 17:19 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/category/domain/CategoryTest.java
> +            softAssertions.assertThat(sub.getMainCategory().getName()).isEqualTo(main.getName());
제가 뭔가 잘못 봤나 보네요. 이 리뷰 왜 달았지..? 죄송합니다

2023-09-28 17:20 UTC, kwonyj1022 approved these changes
수정사항 확인했습니다. 감사합니다.

2023-09-29 05:52 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/fixture/JpaCategoryRepositoryFixture.java
> +        가구_하위_책상_카테고리 = new Category("책상");
그런 이슈가...부끄럽군요

2023-09-29 14:03 UTC, merged