인증 & 인가 관련 테스트 코드 리펙토링
woowacourse-teams/2023-3-ddang pull request #476
Opened 2023-09-29 04:44 UTC by apptie

## 📄 작업 내용 요약

인증 & 인가 관련 테스트 코드 리펙토링
## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- 딱히? 없는 것? 같습니다?
## 📎 Issue 번호

- closed #473

2023-09-29 11:00 UTC, JJ503 requested changes
지토 빠른 리팩토링 짱이네요!
이번 리팩토링도 고생 많으셨습니다.

그런데 몇 가지 수정 사항이 보여 해당 부분들 수정해주시면 감사하겠습니다!

2023-09-29 11:00 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/presentation/AuthenticationControllerTest.java
> +                                           );
### 칭찬
확실히 보기 편하네요!!
굿~ 👍👍👍

2023-09-29 11:05 UTC, swonny requested changes

2023-09-29 11:05 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/AuthenticationServiceTest.java
> +        given(소셜_회원_정보_제공자.findUserInformation(anyString())).willReturn(가입하지_않은_사용자_회원_정보);
### 질문

`이미지가_없는_사용자`를 생성해주신 이유가 여기에서 사용하시려고 했던 게 아닐까요? 메서드명을 보면 이미지가 없는 사용자에 대한 예외를 확인하고 있는 것 같은데 반환값은 가입하지 않은 사용자라서 질문 남깁니다.

### 질문

전에도 이야기 나왔던 적 있는 것 같은데 결론이 기억이 잘 안 나네요..
로그인을 시도하려고 할 때 기본 이미지가 없는 경우 예외를 던져도 괜찮은 걸까요? 서버 내부적인 문제라고 생각해 에외를 던지기보다는 로그로만 남겨두는 것이 좋을 것 같아요.
만약 안드로이드 측에 이미지를 전달해야 할 경우에 기본 이미지가 없는 경우에는 null을 전달하고 null을 전달 받은 경우 안드로이드 측에서 임의의 이미지를 넣어주는 방식으로 대체하는건 어떨까요??

다만 이 부분은 안드로이드 분들과 추가적인 이야기가 필요하다는 점에서 저희 쪽에서도 확실히 정하고 넘어가야 할 것 같아요!

2023-09-29 11:06 UTC, swonny commented
실수로 코멘트를 안 달고 request changes를 날려버렸네요...ㅠ
지토의 의견이 궁금한 부분들이 있어 부득이하게 rc를 남겼어요..
고생 많으셨습니다 지토!! 👍🏻

2023-09-29 11:09 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/oauth2/kakao/KakaoUserInformationProviderTest.java
>  @SuppressWarnings("NonAsciiCharacters")
`@DisplayNameGeneration`의 경우 중요도는 낮지만, 이는 픽스처가 아닌 테스트를 위한 어노테이션이기에 테스트에 위치해 있기로 했습니다.
또한, `@SuppressWarnings`의 경우 클래스에 한글이 있는 경우 무조건 경고가 발생하기 때문에 픽스처와 테스트 모두 있어야 하는 것으로 결정했던 것으로 기억합니다. (해당 어노테이션은 상속으로 자식 클래스에 적용되지 않는다고 합니다.)

2023-09-29 11:10 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/fixture/AuthenticationServiceFixture.java
> +    protected Oauth2Type 지원하지_않는_소셜_로그인 = Oauth2Type.KAKAO;
> 아래는 지원하지 않는 소셜 로그인인데 왜 동일한 걸까요?
그 이유는 Oauth2Type 필드가 하나밖에 존재하지 않기 때문입니다...null로 표현하는것보다는 그냥 동일하게 표현하는게 낫다고 판단했습니다

> 추가적으로 지원하는_소셜_로그인_타입 이런식으로 타입을 붙이면 어떨까요? 
이건...좋을 것 같네요 적용하겠습니다

2023-09-29 11:40 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/oauth2/KakaoOauth2TypeTest.java
> -        final Oauth2Type actual = Oauth2Type.from(typeName);
그게...저는 메리가 말씀해주신 `테스트하는 부분을 제외하고 모든 변수를 Fixture로 빼기로 했었던 것`으로 기억하고 있어서 이렇게 진행을 했었습니다 
간단한 변수 선언을 Fixture로 빼도 그만 안빼도 그만이라면 통일하는게 낫겠다 싶기도 했고 그렇습니다..

2023-09-29 11:42 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/oauth2/kakao/KakaoUserInformationProviderTest.java
>  @SuppressWarnings("NonAsciiCharacters")
`@DisplayNameGeneration`은 제가 날렸던 카테고리 쪽 PR에서 아마 엔초가 제안을 해주셨는데
제이미가 `@DisplayNameGeneration`은 테스트 메서드의 `_`를 ` `로 변경하는 것이기 때문에 Fixture에 두는 것이 어색하다고 말씀해주셨고 저도 동의해서 이렇게 작업을 하게 되었습니다

`@SuppressWarnings`의 경우 `"NonAsciiCharacters"`일 때는 IDE의 경고를 억제하려는 경우인데 
인텔리제이의 경우 `@SuppressWarnings`를 상속받는다고 하더라도 인지를 못하고 계속 경고를 띄워버리더라고요..
그래서 `@SuppressWarnings` 얘는 Fixture와 테스트 모두에 둬야 할 것 같습니다

2023-09-29 11:43 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/presentation/AuthenticationControllerTest.java
> +        login_문서화(resultActions);
👍

2023-09-29 11:43 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/presentation/AuthenticationControllerTest.java
> +                                                            .description("재발급한 Access Token"),
이 부분은 120자 넘어갈 때만 개행하는 걸로 인지를 하고 있었습니다만 사실 확신은 없네요 
다른 분들께도 확인을 부탁드리고 싶군요..

2023-09-29 11:45 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/AuthenticationServiceTest.java
> +        given(소셜_회원_정보_제공자.findUserInformation(anyString())).willReturn(가입하지_않은_사용자_회원_정보);
> 이미지가_없는_사용자를 생성해주신 이유가 여기에서 사용하시려고 했던 게 아닐까요? 메서드명을 보면 이미지가 없는 사용자에 대한 예외를 확인하고 있는 것 같은데 반환값은 가입하지 않은 사용자라서 질문 남깁니다.

제가 이거 할 때에는 멘탈이 터져서 이렇게 된 것 같네요...수정하도록 하겠습니다

> 만약 안드로이드 측에 이미지를 전달해야 할 경우에 기본 이미지가 없는 경우에는 null을 전달하고 null을 전달 받은 경우 안드로이드 측에서 임의의 이미지를 넣어주는 방식으로 대체하는건 어떨까요??

이거 확실히 정해야 한다는 것은 동의합니다 
다만 테스트 코드는 현재 프로덕션 코드에 맞춰야 한다고 생각해서...일단 계속 진행하겠습니다...

2023-09-29 11:55 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/oauth2/kakao/KakaoUserInformationProviderTest.java
>  @SuppressWarnings("NonAsciiCharacters")
아하 그렇게 이야기 했었죠 🥹 제가 또 잊었군요 죄송함다.. 
지토가 리팩토링 해주신 것에 맞춰 저도 통일시키겠습니다.

2023-09-29 12:00 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/oauth2/KakaoOauth2TypeTest.java
> -        final Oauth2Type actual = Oauth2Type.from(typeName);
저는 픽스처 만들기로 한 김에 지토가 리팩토링 해주신 것처럼 빼는 걸로 통일해도 괜찮을 것 같습니다.

2023-09-29 12:07 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/presentation/AuthenticationControllerTest.java
> +                                                            .description("재발급한 Access Token"),
얘기했던 건 기억이 나는데 결과는 기억이 안 나네요...
그런데 그날 얘기할까 말까 고민했던 개인 취향으로는 개행을 아예 안 하는 것인데 어떻게 생각하시나요?
조심스럽게 제안해봅니다...ㅎ

2023-09-29 12:10 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/oauth2/kakao/KakaoUserInformationProviderTest.java
>                                               MediaType.APPLICATION_JSON
그렇다면 이 부분은 제가 변경하도록 하겠습니다 
그런데 무슨...이슈가 있었길래..? 악몽의 시작..?

2023-09-29 12:14 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/fixture/AuthenticationServiceFixture.java
> +    protected Oauth2Type 지원하지_않는_소셜_로그인 = Oauth2Type.KAKAO;
하지만, 현재 로직(`findProvider()`)을 살펴본 결과 해당 오류가 발생하는 경우는 오로지 null인 경우 예외를 반환하는 것으로 보이는 데 아닐까요?
일단 해당 픽스처는 지원하는 소셜 로그인 타입과 지원하지 않는 소셜 로그인 타입이 동일해 의문을 갖게 만드는 듯 합니다.

2023-09-29 12:28 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/AuthenticationServiceTest.java
> +                Oauth2Type.KAKAO,
감사합니다 제이미.....1

2023-09-29 12:29 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/AuthenticationServiceTest.java
> +        final TokenDto actual = authenticationService.login(Oauth2Type.KAKAO, 유효한_소셜_로그인_토큰, 디바이스_토큰);
감사합니다 제이미.....3

2023-09-29 12:30 UTC, kwonyj1022 requested changes
수고하셨습니다. 지토!
테스트하려고 했던 것이 달라진 부분이 있어 rc 남깁니다. `필수`로 지정해두었으니 확인 부탁드립니다.

2023-09-29 12:30 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/AuthenticationServiceTest.java
>      }
### 필수
해당 테스트의 경우 사용자의 기본 이미지가 없는 경우가 아니라, 서버에서 기본 이미지를 찾을 수 없을 때를 테스트하는 것입니다.
가입하지 않은 회원이 로그인을 하면 서버에서 기본이미지를 찾아서 그 회원에게 할당해 주는 로직인데, 서버에서 기본 이미지를 찾을 수 없으면 예외를 던지는 것입니다.

2023-09-29 12:32 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/AuthenticationServiceTest.java
> +        assertThatThrownBy(() -> authenticationService.withdrawal(Oauth2Type.KAKAO, 유효하지_않은_액세스_토큰, 유효한_리프레시_토큰))
감사합니다 제이미.....6

2023-09-29 12:33 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/AuthenticationServiceTest.java
> +        final TokenDto actual = authenticationService.login(Oauth2Type.KAKAO, 유효한_소셜_로그인_토큰, 디바이스_토큰);
감사합니다 제이미.....8

2023-09-29 12:34 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/AuthenticationServiceTest.java
>      }
👍

2023-09-29 12:38 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/presentation/AuthenticationControllerTest.java
> +                                                            .description("재발급한 Access Token"),
저도 진짜 별로 큰 상관은 없는데 개인적으로는 개행 안 하는 걸 선호하지만,, 자동 정렬이 또 마음에 걸리네요ㅠㅠ
```java
requestFields(
                                fieldWithPath("accessToken").description("소셜 로그인 AccessToken"),
                                fieldWithPath("deviceToken").description("기기 디바이스 토큰")
                        ),
                        responseFields(
                                fieldWithPath("accessToken").type(JsonFieldType.STRING).description("Access Token"),
                                fieldWithPath("refreshToken").type(JsonFieldType.STRING).description("Refresh Token")
                        )
```
이 코드 예시로 봤을 때 type이 있는 경우는 description을 개행하는 것이 더 좋고, type이 없는 경우에는 개행을 안 하는 게 좋은 것 같아요. 그렇지만 통일성을 위해 개행하는 것이 어떨까 하는 생각이 듭니다!

2023-09-29 12:57 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/oauth2/kakao/KakaoUserInformationProviderTest.java
>                                               MediaType.APPLICATION_JSON
앗 근데 `MediaType.APPLICATION_FORM_URLENCODED`으로 바꾸니까 `no suitable HttpMessageConverter found for response type`이라는 예외가 발생하네요 

이거는 보니까 `HttpMessageConverter`가 `APPLICATION_FORM_URLENCODED`를 지원하지 않아서 그런 것 같은데...이 부분은 좀 더 찾아보고 결론은 지어야 할 것 같습니다 일단 변경하지는 않도록 하겠습니다

2023-09-29 12:57 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/presentation/AuthenticationControllerTest.java
> +        given(authenticationService.login(eq(Oauth2Type.KAKAO), anyString(), anyString())).willReturn(발급된_토큰);
이 부분...도...Fixture 추가하도록 하겠습니다...감사합니다..

2023-09-29 13:02 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/presentation/AuthenticationControllerTest.java
> +                                           );
이 부분...은...밑에 메리가 작성해주신 파트랑 엮어서 고민을 좀 해야겠네요...

2023-09-29 13:02 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/presentation/AuthenticationControllerTest.java
> +                                           );
👍

2023-09-29 13:04 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/oauth2/kakao/fixture/KakaoUserInformationProviderFixture.java
> +    protected ObjectMapper objectMapper = new ObjectMapper();
동의합니다 왜 여기다 놨는지 잘 모르겠네요 이동시키도록 하겠습니다

2023-09-29 13:07 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/AuthenticationServiceTest.java
> +    void 로그인할_때_이미지가_없는_사용자라면_예외가_발생한다() {
Fixture를 생성하는 과정 중 jacoco가 테스트 커버리지가 없다고 해서 추가한 테스트 케이스입니다

2023-09-29 13:07 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/AuthenticationServiceTest.java
> +    void 로그인할_때_가입하지_않은_사용자라면_회원가입을_진행한다() {
Fixture를 생성하는 과정 중 jacoco가 테스트 커버리지가 없다고 해서 추가한 테스트 케이스입니다 22

2023-09-29 13:09 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/AuthenticationServiceTest.java
>      }
그런 로직이었군요 해당 로직을 잘못 이해했었습니다
이에 맞춰서 테스트 케이스를 수정하도록 하겠습니다

2023-09-29 13:11 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/presentation/AuthenticationControllerTest.java
> +                                           );
적용하도록 하겠습니다

2023-09-29 13:12 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/presentation/AuthenticationControllerTest.java
> +                                                   );
이런 느낌이었군요 적용하도록 하겠습니다

2023-09-29 13:13 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/presentation/fixture/AuthenticationControllerFixture.java
> +    protected TokenDto 발급된_토큰 = new TokenDto(유효한_액세스_토큰, "Bearer refreshToken");
네이밍은 항상 어렵네요 적용하도록 하겠습니다

2023-09-29 13:17 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/presentation/fixture/AuthenticationControllerFixture.java
> +            new LoginTokenRequest("kakaoAccessToken", "deviceToken");
한글이라서 120자가 넘는 줄 알았네요 수정하도록 하겠습니다

2023-09-29 13:19 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/persistence/fixture/JpaBlackListTokenRepositoryFixture.java
> +    protected String 만료되지_않은_토큰_내용 = "not expired token";
반박할 수가 없군요 변경하도록 하겠습니다

2023-09-29 13:20 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/persistence/fixture/JpaBlackListTokenRepositoryFixture.java
> +    protected BlackListToken 만료된_토큰 = new BlackListToken(TokenType.ACCESS, "accessToken");
요것도 적용하도록 하겠습니다

2023-09-29 13:23 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/oauth2/kakao/KakaoUserInformationProviderTest.java
> +        assertThat(actual.id()).isEqualTo(회원_정보.id());
맞네요 동일한 dto로군요 변경하도록 하겠습니다

2023-09-29 13:23 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/oauth2/kakao/KakaoUserInformationProviderTest.java
> +        assertThat(actual.id()).isEqualTo(회원_정보.id());
해당 부분도 변경하도록 하겠습니다

2023-09-29 13:35 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/AuthenticationServiceTest.java
> +    void 로그인할_때_이미지가_없는_사용자라면_예외가_발생한다() {
다만 이 경우는 위에서 알려주셨던 이미지 관련 로직에 대한 잘못된 이해로 발생한 이슈고 현재는 해결되었으므로 이 테스트 케이스는 삭제하도록 하겠습니다

2023-09-29 13:40 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/AuthenticationServiceTest.java
> +        given(소셜_회원_정보_제공자.findUserInformation(anyString())).willReturn(가입하지_않은_사용자_회원_정보);
하지만 해당 테스트 케이스는...제가 잘못된 이해로 인한 잘못된 테스트 케이스를 수행하고 있어서 추가한 케이스라서 엔초가 알려주신 이후 이 테스트 케이스를 삭제했습니다

2023-09-29 13:48 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/presentation/AuthenticationControllerTest.java
> +                                                            .description("재발급한 Access Token"),
그렇다면 일단은 그냥 개행을 하도록 하겠습니다

2023-09-29 14:01 UTC, swonny approved these changes
고생 많으셨습니다 지토..
저는 충분한 것 같아 approve 하겠습니다!

2023-09-29 17:08 UTC, kwonyj1022 requested changes
이 부분 굉장히 복잡하네요ㅠ 리팩토링하느라 수고 많으십니다.
송구하게도 꼭 수정해주셨으면 하는 사항(사용하지 않는 필드 삭제)이 있어서 rc 유지하겠습니다..

2023-09-29 17:08 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/fixture/AuthenticationServiceFixture.java
> +    protected AuthenticationService profileImageAuthenticationService;
### 필수
AuthenticationServiceTest에서는 AuthenticationService가 테스트하려는 객체이므로 픽스처 클래스보다는 테스트 클래스에 있는 것이 더 적절할 것 같습니다!

### 선택
서비스 테스트만 봤을 때 `profileImageAuthenticationService`라는 이름으로는 프로필 이미지를 찾을 수 없는 상황을 가정한 service라는 것을 파악하기 힘들었습니다.
네이밍이 좀 길어지긴 하겠지만 `profileImageNotFoundAuthenticationService`라던가 `nullProfileImageAuthenticationService` 라든가 `ProfileImageErrorAuthenticationService` 등등 좀 더 상황을 구체적으로 나타내는 네이밍이면 좋을 것 같습니다!

2023-09-29 17:16 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/oauth2/kakao/KakaoUserInformationProviderTest.java
>                                               MediaType.APPLICATION_JSON
앗 그렇군요 확인 감사합니다!

2023-09-29 17:22 UTC, JJ503 approved these changes
엔초가 이야기한 부분 외에는 수정할 사항은 더 이상 보이지 않아 approve 하도록 하겠습니다.
고생 많으셨습니다 지토!
마지막으로 `지원하지_않는_소셜_로그인_타입`에 대한 null로 수정하면서 마무리하겠습니다 ㅎㅎ
([이유](https://github.com/woowacourse-teams/2023-3-ddang/pull/476#discussion_r1341293759))

2023-09-29 17:40 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/fixture/AuthenticationServiceFixture.java
> +    protected Oauth2Type 지원하지_않는_소셜_로그인 = Oauth2Type.KAKAO;
일단 로직상 null이 올 수가 없습니다 Converter에서 값이 없거나 존재하지 않으면 Controller까지 오지 못하기 때문입니다 
api 호출 시의 문자열이 null일 수는 있지만 Oauth2Type이 null인 경우는 존재하지 않습니다 

그래서 지원하지 않는 소셜 로그인 타입을 null로 만들게 된다면 Authentication 관련 로직이 아닌 Service 메서드 파라미터에 null이 올 수 없는 상황에서 오게 되는 과정으로 인한 NPE가 발생하므로 해당 테스트 케이스와는 전혀 맞지 않다고 생각합니다

2023-09-29 17:57 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/fixture/AuthenticationServiceFixture.java
> +    protected UserInformationDto 이미지가_없는_사용자_회원_정보 = new UserInformationDto(-11111L);
이미지가_없는_사용자_회원_정보를 말씀하신게 맞으실까요? 일단 삭제했습니다

2023-09-29 17:58 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/fixture/AuthenticationServiceFixture.java
> +    protected JpaProfileImageRepository 프로필_이미지_저장소 = mock(JpaProfileImageRepository.class);
해당 이슈는 밑에 Service를 테스트 클래스로 이동시키면서 사라졌고 영어 이름을 사용하는 식으로 진행했습니다
생각해보면 Fixture는 현재 테스트에서 직접적으로 테스트하지는 않지만 연관관계 상 필요한 도메인 엔티티 등을 만드는 것이니 Service를 구현하는데 필요한 구성요소들을 Fixture로 만드는건 좀 이상하다 싶기는 하네요

2023-09-29 18:00 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/fixture/AuthenticationServiceFixture.java
> +    protected AuthenticationService profileImageAuthenticationService;
> AuthenticationServiceTest에서는 AuthenticationService가 테스트하려는 객체이므로 픽스처 클래스보다는 테스트 클래스에 있는 것이 더 적절할 것 같습니다!

이동했습니다

> profileImageAuthenticationService 네이밍 관련

profileImageNotFoundAuthenticationService로 변경하도록 하겠습니다

2023-09-29 18:02 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/fixture/AuthenticationServiceFixture.java
> +    protected JpaProfileImageRepository 프로필_이미지_저장소 = mock(JpaProfileImageRepository.class);
계속 제가 Fixture로 뭘 쓸지 헷갈려하고 있는데 일단 스프링 빈으로 등록된건 모조리 제외하는 식으로 하는게 맞겠네요

2023-09-29 18:09 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/fixture/AuthenticationServiceFixture.java
> +    protected Oauth2Type 지원하지_않는_소셜_로그인 = Oauth2Type.KAKAO;
제가 이렇게 한 이유는 로직상 null이 올 수 없기 때문입니다 
Converter에서 값이 없거나 존재하지 않으면 Controller까지 오지 못하기 때문입니다
api 호출 시의 문자열이 null일 수는 있지만 이로 인해 Oauth2TypeConverter에서 예외가 발생하므로 Oauth2Type이 null인 경우는 존재하지 않습니다
그래서 AuthenticationService에서 이를 고려할 필요는 없다고 생각합니다

현재 테스트 케이스에서 `지원하지 않는 소셜 로그인 타입`을 null로 주게 되면 NPE가 발생하게 됩니다 
이 경우 테스트 케이스에서 검증하고자 하는 내용과는 다르며, NPE를 핸들링하는 예외 처리 로직을 추가하게 된다면 이미 다른 구간에서 핸들링하고 있는 경우를 테스트 케이스(Fixture) 하나로 인해 프로덕션 코드가 영향을 받게 되어 이는 테스트하는 목적과는 전혀 맞지 않다고 생각합니다

2023-09-29 19:53 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/fixture/AuthenticationServiceFixture.java
> +    protected UserInformationDto 이미지가_없는_사용자_회원_정보 = new UserInformationDto(-11111L);
맞습니다. 블럭 처리가 이상하게 됐네유

2023-09-29 19:57 UTC, kwonyj1022 approved these changes
엄청난 대장정이 마무리되었네요 정말 정말 수고하셨어요!

2023-09-30 02:40 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/application/fixture/AuthenticationServiceFixture.java
> +    protected Oauth2Type 지원하지_않는_소셜_로그인 = Oauth2Type.KAKAO;
아하 그렇군요! `provier`에 대한 검증인데 제가 잘못 확인했네요 죄송합니다..!

2023-09-30 07:19 UTC, merged