지역 관련 테스트 코드 리팩토링
woowacourse-teams/2023-3-ddang pull request #484
Opened 2023-09-29 16:32 UTC by kwonyj1022

## 📄 작업 내용 요약

지역 관련 테스트 코드 리팩토링
## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- `RegionServiceTest`에 고민 todo 하나 있습니다.
## 📎 Issue 번호

- closed #478

2023-09-29 16:51 UTC, apptie approved these changes
고생하셨습니다 
RestTemplateInitRegionProcessorFixture에서 의미 있는 값을 지정하기 위해 진짜 고생하신게 보이네요 

큰 문제가 없는 것 같아 몇 가지 선택사항만 띄워놓고 Approve를 드리도록 하겠습니다

2023-09-29 16:51 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/region/presentation/RegionController.java
> +    public ResponseEntity<List<ReadRegionResponse>> readAllThird(
### 칭찬

칭찬해요!@@@@@@@@@!@!@#!@#!@#!#!@#!@#!@# 
이거 전에 바꿔야한다고 얘기가 나왔던 것 같은데 엔초 PR 보기 전까지는 생각도 못했습니다

2023-09-29 16:51 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/region/application/RegionServiceTest.java
> +        // TODO: 9/30/23 여기 너무 극혐인데 어떻게 하면 깔끔하게 할 수 있을까요..
### 선택

와! 쌉극혐!
근데 어쩔 수 없지 않나 싶습니다..

그나마 지금 떠오르는 방식은 별도의 메서드로 분리하는 것입니다..
그렇다면 적어도 필드 네이밍만음 비교적 간단해질 것 같습니다 

다만 메서드가...귀찮음이...선택에 맞기도록 하겠습니다...

2023-09-29 16:51 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/region/application/RegionServiceTest.java
> +            softAssertions.assertThat(actual.get(1).name()).isEqualTo(두번째_지역이_없는_첫번째_지역.getName());
### 질문

Fixture에서 봤을 땐 save()까지 수행하고 있어 id 세팅까지 되어 있을 것 같은데 Service인데도 name으로 비교하는 이유가 있을까요?

2023-09-29 16:51 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/region/infrastructure/api/fixture/RestTemplateInitRegionProcessorFixture.java
> +public class RestTemplateInitRegionProcessorFixture {
### 칭찬

칭찬해요!@#!!!!!!!!!!!!!!!!!@#!@#!@#
이거 의미 있는 Fixture 만들기 매우 고통스러우셨을텐데 고생하셨습니다...

2023-09-29 16:51 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/region/presentation/RegionControllerTest.java
> +                .andDo(
### 선택

이 부분 개행을 해줄 필요가 있을까 싶은데 그렇습니다

2023-09-29 16:51 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/region/presentation/RegionControllerTest.java
> +        readAllFirst_문서화(resultActions);
### 선택

여기 개행..?

2023-09-29 17:11 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/region/infrastructure/api/fixture/RestTemplateInitRegionProcessorFixture.java
> +public class RestTemplateInitRegionProcessorFixture {
맞습니다ㅠㅠ 이거 하면서 자꾸 헷갈려서 몇 번이나 롤백을 했는지.. 
칭찬 감사합니다!

2023-09-29 17:13 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/region/application/RegionServiceTest.java
> +            softAssertions.assertThat(actual.get(1).name()).isEqualTo(두번째_지역이_없는_첫번째_지역.getName());
그러게요.. 왜 그랬을까요.. 예리하네요 지토
리뷰 반영하겠습니다!

2023-09-29 17:14 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/region/application/RegionServiceTest.java
> +        // TODO: 9/30/23 여기 너무 극혐인데 어떻게 하면 깔끔하게 할 수 있을까요..
다른 분들 의견도 궁금하니 다 듣고 결정하도록 하겠습니다!

2023-09-29 17:15 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/region/presentation/RegionControllerTest.java
> +                .andDo(
문서화 부분 변수 추출하고 그냥 복붙했더니 다 그런 것 같네요. 반영하겠습니다!!

2023-09-30 11:36 UTC, JJ503 requested changes
엔초 밤샘 리팩토링 고생 많으셨습니다..!
그럼에도 꼼꼼하게 잘해주셨네요. 역시 엔초 짱 🙌
몇 가지 질문과 수정해야 하지 않을까 하는 내용이 있어 일단 rc 해둡니다.

2023-09-30 11:36 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/region/application/RegionServiceTest.java
> +            softAssertions.assertThat(actualThirdRegion1OfSecondRegion2).isEqualTo(서울특별시_강남구_대치동);
### 선택 - 참고
제안을 하나 드리자면 아래와 같이 변수끼리 묶어준다면 아주 조금 나아지지 않을까 싶습니다.
```suggestion
            softAssertions.assertThat(actual).hasSize(6);
            final Region actualFirstRegion1 = actual.get(0);
            final Region actualFirstRegion2 = actual.get(5);
            softAssertions.assertThat(actualFirstRegion1).isEqualTo(서울특별시);
            softAssertions.assertThat(actualFirstRegion2).isEqualTo(두번째_지역이_없는_첫번째_지역);

            softAssertions.assertThat(actualFirstRegion1.getSecondRegions()).hasSize(2);
            final Region actualSecondRegion1OfFirstRegion1 = actualFirstRegion1.getSecondRegions().get(0);
            final Region actualSecondRegion1OfFirstRegion2 = actualFirstRegion1.getSecondRegions().get(1);
            softAssertions.assertThat(actualSecondRegion1OfFirstRegion1).isEqualTo(서울특별시_강남구);
            softAssertions.assertThat(actualSecondRegion1OfFirstRegion2).isEqualTo(세번째_지역이_없는_두번째_지역);

            softAssertions.assertThat(actualSecondRegion1OfFirstRegion1.getThirdRegions()).hasSize(2);
            final Region actualThirdRegion1OfSecondRegion1 = actualSecondRegion1OfFirstRegion1.getThirdRegions().get(0);
            final Region actualThirdRegion1OfSecondRegion2 = actualSecondRegion1OfFirstRegion1.getThirdRegions().get(1);
            softAssertions.assertThat(actualThirdRegion1OfSecondRegion1).isEqualTo(서울특별시_강남구_삼성동);
            softAssertions.assertThat(actualThirdRegion1OfSecondRegion2).isEqualTo(서울특별시_강남구_대치동);
```

2023-09-30 11:36 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/region/application/RegionServiceTest.java
> +        // TODO: 9/30/23 여기 너무 극혐인데 어떻게 하면 깔끔하게 할 수 있을까요..
### 선택
보기 안 좋을 수 있긴 하지만, 메서드로 분리하면 더 귀찮아질 것 같습니다...
아래와 같이 제안해 봅니다.
아주 미미한 효과겠지만...

2023-09-30 11:36 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/region/domain/AuctionRegionTest.java
> +        assertThat(auctionRegion.getAuction().getTitle()).isEqualTo(auction.getTitle());
### 질문 & 선택
피드백하고자 하는 코드에 코멘트를 남기지 못해 부득이하게 여기에 남깁니다.
도메인 테스트의 경우 테스트하려는 도메인 외의 다른 도메인 객체는 픽스처 클래스를 만들어 세팅하기로 했던 걸로 기억하는데, 그러지 않은 이유가 있으신지 궁금합니다!

2023-09-30 11:36 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/region/application/fixture/RegionServiceFixture.java
> +        서울특별시_강남구 = new Region("서울특별시 강남구");
### 질문 & 필수
서울특별시 하위 지역에 강남구가 있는 것이라면 `new Region("강남구")`지 않나요??

2023-09-30 11:36 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/region/application/fixture/RegionServiceFixture.java
> +        서울특별시_강남구 = new Region("서울특별시 강남구");
### 선택
카테고리에서 서브 카테고리라면 `전자기기_서브_노트북`으로 정한 것처럼 지역도 그러면 어떨까요?
예를 들자면, `서울특별시_하위_강남구`와 같이요.

2023-09-30 14:12 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/region/application/RegionServiceTest.java
> +            softAssertions.assertThat(actualThirdRegion1OfSecondRegion2).isEqualTo(서울특별시_강남구_대치동);
좋네요! 좀 더 나아가서, assertion이 아닌 단순 변수 추출을 sofAssertions 외부에서 진행했더니 그나마 아주 조금 더 나아진 것 같습니다!

2023-09-30 14:15 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/region/domain/AuctionRegionTest.java
> +        assertThat(auctionRegion.getAuction().getTitle()).isEqualTo(auction.getTitle());
이거 만들었을 때는 AuctionRegion이라 Auction과 Region 모두 테스트에 있어야 한다고 생각했는데 지금 보니 왜 그렇게 생각했는지 모르겠네요.. Auction과 Region을 각각 픽스처로 두고 AuctionRegion만 이 테스트 클래스에서 만들면 되는데,,, 코멘트 감사합니다 제이미!

2023-09-30 14:23 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/region/application/fixture/RegionServiceFixture.java
> +        서울특별시_강남구 = new Region("서울특별시 강남구");
궁금한 점이 있는데 그렇다면 서울특별시 강남구 역삼동은
`강남구_하위_역삼동`인가요, `서울특별시_하위_강남구_하위_역삼동`인가요?

2023-09-30 16:29 UTC, swonny approved these changes
고생하셨습니다 엔초!!
저는 특이한 사항은 발견하지 못해 approve합니다!

2023-10-02 12:36 UTC, JJ503 approved these changes
확인 완료했습니다!
그런데 `_하위_`의 경우 굳이 필요 없다는 의견도 있었기에 이 부분은 엔초가 편하신 대로 진행해주세요!

2023-10-03 08:58 UTC, merged