쪽지 컨트롤러 관련 테스트 코드 리팩토링
woowacourse-teams/2023-3-ddang pull request #486
Opened 2023-09-29 20:01 UTC by swonny

## 📄 작업 내용 요약

쪽지 컨트롤러 관련 테스트 코드 리팩토링

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- `@BeforeEach` 내부에서 초기화를 진행하면 NPE가 떠서.. 지토 코드 참고해서 필드에서 바로 값을 세팅하도록 구현했습니다.
- 이건 주의 깊게 확인해야 하는 부분은 아니고 약간의 고민(?)입니다.
    - 컨트롤러 테스트에서 서비스를 모킹하다보니 잘못된 dto를 넘겨주어도 의도한대로 동작하니까 뭔가 의미 없는 테스트코드처럼 느껴지더라구요.  다른 분들도 비슷하게 느끼셨는지 궁금합니다..!

## 📎 Issue 번호

- closed #482

2023-09-29 21:48 UTC, kwonyj1022 requested changes
### 칭찬
채팅방 관련된 것도 같이 리팩토링 해주셔서 정말 감사합니다 메리!

필수로 수정해주셨으면 하는 사항이 조금 있어서 rc 하겠습니다.

2023-09-29 21:48 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +                       jsonPath("$.message", is("지정한 아이디에 대한 채팅방을 찾을 수 없습니다."))
### 필수
```suggestion
                       jsonPath("$.message").exist()
```
`예외 메세지 테스트 검증 시 exists() 사용` 으로 컨벤션을 정했었습니다!
밑에 다른 부분도 고쳐주세요~

2023-09-29 21:48 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +    private void createMessage_문서화(final ResultActions resultActions) throws Exception {
### 필수
여기 말고도 문서화 전체적으로 description 앞에서 개행이 된 것도 있고 안된 것도 있어서 통일해 주시면 감사하겠습니다!

2023-09-29 21:48 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/fixture/ChatRoomControllerFixture.java
> +    protected TokenDecoder tokenDecoder = mock(TokenDecoder.class);
### 질문
TokenDecoder를 픽스처에서 사용하지 않기도 하고, 테스트 클래스의 setUp에서 사용하고 있고, 테스트에 필요한 데이터 mocking에 사용되기 때문에 저는 테스트 클래스에 두었는데요, 메리는 어떤 이유로 픽스처 클래스에 두었는지 궁금합니다.

2023-09-29 21:48 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/fixture/ChatRoomControllerFixture.java
> +    private final ReadAuctionInChatRoomDto 조회용_경매_dto2 = new ReadAuctionInChatRoomDto(2L, "경매2", 20_000, 1L);
### 필수
```suggestion
    private ReadAuctionInChatRoomDto 조회용_경매1 = new ReadAuctionInChatRoomDto(1L, "경매1", 10_000, 1L);
    private ReadAuctionInChatRoomDto 조회용_경매2 = new ReadAuctionInChatRoomDto(2L, "경매2", 20_000, 1L);
```
네이밍과 final 을 통일해주셨으면 좋겠습니다!

2023-09-29 21:48 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/fixture/ChatRoomControllerFixture.java
> +    protected CreateChatRoomRequest 유효하지_않은_경매_아이디_채팅방_생성_요청 = new CreateChatRoomRequest(1L);
### 선택
`정상적인 채팅방 생성 요청` 처럼 유효하지 않은 경우와 대비됨을 명확하게 표현하면 좋을 것 같습니다.
또한, 유효한 경매 아이디도 1L이고 유효하지 않은 경매 아이디도 1L이라 어색하게 느껴집니다. 유효하지 않은 경매 아이디는 -999L 과 같은 값으로 표현하면 더 좋을 것 같습니다!

2023-09-29 21:48 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +        mockMvc.perform(post("/chattings/{chatRoomId}/messages", 유효하지_않은_사용자_아이디)
### 필수
```suggestion
        mockMvc.perform(post("/chattings/{chatRoomId}/messages", 유효하지_않은_채팅방_아이디)
```

2023-09-29 21:48 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +        final ResultActions resultActions = mockMvc.perform(RestDocumentationRequestBuilders.get("/chattings/{chatRoomId}/messages", 1L)
### 선택
```suggestion
        final ResultActions resultActions = mockMvc.perform(RestDocumentationRequestBuilders.get("/chattings/{chatRoomId}/messages", 채팅방_아이디)
```

2023-09-29 21:48 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +        given(tokenDecoder.decode(eq(TokenType.ACCESS), anyString())).willReturn(Optional.of(비공개_클레임));
### 선택
블럭 설정이 안돼서 이곳에 남깁니다.
밑에 perform 부분 형식도 픽스처를 사용하는 것으로 통일하는 것은 어떤가요?
`mockMvc.perform(get("/chattings/{chatRoomId}/messages", 채팅방_아이디)`

2023-09-29 21:48 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
>                         .queryParam("lastMessageId", "1"))
### 선택
여기도 형식을 통일해주면 좋을 것 같아요!
```suggestion
        mockMvc.perform(get("/chattings/{chatRoomId}/messages", 유효하지_않은_채팅방_아이디)
                       .header(HttpHeaders.AUTHORIZATION, "Bearer accessToken")
                       .contentType(MediaType.APPLICATION_JSON)
                       .queryParam("lastMessageId", 마지막_메시지_아이디.toString()))
```

2023-09-29 21:48 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
>                         .contentType(MediaType.APPLICATION_JSON)
```suggestion
        mockMvc.perform(get("/chattings/{chatRoomId}/messages", 채팅방_아이디)
                       .header(HttpHeaders.AUTHORIZATION, "Bearer accessToken")
                       .contentType(MediaType.APPLICATION_JSON)
```

2023-09-29 21:48 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +        final ResultActions resultActions = mockMvc.perform(RestDocumentationRequestBuilders.get("/chattings/{chatRoomId}", 1L)
```suggestion
        final ResultActions resultActions = mockMvc.perform(RestDocumentationRequestBuilders.get("/chattings/{chatRoomId}", 채팅방_아이디)
```

2023-09-29 21:48 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
>          mockMvc.perform(get("/chattings/1")
```suggestion
        mockMvc.perform(get("/chattings/{chatRoomId}", 채팅방_아이디)
```

2023-09-29 21:48 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
>          mockMvc.perform(get("/chattings/1")
```suggestion
        mockMvc.perform(get("/chattings/{chatRoomId}", 채팅방_아이디)
```

2023-09-29 21:48 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +        given(chatRoomService.readAllByUserId(유효하지_않은_사용자_아이디)).willThrow(new UserNotFoundException("사용자 정보를 찾을 수 없습니다."));
### 선택
여기 제가 작성했던 테스트인데, chatRoomService 모킹은 필요가 없었네요ㅠ 어차피 위에서 터져서 밑에까지 안 갈 것 같아요. 이 클래스 수정하시는 김에 같이 수정해 주실 수 있을까요?

2023-09-30 05:02 UTC, apptie approved these changes
고생하셨습니다 메리...
메리도 지옥의 리펙토링으로 오셨군요..화이팅입니다..

엔초가 많은 부분을 리뷰해주셔서 저는 몇 가지 선택만 남기고 Approve를 하도록 하겠습니다

2023-09-30 07:30 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +    private void createMessage_문서화(final ResultActions resultActions) throws Exception {
description() 앞에 type()이 존재하는 경우에만 저희 기존 컨벤션에 맞춰 개행을 해주었습니다.
type()이 없는 경우에도 개행을 무조건 하는 것으로 통일일까요..?
지토 코드도 기존 컨벤션에 맞춰 개행을 해주셨던 것 같아서 헷갈리기 시작하네요......... 개행 너무 어려워요...

2023-09-30 07:31 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/fixture/ChatRoomControllerFixture.java
> +    private final ReadAuctionInChatRoomDto 조회용_경매_dto2 = new ReadAuctionInChatRoomDto(2L, "경매2", 20_000, 1L);
ㅠㅠ 죄송합니다.... 이런 기본적인 부분을.......... 수정하도록 하겠습니다

2023-09-30 07:42 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/fixture/ChatRoomControllerFixture.java
> +    protected CreateChatRoomRequest 유효하지_않은_경매_아이디_채팅방_생성_요청 = new CreateChatRoomRequest(1L);
> 정상적인 채팅방 생성 요청 처럼 유효하지 않은 경우와 대비됨을 명확하게 표현하면 좋을 것 같습니다.
→ 해당 부분은 다같이 작업할 때 정상 케이스에 `정상적인`을 추가하지 않았던 것 같아서 추가해주지 않았습니다! 명시해주는 것이 나을까요? 다른 분들의 의견도 궁금합니다.

> 또한, 유효한 경매 아이디도 1L이고 유효하지 않은 경매 아이디도 1L이라 어색하게 느껴집니다. 유효하지 않은 경매 아이디는 -999L 과 같은 값으로 표현하면 더 좋을 것 같습니다!

→ 사실 이 부분은 -999L로 지정해두면 모킹한 서비스에서 예외를 던지기 전 DTO 단에서 유효하지 않은 아이디 값으로 예외를 던지기 때문에 1L로 해두었습니다.... (새벽이라 졸려서 그렇게 해버린 점 죄송합니다........) 그런데 생각해보니 그러면 컨트롤러에서 발생할 수 있는 예외 케이스가 유효하지 않은 경매 아이디를 입력한 경우와 유효한 아이디를 입력했지만 해당 아이디로 경매를 찾을 수 없는 경우 두 가지인 것 같아 테스트 코드를 추가해주었습니다.

테스트 픽스처의 효과가 이런 부분에서 드러나느 것 같아 조금 뿌듯네요!

2023-09-30 07:45 UTC, JJ503 approved these changes
메리 고생 많으셨습니다!
이미 앞서 대부분 수정이 필요한 내용에 대해 이야기 해주어 질문만 하나 남깁니다!
해당 부분만 확인해주시면 감사하겠습니다.

2023-09-30 07:45 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/fixture/ChatRoomControllerFixture.java
> +    protected TokenDecoder tokenDecoder = mock(TokenDecoder.class);
### 선택
저도 동일한 이유로 테스트하고자 하는 클래스에 둔 상태입니다.

2023-09-30 07:45 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/fixture/ChatRoomControllerFixture.java
> +    protected final Long 유효하지_않은_마지막_메시지_아이디 = -999L;
### 질문
`final`을 붙이는 필드와 그렇지 않은 필드의 기준이 궁금합니다!

2023-09-30 07:54 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +        mockMvc.perform(post("/chattings/{chatRoomId}/messages", 유효하지_않은_사용자_아이디)
ㅠㅠ.. 감사합니다 엔초

2023-09-30 07:54 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +        final ResultActions resultActions = mockMvc.perform(RestDocumentationRequestBuilders.get("/chattings/{chatRoomId}/messages", 1L)
ㅠㅠ.. 감사합니다 엔초...2

2023-09-30 07:56 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
>                         .queryParam("lastMessageId", "1"))
ㅠㅠ.. 감사합니다 엔초...3

2023-09-30 07:58 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +        given(chatRoomService.readAllByUserId(유효하지_않은_사용자_아이디)).willThrow(new UserNotFoundException("사용자 정보를 찾을 수 없습니다."));
넵! 수정 완료했습니다

2023-09-30 07:58 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
>                         .contentType(MediaType.APPLICATION_JSON)
ㅠㅠ.. 감사합니다 엔초...4

2023-09-30 07:58 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +        final ResultActions resultActions = mockMvc.perform(RestDocumentationRequestBuilders.get("/chattings/{chatRoomId}", 1L)
ㅠㅠ.. 감사합니다 엔초...5

2023-09-30 07:58 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
>          mockMvc.perform(get("/chattings/1")
ㅠㅠ.. 감사합니다 엔초...6

2023-09-30 07:59 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
>          mockMvc.perform(get("/chattings/1")
ㅠㅠ.. 감사합니다 엔초...7

2023-09-30 08:00 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/fixture/ChatRoomControllerFixture.java
> +    private ReadUserInChatRoomDto 구매자2 = new ReadUserInChatRoomDto(3L, "사용자3", 3L, 5.0d, false);
반영했습니다! 감사합니다 지토..

2023-09-30 08:01 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/fixture/ChatRoomControllerFixture.java
> +    protected final PrivateClaims 비공개_클레임 = new PrivateClaims(1L);
좋은 의견 감사합니다.
반영해두었습니다.

2023-09-30 08:03 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/fixture/ChatRoomControllerFixture.java
> +    protected final Long 유효하지_않은_마지막_메시지_아이디 = -999L;
원래 필드에서 바로 주입해주는 값들은 final을 붙이자고 했던 것 같아 final을 붙여주었는데,
컨트롤러 테스트 특성상 모든 필드를 바로 주입해주는 형태가 되면서 모두 final을 붙여도 될 것 같네요! 모두 final 붙이는 방향으로 통일하겠습니다.

2023-09-30 08:06 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +        final ResultActions resultActions = mockMvc.perform(RestDocumentationRequestBuilders.post("/chattings/{chatRoomId}/messages", 1L)
픽스처로 통일해주었습니다!
감사합니다 지토

2023-09-30 08:08 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +        given(tokenDecoder.decode(eq(TokenType.ACCESS), anyString())).willReturn(Optional.of(비공개_클레임));
이 부분도 다른 테스트처럼 픽스처로 통일시켰습니다.
감사합니다

2023-09-30 08:09 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
> +        given(tokenDecoder.decode(eq(TokenType.ACCESS), anyString())).willReturn(Optional.of(비공개_클레임));
좋습니다! 말씀해주신 부분들 모두 반영해 픽스처로 변경해두었습니다.

2023-09-30 08:11 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/fixture/ChatRoomControllerFixture.java
> +    protected TokenDecoder tokenDecoder = mock(TokenDecoder.class);
이 부분은 그냥 픽스처로 두었을 때의 가독성이 좋은 것 같다고 생각해 픽스처에 둘 수 있는 것들은 대부분 픽스처로 빼려고 픽스처에 두었습니다.
그런데 말씀해주신 부분에 동의해서 그냥 테스트 클래스에 두고 영어로 하는 게 자연스러운 것 같아 테스트 클래스로 이동해두었습니다.

2023-09-30 09:06 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/fixture/ChatRoomControllerFixture.java
> +    protected final Long 유효하지_않은_마지막_메시지_아이디 = -999L;
### 질문
`BidService`를 예시로 함께 진행할 때는 final을 모두 붙여주지 않은 것으로 기억하고 있는데 이에 대해 어떻게 생각하시는 지 궁금합니다!
저도 고민 중인 사항이라 확실히 하면 좋을 것 같아서요!

2023-09-30 09:10 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/fixture/ChatRoomControllerFixture.java
> +    protected final Long 유효하지_않은_마지막_메시지_아이디 = -999L;
저는 필드에서 바로 주입해주는 상황에서는 final을 붙이고, `@BeforeEach`를 통해 주입해주는 값은 final을 붙이지 않는 것으로 생각하고 있었습니다. 헐 그런데 다시 확인해보니까 바로 주입해주더라도 final을 붙이지 않았네요.......
final을 붙이지 않을 이유가 없을 것 같긴합니다만.. 다른 분들의 의견을.. 불가피하게 다시 여쭤봐야겠네요..

2023-09-30 09:13 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/fixture/ChatRoomControllerFixture.java
> +    protected final Long 유효하지_않은_마지막_메시지_아이디 = -999L;
저도 이 부분은 그냥 final을 다 붙이지 않는 것으로 기억하고 있습니다

2023-09-30 10:19 UTC, kwonyj1022 approved these changes
수정해주신 부분 확인했습니다! 수고하셨어요 메리!!

2023-09-30 10:25 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/fixture/ChatRoomControllerFixture.java
> +    protected CreateChatRoomRequest 유효하지_않은_경매_아이디_채팅방_생성_요청 = new CreateChatRoomRequest(1L);
맞네요 저번에는 '정상적인' 안썼던 것 같습니다!

2023-09-30 12:32 UTC, merged