디바이스 토큰 관련 테스트 코드 리팩토링
woowacourse-teams/2023-3-ddang pull request #491
Opened 2023-09-29 20:57 UTC by kwonyj1022

## 📄 작업 내용 요약

디바이스 토큰 관련 테스트 코드 리팩토링
## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

## 📎 Issue 번호

- closed #480

2023-09-30 07:44 UTC, apptie approved these changes
고생하셨습니다
여기나 지역이나 서비스 테스트 Fixture 관련해서 동일한 이슈가 있는 것 같습니다
그래서 이거를 어케 둬야하나 싶었는데 아직 확정은 아니니까...일단 approve로 두겠습니다

2023-09-30 07:44 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/device/application/fixture/DeviceTokenServiceFixture.java
> +                                         .build();
### 선택

`.`을 기준으로 하는 개행?이 잘 안맞는 것 같습니다

2023-09-30 07:44 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/device/domain/fixture/DeviceTokenFixture.java
> +                  .build();
### 선택

해당 구간도 `.` 개행의 스타일?이 잘 맞지 않는 것 같습니다

2023-09-30 07:44 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/device/infrastructure/persistence/fixture/JpaDeviceTokenRepositoryFixture.java
> +                  .build();
### 선택

해당 부분도 `.`의 개행이 잘 안되어 있는 것 같습니다

2023-09-30 07:44 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/device/presentation/DeviceTokenControllerTest.java
> +                               .header(HttpHeaders.AUTHORIZATION, "Bearer accessToken")
### 질문

갑자기 또 궁금해진 부분인데 
`header(HttpHeaders.AUTHORIZATION, "Bearer accessToken")`에서 `Bearer accessToken`도 Fixture로 분리를 해야 할까요?

2023-09-30 07:44 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/device/presentation/fixture/DeviceTokenControllerFixture.java
> +    protected PrivateClaims 유효하지_않은_비공개_클레임 = new PrivateClaims(-999L);
### 선택

privateClaims가 jwt에 암호화한 내용이고 지금은 userId를 암호화하고 있어서 유효한_사용자_id_클레임 이정도로 표현하는건 어떨까요?

2023-09-30 10:27 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/device/application/fixture/DeviceTokenServiceFixture.java
> +                                         .build();
이거 방금 확인해보니 제 인텔리제이에서는 변수명이 한글일 때는 저렇게 이상하게 되더군요ㅠ 일일이 해줘야겠네요

2023-09-30 10:28 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/device/presentation/DeviceTokenControllerTest.java
> +                               .header(HttpHeaders.AUTHORIZATION, "Bearer accessToken")
하는게 좋을 것 같습니다. 적용하겠습니다!!

2023-09-30 10:28 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/device/presentation/fixture/DeviceTokenControllerFixture.java
> +    protected PrivateClaims 유효하지_않은_비공개_클레임 = new PrivateClaims(-999L);
메리 pr에서도 봤던 리뷰네요 좋습니다~ 수정하겠습니다!!!

2023-09-30 13:14 UTC, JJ503 approved these changes
엔초 고생 많으셨습니다!
따로 수정 사항은 보이지 않아 이만 approve 하도록 하겠습니다~!

2023-09-30 14:19 UTC, swonny requested changes
엔초 고생 많으셨습니다!!
궁금한 부분이 몇 가지 있어 rc 남깁니다!
댓글만 확인하고 바로 approve할게요!

2023-09-30 14:19 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/device/application/DeviceTokenServiceTest.java
> +        final Optional<DeviceToken> deviceTokenResult = deviceTokenRepository.findByUserId(디바이스_토큰이_있는_사용자.getId());
### 질문

검사하는 대상의 변수명은 actual로 하기로 했던 것 같은데 조금 헷갈리네요,,

2023-09-30 14:19 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/device/application/DeviceTokenServiceTest.java
> +        deviceTokenService.persist(디바이스_토큰이_있는_사용자.getId(), 존재하는_디바이스_토큰과_동일한_토큰을_저장하려는_DTO);
### 질문

저는 지토 코드를 참고해 Dto를 Dto라는 이름 없이 설명만 작성해주었는데 dto를 붙일지 여부도 통일시키면 좋을까요?

엔초가 작성해주신 방식이 가독성이 더 좋은 것 같다는 의견이긴 합니다..!

2023-09-30 14:19 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/device/presentation/DeviceTokenControllerTest.java
> +        willThrow(new UserNotFoundException("해당 사용자를 찾을 수 없습니다."))
### 질문

여기에서는 왜 willThrow()가 먼저 왔는지 궁금합니다!

2023-09-30 14:38 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/device/application/DeviceTokenServiceTest.java
> +        deviceTokenService.persist(디바이스_토큰이_있는_사용자.getId(), 존재하는_디바이스_토큰과_동일한_토큰을_저장하려는_DTO);
통일하면 좋을 것 같아서 내일 데일리에 물어보도록 하죠!

2023-09-30 14:41 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/device/presentation/DeviceTokenControllerTest.java
> +        willThrow(new UserNotFoundException("해당 사용자를 찾을 수 없습니다."))
deviceTokenService.persist()가 아무런 반환값이 없어서 `given(deviceTokenService.persist()).willThrow(~)` 형식으로 작성할 수 없었습니다.

2023-09-30 14:44 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/device/application/DeviceTokenServiceTest.java
> +        final Optional<DeviceToken> deviceTokenResult = deviceTokenRepository.findByUserId(디바이스_토큰이_있는_사용자.getId());
테스트 하고자 하는 메서드는 when 절에 있는데 해당 메서드는 반환값이 없기 때문에 then 절에서 직접 다시 조회해 온 후 테스트를 진행하는지라 actual을 사용하지 않았습니다. 이런 부분에도 actual을 사용하는 것이 좋을까요? 다른 분들의 의견도 궁금하군요!

2023-09-30 15:22 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/device/application/DeviceTokenServiceTest.java
> +        final Optional<DeviceToken> deviceTokenResult = deviceTokenRepository.findByUserId(디바이스_토큰이_있는_사용자.getId());
그런데 생각해보니 actual이 맞는 것 같네요. 수정하도록 하겠습니다!

2023-10-01 14:43 UTC, swonny approved these changes
수정사항 확인하여 approve합니다!
고생하셨어요!

2023-10-02 16:06 UTC, merged