신고 관련 테스트 코드 리팩토링
woowacourse-teams/2023-3-ddang pull request #493
Opened 2023-09-30 07:06 UTC by JJ503

## 📄 작업 내용 요약

신고 관련 테스트 코드 리팩토링

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

## 📎 Issue 번호

- closed #489

2023-09-30 09:32 UTC, apptie approved these changes
안녕하세요 제이미?
반갑습니다 
잘 작성해주신 것 같습니다 
고생하셨고 approve를 드리도록 하겠습니다

2023-09-30 09:32 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/report/application/AuctionReportServiceTest.java
> +import org.assertj.core.api.*;
### 필수

`*`를 없애주세요

2023-09-30 09:32 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/fixture/ReportControllerFixture.java
> +    // TODO: 9/30/23 final을 붙일지 말지 고민되네요, 경고가 보기 싫어서 일단 private에만 붙인 상태입니다.
### 선택

아마 그 때 final을 붙일까말까 했었던게 어디에는 final이 있고 어디에는 final이 없으면 좀..미관상 좋지 않아서 이렇게 하기로 기억하고 있습니다

final을 골라 붙이는 수고로움과 미관상의 단점이라면 경고를 억제하는 방법은 어떨까요?

2023-09-30 09:32 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/fixture/ReportControllerFixture.java
> +    protected PrivateClaims 채팅방_참여자가_아닌_사용자_ID_클레임 = new PrivateClaims(999L);
### 칭찬

칭찬해요!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!@#!@#!@#
이름 좋습니다 명확하고 이 값이 jwt의 클레임이라는 것도 확인할 수 있고 아주좋네요

2023-09-30 09:47 UTC, apptie requested changes
앗 `*` 이거 바꾸셔야해서 rc로 바꾸겠습니다 ㅎㅎ;

2023-09-30 12:23 UTC, kwonyj1022 requested changes
제이미 수고하셨습니다! 필수로 수정되었으면 하는 사항이 있어서 rc 남겨요~

2023-09-30 12:23 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/report/application/fixture/AuctionReportServiceFixture.java
> +                          .build();
### 필수
왜 변수명이 한글이면 체이닝이 잘 안되는걸까요? ㅠㅠ 저만 그런게 아니었군요

2023-09-30 12:23 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/report/application/fixture/AuctionReportServiceFixture.java
> +        삭제된_경매.delete();
### 필수
여기도 체이닝이..!!

2023-09-30 12:23 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/report/application/fixture/ChatRoomReportServiceFixture.java
> +                              .build();
### 필수
여기두요

2023-09-30 12:23 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/report/application/fixture/ChatRoomReportServiceFixture.java
> +                                   .build();
### 필수
여기도!!

2023-09-30 12:23 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/report/infrastructure/persistence/JpaChatRoomReportRepositoryTest.java
> +    private EntityManager em;
### 질문
여기는 왜 private을 붙였나요?

2023-09-30 12:23 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/ReportControllerTest.java
> +                                                           .header(HttpHeaders.AUTHORIZATION, "Bearer accessToken")
### 질문
제 pr에서 여기 헤더에 들어가는 것도 픽스처로 하면 어떨까 하는 지토의 의견이 있었습니다. 제이미는 어떻게 생각하시나요?

2023-09-30 12:23 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/ReportControllerTest.java
>          given(auctionReportService.create(any(CreateAuctionReportDto.class))).willReturn(1L);
### 선택
여기 밑에 있는 1L도 픽스처로 두는 것은 어떤가요?

2023-09-30 12:23 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/ReportControllerTest.java
>          given(auctionReportService.create(any(CreateAuctionReportDto.class))).willReturn(1L);
### 필수
request 단에서 예외가 터지므로 두 번째 given 은 없어도 될 것 같습니다.

2023-09-30 12:23 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/ReportControllerTest.java
>          given(auctionReportService.create(any(CreateAuctionReportDto.class))).willReturn(1L);
### 필수
request 단에서 예외가 터지므로 두 번째 given 은 없어도 될 것 같습니다.

2023-09-30 12:23 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/ReportControllerTest.java
>          given(auctionReportService.create(any(CreateAuctionReportDto.class))).willReturn(1L);
### 필수
request 단에서 예외가 터지므로 두 번째 given 은 없어도 될 것 같습니다.

2023-09-30 12:23 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/ReportControllerTest.java
>          given(chatRoomReportService.create(any(CreateChatRoomReportDto.class))).willReturn(1L);
### 필수
request 단에서 예외가 터지므로 두 번째 given 은 없어도 될 것 같습니다.

2023-09-30 12:23 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/ReportControllerTest.java
>          given(chatRoomReportService.create(any(CreateChatRoomReportDto.class))).willReturn(1L);
### 필수
request 단에서 예외가 터지므로 두 번째 given 은 없어도 될 것 같습니다.

2023-09-30 12:23 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/ReportControllerTest.java
>          given(chatRoomReportService.create(any(CreateChatRoomReportDto.class))).willReturn(1L);
### 필수
request 단에서 예외가 터지므로 두 번째 given 은 없어도 될 것 같습니다.

2023-09-30 13:35 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/application/AuctionReportServiceTest.java
> +import org.assertj.core.api.*;
`SoftAssertions`은 항상 `*`로 바뀌어 버리네요... 흑...

2023-09-30 13:41 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/fixture/ReportControllerFixture.java
> +    // TODO: 9/30/23 final을 붙일지 말지 고민되네요, 경고가 보기 싫어서 일단 private에만 붙인 상태입니다.
확인했습니다.
말씀해주신대로 final은 모두 제거했습니다!

2023-09-30 13:44 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/application/fixture/AuctionReportServiceFixture.java
> +                          .build();
한글이어서 그런 거였군요...
아무리 설정 관련해서 검색해봐도 안 나오더라고요... 쩝
저도 직접 수정해보도록 하겠습니다!

2023-09-30 13:46 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/infrastructure/persistence/JpaChatRoomReportRepositoryTest.java
> +    private EntityManager em;
오잉... 복붙의 실수인가 보군요..ㅎㅎ

2023-09-30 13:48 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/ReportControllerTest.java
> +                                                           .header(HttpHeaders.AUTHORIZATION, "Bearer accessToken")
앗 그게 좋겠네요 수정해두도록 하겠습니다!

2023-09-30 13:59 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/ReportControllerTest.java
>          given(auctionReportService.create(any(CreateAuctionReportDto.class))).willReturn(1L);
해당 부분도 수정해두었습니다!

2023-09-30 14:03 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/report/application/fixture/AuctionReportServiceFixture.java
> +                          .build();
사실 저도 귀찮긴 한데 어긋난 거 보이면 괜히 또 맞추고 싶고 그래서~ 아마 보이면 최대한 맞추려고는 할 것 같아요! 안 보이면 어쩔 수 없는 것 같습니다..

2023-09-30 14:04 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/ReportControllerTest.java
>          given(auctionReportService.create(any(CreateAuctionReportDto.class))).willReturn(1L);
오 좋은 지적 감사합니다!
아무 생각 없이 그냥 넣었네요.
엔초 짱!

2023-09-30 14:04 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/ReportControllerTest.java
>          given(auctionReportService.create(any(CreateAuctionReportDto.class))).willReturn(1L);
엔초 짱 22

2023-09-30 14:04 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/ReportControllerTest.java
>          given(auctionReportService.create(any(CreateAuctionReportDto.class))).willReturn(1L);
엔초 짱33

2023-09-30 14:04 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/ReportControllerTest.java
>          given(chatRoomReportService.create(any(CreateChatRoomReportDto.class))).willReturn(1L);
엔초 짱 44

2023-09-30 14:04 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/ReportControllerTest.java
>          given(chatRoomReportService.create(any(CreateChatRoomReportDto.class))).willReturn(1L);
엔초 짱 55

2023-09-30 14:05 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/ReportControllerTest.java
>          given(chatRoomReportService.create(any(CreateChatRoomReportDto.class))).willReturn(1L);
엔초 짱 66

2023-09-30 14:11 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/report/application/fixture/AuctionReportServiceFixture.java
> +                          .build();
한글인것때문에 안맞추기에는 다른 곳에는 다 맞추고 있어서...그냥 테스트 환경에서는 이걸 필수보다는 선택으로 하는게 나아 보이기는 하네요

2023-09-30 14:39 UTC, swonny requested changes
고생 많으셨습니다 제이미!!
같이 논의해보면 좋을 내용 관련해 질문을 남겨두어서 rc를 드립니다... ㅠㅠ
같이 논의해본 뒤 approve하겠습니다

2023-09-30 14:39 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/report/application/fixture/AuctionReportServiceFixture.java
> +        final Long 존재하지_않는_경매_아이디 = -9999L;
### 필수

엔초는 해당 변수들을 private 필드로 두었던데 확실히 통일시킬 필요가 있어보입니다!

2023-09-30 14:39 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/report/infrastructure/persistence/JpaAuctionReportRepositoryTest.java
> +        final AuctionReport auctionReport = new AuctionReport(판매자, 경매, "신고합니다");
### 질문

이건 제가 너무 몰라서 남기는 질문 ...입니다
왜 여기에서만 em.flish()를 해주는 것인가요 🥺..

2023-09-30 14:39 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/report/infrastructure/persistence/fixture/JpaChatRoomReportRepositoryFixture.java
> +        final User 구매자2겸_신고자 = User.builder()
### 칭찬

명확한 변수명 칭찬합니다~!

2023-09-30 14:39 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/fixture/ReportControllerFixture.java
> +    private ReadAuctionInReportDto 신고할_채팅방의_경매_정보1 = new ReadAuctionInReportDto(
### 필수 & 질문

'정보'가 변수명에 포함되어야 하는지 잘 모르겠네요..!
엔초는 Dto라고 명시해주었던데 시간을 거듭할수록 이런 사소한 부분에서 큰 차이가 생길 것 같아 미리 맞추고 가는 게 좋을 것 같아보여요.

dto의 네이밍에 대해서도 함께 이야기해봅시다!

2023-09-30 15:06 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/application/fixture/AuctionReportServiceFixture.java
> +                          .build();
맞추려고 해도 결국 체이닝 설정을 통해 정렬된 것에 비해 미묘하게 어긋나는 게 개인적으로 더 불편한 것도 이유 중 하나였습니다...
그리고 오히려 해당 부분을 맞추려다가 정렬 단축키를 못쓰게 되었을 때 다른 파트에 대한 정렬도 직접 신경써줘야 하기에 이 부분에 대해서도 추가적인 비용이 들 것이라 생각했습니다.

2023-09-30 15:08 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/application/fixture/AuctionReportServiceFixture.java
> +        final Long 존재하지_않는_경매_아이디 = -9999L;
맞습니다.
저는 개인적으로 필드가 너무 많아진다면 어떤 것이 픽스처인지 확인이 어렵고 굳이 밖으로 뺄 필요성을 느끼지 못해 해당 부분은 BforeEach 내부로 넣어두었습니다.
이가 엔초와 다른 것을 확인해 엔초 pr에 의견 남겨둔 상태입니다.
이에 대해 다른 분들의 의견이 궁금합니다!

2023-09-30 15:30 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/infrastructure/persistence/JpaAuctionReportRepositoryTest.java
> +        final AuctionReport auctionReport = new AuctionReport(판매자, 경매, "신고합니다");
`repository` 테스트이기 때문인 것 같습니다.
사실 해당 코드가 없어도 테스트 자체는 통과할 수도 있긴 하지만, 그래도 명확하게 동기화하기 위해 명시적으로 작성해 주었습니다. 
또한, 기존 save() 관련된 코드들 역시 flush, clear를 통해 작성했기에 그냥 동일하게 진행했습니다.
굳이 스럽다면 제거하도록 하겠습니다.

2023-09-30 15:30 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/fixture/ReportControllerFixture.java
> +    private ReadAuctionInReportDto 신고할_채팅방의_경매_정보1 = new ReadAuctionInReportDto(
좋습니다!
Request dto를 요청이라 칭하듯, service 레이어에서의 dto는 정보라고 칭하는 것으로 설정했습니다.
DTO도 괜찮긴 하지만, 당시에는 해당 네이밍을 생각하지 못했기도 했고 해당 객체가 경매 정보를 의미한다는 것을 알리고 싶었기 때문입니다.
이에 대해 다른 분들의 의견이 궁금하네요!

2023-09-30 15:36 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/report/infrastructure/persistence/JpaAuctionReportRepositoryTest.java
> +        final AuctionReport auctionReport = new AuctionReport(판매자, 경매, "신고합니다");
해당 테스트는 Repository 테스트로, 정상적으로 외부 저장소(여기서는 DB)에 CRUD가 정상적으로 수행되는지를 체크하기 위한 테스트라고 생각합니다 

`em.flush()`와 `em.clear()`를 하지 않는다면 JPA의 특성상 1차 캐시에 저장되기만 하고 그 1차 캐시에 저장된 값을 단순히 불러오게 될 것이므로 특정 Repository를 테스트하고자 하는 목적을 만족시키지 못한다고 생각합니다 

실제 외부 저장소에 값을 저장시키고 그 값을 조회하고를 하기 위해서 반드시 두 메서드는 호출해야 한다고 생각합니다

2023-09-30 15:44 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/report/application/fixture/AuctionReportServiceFixture.java
> +                          .build();
정렬 단축키라는 기능에 초점을 맞춘다면 저는 `.`을 기준으로 개행하는 걸 빼면 되지 않을까 싶습니다 

일단 한글이라는 이유로 특정 환경에서는 개행을 맞추지 않는다는게 저는 상당히 이질적으로 느껴집니다
문제가 되는건 `.`을 기준으로 개행을 하고 있는 상황이니 특정 상황에만 개행을 하는 것이 아니라 개행에 대한 전체적인 컨벤션을 수정해야한다고 생각합니다

2023-09-30 15:48 UTC, apptie requested changes
의견을 적는 와중 별을 하나 더 찾아서 rc로 변경하겠습니다

2023-09-30 15:48 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/report/infrastructure/persistence/JpaChatRoomReportRepositoryTest.java
> +import org.assertj.core.api.*;
### 필수

여기도 별이 있어요 홀리몰리

2023-09-30 15:48 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/fixture/ReportControllerFixture.java
> +    private ReadAuctionInReportDto 신고할_채팅방의_경매_정보1 = new ReadAuctionInReportDto(
만약 DTO에 대한 네이밍을 맞춘다면 그냥 끝에 사용하는 영어를 그대로 사용하는게 가장 오해의 소지가 없다고 생각합니다 

`신고할_채팅방의_경매_정보_Dto`나 `채팅방_신고_Request` 이런식이 용어의 혼란 없이 명확하게  생각합니다

2023-09-30 16:03 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/report/application/fixture/AuctionReportServiceFixture.java
> +        final Long 존재하지_않는_경매_아이디 = -9999L;
이건 저는 굳이 통일시켜야하는지 의문이 듭니다...

Fixture의 가독성을 챙겨야 할까요?
테스트가 너무 복잡해서 Fixture를 적용했다고 생각했는데 그렇다면 테스트에서 언급되는 모든 Fixture를 때려박은 그 클래스는 IDE의 힘으로 봐야 하는게 아닐까하고 생각합니다
그렇다면 이렇게 비용을 들여가면서 통일을 시켜야할까 싶네요 Fixture의 이름 같은 부분이 아니라 위치의 문제라면 어느 정도 가독성이나 통일성을 버려도 괜찮지 않을까 생각합니다

만약 그럼에도 불구하고 통일시켜야 한다면...`@BeforeEach`에 위와 같이 선언하면 테스트가 생성될 때 마다 매번 새로운 인스턴스를 할당받게 되니 이를 고려해 private 필드로 두는 것이 더 효율적이겠네요

2023-10-01 01:43 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/report/infrastructure/persistence/JpaAuctionReportRepositoryTest.java
> +        final AuctionReport auctionReport = new AuctionReport(판매자, 경매, "신고합니다");
두 분의 소중한 답변 감사합니다🙇🏻‍♀️

2023-10-01 15:03 UTC, swonny approved these changes
논의했던 내용은 모두 반영된 것 같아 approve합니다. 고생많으셨습니다.

2023-10-02 12:59 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/application/fixture/AuctionReportServiceFixture.java
> +                          .build();
해당 부분은 회의 결과 픽스처의 경우 작성자가 편한대로 진행하기로 했기에 따로 수정은 진행하지 않도록 하겠습니다!

2023-10-02 13:01 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/application/fixture/AuctionReportServiceFixture.java
> +        final Long 존재하지_않는_경매_아이디 = -9999L;
해당 부분 역시 굳이 통일시키지 않기로 했기에 따로 수정은 진행하지 않도록 하겠습니다!

2023-10-02 13:04 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/presentation/fixture/ReportControllerFixture.java
> +    private ReadAuctionInReportDto 신고할_채팅방의_경매_정보1 = new ReadAuctionInReportDto(
dto와 request 등으로 수정 진행했습니다!

2023-10-02 13:15 UTC, apptie approved these changes
별이 없어졌으므로 Approve 하도록 하겠습니다

2023-10-02 14:47 UTC, kwonyj1022 approved these changes
수정 감사합니다 수고하셨어요!!

2023-10-03 03:24 UTC, merged