입찰 관련 테스트 코드 리팩토링
woowacourse-teams/2023-3-ddang pull request #496
Opened 2023-10-01 03:51 UTC by JJ503

## 📄 작업 내용 요약

입찰 관련 테스트 코드 리팩토링

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

아직 명확히 정해지지 않은 부분에 대해선 일단 제 개인적인 취향으로 진행했습니다.
규칙이 명확히 정해진다면 해당 내용에 따를 수 있도록 수정 진행하겠습니다.

## 📎 Issue 번호

- closed #488

2023-10-01 04:26 UTC, swonny requested changes
고생 많으셨습니다 제이미!!
질문이 있어 rc 남깁니다!

2023-10-01 04:26 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/bid/application/fixture/BidServiceFixture.java
> +
### 칭찬

`protected` 타입 중에서도 필드에서 초기화하는 필드와 setUp()에서 초기화하는 필드를 구분하는 방식 좋네요!

2023-10-01 04:26 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/bid/application/fixture/BidServiceFixture.java
> +                   .name("구매자1")
### 필수

```suggestion
                   .name("입찰자1")
```
name()을 필드명에 맞춰 바꿔주세요!

2023-10-01 04:26 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/bid/application/fixture/BidServiceFixture.java
> +                   .name("구매자2")
### 필수

```suggestion
                   .name("입찰자2")
```
name()을 필드명에 맞춰 바꿔주세요! 22

2023-10-01 04:26 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/bid/application/fixture/BidServiceFixture.java
> +        userRepository.saveAll(List.of(판매자, 입찰자1, 입찰자2));
### 선택
(인지 필수인지 헷갈ㄹ ㅕ 요..)

`userRepository.saveAll(List.of(판매자, 입찰자1, 입찰자2));`는 79번째 줄로 이동하는 것이 순서상 보기 편할 것 같습니다.

2023-10-01 04:26 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/bid/application/fixture/BidServiceFixture.java
> +        존재하지_않는_경매_아이디에_대한_입찰_요청_dto = new CreateBidDto(존재하지_않는_경매_아이디, 10_000, 입찰자1.getId());
### 질문

저랑 엔초는 `입찰_요청_DTO`와 같이 대문자를 사용했는데 이것도 통일시킬 필요가 있을까요?

2023-10-01 04:26 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/bid/domain/BidTest.java
> +        final boolean actual = bid.isNextBidPriceGreaterThan(이전_입찰액보다_크지만_입찰_단위보다_작은_입찰액);
### 칭찬

명확한 변수명 👍🏻👍🏻

2023-10-01 04:26 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/bid/domain/fixture/BidFixture.java
> +        전자기기_카테고리.addSubCategory(전자기기_서브_노트북_카테고리);
### 질문

쪽지 관련 테스트 리팩토링 시 경매글 생성 시 카테고리는 필요하지 않은 속성이라고 생각해 `title` 속성만 생성한 상태로 경매글 엔티티를 생성해주었습니다. 그런데 제이미는 카테고리까지 추가해주셔서 질문 남깁니다.

테스트에서 필요하지 않은 속성이라도 온전한 경매 엔티티를 생성해주어야 할까요?

2023-10-01 04:26 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/bid/infrastructure/persistence/fixture/JpaBidRepositoryFixture.java
> +        userRepository.saveAll(List.of(판매자, 입찰자1, 입찰자2));
### 선택
(인지 필수인지 헷갈려요..)

이것도 위에 남긴 코멘트와 동일합니다.
함께 진행할 때는 user관련 레포지토리 저장 로직은 user 엔티티 생성 로직 바로 하위에 두기로 했던 것 같아서 코멘트 남깁니다!

2023-10-01 17:00 UTC, kwonyj1022 approved these changes
수고하셨습니다!!

2023-10-01 17:03 UTC, kwonyj1022 requested changes
approve를 드리려 했으나 `*`을 발견해서 rc로 바꿨습니다..

2023-10-01 17:03 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/bid/application/BidServiceTest.java
> +import org.assertj.core.api.*;
### 필수
별을 발견했어요!!

2023-10-02 05:28 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/bid/domain/fixture/BidFixture.java
> +        전자기기_카테고리.addSubCategory(전자기기_서브_노트북_카테고리);
해당 부분은 필요가 없다면 Fixture에서는 생략해도 괜찮다고 생각합니다 (Fixture 만드는 개인 책임 느낌)

테이블 컬럼에 not null이 들어간다고 하더라도 BidTest에서는 DB에 저장하는 로직을 아에 배제하고 테스트하기 때문에 큰 문제가 없을 것 같고 
만약 Bid에 Auction에 Category가 반드시 필요하게 된다면 그 때는 수정을 하는게 자연스러워 보이네요

---

이와는 별개로 Bid가 너무 많은 정보를 알고 있는 것 같습니다
Bid -> Auction -> Category의 정보까지 Bid가 알고 있는 지금 설계 자체에 문제가 있다고 생각되네요

2023-10-02 05:33 UTC, apptie approved these changes
다른 분들이 이미 리뷰를 잘 해주셨네요 ㄷㄷ..

별 관련된거 제외하고는 문제가 없는 것 같습니다
엔초가 RC 해주셨으니 저는 Approve를 해도 될 것 같아요..?

2023-10-02 05:33 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/bid/application/BidServiceTest.java
> -        // given
동의합니다 테스트 코드에서 어떤 로직이 돌아가는지는 명시해야 된다고 생각합니다

2023-10-02 05:33 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/bid/application/fixture/BidServiceFixture.java
> +        userRepository.saveAll(List.of(판매자, 입찰자1, 입찰자2));
이거는 선택이 맞는 것 같습니다 
Fixture에 대한 가독성은...사실 버리는게 맞지 않을까요?

2023-10-02 05:33 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/bid/application/fixture/BidServiceFixture.java
> +        존재하지_않는_경매_아이디에_대한_입찰_요청_dto = new CreateBidDto(존재하지_않는_경매_아이디, 10_000, 입찰자1.getId());
이 부분은...Fixture 만들고 그냥 포괄적으로 변경하는게 나을지도...모르겠네요 
사실 DTO던 dto건 Dto건 의미는 통하기는 하니까...불편해도 일단은 넘겨도 될 것 같네요

2023-10-02 13:08 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/bid/application/fixture/BidServiceFixture.java
> +                   .name("구매자1")
오 해당 부분을 놓쳤네요! 감사합니다 메리!

2023-10-02 13:11 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/bid/application/fixture/BidServiceFixture.java
> +        userRepository.saveAll(List.of(판매자, 입찰자1, 입찰자2));
저는 개인적으로 필드들에 대한 초기화와 repository를 사용한 저장이 함께 진행하는 것이 더 헷갈려 위와 같은 순서가 되었습니다.
그러므로 해당 부분은 따로 수정을 진행하지 않도록 하겠습니다..!

2023-10-02 13:12 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/bid/application/fixture/BidServiceFixture.java
> +        존재하지_않는_경매_아이디에_대한_입찰_요청_dto = new CreateBidDto(존재하지_않는_경매_아이디, 10_000, 입찰자1.getId());
저도 의미적으로만 전달되고 서로 이해만 된다면 생각하는지라 굳이 수정은 진행하지 않도록 하겠습니다!

2023-10-02 13:15 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/bid/domain/fixture/BidFixture.java
> +        전자기기_카테고리.addSubCategory(전자기기_서브_노트북_카테고리);
저도 해당 부분에 대해선 계속 고민 중인 상태입니다.
그래서 픽스처별로 넣은 것과 넣지 않은 것이 혼용되어 있는.... 😨
하지만, 말씀해주신 내용처럼 도메인 테스트에서는 굳이 필요하지 않은 정보이기에 카테고리는 제거하도록 하겠습니다!

2023-10-02 13:17 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/bid/infrastructure/persistence/fixture/JpaBidRepositoryFixture.java
> +        userRepository.saveAll(List.of(판매자, 입찰자1, 입찰자2));
위에서 설명했듯이 저는 개인적으로 해당 방식이 이해 및 가독성에 더 좋다고 생각해 굳이 수정은 진행하지 않겠습니다.
사실 해당 내용과 관련해 이야기한 것은 전혀 기억이 나지 않네요...

2023-10-02 13:19 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/bid/application/BidServiceTest.java
> -        // given
로직이 잘 이해가 되지 않습니다.
해당 경우는 첫 입찰로 알람이 누구에게도 가지 않는 상황입니다.
그렇기에 기존에 있던 send()를 아예 호춣도 하지 않는 것으로 이해했습니다.
그래서 두 번째 테스트에서만 진행한 상태입니다.
제가 이해한 내용이 틀렸다면 말씀해주시면 감사하겠습니다!

2023-10-02 13:23 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/bid/application/BidServiceTest.java
> +        });
좋은 의견 감사합니다!
auctioneerCount 때문에 create를 두 번 하는 걸 보여주는 것이 더 직관적일 것이라 생각했는데 오히려 혼란을 가중시켰군요... 🥲

2023-10-02 13:29 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/bid/application/BidServiceTest.java
> +        final Long actual = bidService.create(시작가로_입찰_요청_dto, 이미지_절대_url);
해당 이름으로 수정했습니다!

2023-10-02 13:33 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/bid/application/BidServiceTest.java
> +        assertThatThrownBy(() -> bidService.create(이전_입찰액보다_낮은_입찰액으로_입찰_요청_dto, 이미지_절대_url))
좋은 의견 수용했습니다!

2023-10-02 14:41 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/bid/application/BidServiceTest.java
> -        // given
앗 그렇네요 그렇다면 테스트 메서드명을 변경하는 것은 어떤가요? 테스트명이 단순히 입찰을 등록한다고만 되어있어서 첫 번째 입찰인지 그 이후 입찰인지 바로 알 수 없어서 헷갈린 것 같습니다.

2023-10-02 14:44 UTC, kwonyj1022 approved these changes
수정 감사합니다 수고하셨어요!!

2023-10-03 02:21 UTC, swonny approved these changes
고생많으셨습니다!
변경 내용 확인했고 approve할게요!!

2023-10-03 03:28 UTC, merged