사용자 관련 테스트 코드 리팩토링
woowacourse-teams/2023-3-ddang pull request #499
Opened 2023-10-01 08:23 UTC by JJ503

## 📄 작업 내용 요약

사용자 관련 테스트 코드 리팩토링

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

`ReadUserDto` 테스트의 경우 DB 제약 조건 변경으로 해당 로직이 불필요해짐에 따라 테스트도 불필요해져 제거했습니다.

## 📎 Issue 번호

- closed #490

2023-10-01 10:13 UTC, apptie approved these changes
고생하셨습니다
매우 깔끔하게 잘 짜신 것 같네요 
리스펙하는 의미로 Approve와 질문 하나를 드리도록 하겠습니다

2023-10-01 10:13 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/user/application/UserServiceTest.java
> +                          .isEqualTo(새로운_프로필_이미지_dto.uploadName());
### 질문

문서화가 아닌 코드에서도 위처럼 개행을 하기로 정해졌었나요? 헷갈려서 질문드립니다

2023-10-01 10:13 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/user/presentation/UserAuctionControllerTest.java
> +        given(tokenDecoder.decode(eq(TokenType.ACCESS), anyString())).willReturn(Optional.of(사용자_ID_클레임));
### 칭찬

명확한 네이밍 좋아요 👍

2023-10-01 10:13 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/user/presentation/fixture/UserControllerFixture.java
> +    );
### 칭찬

타입 캐스팅 👍

2023-10-01 14:53 UTC, swonny approved these changes
깔끔하네요!
고생하셨습니다 제이미!!

2023-10-01 17:13 UTC, kwonyj1022 requested changes
별 때문에 rc입니다

2023-10-01 17:13 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/user/application/UserService.java
> +    private void updateUserByRequest(final UpdateUserDto userDto, final User user) {
### 칭찬
오타 발견!! 어떻게 하셨나요!! 대박 뭐가 바뀐건지 한참 봤네요

2023-10-01 17:13 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/user/application/UserServiceTest.java
> +import org.assertj.core.api.*;
### 필수
별을 발견했어요!! 😱😱

2023-10-01 17:13 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/user/application/fixture/UserServiceFixture.java
> +    JpaUserRepository userRepository;
### 필수
private으로 변경 부탁드립니다!!

2023-10-02 05:33 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/user/application/UserService.java
> +    private void updateUserByRequest(final UpdateUserDto userDto, final User user) {
?????이거 오타 있었나요?
저 그냥 줄 위치만 변경된줄

2023-10-02 05:34 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/user/application/UserService.java
> +    private void updateUserByRequest(final UpdateUserDto userDto, final User user) {
### 칭찬

아 Reqeust였군요... 엄청납니다 
칭찬해요!!!!!!!!!!!!!!!!!!!!!@#!@

2023-10-02 13:39 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/user/application/UserServiceTest.java
> +                          .isEqualTo(새로운_프로필_이미지_dto.uploadName());
해당 부분은 아예 정한 기억이 있는지 싶네요.
일단 정한 기억이 없어 원래의 컨벤션인 120자 초과 시 개행에 따랐습니다.

2023-10-02 13:40 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/user/application/UserService.java
> +    private void updateUserByRequest(final UpdateUserDto userDto, final User user) {
제가 저지른 오타 같습니다...
인텔리제이가 노란줄 띄워줘서 발견 😂
이것이 인텔리제이주도 개발이다..!

2023-10-02 13:40 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/user/application/UserServiceTest.java
> +import org.assertj.core.api.*;
SoftAssertions... 너 나한테 왜그래... 😭

2023-10-02 13:40 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/user/application/fixture/UserServiceFixture.java
> +    JpaUserRepository userRepository;
오 굿 감사합니다!

2023-10-02 14:38 UTC, kwonyj1022 approved these changes
수정 감사합니다 수고하셨어요!!

2023-10-03 03:17 UTC, merged