다크모드 적용
woowacourse-teams/2023-3-ddang pull request #500
Opened 2023-10-01 11:30 UTC by hyemdooly

## 📄 작업 내용 요약
DatePicker, TimePicker를 제외한 모든 뷰에 다크 모드를 적용했습니다.

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드
1. font를 pretendard로 전부 적용했습니다. 이유는 Roboto에는 한글 폰트가 정의되어있지 않기 때문입니다. 그래서 그동안 핸드폰의 기본 폰트로 적용되어왔던 것 같아요!

2. Styles쪽에 많은 변화가 생겼습니다. 앞으로는 Figma에 정의된 TextStyle에 따라 style를 적용해주시면 됩니다.
예시) `style="@style/Header1"`
style과 다른 부분은 또 속성을 지정해주시면 덮어씌우기가 가능합니다.
예시)
`style="@style/Header2"
android:textColor="@color/grey_800"
`

3. 색상을 다시 정의했고, 1:1 매칭이 아닌 경우 별도의 color을 정의했습니다. Figma와 함께 보시면 좋을 것 같아요. 기본적으로 일반과 다크모드의 색상은 이렇게 1:1 매칭이 되는데요.
![image](https://github.com/woowacourse-teams/2023-3-ddang/assets/15646373/ef85e369-bf4d-481d-a5ab-925ffb80da6d)
예를 들어 다크 모드가 아닐 때 Primary 900은 다크모드에서 Primary 50과 색깔이 유사합니다. (다크모드에서는 채도가 좀 더 낮아져야해서 컬러코드가 같지 않습니다!)
하지만 그 동안 그려온 큰 버튼들의 경우 (ex. 입찰하기), 똑같은 빨간색의 색깔이 필요합니다. red_900으로 줘버리면 다크모드에서는 아주아주 옅은 빨간색이 나오기 때문이에요. 
따라서
values/colors.xml : `<color name="primary">@color/red_900</color>`
values-night/colors.xml : ` <color name="primary">@color/red_50</color>`
다음과 같이 primary라는 컬러를 정의하여 다른 색상을 놓고, Button에는 이 primary color를 사용했습니다.

4. DatePicker와 TimePicker에서 다크모드 상태의 Style이 먹여지지 않아 도움을 요청합니다!!😭 집단지성이 필요해요!!

## 📎 Issue 번호

- closed: #466

2023-10-01 17:33 UTC, ippnsj requested changes
일단 DatePicker랑 TimePicker는 parent를 제거하면 다크모드 적용이 잘 되는데 문제는 저희가 원하는 theme의 Picker가 뜨지 않는다는 문제가 있네요ㅠㅠ
[DatePicker Theme 설정 문제 이슈](https://github.com/xamarin/Xamarin.Forms/issues/9033)
이 문제는 좀 더 고민해봐야 할 것 같아요!
일단은 parent를 Theme.Material3.Light.Dialog로 하는건 어떨까요? 🤔
아니면 현재 상태에서 <item name="android:windowBackground">@color/grey_50</item> 이 태그만 추가하면 흰 배경색상으로 인해 글자가 보이지 않는 현상은 해결할 수 있습니다!

2023-10-02 05:40 UTC, hyemdooly commented on android/app/src/main/res/layout/item_select_region_second.xml
> +        android:background="@color/grey_50_to_primary_selected"
다크모드 색깔 타협을 아직 못봐서 일단 이렇게 해두었어요🥲🥲

2023-10-02 06:05 UTC, rhthrhrl0 approved these changes
고생많으셨습니다! 전체적으로 실행해보고, 코드 어떻게 적용하는지 방법을 좀 더 살펴봤습니다. 
전체적으로 색상도 예뻐진 것 같고, 고생 많이 하신 것 같아서 감사합니다! 
리뷰 하나 달았는데, 색상이 의도하셨던 것인지만 궁금했던 거여서 일단 바로 승인하겠습니다. 정말 고생많으셨습니다!

2023-10-02 06:05 UTC, rhthrhrl0 commented on android/app/src/main/res/values/themes.xml
> +        <item name="android:textColorHighlight">@color/red_700</item>
라이트 모드일때 색상이 너무 강해서 시인성이 떨어지는 것 같아요

![image](https://github.com/woowacourse-teams/2023-3-ddang/assets/67176829/c7c423bf-157d-4610-8833-24ec94425a20)

2023-10-02 07:18 UTC, hyemdooly commented on android/app/src/main/res/values/themes.xml
> +        <item name="android:textColorHighlight">@color/red_700</item>
오우 세상에 수정하겠습니다!!!

2023-10-02 13:04 UTC, ippnsj approved these changes
다크모드에서 피커 커스텀 테마 설정하는게 상당히 까다롭던데 성공하셨군요! 대단해요~!! 🥳
타임피커는 스피너로 바뀌니까 확실히 예전보다 편한 것 같아요! 👍
다크모드에서의 색상은 함께 논의해보아요! 🤗

2023-10-02 13:11 UTC, rhthrhrl0 approved these changes
제가 빼먹었던 백그라운드 처리 해주셔서 감사합니다! 정상 동작하는거 확인했습니다.

2023-10-02 14:50 UTC, merged