이미지 관련 테스트 코드 리팩토링
woowacourse-teams/2023-3-ddang pull request #501
Opened 2023-10-01 13:11 UTC by JJ503

## 📄 작업 내용 요약

이미지 관련 테스트 코드 리팩토링

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

## 📎 Issue 번호

- closed #487

2023-10-01 15:01 UTC, swonny approved these changes
깔끔하네요
역시 제이미..

필수로 남겨두긴 했지만 중요한 오타는 아닌 것 같아 어프루브합니다!
고생많으셨어요!!

2023-10-01 15:25 UTC, apptie requested changes
고생하셨습니다

하지만 RC입니다..

2023-10-01 15:25 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/image/infrastructure/local/LocalStoreProfileImageProcessorTest.java
> +import org.assertj.core.api.*;
### 필수

별을 발견해버렸습니다

이상하게 이런것밖에 안보이네요

2023-10-01 17:28 UTC, kwonyj1022 requested changes
테스트명 관련해서 이전에 인텔리제이의 `shift+f6`을 사용했을 때 문제가 있었나보군요. 이번에 같이 수정하면 좋을 것 같아서 rc 남겼습니다.

2023-10-01 17:28 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/image/application/ProfileImageServiceTest.java
>      void 지정한_아이디에_해당하는_이미지를_조회한다() throws Exception {
### 선택
```suggestion
    @Test
    void 지정한_아이디에_해당하는_프로필_이미지를_조회한다() throws Exception {
```

2023-10-01 17:28 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/image/application/ProfileImageServiceTest.java
>      void 지정한_아이디에_해당하는_이미지가_없는_경우_null을_반환한다() throws MalformedURLException {
### 선택
```suggestion
    @Test
    void 지정한_아이디에_해당하는_프로필_이미지가_없는_경우_null을_반환한다() throws MalformedURLException {
```

2023-10-01 17:28 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/image/application/fixture/ProfileImageServiceFixture.java
> +    JpaAuctionImageRepository auctionImageRepository;
### 필수
private으로 변경 부탁드립니다!

2023-10-01 17:28 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/image/infrastructure/local/LocalStoreProfileImageProcessorTest.java
> +class LocalStoreProfileImageProcessorTest extends LocalStoreProfileImageProcessorFixture {
```suggestion
class LocalStoreImageProcessorTest extends LocalStoreImageProcessorFixture {
```

2023-10-01 17:28 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/image/domain/AuctionProfileImageTest.java
> +class AuctionProfileImageTest extends AuctionProfileImageFixture {
```suggestion
class AuctionImageTest extends AuctionImageFixture {
```

2023-10-01 17:28 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/image/presentation/ProfileImageControllerTest.java
> +class ProfileImageControllerTest extends ProfileImageControllerFixture {
```suggestion
class ImageControllerTest extends ImageControllerFixture {
```

2023-10-02 13:43 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/image/application/fixture/ProfileImageServiceFixture.java
> +    protected String 프로필_이미지_파읾명;
허거덩 메리가 남겨준 것도 어디가 달라졌는지 한참 봤네요..!
예리하십니다 🫡

2023-10-02 13:46 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/image/infrastructure/local/LocalStoreProfileImageProcessorTest.java
> +import org.assertj.core.api.*;
애증의 SoftAssertions...

2023-10-02 13:56 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/image/infrastructure/local/LocalStoreProfileImageProcessorTest.java
> +class LocalStoreProfileImageProcessorTest extends LocalStoreProfileImageProcessorFixture {
헉... 지난번에도 얘기해줬던 것 같은데 추가로 더 있었군요...
알아채지 못했는데 고마워요 엔초!

2023-10-02 14:10 UTC, apptie approved these changes
별이 없다면 그걸로 approve입니다...

2023-10-02 14:36 UTC, kwonyj1022 approved these changes
수정 감사합니다 수고하셨어요!!

2023-10-03 03:33 UTC, merged