메시지 서비스 테스트 관련 리팩토링
woowacourse-teams/2023-3-ddang pull request #502
Opened 2023-10-01 13:52 UTC by swonny

## 📄 작업 내용 요약

메시지 서비스 테스트 관련 리팩토링

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- 딱히 없는 것 같습니다.

## 📎 Issue 번호

- closed #498

2023-10-01 15:59 UTC, kwonyj1022 requested changes
완전 필수 수정 사항(`System.out.println()`)이 있어서 rc입니다.

2023-10-01 15:59 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/MessageServiceTest.java
> +        final List<ReadMessageDto> actual = messageService.readAllByLastMessageId(마지막_조회_메시지_아이디가_없는_조회용_메시지_request);
### 선택
`~~메시지_조회용_request`가 좀 더 잘 읽힐 것 같습니다!

2023-10-01 15:59 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/MessageServiceTest.java
> +        final List<ReadMessageDto> actual = messageService.readAllByLastMessageId(두_번째_메시지부터_모든_메시지_조회용_메시지_request);
### 필수
여기 sout 지워주세요

2023-10-02 05:35 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/MessageServiceTest.java
> +        final List<ReadMessageDto> actual = messageService.readAllByLastMessageId(두_번째_메시지부터_모든_메시지_조회용_메시지_request);
앗 이런 치명적인 이슈가...

2023-10-02 05:36 UTC, apptie requested changes
sout이라는 이슈가 있었으므로...용납이 안되는 로그 출력 방식이기 때문에 저도 엔초따라 RC로 하겠습니다

2023-10-02 05:36 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +        if (!userRepository.existsById(request.messageReaderId())) {
### 선택

receiverId가 더 짧은 것 같기는 한데 음...메리의 선택에 맡기겠습니다

2023-10-02 14:13 UTC, JJ503 requested changes
고생 많으셨습니다 메리!
개인적으로 중요하다고 생각하는 질문이 한 가지 있어 일단 rc 해둡니다!

2023-10-02 14:13 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +        if (!userRepository.existsById(request.messageReaderId())) {
### 선택
개인적인 의견으로는 저도 receiver가 조금 더 명확한 것 같습니다..!

2023-10-02 14:13 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/fixture/MessageServiceFixture.java
> +        given(notificationService.send(any(CreateNotificationDto.class))).willReturn(NotificationStatus.SUCCESS);
### 질문 & 필수...?
BidService를 진행할 때 given 절의 경우 테스트에서 직접 //given 절에서 수행하는 것이 더 명확하다는 의견을 들었던 것 같은데 어떻게 생각하시나요?

2023-10-03 08:53 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/MessageServiceTest.java
> +        final List<ReadMessageDto> actual = messageService.readAllByLastMessageId(두_번째_메시지부터_모든_메시지_조회용_메시지_request);
이런 실수를 하다니..

2023-10-03 08:58 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/MessageServiceTest.java
> +        final List<ReadMessageDto> actual = messageService.readAllByLastMessageId(마지막_조회_메시지_아이디가_없는_조회용_메시지_request);
의견 감사합니다.
반영해두었습니다.

2023-10-03 09:06 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +        if (!userRepository.existsById(request.messageReaderId())) {
그런데 여기서 `messageReader`는 메시지 수신자랑은 조금 다른 의미라서 `receiver`로 했을 때 오히려 혼동을 줄 수 있다고 생각했습니다.
여기서 `messageReader`는 메시지 목록을 조회하는 메시지 조회자입니다. 따라서 메시지를 작성한 `writer`가 될 수도 있고 메시지를 수신하는 `receiver`가 될 수도 있습니다. 따라서 `receiver`로 네이밍한다면 오히려 헷갈릴 수도 있을 것 같다고 생각했는데, 이에 대한 지토랑 제이미의 의견이 필요합니다..!

2023-10-03 09:06 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/fixture/MessageServiceFixture.java
> +        given(notificationService.send(any(CreateNotificationDto.class))).willReturn(NotificationStatus.SUCCESS);
흠 그렇게 이야기 했던 게 저도 기억나네요..! 왜 이렇게 했을까요
수정하겠습니다.

2023-10-03 09:21 UTC, kwonyj1022 approved these changes
수고하셨습니다!

2023-10-03 09:34 UTC, apptie approved these changes
네이밍에 대한 이유도 납득이 되고 sout고 사라져서 approve 하겠습니다
고생하셨습니다

2023-10-03 09:34 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +        if (!userRepository.existsById(request.messageReaderId())) {
그런 의미였군요 그렇다면 확실히 receiver는 어울리지 않네요 

왜 messageReader로 네이밍을 지었는지 이제 이해했습니다
음...더 좋은 네이밍은 제 머리로는 떠오르지 않네요 아무튼 그렇습니다 납득했습니다

2023-10-03 10:10 UTC, JJ503 approved these changes
수정 사항 확인했습니다.
고생 많으셨습니다~!

2023-10-03 13:25 UTC, merged