경매 관련 테스트 코드 리펙토링
woowacourse-teams/2023-3-ddang pull request #504
Opened 2023-10-02 12:59 UTC by apptie

## 📄 작업 내용 요약

경매 관련 테스트 코드 리펙토링
## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- `@Nested`의 경우 제가 원한 방식(외부에서 `@BeforeEach`로 초기화 뒤 내부 `@Nested` 클래스에서 단순 변수할당)이 안되서 별도의 `Fixture`로 모두 분리했습니다 
## 📎 Issue 번호

- closed #494

2023-10-02 15:15 UTC, JJ503 requested changes
클래스를 결국 다 분리하시다니... 정말 고생 많으셨습니다... 👍👍👍
그런데 몇 가지 질문과 수정했으면 하는 사항이 있어 일단 rc로 해두었습니다.
확인해주시면 감사하겠습니다!

2023-10-02 15:15 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/fixture/QuerydslAuctionRepositoryImplForListFixture.java
> +    private void bidding(final Auction targetAuction, final User bidder) {
### 칭찬
메서드를 만드니 중복도 줄고 좀 더 보기 편하네요! 👍

2023-10-02 15:24 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
> +        given(imageProcessor.storeImageFiles(any())).willReturn(List.of(경매_이미지_엔티티));
해당 given절은 예외 문제가 아니라 테스트 시 실제 파일이 저장되는 문제로 인해 추가된 given절입니다 
위와 같이 mocking을 진행하지 않으면 실제 파일이 저장되므로 골치아픈 문제가 발생할 수 있습니다 
그러므로 필수라고 생각합니다

2023-10-02 15:26 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
> +        final ReadAuctionDto actual = auctionService.readByAuctionId(채팅방이_있는_경매.getId());
그러네요 수정하도록 하겠습니다

2023-10-02 15:29 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
> +        final ReadAuctionDto actual = auctionService.readByAuctionId(채팅방이_있는_경매.getId());
해당 부분도 수정하도록 하겠습니다

2023-10-02 15:30 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/application/fixture/AuctionServiceFixture.java
> +    AuctionService auctionService;
해당 부분 수정하도록 하겠습니다

2023-10-02 15:30 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/configuration/util/SortParameterTest.java
👍

2023-10-02 15:30 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/domain/AuctionTest.java
> +            softAssertions.assertThat(auction.getAuctionImages()).contains(경매_이미지);
그냥 기존에 존재하던 검증부였기 때문에 삭제할 생각을 하지 못했었습니다
지금 보니 말씀하신대로 제외해도 괜찮아 보이네요 
해당 검증은 삭제하도록 하겠습니다

2023-10-02 15:33 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/AuctionForListSearchByTitleAndSortByClosingTimeTest.java
> +        AuctionForListSearchByTitleAndSortByClosingTimeFixture {
저도 기억이 나지 않습니다 
근데 이건 너무 길어서...그냥 냅두고 싶기는 합니다

2023-10-02 15:33 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/domain/AuctionTest.java
> +        final Bid bid = new Bid(auction, 판매자, 유효한_입찰_금액);
Bid는 생성자에서 Auction이 필수적이며 Auction은 테스트하고자 하는 중요 도메인이므로 불가능하다고 생각합니다
 
Fixture를 만들기 위해서 생각해본 방식은 null을 넣는건데 Bid에서 auction으로 null을 넣는다는 것은 프로덕션 영역의 코드와는 전혀 무관한 코드가 될 것이기도 하고 실제 테스트하는 대상인 auction이 아닌 null이기 때문에 테스트 또한 의미없어질 것이라고 생각합니다

2023-10-02 15:34 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/JpaAuctionRepositoryTest.java
>          auctionRepository.save(expected);
해당 부분은 헷갈렸네요 시간과 관련된 중요한 테스트라고 착각했습니다
Fixture로 분리하도록 하겠습니다

2023-10-02 15:38 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/fixture/QuerydslAuctionRepositoryImplForListFixture.java
> +    private void bidding(final Auction targetAuction, final User bidder) {
👍

2023-10-02 15:38 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
> +                                fieldWithPath("id").type(JsonFieldType.NUMBER).description("경매 ID"),
저는 120줄이 넘는 경우에만 개행으로 인지하고 있었습니다
정말ㄹ로 헷갈리는군요

2023-10-02 15:40 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
> +                                fieldWithPath("id").type(JsonFieldType.NUMBER).description("경매 ID"),
저는 문서화 영역을 별도의 메서드로 분리하면서 컨벤션에 크게 신경 쓰지 않기로 하면서 자동 개행의 기준이 되는 120글자가 넘는 경우에만 120줄이 넘는 경우에만 개행으로 인지하고 있었습니다
정말ㄹ로 헷갈리는군요
일단 냅두겠습니다..

2023-10-03 01:03 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
> +        given(imageProcessor.storeImageFiles(any())).willReturn(List.of(경매_이미지_엔티티));
### 질문
그렇다면 예외 테스트 중 해당 테스트에서만 진행해준 이유는 무엇인가요?

2023-10-03 01:07 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/domain/AuctionTest.java
> +        final Bid bid = new Bid(auction, 판매자, 유효한_입찰_금액);
앗 그렇네요!
급하게 리뷰하느라 해당 부분까지 미처 파악하지 못했습니다.
답변 감사합니다.

2023-10-03 01:09 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
> +                                fieldWithPath("id").type(JsonFieldType.NUMBER).description("경매 ID"),
저도 해당 부분의 결론은 정말 기억이 나지 않아 다른 분들도 괜찮다면 저도 괜찮습니다.

2023-10-03 01:12 UTC, JJ503 approved these changes
답변 및 수정 적용 내용 모두 확인했습니다!
다만, mocking 관련해 추가적인 질문이 있어 해당 부분 확인해주시면 감사하겠습니다!

2023-10-03 03:00 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
> +        given(imageProcessor.storeImageFiles(any())).willReturn(List.of(경매_이미지_엔티티));
말씀해주신거 다시 로직 확인해보니까 맞네요 
해당 예외 케이스는 저장까지 가는 줄 알았습니다..
수정하겠습니다 감사합니다

2023-10-03 03:06 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
> +                                fieldWithPath("id").type(JsonFieldType.NUMBER).description("경매 ID"),
그와중에 정신이 없어서 120글자가 넘는 경우에만이 두번 들어갔네요

2023-10-03 03:34 UTC, swonny approved these changes
양이 엄청나네요..
고생 많으셨습니다 지토..
간단한 질문 위주로 남겨서 approve하겠습니다.

2023-10-03 03:34 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/AuctionForListSearchByTitleAndSortByClosingTimeTest.java
> +        AuctionForListSearchByTitleAndSortByClosingTimeFixture {
저도 개행 하지 않는걸로 기억하고 있긴 합니다.

2023-10-03 03:34 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/AuctionForListSearchByTitleAndSortByClosingTimeTest.java
> +                PageRequest.of(0, 페이지_크기, 마감_임박순_정렬),
### 질문

페이지 크기는 항상 고정된 값으로 요청이 들어오는건지 궁금합니다.
저희가 경매 이미지 테스트 시에 하나의 이미지만 넣어 테스트해서 이미지가 두 개 이상인 경우 발생하는 문제를 눈치 못 챘던 것처럼 페이지가 3이 아닌 다른 값으로 요청이 들어온 경우에 대한 테스트도 있어야 하지 않나 하는 생각이 들어 질문 남깁니다!

2023-10-03 03:34 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/AuctionForListSearchByTitleAndSortByReliabilityTest.java
> +                PageRequest.of(0, 3, 신뢰도순_정렬),
### 질문

여기에서는 `페이지_크기`를 사용하지 않으신 이유가 궁금합니다.

2023-10-03 03:34 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/AuctionForListSortByReliabilityTest.java
> +                PageRequest.of(0, 3, 신뢰도순_정렬),
### 질문

여기에도 `페이지_크기` 대신 3이 잘못 들어간걸까요??

2023-10-03 03:34 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImplForObjectTest.java
> +
### 칭찬

개행으로 구분해주셔서 보기 편하네요! 👍🏻

2023-10-03 03:38 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/AuctionForListSearchByTitleAndSortByClosingTimeTest.java
> +        AuctionForListSearchByTitleAndSortByClosingTimeFixture {
그렇다면 일단 개행을 지우도록 하겠습니다

2023-10-03 03:45 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/AuctionForListSearchByTitleAndSortByReliabilityTest.java
> +                PageRequest.of(0, 3, 신뢰도순_정렬),
그것은 까먹었기 때문입니다 수정하도록 하겠습니다

2023-10-03 03:55 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/AuctionForListSearchByTitleAndSortByClosingTimeTest.java
> +                PageRequest.of(0, 페이지_크기, 마감_임박순_정렬),
항상 고정된 값은 아니지만 그게 중요한 내용은 아니라고 생각합니다

이미지의 경우 이미지가 10개든 2개든 결과가 증가할 것이기 때문에 이미지의 경우 하나와 둘 이상인 경우의 동작이 다르다고 기억하고 있습니다
그것처럼 현재 페이지네이션 테스트의 초점은 크기보다는 별도의 정렬이나 검색과 같은 조건이 있을 때, 동일한 결과를 가진 경매들이 정확히 페이징 처리가 되는지 유무와 다음 페이지가 존재하는지 유무를 체크하는게 중점이라고 생각합니다

```
신뢰도 4, id 7
신뢰도 4, id 6 
신뢰도 4, id 5 
신뢰도 4, id 4
신뢰도 4, id 3
신뢰도 5, id 2 
```

이러한 경매 목록이 있을 때 페이지 크기가 2, 3, 4인 것과 상관 없이 동일한 신뢰도 기반의 목록에서 그 다음 정렬 순위인 id로 정상적으로 페이징 처리가 되었는지, 다음 페이지가 존재하는지 유무를 체크해야 한다고 생각합니다
그러므로 페이징 크기는 큰 상관이 없다고 생각하고 테스트 케이스와 Fixture만 신경 쓰면 된다고 생각합니다

2023-10-03 03:55 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/AuctionForListSortByReliabilityTest.java
> +                PageRequest.of(0, 3, 신뢰도순_정렬),
그렇습니다 여기도 까먹었습니다 감사합니다

2023-10-03 03:57 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImplForObjectTest.java
> +
👍

2023-10-03 07:14 UTC, kwonyj1022 requested changes
필수 수정 사항과 질문이 있어서 rc 남겼습니다.
리뷰하다 지쳐서 repository쪽은 자세히 보지 못했습니다. 지토가 리뷰에 답변 및 적용해주시는 동안 다시 보겠습니다.

2023-10-03 07:22 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/domain/AuctionTest.java
> +class AuctionTest extends AuctionFixture {
그러네요 테스트에서는 안쓰는데 설정이 남아있었네요 제거하도록 하겠습니다

2023-10-03 07:24 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/application/fixture/AuctionServiceFixture.java
> +    );
Fixture는 네이밍과 값을 제외하고는 개인 재량으로 하기로 했던 것 아니었나요?

2023-10-03 07:30 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
>      StoreImageProcessor imageProcessor;
해당 내용 삭제하면서 테스트 케이스도 일부 수정했습니다

2023-10-03 07:31 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
> +        given(imageProcessor.storeImageFiles(any())).willReturn(List.of(경매_이미지_엔티티));
조회에도 붙여버렸군요 삭제하도록 하겠습니다

2023-10-03 07:31 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
> +        given(imageProcessor.storeImageFiles(any())).willReturn(List.of(경매_이미지_엔티티));
다른 조회 케이스에서도 삭제하도록 하겠습니다

2023-10-03 07:38 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
>          });
적절한 값으로 변경하도록 하겠습니다

2023-10-03 07:39 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
> +        given(imageProcessor.storeImageFiles(any())).willReturn(List.of(경매_이미지_엔티티));
제거하도록 하겠습니다

2023-10-03 07:48 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
> +        final ReadAuctionDto actual = auctionService.readByAuctionId(채팅방이_없는_경매.getId());
적용하도록 하겠습니다

2023-10-03 07:49 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
>              softAssertions.assertThat(actual.auctioneerCount()).isEqualTo(0);
이 부분도 위에랑 동일하게 변경했습니다

2023-10-03 07:50 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
> +        given(imageProcessor.storeImageFiles(any())).willReturn(List.of(경매_이미지_엔티티));
위에랑 동일한 이유로 삭제했습니다

2023-10-03 07:52 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
> +        final ResultActions resultAuctions = mockMvc.perform(multipart("/auctions")
네 get에서 PathVariable을 사용하지 않는 이상 Rest Docs의 Builder를 사용하는것이 필수는 아닙니다

2023-10-03 07:56 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/application/fixture/AuctionServiceFixture.java
> +        종료후_채팅방이_없는_경매 = 유효한_경매_생성_dto.toEntity(판매자, 가구_서브_의자_카테고리);
저는 toEntity는 Service 로직의 일부라고 생각하지 않습니다

toEntity는 DTO를 도메인 엔티티로 변환해주는 로직일 뿐이므로 이는 특정 도메인 엔티티를 Repository에게 저장 로직을 호출하거나 변경하거나 아무튼 기타 등등을 수행하는 Service와는 가깝지 않다고 생각합니다

그렇기 때문에 DTO에 toEntity()를 넣었다고 생각합니다 
만약 toEntity()가 Service 관련 로직이라면 처음부터 DTO가 아니라 Service에 위치시켰을 것 같습니다 

그러므로 이를 Service 테스트 시 사용하는 것은 괜찮다고 생각합니다 
또한 Service 테스트에서 create() 메서드를 테스트하면서 간접적으로 toEntity를 테스트했기 때문에 잘못되었다고 생각하지 않습니다

2023-10-03 08:01 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
> +                       .file(유효하지_않은_카테고리_경매_등록_request_multipartFile)
적용하도록 하겠습니다

2023-10-03 08:01 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
>          // given
그러네요 왜 날라갔는지는 모르겠지만 적용하도록 하겠습니다

2023-10-03 08:03 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
> +                         );
어떤 부분에서 빠졌는지 알려주실 수 있나요?

2023-10-03 08:10 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/application/fixture/AuctionServiceFixture.java
> +    );
필드에서 객체할당 하는 것은 한 번만 이루어지지만 setup은 매 테스트 실행시마다 실행되기 때문에 객체 상태가 원하지 않게 변할 수도 있다는 생각에 리뷰를 달았는데 그런 상황은 걱정하지 않아도 되는 것일까요? 구체적인 예시 상황은 생각나지 않지만 테스트 격리가 제대로 되지 않을까 걱정이 되었습니다.

2023-10-03 08:16 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
> +                         );
jsonPath에서 검증해야하는 필드 중 일부가 누락되었다는 것이었습니다.
`auction.images`, `auction.category.main`, `auction.category.sub`, `auction.lastBidPrice`, `auction.status`, `auction.directRegions 관련` `seller.id`, `seller.image`, `seller.nickname`, `seller.reliability`, `chat.id`, `chat.isChatParticipant`, `isOwner` 등의 필드가 누락되었습니다.

2023-10-03 08:19 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
> +                         );
제가 설명을 덜 적었었네요 

auction은 제가 아는 부분이라서 제가 추가할 수 있는데 chat 관련 필드는 제가 전혀 모르는 파트라서 이 부분만 알려주시면 될 것 같습니다 

근데 일단 제가 혼자서 한 번 해보겠습니다

2023-10-03 08:21 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/application/fixture/AuctionServiceFixture.java
> +    );
테스트 격리는 `@IsolateDatabase`로 이루어져서 테스트 격리가 제대로 되지 않을 가능성은 없을 것 같습니다 
또한 현재 필드에서는 영속화 계층에서 다뤄지는 필드 값들(id, createTime 등등)이 전혀 언급되어 있지 않기 때문에 영향이 없다고 생각합니다

2023-10-03 08:39 UTC, kwonyj1022 approved these changes
레포지토리 쪽 리뷰 추가했습니다.
또한 이전 리뷰 사항에 대한 적용도 확인했으므로 approve 하도록 하겠습니다.
다만 선택 사항과 질문에 대한 답변이 궁금하기 때문에 머지 전에 멘션 한 번 부탁드립니다!

2023-10-03 08:39 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/AuctionForListByBidderIdTest.java
> +        void 첫번째_페이지_요청_테스트() {
### 선택
테스트 코드만 봤을 때는 총 몇개의 경매에 참여했는지, 한 페이지 당 페이지 크기는 몇인지 알 수 없어서 테스트 코드를 보면서 페이지 크기는 3이구나, 총 7개이구나 라는 것을 파악해야 했습니다.
하지만 이는 테스트에 대한 이해 뿐만 아니라 픽스처에 대한 이해를 같이 해야 하기 때문에 적절하지 않은 것 같습니다.

`참여한 경매가 7개인 사용자 테스트` `페이지 크기 3으로 첫 번째 페이지 요청 테스트` 와 같이 테스트 이름을 변경해주면 좋을 것 같습니다!

2023-10-03 08:39 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/AuctionForListByBidderIdTest.java
> +@Import({JpaConfiguration.class, QuerydslConfiguration.class})
### 선택
별 건 아니지만 여기 auction의 infrastructure 패키지에 있는 테스트 클래스 전체적으로 `@Import`를 `@DataJpaTest` 밑으로 이동시켜 주었으면 좋겠습니다.

2023-10-03 08:39 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImplForObjectTest.java
> +        });
### 칭찬
변수로 한 번 빼주어서 더 알아보기 편해졌네요 👍

2023-10-03 09:04 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/AuctionForListByBidderIdTest.java
> +        void 첫번째_페이지_요청_테스트() {
적용하겠습니다
추가로 Fixture에서 페이지_크기도 페이지_크기_3으로 변경해야겠네요

2023-10-03 09:10 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/AuctionForListByBidderIdTest.java
> +@Import({JpaConfiguration.class, QuerydslConfiguration.class})
적용하도록 하겠습니다

2023-10-03 09:10 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImplForObjectTest.java
> +        });
👍

2023-10-03 09:19 UTC, kwonyj1022 approved these changes
수고하셨습니다! 리뷰 반영할 게 많았는데 잘 반영해 주셨네요 짱

2023-10-03 09:23 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/application/fixture/AuctionServiceFixture.java
> +    );
답변 감사합니다!

2023-10-03 09:40 UTC, merged