유저 상호 평가 api 추가
woowacourse-teams/2023-3-ddang pull request #515
Opened 2023-10-03 08:05 UTC by kwonyj1022

## 📄 작업 내용 요약

유저 상호 평가 api 추가
## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- 신뢰도 갱신의 경우 일단은 평가 대상 사용자가 받은 모든 평가 목록을 가져와서 매번 평균을 계산하는 식으로 구현했습니다. 고도화 pr에서 리팩토링 예정입니다.
- Review 엔티티 연관관계와 cascade 설정 등등 확인 부탁드립니다. 자신이 없네요..
- flyway 스크립트에 실수가 없는지 확인 부탁드립니다. 아마 없을 것 같긴 한데 음..
- flyway에서 score 부분을 현재 float 타입으로 해놓았는데요, 어떤 타입이 좋을까요? 오차 조금 난다고 큰 문제가 발생하는 데이터가 아니다 보니 고민이 됩니다.
- controller 부분 api uri 적절한지 의견 부탁드립니다. 현재  특정 경매에 특정 사용자가 작성한 평가 가져오는 것은 `/reviews?auctionId={auctionId}`입니다. 이때 지정한 유저가 받은 모든 평가 목록을 가져오는 것을
    - /reviews?userId={userId}
    - pr에 올라온 것처럼 (`/reviews/users/{userId}`)
    - 이 둘 중에 고민입니다. 전자의 경우 각자 다른 쿼리파라미터를 받는 컨트롤러 메서드를 2개 만들 수 없어서 하나의 컨트롤러 메서드에 분기처리를 해야 합니다.
## 📎 Issue 번호

- closed #294

2023-10-03 10:11 UTC, apptie requested changes
고생하셨습니다

`Review 엔티티 연관관계와 cascade 설정 등등 확인 부탁드립니다.`
-> 연관관계는 잘 된 것 같고 cascade는 설정이 없던 것 같습니다

`flyway 스크립트에 실수가 없는지 확인 부탁드립니다.`
-> Review 테이블과 외래 키 설정이 없는 H2에서 테스트해본 결과 정상적으로 잘 되기는 했습니다만 역시 DB서버에서는 어케될지 좀 무섭기는 하네요 

`flyway에서 score 부분을 현재 float 타입으로 해놓았는데요`
-> float 괜찮을 것 같습니다 float이나 double이나 그게 그거일 것 같고 부정확하다고 해도 사용자는 알 방도가 없으니까 괜찮지 않을까요?

`controller 부분 api uri`
-> 저는 PR에 올라온 버전이 후보군보다 좋은 것 같습니다

2023-10-03 10:11 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/review/infrastructure/persistence/JpaReviewRepository.java
> +           """)
### 질문 & 선택

`@Query`의 내부가 결국에는 `JPQL`이기도 하고, `@Query` 내부에서 이미 `JOIN FETCH`를 쓰고 있어서 `@EntityGraph`를 생략해도 될 것처럼 보입니다

일단 `@EntityGraph`를 주석처리하고 테스트를 실행시켜보니 테스트가 모두 통과하기는 했는데, 특별한 이유가 있을 수 있으니 이 부분 확인해주시면 감사하겠습니다

2023-10-03 10:11 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/user/domain/User.java
> +                                  .orElseGet(null);
### 선택

```suggestion
    public void updateReliability(final List<Review> reviews) {
        if (reviews.isEmpty()) {
            this.reliability = 0.0d;

            return;
        }

        this.reliability = reviews.stream()
                                  .mapToDouble(Review::getScore)
                                  .average()
                                  .orElse(0.0d);
```

Double이라서 null도 가능하겠지만 숫자형 타입의 Wrapper인 만큼 0의 초기값을 넣어주는 편이 더 자연스러울 것 같습니다

2023-10-03 10:11 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/configuration/CommonControllerSliceTest.java
> +    protected ReviewService reviewService;
### 칭찬

칭찬해요!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!@###########@!!#!@#!#

컨트롤러 설정 묶어놓은 곳에 잘 적용해주셨네요

2023-10-03 10:11 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/review/presentation/ReviewController.java
> +                             .build();
### 필수

해당 Location인 `/reviews/{reviewId}`에 대한 api가 없는 것 같아서 이 부분을 수정해주셨으면 좋겠습니다
근데 자기 자신이 작성한 리뷰 리스트를 조회하는 기능이 있었나요? 기억이 잘 안나네요 
자신이 작성한 리뷰를 못본다면 이 Location도 비우거나 /auctions로 보내버리는 등의 처리가 필요할 것 같습니다

2023-10-03 12:49 UTC, JJ503 requested changes
엔초 고생 많으셨습니다!
대부분 질문이긴 한데, 일단 rc로 처리해두도록 하겠습니다.

`Review 엔티티 연관관계와 cascade 설정 등등 확인 부탁드립니다.`
-> 저도 cascade는 설정은 보이지 않고 필요하지도 않을 것 같네요!

`flyway 스크립트에 실수가 없는지 확인 부탁드립니다.`
-> flyway가 존재하는 pr은 캠퍼스에 출근 후 머지하고 싶은데 어떻게 생각하시나요? 터졌을 때를 상상하고 싶지 않아서요... 🥲

`flyway에서 score 부분을 현재 float 타입으로 해놓았는데요`
-> 저도 float 괜찮을 것 같습니다. double을 할 정도로 소수점 자리를 길게 두지도 않고 그럴 필요도 없을 것 같아서요!

`/reviews?userId={userId}` vs `/reviews/users/{userId}`
-> 저도 후자가 더 좋습니다.

2023-10-03 13:11 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/user/domain/User.java
> +                                  .orElseGet(null);
넵 저도 평가가 없는 경우와 0점인 부분을 구분하고자 null을 넣어주었습니다.
또한 회원 가입에서 유저 엔티티 생성 시 신뢰도를 null로 넣도록 변경해야 한다고 생각하는데 이 부분은 또 다른 이슈로 가져가야 하지 않을까 해서 그 부분은 변경하지 않았습니다.

2023-10-03 13:25 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/review/presentation/ReviewController.java
> +                             .build();
자신이 작성한 리뷰 '리스트'를 조회하는 기능은 없습니다.
제이미 말씀대로 리뷰 작성 후에는 자신이 작성한 그 리뷰가 보이게 됩니다.

create 부분을 `/reviews?auctionId={auctiond}`를 추가하는 것으로 해결하는 것은 어떤지 묻고 싶습니다.

2023-10-03 13:27 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/review/presentation/ReviewController.java
> +    public ResponseEntity<List<ReadReviewResponse>> readAllReviewsOfTargetUser(@PathVariable final Long userId) {
그냥 있으면 좋겠다~ 하고만 이야기했는데 방학때 만들어두었어서 그냥 같이 올렸습니다.

2023-10-03 13:38 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/review/application/ReviewServiceTest.java
> +        final double expect = (previousScore1 + previousScore2 + newScore) / 3;
컨벤션 정해지기 전에 만들어놓고 수정을 안했네요ㅠ 감사합니다 제이미!

2023-10-03 13:45 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/review/application/ReviewServiceTest.java
> +        final CreateReviewDto createReviewDto =
컨벤션 정해지기 전에 만들어놓고 수정을 안했네요ㅠ 감사합니다 제이미!

2023-10-03 14:01 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/review/infrastructure/persistence/JpaReviewRepository.java
> +           """)
n+1 제거할 때 둘 다 실험해보고 싶어서 써놨다가 entity graph 부분을 안지웠네요.. 리뷰 감사합니다!

2023-10-03 14:18 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/user/domain/User.java
> +                                  .orElseGet(null);
확인했습니다 답변 감사합니다 제가 헛소리를 했던것으로...

2023-10-03 14:38 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/review/presentation/ReviewController.java
> +                             .build();
`/reviews/{reviewId}` api는 현재 없어서 추가하기 귀찮았었습니다. (테스트 및 문서화 추가 때문에..ㅎㅎ)
rest api 관점에서(?) 문제가 되는지 아닌지 모르겠지만 문제가 되지 않는다면 이미 있는 url(`/reviews?auctionId={auctiond}`)을 사용하는 것은 어떤가 했습니다.

2023-10-03 14:44 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/review/presentation/ReviewController.java
> +                             .build();
`/reviews?auctionId={auctionId}`의 경우 특정 `auctionId`에 해당하는 모든 리뷰를 보여줄것처럼 생겨서 판매자와 구매자의 리뷰 모두를 볼 수 있을 것 처럼 생겨서 그랬습니다 
그게 아닌가요? 굉장히 헷갈리는군요

2023-10-03 14:52 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/review/presentation/ReviewController.java
> +                             .build();
아니군요 userId랑 auctionId랑 받아서 처리하는군요...

### 선택 

저라면 이걸 user의 presentation 하위에 UserReviewController 같은걸 새로 만들어서 
`/users/auctions/{auctionId}/reviews/{reviewId}`로 처리할 것 같습니다 
혹은 `/users/reviews/{reviewId}/auctions/{auctionId}` 이렇게 처리할 것 같습니다 

하지만 이건 선택사항으로 두겠습니다..

2023-10-04 04:41 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/review/presentation/ReviewController.java
> +                             .build();
`/reviews/{reviewId}` 부분은 그다지 큰 작업이 아닐 것 같기도 하고, 귀찮다고 안하기도 그렇고.. 해서 그냥 추가했습니다.
특정 사용자가 특정 경매 거래 후에 상대방에게 작성한 평가 조회(현재 `/reviews?auctionId={autionId}` 이 부분은 일단 api 명세로는 이걸로 하기로 했는데 말씀드리고 바꿀지 이대로 갈지 고민이 되긴 하네요ㅠ 백엔드 데일리에서 이야기해보도록 하고 일단은 그대로 두었습니다.

2023-10-04 04:58 UTC, swonny requested changes
고생하셨습니다 엔초!!
API 관련 질문 몇 가지 남겨서 rc를 드립니다..!
잘 구현해주신 것 같아서 질문 답변만 확인하면 approve하겠습니다.

2023-10-04 04:58 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/user/domain/User.java
> +            this.reliability = null;
### 선택

null이 반드시 들어가야 하는 로직이었군요.
그러면 `reliability`는 VO를 생성하여 VO에서 존재하지 않는 값에 대해 처리해주는 것은 어떤가요??
null을 그대로 넣어두는 것보다 더 안전하지 않을까 싶어 건의드려봅니다!

2023-10-04 04:58 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/user/domain/UserTest.java
> +        assertThat(평가_대상.getReliability()).isNull();
### 선택

만약 reliability에 VO를 적용한다면 VO에서 null인 경우를 판단하여 boolean을 반환하는 메서드를 만들고, user엔티티에서 `평가대상.isInitialReliability()`와 같은 메서드를 통해 신뢰도가 생성되기 전인지를 판단하는 정도로 생각해봤습니다!

2023-10-04 04:58 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/review/application/ReviewService.java
> +    private Review saveReviewAndUpdateReliability(final Review review, final User target) {
### 칭찬

오!! 이 부분 선택사항으로 메서드 분리를 요청하려고 했었는데 이미 해주셨네요
역시 엔초

2023-10-04 04:58 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/review/presentation/ReviewController.java
> +        final ReadReviewDetailDto readReviewDetailDto = reviewService.read(userInfo.userId(), auctionId);
### 질문

해당 API는 리뷰를 작성한 뒤, 리뷰를 작성한 사용자가 받아보게 될 리뷰 디테일 페이지가 맞을까요?

지토가 남겨주신 것처럼 `/users/reviews/{reviewId}/auctions/{auctionId}`이런 방식이 자연스러울 것 같습니다. 특히 userInfo에서 가져온 사용자 아이디로 조회하고 있고, 해당 아이디를 받는 파라미터명은 `writerId`라는 점에서 이해하는 데 직관적이지 않은 것 같다는 의견입니다!

그리고 메서드명도 `readDetailReviewByWriter`과 같이 조회자가 작성한 글에 대한 상세조회라는 점이 드러나면 더 좋을 것 같아요!

---

### 선택 

추가적으로 현재는 해당 API가 리뷰 생성 후 리다이렉트 url로만 사용되고 있는데, 실제 로직을 보면 특정 사용자가 작성한 리뷰를 조회하고 있어 나중에 조금 혼동이 올 수도 있을 것 같다고 생각했습니다. 
지정한 리뷰 작성자의 리뷰를 조회하는 API로 사용된다면 userInfo에서 가져온 id보다는  writer의 id를 전달 받아 조회하는 것이 조금 더 자연스럽다고 생각했는데, 엔초의 의견도 궁금합니다!

2023-10-04 06:54 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/review/domain/Review.java
> +@EqualsAndHashCode(of = "id", callSuper = false)
이 부분은 명시를 하는게 좋을 것 같습니다 자꾸 빌드할때마다 gradle이 경고 띄워서 살짝 느려지더라고요..

2023-10-04 08:03 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/review/domain/Review.java
> +@EqualsAndHashCode(of = "id", callSuper = false)
네 저번에 붙이기로 했어서 붙였습니다. 아마 이전 엔티티들은 따로 리팩토링을 진행하지 않아서 명시가 안되어있는 것 같아요.

2023-10-04 08:05 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/review/domain/Review.java
> +    private Double score;
음 score도 따지고 보면 0.5 단위라는 정책이 존재하니까 VO를 만들면 좋겠네요. 그런데 이게 부동소수점이라 정확히 비교할 수 있을지 몰겠어요.

2023-10-04 15:46 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/user/domain/UserTest.java
> +        assertThat(평가_대상.getReliability()).isNull();
`isInitialReliability()` 라는 메서드가 서비스 로직에서 어디에 사용될지 모르겠습니다.
response 같은 경우 reliability는 숫자(Double) 형태로 반환하기 때문에 서버에서 `-` 등의 숫자가 아닌 값을 반환할 수 없는 상태입니다. 따라서 초기 값이라는 의미로 null을 보내줄 수밖에 없습니다.
따라서 `isInitialReliability()` 라는 메서드를 만들더라도 response에는 아래와 같은 방식으로 처리해서 응답을 하게 될 것 같은데,
```java
if(user.isInitialReliability()) {
    reiliability = null
}
reliability = user.getReliability();
```
현재 구조보다 더 나은지는 잘 모르겠어서요.

혹시 제가 생각하는 isInitialReliability()의 사용처와 메리가 생각하는 사용처가 다르다면 예시 부탁드립니다.

2023-10-04 15:58 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/review/presentation/ReviewController.java
> +        final ReadReviewDetailDto readReviewDetailDto = reviewService.read(userInfo.userId(), auctionId);
백엔드 회의 결과 결정된 URI는 `/auctions/{auctionId}/reviews` + `헤더에 작성자 정보`입니다

선택 리뷰로 작성해주신 writer의 id를 전달 받아 조회하는 것에 대해서는 request dto 와 쿼리 파라미터를 사용하는 것 중 어느 방법을 말씀하시는지 애매해서 두 부분 다 말씀드리겠습니다.

우선 request dto로 받아오는 것에 대해서는, get 요청이기 때문에 request dto로 writerId를 받아오는 것은 어색하다고 생각합니다.

쿼리 파라미터로 받아오는 방법에 대해서는, 제가 pr에서 말은 '특정 사용자가 작성한'이라고 하였지만 실제로는 요청을 한 사용자 '자신이 작성한'에 해당하기 때문에 userInfo를 통해 받아오는 것으로 결정했습니다. userInfo에서 나타내는 사용자가 곧 writer이기 때문에 굳이 중복으로 가져와야할 필요가 있을까 하는 생각이 들어서 writerId를 쿼리파라미터로 받지 않아도 된다고 생각을 했었습니다.

다만 이 부분에 대해 혼동의 여지가 있었다면 이 부분은 내일 백엔드 데일리 회의에서 다른 분들의 의견도 함께 듣고 결정하면 좋을 것 같습니다.

2023-10-04 16:19 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/review/presentation/ReviewController.java
> +        final ReadReviewDetailDto readReviewDetailDto = reviewService.read(userInfo.userId(), auctionId);
해당 리뷰는 데일리 전에 작성한 리뷰입니다.. 지우거나 수정했어햐했는데 까먹었어요 죄송합니다 🥲

2023-10-05 04:31 UTC, apptie approved these changes
리뷰 적용한 부분 확인했습니다
이와 관련해서 회의를 또 해야할 게 생각났는데 (`null` 허용 여부나 `@Builder` 사용 시 검증 방식 등등) 지금은 이대로 진행해도 충분할 것 같아 Approve를 하도록 하겠습니다

2023-10-05 04:37 UTC, swonny requested changes
빠른 적용 감사합니다!
다른 부분은 모두 확인했습니다!
값객체 관련한 부분 질문이 있어 엔초의 의견이 궁금해 다시 rc를..드립니다..

2023-10-05 04:37 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/user/domain/fixture/UserFixture.java
> +
### 필수

개행이 두 번 들어갔습니다.

2023-10-05 04:37 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/user/domain/User.java
> +
### 선택

저는 해당 로직이 `Reliability`로 갈 수 있을 것이라고 생각했습니다.
Reliability 생성자에서 진행해주면 어떨까요?

2023-10-05 05:44 UTC, JJ503 approved these changes
엔초 고생 많으셨습니다!
수정하기로 한 부분들에 대해 수정한 것을 확인해 approve합니다!

2023-10-05 08:36 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/user/domain/User.java
> +
해당 부분은 아래와 같은 코드로 User를 작성하게 됐을 경우에 대한 처리입니다.
```java
final User user = User.builder()
                      .name("kakao12345")
                      .profileImage(new ProfileImage("uplad.png", "store.png"))
                      .reliability(null)
                      .oauthId("12345")
                      .build();
```
정상적으로라면 reliability()안에 new를 통해 Reliability를 생성해서 넣어주어야 하지만, 그렇게 작성하지 않았을 때도 의도한 대로로(Reliability가 null이 아니라 Reliability의 value가 null이 되도록) 동작하게 하기 위한 코드입니다. 그래서 해당 코드는 Reliability로 옮길 수 없을 것 같습니다.

2023-10-05 08:49 UTC, swonny approved these changes
고생하셨습니다 엔초!!!

2023-10-05 08:49 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/user/domain/User.java
> +
오.. 그런 것이었군요 제가 이해를 잘못했네요 죄송합니다 😭
이해했습니다!

2023-10-06 04:25 UTC, merged