메시지 전송, 상위 입찰 생성과 알림 전송 이벤트 분리
woowacourse-teams/2023-3-ddang pull request #525
Opened 2023-10-03 17:06 UTC by swonny

## 📄 작업 내용 요약

메시지 전송, 상위 입찰 생성과 알림 전송 이벤트 분리

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

- 입찰에서도 메시지 전송과 동일한 알림 서비스를 사용하고 있다보니 입찰 생성까지 이벤트로 만들게 되었습니다.
- 생각보다(엄청 겁먹었었던 것보다..) 어려운 내용은 없었고, 예상했던 것처럼 테스트쪽에서 막혀서 시간이 걸린 것 같습니다.
    - 이벤트 리스너로 등록된 경우에는 jacocoTestCoverage가 안 먹히는 것 같았습니다. 원인은 아직 명확하게 파악은 못 했는데, 피움이랑 이돈이면팀 코드 참고해서 이벤트 리스너 클래스를 분리하면서 자연스럽게 해결되었습니다.

### 패키지 구조

- 아래에 패키지를 나눈 기준과 간단한 설명 작성한 것 참고해주시면 코드 이해하는 데 큰 어려움은 없을 것 같습니다.

- 이벤트 퍼블리셔(`ApplicationEventPublisher`) : 이벤트를 발행하는 객체입니다. 현재는 `MessageService.create()` 메서드와 `BidService.create()`메서드에서 호출되고 있습니다.

- 이벤트 클래스(`MessageNotificationEvent`, `BidNotificationEvent`) : 이벤트가 발행되었을 때 이벤트 리스너에게 전달할 객체입니다. 이벤트가 publish될 때 전달되어야 하는 객체를 가지고 있습니다. 이벤트가 publish되는 위치(`MessageService`와 `BidService`)와 동일한 위치에 `event` 패키지를 생성한 뒤 `event` 패키지 하위에 두었습니다. 

- 이벤트 리스너 클래스(`NotificationEventListener`) : 이벤트가 발행되면 메서드를 실행시키는 역할을 하는 클래스입니다. 알림 이벤트 리스너 클래스(`NotificationEventListener`)는 `FcmNotificationService`를 호출하므로 `FcmNotificationService`가 포함된 패키지와 동일한 위치에 생성했습니다.

## 📎 Issue 번호

- closed #503

2023-10-04 04:16 UTC, apptie requested changes
고생하셨습니다

여담으로 jacoco는 계속 찾아봤는데 그런 내용이 안보이더라고요..
그래서 슬랙 이모지로 표현만..했습니다...왜 그런지 전혀 모르겠네요

아무튼 Bid 관련 이벤트리스너에서 꼭 답변을 듣고 싶은 내용이 있어 필수로 두고 RC로 하도록 하겠습니다

2023-10-04 04:16 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java
> +    private final ApplicationEventPublisher eventPublisher;
### 선택 

어떤 `eventPublisher`인지 표현해보시는건 어떨까요?
`notificationPublisher`? `notificationEventPublisher`?

2023-10-04 04:16 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +    private final ApplicationEventPublisher eventPublisher;
### 선택

동일한 `EventPublisher`이지만 각 서비스에서 하는 역할이 다르니 이것도 특정지을 수 있을 것 같아요

`messageEventPublisher`나 뭐 그런걸로?

2023-10-04 04:16 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
> +    private static final String BID_NOTIFICATION_MESSAGE_FORMAT = "상위 입찰자가 나타났습니다. 구매를 원하신다면 더 높은 가격을 제시해 주세요.";
### 선택

여담이지만 이런 메세지도 모두 분리했으면 좋겠네요 MessageSource 써서..
그냥 생각나서 까먹기 전에 쓴거고 무시하셔도 좋습니다

2023-10-04 04:16 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
> +    public void sendMessageNotification(final MessageNotificationEvent messageNotificationEvent) {
### 칭찬

칭찬해요!!!!!!!!!!!!!!!!!!!!!!!
이벤트 잘 써주셨네요

2023-10-04 04:16 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
> +    public void sendBidNotification(final BidNotificationEvent bidNotificationEvent) {
### 질문 & 필수 

해당 이벤트리스너 메서드는 `Bid`의 내용이 DB에 저장된 이후에 동작해야 할 것 같은데, 이에 대해서 고려했는지 궁금합니다! 

위에 쪽지같은 경우는 그냥 씹혔나보다 싶은 느낌으로 가볍게 넘길 수도 있겠지만, 해당 `Bid`는 입찰이라는 중요한 도메인이기 때문에 꼭 확인하고 싶어서 필수로 두었습니다

2023-10-04 11:54 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java
> +    private final ApplicationEventPublisher eventPublisher;
직관적이어서 좋네요!
그런데 해당 `eventPublisher`가 현재는 알림에만 사용되긴 하지만 추후에 새로운 이벤트가 추가되었을 때에도 동일한 `ApplicationEventPublisher`를 사용할텐데 `notification`이라는 네이밍이 적절한지는 잘 모르겠습니다 허허..
하지만 지금으로서는 말씀해주신 부분이 더 명확한 것 같아 반영해두었습니다.

2023-10-04 18:25 UTC, kwonyj1022 requested changes
제가 생각했던 부분과 다른 부분에 대한 질문을 남겼습니다. 답변을 꼭 보고 싶어서 rc를 하였습니다.

2023-10-04 18:25 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
> +    }
제가 생각했던 이벤트 분리 코드는 아래와 같았습니다.
```java
@Component
@RequiredArgsConstructor
public class NotificationEventListener {

    private final NotificationService notificationService;

    @EventListener
    public void send(final NotificationEvent notificationEvent) {
        final CreateNotificationDto createNotificationDto = notificationEvent.createNotificationDto();
        notificationService.send(createNotificationDto);
    }
}
```

```java
public record NotificationEvent(CreateNotificationDto createNotificationDto) {
}
```

```java
// MessageService에서 event를 publish하는 부분
eventPublisher.publishEvent(new NotificationEvent(CreateNotificationDto.from(messageDto)));
```

```java
// BidService에서 event를 publish하는 부분
eventPublisher.publishEvent(new NotificationEvent(CreateNotificationDto.of(previousBidder.get().getId(), auctionAndImageDto, auctionImageAbsoluteUrl)));
```

2023-10-04 18:48 UTC, JJ503 requested changes
이벤트라는 새로운 개념을 학습하셨어야 했을 텐데 정말 고생 많으셨습니다!
칭찬합니다!!!

그런데 수정이 필요한 부분과 엔초 질문에 대한 답변을 확인하고 싶어 rc로 처리해 두도록 하겠습니다.

2023-10-04 18:48 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java
> +        eventPublisher.publishEvent(new BidNotificationEvent(bidNotificationDto));
### 선택
한 메서드에서 하는 일이 너무 많은 느낌인데 알림이라도 분리하면 어떨까요?
하지만, 개인 의견이기에 메리 판단에 맡기도록 하겠습니다.

2023-10-04 18:48 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
> +                                                                                               .getId())
### 선택
아래 `sendBidNotificatoin()`에서 처럼 `messageDto.receiver() .getProfileImage()`를 변수로 할당해 준다면 더 보기 좋을 것 같네요.

2023-10-04 18:48 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/MessageServiceTest.java
> +    }
### 필수
moking 내용은 각 테스트 메서드에 표시해주기로 했던 것으로 기억합니다.

2023-10-04 18:48 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/MessageServiceTest.java
> +class MessageServiceTest {
### 필수
머지를 하다 잘못된 걸까요?
Fixture 적용 코드가 모두 사라졌는데 확인해 주시면 감사하겠습니다.

2023-10-04 18:48 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/notification/application/FcmNotificationServiceTest.java
> +    MessageService messageService;
### 질문 & 필수
두 필드는 테스트에서 사용되지 않는 것으로 보이는데 필드로 선언한 이유가 있는 걸까요?

2023-10-05 00:49 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java
> +    private final ApplicationEventPublisher eventPublisher;
같은 타입의 `ApplicationPublisher`라고 해도 사용되는 Service에 따라 용도가 달라질테니 만약 쪽지 보내는 행위를 이벤트로 처리한다면 `messageSendingApplicationPublisher` 등등으로 표현할 수 있지 않을까 생각합니다

2023-10-05 00:51 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
> +    public void sendBidNotification(final BidNotificationEvent bidNotificationEvent) {
답변 확인했습니다 디스커션 기다리고 있겠습니다

2023-10-05 02:31 UTC, kwonyj1022 requested changes
질문이 하나 더 생겼습니다.

2023-10-05 02:31 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
> +public class NotificationEventListener {
### 질문
이벤트 리스너를 비동기적으로 처리할 필요는 없을까요?

2023-10-05 03:33 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
> +    }
저도 이 부분에 대해 고민을 많이 했던 것 같습니다.

저는 책임 분리의 관점에서 메서드를 분리하게 되었습니다.

먼저 이벤트를 도입한 이유는 `MessageService`,`BidService` <-> `NotificationService`의 의존성을 분리하는 목적이 가장 크다고 생각했습니다. 따라서 `NotificationService`에서 어떤 객체를 받아 어떤 일을 수행하는지에 대해서는 Message나 Bid 서비스에서 관심이 없고, 단지 생성한 메시지/입찰 데이터로 알림 이벤트를 전송해야 한다는 사실까지만 아는 것이 좋다고 생각했습니다.

이벤트 리스너를 생성하기 전 `Message/BidService` 서비스에서 직접 `NotificationService`를 호출했기 때문에 알림 서비스에 전달해야 하는 객체를 생성하는 역할을 `Message/BidService`에서 가져갔던 것처럼,
이벤트를 추가하면서 `NotificationService`에 의존성을 갖는 계층은 이벤트 리스너가 되었으므로 알림을 전송하기 위한 객체를 생성하는 책임 또한 이벤트 리스너에게 있다고 생각했습니다.

따라서 `MessageService`와 `BidService`는 단순히 생성한 엔티티를 계층간 이동 시 생성되는 dto로만 생성하고, 알림에 필요한 필드들을 선별하거나 알림 서비스에 전달하기 위한 객체를 생성하는 작업을 수행하는 것을 지양하고자 했습니다. 그러다보니 자연스럽게 메시지 엔티티를 변환한 dto를 받아 해당 dto를 알림 서비스에 전달하기 위한 dto로 변환하는 메서드와, 입찰 엔티티 dto를 알림 서비스에 전달하기 위한 dto를 생성하는 메서드가 분리되었습니다.

정리하면 관심사 분리의 관점에서 이벤트를 발행하는 서비스(Message, Bid 서비스)에서는 알림을 위한 객체(`CreateNotificationDto`)를 생성하지 않도록 했습니다. 따라서 메시지 엔티티를 감싼 dto, 입찰 엔티티를 감싼 dto를 `CreateNotificationDto`로 변환해주는 책임은 이벤트 리스너에게 종속되도록 했고, 두 개의 다른 dto를 받기 위한 메서드가 두 개 필요해져 위와 같이 분리하게 되었습니다.

그런데 알림을 보내야 한다는 것은 동일하니, `MessageService`,`BidService` -> 이벤트 리스너로 전달하기 위한 DTO(이벤트 리스너 → `NotificationService`로 전달되는 `CreateNotificationDto`와는 다른 dto)를 생성해주는 것도 방법일 수 있겠네요!

저는 이런 배경에 의해 위와 같이 분리하게 되었는데, 이에 대한 엔초의 의견도 궁금합니다!

2023-10-05 04:12 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java
> +        eventPublisher.publishEvent(new BidNotificationEvent(bidNotificationDto));
좋은 의견 감사합니다.
`previousBidder`를 찾은 이후 첫 입찰자인 경우를 판단하는 분기문 또한 알림 전송 여부를 결정하기 위한 로직이므로 함께 분리해주었습니다.

2023-10-05 04:14 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
> +                                                                                               .getId())
그러네요! 반영해두었습니다. 감사합니다.

2023-10-05 04:18 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
> +public class NotificationEventListener {
저도 해당 부분을 고려했었는데요!
알림을 전송하기 위해서는 입찰 내역 저장 또는 메시지 저장에 대한 커밋이 반드시 완료된 이후에 이루어져야 한다고 생각했습니다.
메시지를 조회해보면 조회되는 메시지가 없거나 상위 입찰자 알림을 받아 새로운 입찰금액을 확인하는 경우 이에 대해 반영되어있지 않다면 사용자이 의문을 가질 것이고, 따라서 `메시지 저장 → 알림 전송` 또는 `입찰 내역 저장 → 알림 전송`의 과정은 동기적으로 진행되어야 한다고 생각해서 적용하지 않았습니다.

엔초는 비동기로 처리되어도 된다고 생각해서 남겨주신 질문이신지도 궁금합니다!

2023-10-05 04:21 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/MessageServiceTest.java
> +    }
아래 남겨주신 것처럼 머지 시 누락된 것 같네요..
다시 적용해두었습니다!

2023-10-05 04:21 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/chat/application/MessageServiceTest.java
> +class MessageServiceTest {
완전 감사합니다 제이미 🙇🏻‍♀️

2023-10-05 04:51 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
> +public class NotificationEventListener {
메시지/입찰내역 저장과 알림 전송을 하나의 트랜잭션으로 처리하면 결국 둘이 결합하고 있는 것이고, 알림 전송이 딜레이 될 경우 그 트랜잭션이 계속 하나로 물려있게 되지 않나 싶습니다. 그래서 데이터를 저장하는 로직과 알림 전송은 비동기로 처리되어도 된다고 생각했습니다. (알림을 조금 늦게 받더라도 상관없다고 생각했어요) 또한 찾아보았을 때 `@TransactionalEventListener`의 phase 속성을 AFTER_COMMIT으로 설정하면 기존의 트랜잭션이 커밋된 이후에 이벤트 핸들러가 동작한다고 하는데 이 설정을 사용하면 메리가 우려하신 상황(데이터 저장과 관련된 트랜잭션이 커밋되지 않았는데 알림이 발송되는 상황)을 해결할 수 있지 않을까요?

저 어노테이션에 대해 저도 깊이 학습한건 아니라서 한 번 확인해보시면 좋을 것 같습니다.

2023-10-05 05:08 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
> +    }
> 따라서 NotificationService에서 어떤 객체를 받아 어떤 일을 수행하는지에 대해서는 Message나 Bid 서비스에서 관심이 없고, 단지 생성한 메시지/입찰 데이터로 알림 이벤트를 전송해야 한다는 사실까지만 아는 것이 좋다고 생각했습니다.

이 부분에 대해서는 납득했습니다.

그런데 알림을 보낸다는 것이 동일하니까 메시지 알림 이벤트, 입찰 알림 이벤트 이렇게 따로의 이벤트가 아니라 알림 이벤트라는 하나의 이벤트로 처리되었으면 좋겠는데 dto가 다르다 보니 어떻게 해야 할지 잘 모르겠네요ㅠ 같은 dto로 만들자니 결국에는 CreateNotificationDto랑 똑같을 것 같구요. 어렵네요..

2023-10-05 05:12 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/notification/application/FcmNotificationServiceTest.java
> +    MessageService messageService;
이것은 실수입니다
수정했습니다
감사해요 제이미ㅎㅎ

2023-10-05 05:39 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
> +public class NotificationEventListener {
이 부분이 오늘 데일리에서 말씀드린,, 디스커션에 정리중이라 내일 말씀드리겠다고 했던 부분 중 일부입니다!
`@TransactionalEventListener`는 해당 PR에서 작업 중이어서 리팩토링 이후 다시 리뷰 요청 드리겠습니다! (디스커션에도 오늘 정리해보도록 노력할 예정임다.. 현재 작업즁..)

---

남겨주신 코멘트를 완전히 이해하지 못한 것 같아 질문 먼저 드립니다.

> 메시지/입찰내역 저장과 알림 전송을 하나의 트랜잭션으로 처리하면 결국 둘이 결합하고 있는 것이고, 알림 전송이 딜레이 될 경우 그 트랜잭션이 계속 하나로 물려있게 되지 않나 싶습니다. 그래서 데이터를 저장하는 로직과 알림 전송은 비동기로 처리되어도 된다고 생각했습니다.

해당 부분에서 엔초가 말씀해주신 의견은 `하나의 트랜잭션에서 수행되지 않아도 되는 작업이기 때문에 비동기로 수행되어도 된다`라고 이해했는데, 제가 이해한 게 맞을까요?! 

그리고

> 알림을 조금 늦게 받더라도 상관없다고 생각했어요

해당 부분은 비동기로 처리되었을 때에 알림을 조금 늦게 받을 수 있는 상황이라고 이해하고 말씀해주신 것 같은데, 맞을까요?

이 부분에서 조금 헷갈려 엔초가 남겨주신 코멘트 보고 저도 다시 동기/비동기에 대해 다시 찾아봤습니다!
비동기로 처리하게 되면 작업을 수행하는 스레드가 분리되어 먼저 호출된 작업(메시지 저장 혹은 입찰 저장 로직)이 실행되는 동시에 알림 서비스를 위한 스레드가 실행됩니다. 따라서 메시지 저장 또는 입찰 저장 작업이 완료되는 것을 기다리지 않고 알림 서비스를 수행한다는 점에서 알림이 오히려 빨리 수행될 가능성이 높을 것 같습니다. 

다만 선행작업이 처리되는 것을 기다리지 않고 다음 작업을 시작하기 때문에 시간적인 측면에서의 성능은 좋을 수 있겠지만,
순서는 보장되지 않는다고 생각했습니다.
그리고 제가 해당 로직의 동기/비동기 처리 방식을 결정할 때 신경썼던 부분은 순서의 관점이었습니다.

예를 들어 비동기로 처리되어 입찰 내역 저장 작업을 수행하는 중에 다른 스레드에서 알림 전송이 완료되었다고 가정했을 때,
입찰 내역 저장 중 예기치 못한 예외 발생으로 해당 작업이 롤백된다면 입찰 내역이 업데이트 되지 않았음에도 사용자는 입찰 업데이트 알림을 받게 됩니다.

따라서 이런 부분을 고려해 남겨주신 것처럼 AFTER_COMMIT이 디폴트인 `@TransactionalEventListener`를 사용하려고 했고, 현재 작업중에 있습니다!

2023-10-05 05:42 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
> +public class NotificationEventListener {
앗 그렇군요 데일리 때는 저거를 몰랐어서 데일리에서 언급을 했다는 사실을 기억을 못했나봐요ㅠ 화이팅입니다!!

2023-10-05 05:44 UTC, apptie approved these changes
제가 리뷰했던 내용은 모두 적용되었고 답변도 확인했으니 approve 하겠습니다 
`@TransactionalEventListener` 기대하겠습니다

2023-10-05 05:57 UTC, JJ503 approved these changes
답변해 주시는 내용을 보니 메리가 얼마나 열심히 이벤트에 대해 학습하고 고민했는지가 보이네요..!
멋져요 메리~ 👍
제가 말씀드린 내용은 모두 수정이 완료되어 approve 합니다.

2023-10-05 09:08 UTC, kwonyj1022 approved these changes
수고하셨습니다 메리!!
디스커션 기대하겠습니다 ㅎㅎ

2023-10-05 09:08 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/notification/application/NotificationEventListenerTest.java
> +        final long actual = events.stream(MessageNotificationEvent.class).count();
### 선택
이 부분은 then 절에 해당할 것 같습니다.

2023-10-05 09:08 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/notification/application/NotificationEventListenerTest.java
> +        final long actual = events.stream(BidNotificationEvent.class).count();
### 선택
이 부분도 then 절에 해당할 것 같습니다.

2023-10-05 10:59 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/notification/application/NotificationEventListenerTest.java
> +        final long actual = events.stream(MessageNotificationEvent.class).count();
반영 완료했습니다

2023-10-05 10:59 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/notification/application/NotificationEventListenerTest.java
> +        final long actual = events.stream(BidNotificationEvent.class).count();
반영 완료했습니다

2023-10-05 11:01 UTC, merged