Q&A 기능 추가
woowacourse-teams/2023-3-ddang pull request #526
Opened 2023-10-04 01:33 UTC by JJ503

## 📄 작업 내용 요약

Q&A 기능 추가

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

복잡한 내용을 없을 것 같습니다.
고민인 내용들은 todo를 통해 작성해 두었습니다.

## 📎 Issue 번호

- closed # 314

2023-10-04 03:22 UTC, apptie requested changes
고생하셨습니다

고민에 대해서는 제가 이해를 잘 못해서 질문을 드렸고
테스트 쪽에 필수 두 개가 있어서 RC를 하도록 하겠습니다

2023-10-04 03:22 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/application/QuestionService.java
> +        }
### 질문

DB에서 조회할 때 처음부터 삭제되지 않은 경매만 조회할 수 있을 것 같은데, 조건 없이 조회해 서비스 단에서 검증해주신 이유가 있으실까요?
서비스 사용자가 봤을 때에는 삭제된 경매는 보이지 않을 것이기 때문에 바로 삭제되지 않은 Auction만 찾으면 될 것 같아서 질문드립니다

2023-10-04 03:22 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/application/QuestionService.java
> +    // TODO: 2023-10-04 [고민] 내가 참여한 경매와 같이 user에 경매 조회가 있는 것처럼, 경매 쪽에 Q&A 조회 메서드가 있는 게 적절할까요?
### 선택

저라면 Auction 패키지에서 별도의 클래스(Controller - Service)를 만들어서 처리해줄 것 같기는 합니다
다만 어떤 로직은 분리되어있고 어떤 로직은 하나로 합쳐져 있는 상황이라 전체적으로 회의를 하고 리펙토링을 해야 할 것 같습니다 
그래서 지금 당장은 선택에 맡기도록 하겠습니다

2023-10-04 03:22 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/application/QuestionService.java
> +        checkInvalidAuction(auction);
### 선택

여기 개행..?

2023-10-04 03:22 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/domain/Answer.java
> +    // TODO: 2023-10-04 [고민] answer에 writer를 만들어 바로 가져오는 방식이 좋을까요?
### 질문

answer에 writer를 만들어 바로 가져오는 방식을 이해하지 못했습니다 
answer에 writer 관련 정보까지 포함하자는 말씀이신가요?(연관관계 세팅)

2023-10-04 03:22 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/presentation/QuestionAndAnswerController.java
> +    // TODO: 2023/08/18 [고민] auctionId를 클라이언트에게서 받기 vs create 후 생성된 객체 아이디가 아닌 경매 아이디도 받아오기 (일단 전자)
### 질문

`create 후 생성된 객체 아이디가 아닌 경매 아이디도 받아오기`에 대한 로직 흐름을 이해하지 못했습니다
 
`answerService.create()`의 반환값에서 생성한 `Answer`의 `id`만 반환하는게 아니라 `auction`도 같이 반환하자는 말씀이신가요?

2023-10-04 03:22 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/presentation/QuestionAndAnswerController.java
> +package com.ddang.ddang.questionandanswer.presentation;
### 선택

`questionandanswer` 패키지명이 너무 이질적입니다...그냥 `qna`로 하는게 나을 것 같은데 어케 생각하시나요

2023-10-04 03:22 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionQuestionControllerTest.java
> +                               status().isOk(),
### 칭찬

칭찬해요!!!!!!!!!!!!!!!!!!!!!!

검증 열심히 하셨네요..

2023-10-04 03:22 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/presentation/QuestionAndAnswerController.java
> +public class QuestionAndAnswerController {
### 선택

해당 컨트롤러 이름도 QnaController 어떠신가요

2023-10-04 03:22 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/questionandanswer/infrastructure/JpaAnswerRepositoryTest.java
> +        em.clear();
### 필수

`@Id` 전략을 `Identity`로 사용하고 있기 때문에 해당 구문은 필요없을 것 같습니다 

`em.flush()`랑 `em.clear()`를 호출하지 않아도 `insert`문이 나가게 되므로 삭제하면 될 것 같습니다

2023-10-04 03:22 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/questionandanswer/infrastructure/JpaQuestionRepositoryTest.java
> +        em.clear();
### 필수

`JpaQuestionRepositoryTest`와 동일합니다 
삭제 부탁드립니다

2023-10-04 03:22 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/questionandanswer/infrastructure/fixture/JpaAnswerRepositoryFixture.java
> +
### 선택

개행 2개..?

2023-10-04 03:22 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/questionandanswer/presentation/QuestionAndAnswerControllerTest.java
> +        final ResultActions resultActions = mockMvc.perform(RestDocumentationRequestBuilders.post("/questions/{questionId}/answers", 질문_아이디)
### 선택 

140글자인데 `=` 앞에서 개행 한 번 어떠신가요

2023-10-04 03:22 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/questionandanswer/presentation/QuestionAndAnswerControllerTest.java
> +    void 답변을_입력하지_않은_경우_답변시_400을_반환한다(final CreateAnswerRequest 답변_내용이_빈값인_답변_등록_request) throws Exception {
### 칭찬

칭찬해요!!!!!!!!!!!!!!

`@MethodSource`로 명확하게 값을 전달할 수 있네요

2023-10-04 03:22 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadQuestionAndAnswersResponse.java
> +public record ReadQuestionAndAnswersResponse(List<ReadQuestionAndAnswerResponse> questionAndAnswers) {
아니면 `Qnas`? 뭔가 괴상하네요

2023-10-04 07:05 UTC, kwonyj1022 requested changes
제이미 정말 잘 짜셨네요. 그런데 필수 하나 있어서 rc입니다.

2023-10-04 07:05 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/domain/Answer.java
> +    // TODO: 2023-10-04 [고민] answer에 writer를 만들어 바로 가져오는 방식이 좋을까요?
채팅방에서도 참여자 두 명을 다 필드에 두지 않고 한 명은 경매의 판매자를 통하도록 되어있어서 이대로 가도 될 것 같아요. 만약 수정한다면 채팅방 쪽도 동일하게 수정이 필요할 것 같습니다.

2023-10-04 10:58 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/presentation/QuestionAndAnswerController.java
> +package com.ddang.ddang.questionandanswer.presentation;
저도 qna가 더 좋은 것 같아요!

2023-10-04 11:45 UTC, swonny requested changes
궁금한 부분이 있어 질문 몇 가지 남겨두었습니다!
코드량이 어마무시하네요.. 연휴 마지막까지 고생 많으셨습니다 제이미!!

2023-10-04 11:45 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/presentation/QuestionAndAnswerController.java
> +public class QuestionAndAnswerController {
저도 동의합니다.

2023-10-04 11:45 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/presentation/QuestionAndAnswerController.java
> +    // TODO: 2023/08/18 [고민] auctionId를 클라이언트에게서 받기 vs create 후 생성된 객체 아이디가 아닌 경매 아이디도 받아오기 (일단 전자)
### 선택

저도 지금이 좋은 것 같습니다.
answerService에서 AuctionId를 반환하는 것이 서비스에서 컨트롤러를 알고 필요한 값을 골라서 주는 느낌이라 presentation 레이어 변경에 따라 서비스에도 영향이 있을 것 같아요.

2023-10-04 11:45 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/questionandanswer/presentation/QuestionAndAnswerControllerTest.java
> +                .willThrow(new AuctionNotFoundException("해당 질문을 찾을 수 없습니다."));
### 필수

리마인드 차원에서 작성합니다.
엔초가 남겨준 날카로운 리뷰 반영 완료되면 여기도 잊지 않고 바꿔주세요!!
다른 곳은 테스트에서 깨질 것 같은데 여기는 `isNotFound()`인지만 확인하고 있어 혹시나 하는 마음에 코멘트 달아둡니다!

2023-10-04 11:45 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionQuestionController.java
> +public class AuctionQuestionController {
###  선택

패키지명과 클래스명을 변경하게 된다면 여기도 `AuctionQnaController`로 통일해주시면 좋을 것 같습니다.

2023-10-04 11:45 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/domain/Answer.java
> +    // TODO: 2023-10-04 [고민] answer에 writer를 만들어 바로 가져오는 방식이 좋을까요?
### 선택

엔초가 말씀해주신 것처럼 채팅방에서 경매를 통해 판매자를 가져오게 되어있습니다.
저는 남겨주신 것처럼 answer에 writer를 바로 가져오는 방식이 좋을 것 같다고 생각했습니다. (엔초 말처럼 변경된다면 이에 맞춰 채팅방도 수정이 필요할 것 같아요.)
이유는 채팅방을 테스트 할 때 판매자 정보를 얻기 위해 항상 경매에 의존적이게 되어 비효율적인 테스트가 발생한다고 생각했기 때문입니다.

2023-10-04 11:45 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionQuestionController.java
> +    public ResponseEntity<ReadQuestionAndAnswersResponse> readAllByAuctionId(@PathVariable final Long auctionId) {
### 질문 & 선택

해당 로직을 `auction.presentation` 하위에 위치시키신 이유가 궁금합니다!
경매글을 통해 qna에 접근하긴 하지만 `qna(questionandanswer)` 하위에 있는 서비스를 의존하고 있다는 점에서 해당 컨트롤러는 qna 패키지 하위에 위치하는 것도 충분히 자연스러울 것 같다고 생각했습니다.

채팅방도 경매글을 통해 조회하는 로직이 있지만 `/chattings` uri를 통해 조회하는 것처럼 qna도 비슷하게 가져가면 어떤지 건의드려봅니다!

2023-10-04 19:01 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadQuestionAndAnswersResponse.java
> +public record ReadQuestionAndAnswersResponse(List<ReadQuestionAndAnswerResponse> questionAndAnswers) {
`QuestionAndAnswer`를 모두 `qna`로 바꾸기로 했기에 `Qnas`로 수정해보았습니다.
괜찮을까요?

2023-10-04 19:02 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/application/AnswerService.java
> +
이... 이게 무슨일이야..!
감사합니다 🙇‍♀️

2023-10-04 19:24 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/application/QuestionService.java
> +        }
다른 기능 구현 시 이와 동일하게 진행했기 때문입니다.
하지만, 해당 방법이 더 적절할 것 같아 현재 로직에서는 말씀해 주신 내용과 같이 수정한 후 따로 이슈를 만들어 다른 부분에서도 해당 로직으로 수정할 수 있도록 하겠습니다.

2023-10-04 19:39 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/application/QuestionService.java
> +    // TODO: 2023-10-04 [고민] 내가 참여한 경매와 같이 user에 경매 조회가 있는 것처럼, 경매 쪽에 Q&A 조회 메서드가 있는 게 적절할까요?
현재 Auctin 패키지에 별도의 클래스만 만들어 작업한 상태입니다.
해당 부분은 일단 유지하도록 하겠습니다.

2023-10-05 01:40 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/questionandanswer/infrastructure/JpaAnswerRepositoryTest.java
> +        em.clear();
[지난 pr 코멘트](https://github.com/woowacourse-teams/2023-3-ddang/pull/493#discussion_r1341975485)와 의견이 상반되어 헷갈리네요...
해당 내용과 어떤 점이 다르기에 의견이 바뀌신건지 궁금합니다.

2023-10-05 02:48 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/domain/Answer.java
> +    // TODO: 2023-10-04 [고민] answer에 writer를 만들어 바로 가져오는 방식이 좋을까요?
현재 답변은 판매자만 진행할 수 있기에 Question에 연관관계로 세팅되어 있는 Auction을 통해 타고 타고 가서 seller를 통해 답변 작성자를 가져오는 상태입니다.
그렇게 진행한 이유는 Answer의 경우 조회 시 무조건 Question과 함께 fetch join을 통해 가져오기에 Quesiton에 있는 Seller를 통해 가져올 수 있을 것이라 생각했기 때문입니다. 그런데, 질문과 답변 조회 시 Auction의 판매자 정보 외에는 전혀 필요하지 않기에 Auction의 판매자 정보를 통해 답변자 정보를 가져오는 방식이 정말 괜찮은지 의문이 들게 되었습니다.

그런데, 이번 pr에서는 현재 구조를 유지한 후 도메인 범위 축소 회의를 진행할 때 다시 이야기해 보도록 했기에 유지하도록 하겠습니다.

2023-10-05 02:49 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/domain/Answer.java
> +    // TODO: 2023-10-04 [고민] answer에 writer를 만들어 바로 가져오는 방식이 좋을까요?
이번 pr에서는 현재 구조를 유지한 후 도메인 범위 축소 회의를 진행할 때 다시 이야기해 보도록 했기에 유지하도록 하겠습니다.

2023-10-05 02:49 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/application/QuestionService.java
> +    // TODO: 2023-10-04 [고민] 내가 참여한 경매와 같이 user에 경매 조회가 있는 것처럼, 경매 쪽에 Q&A 조회 메서드가 있는 게 적절할까요?
이번 pr에서는 현재 구조를 유지한 후 도메인 범위 축소 회의를 진행할 때 다시 이야기해 보도록 했기에 유지하도록 하겠습니다.

2023-10-05 02:52 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/questionandanswer/infrastructure/JpaAnswerRepositoryTest.java
> +        em.clear();
지난 pr 코멘트의 경우 `Fixture`를 적용하기 전의 코드로 인지하고 코멘트를 달았었습니다 
근데 지금보니까 아니네요? 이 부분은 제가 착각한 것 같습니다 
죄송합니다!!!!!!!!!!!!!!!!!!!! 

변명을 하자면 지난 pr 코멘트에서 실제 `em.flush()`와 `em.clear()`를 호출하는 부분이 github가 그...접는 페이지 표시로 생략해서 헷갈린 것 같네요 

---

조금 더 설명을 하자면 

지난 pr 코멘트의 경우 `given`절에서 테스트하고자 하는 주체가 아닌 다른 값들(신고 테스트하는데 필요한 `auction`이랑 `user` 등등)을 저장해주고 `em.flush()`와 `em.clear()`를 호출하는 과정으로 인지했었습니다

그래서 테스트하고자 하는 대상(`신고 Repository`)의 정확한 동작을 확인하기 위해 `given`절에서 세팅한 `em.flush()`로 메모리 DB에 쿼리를 실행시키고, `em.clear()`로 1차 캐시에 캐싱된 값을 모두 제거를 한 뒤에 테스트를 해야한다는 의미였습니다 

지금 테스트의 경우 `Fixture`에 `em.flush()`와 `em.clear()`를 호출하기 때문에 `given`절에서의 처리는 모두 끝난 상태입니다
해당 부분은 위의 이유로 반드시 호출되어야 하는 상태라고 생각합니다

다른 점은 이제부터인데 
`save()` 호출 시 `id` 전략이 `Identity`이므로 `save()` 호출 즉시 `insert`를 날리고 그 결과를 `save()`의 반환값으로 반환합니다 

그러므로 `em.flush()`는 이미 `save()` 호출 시에 호출이 됩니다 (`save()` 메서드 호출 시 `em.flush()`가 내부적으로 호출)
또한 `save()`의 결과를 이미 반환하므로 캐싱된 값을 제거하는 `em.clear()`를 호출하더라도 이미 반환 받은 값에는 영향을 주지 않습니다 

그러므로 필요가 없는 코드라고 볼 수 있을 것 같습니다

2023-10-05 04:23 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/presentation/QuestionAndAnswerController.java
> +    // TODO: 2023/08/18 [고민] auctionId를 클라이언트에게서 받기 vs create 후 생성된 객체 아이디가 아닌 경매 아이디도 받아오기 (일단 전자)
나중에 안드로이드 측 분들과 이야기해 봐야 하긴 하지만, 현재 답변이 생성된 경우 반환되는 경로를 생성할 때 `auctinId`가 필요합니다.
현재 답변을 생성하는 과정에서는 `auctionId`가 필요하지 않지만 클라이언트 측에서 받아와 반환되는 값으로만 사용하는 상태입니다.
그래서 이러한 형태가 괜찮은 지 한번 확인차 todo로 작성하게 되었습니다.

만약 위 과정이 별로라면 save 시 반환 값을 dto 등의 형태로 auctinId를 받아오는 방법도 있을 것이라 생각했습니다.
그런데 일반적으로 save()에서 반환되길 기대하는 값은 아닌 것 같아 현재의 형태가 더 낫다고 생각해 현재 상태를 유지하게 되었습니다.
더 좋은 의견이 있다면 말씀해주시면 감사하겠습니다!

2023-10-05 04:25 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/presentation/QuestionAndAnswerController.java
> +package com.ddang.ddang.questionandanswer.presentation;
좋습니다!
기존 컨벤션 중 줄여 쓰는 것은 하지 말자고 해 불편하더라도 풀어서 사용했습니다.
하지만, 저도 현재 네이밍이 더 보기 힘들다고 생각해 qna로 수정하도록 하겠습니다!

2023-10-05 04:26 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/presentation/QuestionAndAnswerController.java
> +public class QuestionAndAnswerController {
위와 동일한 이유로 Qna로 수정하도록 하겠습니다!

2023-10-05 04:30 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/questionandanswer/infrastructure/JpaAnswerRepositoryTest.java
> +        em.clear();
이해했습니다!
그래서 저는 해당 부분이 필요는 없지만 명시적으로 작성해 주는 코드라고 생각했네요.
이번 pr에서는 해당 부분 코드를 제거하는 방향으로 가고, 이후에 이슈를 만들어 다른 테스트에서도 해당 코드를 제거할 수 있도록 하겠습니다.

2023-10-05 04:35 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/questionandanswer/presentation/QuestionAndAnswerControllerTest.java
> +        final ResultActions resultActions = mockMvc.perform(RestDocumentationRequestBuilders.post("/questions/{questionId}/answers", 질문_아이디)
오 좋습니다!

2023-10-05 04:39 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/presentation/QuestionAndAnswerController.java
> +    // TODO: 2023/08/18 [고민] auctionId를 클라이언트에게서 받기 vs create 후 생성된 객체 아이디가 아닌 경매 아이디도 받아오기 (일단 전자)
개인적으로 Answer를 save()하는 메서드에서 `auctionId`가 넘겨지기를 기대하지는 않을 것 같고, 동일하게 Id라 헷갈릴 것 같아 해당 방법은 적절하지 않다고 생각합니다.
그래서 auctionId를 반환하는 방식으로 수정할 것이라면 dto 등을 통해 묶어줘야 하지 않을까 생각했습니다.

그런데 저도 지금 상태가 현재 후보들 중에선 가장 적절하다고 생각해 유지하도록 하겠습니다!

2023-10-05 04:50 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/application/AnswerService.java
> +                                                    );
아니 무슨일이죠...
감사합니다 엔초!

2023-10-05 04:56 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/questionandanswer/infrastructure/fixture/JpaAnswerRepositoryFixture.java
> +    JpaQuestionRepository questionRepository;
중간 커밋에서 해당 피드백이 달린 것 같습니다.
최종 요청 파일에서는 Private이 붙어 있습니다!

2023-10-05 04:58 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/questionandanswer/presentation/QuestionAndAnswerControllerTest.java
> +                .willThrow(new AuctionNotFoundException("해당 질문을 찾을 수 없습니다."));
오..!
메리가 말씀 안 해주셨으면 놓칠뻔 했네요.
감사합니다 메리!

2023-10-05 05:03 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionQuestionController.java
> +    public ResponseEntity<ReadQuestionAndAnswersResponse> readAllByAuctionId(@PathVariable final Long auctionId) {
저는 채팅보다는 `내가 참여한 경매 목록`에 더 가깝다고 생각했습니다.
채팅은 경매에 종속적이기도 하지만, 채팅 목록을 통해 접근 가능하기에 메리가 말씀해 주신 방법이 적절하다고 생각합니다.
하지만, qna의 경우는 경매 내에만 존재하며, 해당 경매에 대한 qna이기에 내가 참여한 경매 목록과 같은 상황에 더 가깝다고 생각했습니다.

2023-10-05 06:13 UTC, kwonyj1022 approved these changes
제가 말씀드린 내용은 모두 수정이 완료되어 approve 합니다.

2023-10-05 06:41 UTC, apptie approved these changes
제가 언급한 사항도 모두 적용되어 approve 하도록 하겠습니다
고생하셨습니다

2023-10-05 08:53 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionQuestionController.java
> +    public ResponseEntity<ReadQuestionAndAnswersResponse> readAllByAuctionId(@PathVariable final Long auctionId) {
이해했습니다~! 이대로 진행하시면 좋을 것 같습니당

2023-10-05 08:53 UTC, swonny approved these changes
고생 많으셨습니다 제이미!!

2023-10-07 15:05 UTC, kwonyj1022 requested changes
기능 추가 수고하셨습니다! 필수 사항이 몇 개 있어서 rc 남겼습니다.

2023-10-07 15:05 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/report/infrastructure/persistence/JpaQuestionReportRepositoryTest.java
> +    }
### 필수
전체 테스트 돌렸을 때 이 테스트코드 실패하네요.. 근데 자코코 돌렸을 땐 왜 build successful이 나올까요?

2023-10-07 15:05 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/qna/domain/Question.java
> +    }
### 필수
여기도 새로 추가된 메서드들에 대한 테스트코드가 없습니다!

2023-10-07 15:16 UTC, apptie requested changes
엔초 리뷰 구경갔다가 별을 발견해버려서....RC로 변경하겠습니다

2023-10-07 15:16 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/report/infrastructure/persistence/JpaAnswerReportRepositoryTest.java
> +import org.assertj.core.api.*;
### 필수 

별을 발견했습니다 1

2023-10-07 15:16 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/report/infrastructure/persistence/JpaQuestionReportRepositoryTest.java
> +import org.assertj.core.api.*;
### 필수 

별을 발견했습니다 2

2023-10-07 15:16 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/qna/application/QuestionServiceTest.java
> +import com.ddang.ddang.qna.application.exception.QuestionNotFoundException;
### 필수

밑에 13번째줄에 별을 발견했습니다 3

2023-10-07 15:16 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/report/application/AnswerReportServiceTest.java
> +import org.assertj.core.api.*;
### 필수

별을 발견했습니다 4

2023-10-07 15:16 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/report/application/QuestionReportServiceTest.java
> +import org.assertj.core.api.*;
### 필수

별을 발견했습니다 5

2023-10-07 15:22 UTC, kwonyj1022 requested changes
### 필수
신고랑 삭제 부분 문서화 작업도 추가해 주시면 감사하겠습니다!

2023-10-07 15:26 UTC, swonny approved these changes
고생많으셨습니다 제이미
필수 사항이긴한데 크게 중요하지 않은 간단한 컨벤션이라 approve하겠습니다.

2023-10-07 15:26 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/qna/infrastructure/JpaAnswerRepository.java
> +    Optional<Answer> findByIdAndDeletedIsFalse(Long answerId);
### 필수

바로 아래 `JpaQuestionRepository`에는 파라미터에 final이 붙어있는데 여기에는 누락된 것 같아요!

2023-10-07 15:26 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/report/application/dto/ReadAnswerReportDto.java
> +    public static ReadAnswerReportDto from(final AnswerReport answerReport) {
### 필수

메서드 윗 줄에 개행을 부탁드리겠습니다

2023-10-07 15:26 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/report/infrastructure/persistence/JpaAnswerReportRepository.java
> +    boolean existsByIdAndReporterId(Long id, Long ReporterId);
### 필수

여기에도 `final` 붙이는걸로 통일해주시면 감사하겠습니다

2023-10-07 15:26 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/report/infrastructure/persistence/JpaQuestionReportRepository.java
> +    boolean existsByIdAndReporterId(Long id, Long reporterId);
### 필수

여기에도 `final` 붙이는걸로 통일해주시면 감사하겠습니다아

2023-10-09 01:11 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/qna/domain/Answer.java
> +    }
헉... 정말 큰일날뻔 헀네요.
고마워요 엔초!

2023-10-09 01:13 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/qna/domain/Question.java
> +    }
저도 해당 부분을 고민하다 Anwer의 경우 가져오는 방법이 Question을 통해서밖에 없어 굳이 삭제처리를 않았습니다.
그런데 갑자기 드는 생각으로는 Question은 삭제되었음으로 표현되고 Answer는 보여야 하지 않을까 싶기도 하네요!
해당 부분에 대해 처리해두도록 하겠습니다..!

2023-10-09 01:27 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/qna/domain/Answer.java
> +    }
확인감사합니다. 추가해두었습니다!

2023-10-09 01:28 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/infrastructure/persistence/JpaQuestionReportRepositoryTest.java
> +    }
제 쪽에서는 실패하는 테스트가 없는데 혹시 어떤 문제인지 알 수 있을까요?
그리고 혹시 모르니 다시 한번 확인해 주시면 감사하겠습니다..!

![image](https://github.com/woowacourse-teams/2023-3-ddang/assets/63184334/3eb4ad73-30fd-4a87-a388-3afa5dff4b6c)

2023-10-09 01:31 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/qna/domain/Question.java
> +    }
자코코.. 생각보다 관대하군요..?ㅎㅎ
`delete()`관련 테스트는 이미 존재했기에 `isWriter()` 테스트만 추가해 두었습니다.
감사합니다!

2023-10-09 01:47 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/qna/application/QuestionServiceTest.java
> +import com.ddang.ddang.qna.application.exception.QuestionNotFoundException;
안 돼~~~
감사합니다...
아래 내용 모두 수정했습니다!

2023-10-09 01:48 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/qna/infrastructure/JpaAnswerRepository.java
> +    Optional<Answer> findByIdAndDeletedIsFalse(Long answerId);
추가했습니다. 감사합니다!

2023-10-09 03:34 UTC, apptie approved these changes
별이 사라져서 Approve 하겠습니다

2023-10-09 08:00 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadQuestionAndAnswersResponse.java
> +public record ReadQuestionAndAnswersResponse(List<ReadQuestionAndAnswerResponse> questionAndAnswers) {
저는 괜찬을 것 같습니다 너무 늦게 확인했네요 죄송합니다

2023-10-09 08:00 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/domain/Answer.java
> +    // TODO: 2023-10-04 [고민] answer에 writer를 만들어 바로 가져오는 방식이 좋을까요?
확인했습니다

2023-10-09 08:01 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/questionandanswer/presentation/QuestionAndAnswerController.java
> +    // TODO: 2023/08/18 [고민] auctionId를 클라이언트에게서 받기 vs create 후 생성된 객체 아이디가 아닌 경매 아이디도 받아오기 (일단 전자)
확인했습니다 
나중에 도메인 범위쪽 리펙토링할 때 언급해야겠네요

2023-10-09 11:24 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/qna/domain/Answer.java
> +    }
### 필수
isWriter() 테스트코드가 없네요

2023-10-09 11:24 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/report/infrastructure/persistence/JpaQuestionReportRepositoryTest.java
> +    }
저는 계속 실패했다고 나오네요..
![image](https://github.com/woowacourse-teams/2023-3-ddang/assets/96688810/466bff34-d5b2-4e45-b5d4-c50abd3bc03e)

이유는 모르겠어요. 픽스처 들어가보니까 `질문` 이라는 픽스처는 신고가 안된거라 false여야하는데 왜 true가 나올까요?ㅜㅜ

2023-10-09 11:26 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/qna/domain/Question.java
> +    }
### 필수
isDelete() 테스트만 있고. delete() 테스트는 없는 것 같아요!

2023-10-09 11:37 UTC, kwonyj1022 requested changes
테스트 왜 실패하는지 알아냈어요! 그런데 왜 제이미가 돌렸을 때랑 자코코 돌렸을 때는 성공했는지 모르겠네요ㅠㅠ

2023-10-09 11:37 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/qna/domain/QuestionTest.java
> +
### 필수
`isDeleted()` 테스트만 있고 `delete()` 테스트는 없는 것 같습니다.

2023-10-09 11:37 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/report/infrastructure/persistence/JpaQuestionReportRepositoryTest.java
> +
### 필수
"참을 반환한다"인데 false를 검증하고 있어요

2023-10-09 11:37 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/report/infrastructure/persistence/fixture/JpaQuestionReportRepositoryFixture.java
> +        질문_신고4 = new QuestionReport(신고자, 이미_신고한_질문, "신고합니다");
### 필수
질문 신고 1,2,3,4의 신고자가 각각 달라야 할 것 같아요

2023-10-09 11:37 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/report/infrastructure/persistence/JpaQuestionReportRepositoryTest.java
> +    }
### 필수
저는 계속 실패했다고 나오네요..
![image](https://github.com/woowacourse-teams/2023-3-ddang/assets/96688810/466bff34-d5b2-4e45-b5d4-c50abd3bc03e)

왜 제이미는 성공하고 저는 실패하는지는 모르겠지만, jpa 메서드가 잘못되어서 그런 것 같아요.
`JpaQuestionReportRepository`의 메서드가 `existsByQuestionIdAndReporterId()`여야 할 것 같습니다. 관련 리뷰 그 쪽에도 달아놓을게요!

2023-10-09 11:37 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/report/infrastructure/persistence/JpaQuestionReportRepository.java
> +    boolean existsByIdAndReporterId(final Long id, final Long reporterId);
### 필수
메서드가 의도와 다르게 동작할 것 같네요.
```suggestion
    boolean existsByQuestionIdAndReporterId(final Long questionId, final Long reporterId);
```

2023-10-09 11:44 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/qna/domain/Answer.java
> +    }
아이구.. 감사합니다 🙇‍♀️

2023-10-09 11:48 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/report/infrastructure/persistence/JpaQuestionReportRepository.java
> +    boolean existsByIdAndReporterId(final Long id, final Long reporterId);
왜인가요?
JpaRepository가 갑자기 헷갈리는데 Quesiton 테이블의 id가 곧 questionId가 아닌가요?
id로 작성하게 된다면 어떤 아이디를 불러오게 되는 건가요?

2023-10-09 11:52 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/infrastructure/persistence/JpaQuestionReportRepositoryTest.java
> +    }
헉 그렇네요..!
제거엔 대체 어떻게 성공이 된걸까요?
알 수 없는 자코코와 인텔리제이...
엔초 덕분에 문제를 찾을 수 있었네요!
꼼꼼한 리뷰 고마워요 엔초!

2023-10-09 11:56 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/report/infrastructure/persistence/fixture/JpaQuestionReportRepositoryFixture.java
> +        질문_신고4 = new QuestionReport(신고자, 이미_신고한_질문, "신고합니다");
허거덩 만들어두고 사용조차 하지 않았군요..!
수정했습니다!

2023-10-09 11:58 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/report/infrastructure/persistence/JpaQuestionReportRepository.java
> +    boolean existsByIdAndReporterId(final Long id, final Long reporterId);
### 필수
JpaAnswerReportRepository도 `boolean existsByAnswerIdAndReporterId(final Long answerId, final Long ReporterId);`로 수정해주시면 감사하겠습니다.

2023-10-09 12:08 UTC, kwonyj1022 approved these changes
테스트 메서드명 관련해서 필수 사항 하나 있지만 간단한 거라 approve 하겠습니다. 
이거 하나만 수정하고 머지해주시면 될 것 같아요!

2023-10-09 12:08 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/qna/domain/AnswerTest.java
> +    }
### 필수
```suggestion
    @Test
    void 답변의_작성자가_아니라면_거짓을_반환한다() {
        // when
        final boolean actual = 답변.isWriter(답변_작성자가_아닌_사용자);

        // then
        assertThat(actual).isFalse();
    }
```

2023-10-10 01:10 UTC, merged