상호 평가 반영 스케줄링
woowacourse-teams/2023-3-ddang pull request #602
Opened 2023-10-10 18:52 UTC by kwonyj1022

## 📄 작업 내용 요약
상호 평가 반영 스케줄링

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드
- 스케줄링을 구현하는 것은 스프링에서 거의 다 해줘서 실질적으로는 어노테이션만 추가하면 됩니다. 어노테이션 속성 값에 사용하는 스케줄 시간 설정 문법(?)이 있는데 이건 그냥 어노테이션 검색하면 구글에 잘 나와있어요. 스케줄링 적용한 부분에 대해서는 [`스케줄링 설정 추가` 커밋](https://github.com/woowacourse-teams/2023-3-ddang/commit/c7cbc7e9d8b11ebd3bfe0088d3ba7720de0bf674)에서 확인하시면 됩니다.
- 스케줄링을 하면서 한 번에 디비에 많은 데이터를 insert 하게 되고, 지금은 jpa 더티체킹으로 자동으로 되도록 했습니다. 즉, insert 성능은 고려하지 않았습니다. **대규모 insert 최적화는 이후 별도의 이슈로 진행하겠습니다.**
- 처음에는 이전에 말씀드린 대로 신뢰도가 없는 경우에 대한 기본값을 0.0으로 두고 반영된 리뷰 개수를 이용해서 신뢰도가 0.0인 사용자인지 평가를 한 번도 받지 않은 사용자인지 구별해주려고 했습니다. 그런데, 실질적으로 신뢰도 조회에 사용되는 엔티티인 user 엔티티에는 반영된 리뷰의 개수를 필드로 갖고 있지 않기 때문에 신뢰도를 파악하려면 항상 UserReliability를 참조하거나, user 엔티티에 필드를 추가해야 했습니다. 
User 조회 시마다 UserReliability를 참조하는 것은 비효율적일 것 같고, user 엔티티에 반영된 리뷰 개수를 추가하는 것도 구성 상 적합하지 않은 것 같아서 기본값을 음수로 두었습니다. 
이전에는 신뢰도가 음수인 경우에 신뢰도 계산에 오류가 생길지도 모른다는 걱정이 있었는데 어차피 신뢰도가 음수인 경우는 반영된 리뷰 개수가 0개인 상황이라 신뢰도 계산 내에서 둘을 곱하는 로직을 수행할 때 어차피 0이 되기 때문에 문제가 생기지 않을 거라 생각했고, 분기문도 사용하지 않았습니다. 
음수 중에 `-1`보다는 `Double.minValue()`가 좀 더 이상한 값(?) 의미 없는 값(?)이라는 의미를 잘 담는 것 같아서 `Double.minValue()`로 하였습니다. **신뢰도가 음수인 경우에 대한 응답 데이터 가공은 별도의 이슈로 진행하겠습니다.**

## 📎 Issue 번호
- closed #585

2023-10-12 06:42 UTC, apptie requested changes
고생하셨습니다

롬복 관련해서 소소한 필수질문이 있어서 RC로 하겠습니다

2023-10-12 06:42 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/configuration/SchedulingConfiguration.java
> +@EnableScheduling
### 칭찬

칭찬해요!!!!!!!!!!!!!!!!!!!!!!!!!!
테스트 시 설정 파일을 exclude하는 것만으로도 깔끔하게 분리할 수 있겠네요

2023-10-12 06:42 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/review/domain/Reviews.java
> +@ToString
### 질문 & 필수 

해당 도메인은 Review의 일급 컬렉션으로 보입니다 
다른 도메인 엔티티와는 다르게 영속화되지 않을 것이라고 보이는데 
이 경우 `@EqualsAndHashCode`와 `@ToString`이 필요한지 모르겠네요

`@ToString`은 디버깅 시 도움이 될 수 있겠지만, `@EqualsAndHashCode`의 경우 저는 정말 필요없을 것 같습니다
이러한 일급 컬렉션의 동일성 비교를 할 일이 있을까 싶기도 하고, 동일성 비교를 하는 로직이 유효한 로직인지도 모르겠네요 
지금은 동일성 비교를 하는 로직은 불필요할 것 같습니다

그래서 해당 질문과 이 애노테이션을 추가한 특별한 이유가 없다면 `@EqualsAndHashCode`는 삭제했으면 좋겠습니다
`@ToString`은 괜찮을 것 같기도 하고 이건 잘 모르겠군요

2023-10-12 06:42 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/review/domain/Reviews.java
> +@ToString
### 칭찬

하지만 일급 컬렉션을 통해 관련 로직을 도메인 로직으로 분리하신 건 매우 개쩌는 것 같습니다
칭찬해요!!!!!!!!!!!!!!!!!!!!!!!!!@#!@#!@3

2023-10-12 06:42 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/user/application/schedule/ReliabilityUpdateSchedulingService.java
> +    @Scheduled(cron = "0 0 4 ? * MON")  // 매주 월요일 새벽 4시에 동작
### 질문

프로덕션 영역에서 주석을 사용해도 괜찮았었나요?
컨벤션 기억이 안나요

2023-10-12 06:42 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/user/application/schedule/ReliabilityUpdateSchedulingService.java
> +        updateHistoryRepository.save(newHistory);
### 선택

개행..?

2023-10-12 06:42 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/user/domain/ReliabilityUpdateHistory.java
> +@ToString(of = {"id", })
### 선택

이거 `lastAppliedReviewId` 까지 포함하려다가 안하신걸까요?

2023-10-12 17:46 UTC, swonny approved these changes
스케줄링 적용 고생 많으셨어요 엔초!!
바쁜 와중에 학습해서 구현해주셔서 감사합니다 !!
저는 질문과 간단한 컨벤션 위주라서 approve하겠습니다.

2023-10-12 17:46 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/user/domain/Reliability.java
> +    private double value;
### 칭찬

원시타입으로 바꿔주셔서 마음이 굉장히 편안해졌어요 감사합니다@@

2023-10-12 17:46 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/review/infrastructure/persistence/JpaReviewRepository.java
>      List<Review> findAllByTargetId(final Long targetId);
### 선택? 필수?

`JOIN FETCH` 부분은 개행을 일부러 안해주신 건가요?.?

2023-10-12 17:46 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/user/application/schedule/ReliabilityUpdateSchedulingServiceTest.java
> +
### 필수

개행을 없애주시거나 구분하고자 하는 위치에 모두 추가해주시면 감사하겠습니다!

2023-10-12 17:46 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/user/application/schedule/ReliabilityUpdateSchedulingService.java
> +    @Scheduled(cron = "0 0 4 ? * MON")  // 매주 월요일 새벽 4시에 동작
### 선택

프로덕션에서 사용하는건 최대한 지양하자고 이야기했던걸로 기억합니다.
그런데 이것처럼 String 값만으로 한 눈에 의미를 파악하기 어려운 경우에는 적는 것도 괜찮을 것이라고 생각합니다.
다른 분들의 의견도 궁금해요!

2023-10-13 00:32 UTC, JJ503 approved these changes
엔초 고생 많으셨습니다!
저는 별다른 수정 사항은 보이지 않아 approve 합니다.
테스트 코드에서 간단한 제안 사항이 있는데, 이는 엔초의 선택에 따르겠습니다.
그리고 지토 코드에도 flyway가 있는데 두 분 버전 조심하세요...!!

2023-10-13 01:34 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/user/domain/ReliabilityUpdateHistory.java
> +@ToString(of = {"id", })
앗 들켜버렸다

2023-10-13 01:38 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/review/domain/Reviews.java
> +@ToString
그냥 별 생각 없이 습관적으로 추가했던 것 같습니다. `@EqualsAndHashCode`는 삭제하도록 하겠습니다. `@ToString`은 원래 목적이 디버깅에 쓰려고 한 것이기 때문에 남겨두도록 하겠습니다.

2023-10-13 01:41 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/review/infrastructure/persistence/JpaReviewRepository.java
>      List<Review> findAllByTargetId(final Long targetId);
아무 생각 없었어요 ㅠ 개행 추가했습니다.

2023-10-13 01:42 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/user/application/schedule/ReliabilityUpdateSchedulingServiceTest.java
> +
개행을 제거했습니다.

2023-10-13 01:44 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/user/application/schedule/ReliabilityUpdateSchedulingServiceTest.java
> +            softAssertions.assertThat(actual5.get().getAppliedReviewCount()).isEqualTo(구매자5_최종_신뢰도_반영_개수);
반영하겠습니다.

2023-10-13 01:51 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/user/application/schedule/ReliabilityUpdateSchedulingService.java
> +    @Scheduled(cron = "0 0 4 ? * MON")  // 매주 월요일 새벽 4시에 동작
크론식이 익숙하지 않기 때문에 리뷰 시 이해를 위해 추가하였는데 어떻게 할 지 데일리에서 논의하면 좋을 것 같습니다.

2023-10-13 04:01 UTC, apptie approved these changes
제가 남긴 리뷰에 대한 내용이 적용되어 Approve 하겠습니다

2023-10-13 08:14 UTC, merged