경매 목록 조회 시 마감된 경매의 정렬 순서를 후순위로 변경
woowacourse-teams/2023-3-ddang pull request #608
Opened 2023-10-11 03:56 UTC by apptie

## 📄 작업 내용 요약

- 경매 목록 조회 시 마감된 경매의 정렬 순서를 후순위로 변경
- 레포지토리 메서드 변경
  - 메서드 분리 
  - left outer join이 필요없는 경우 inner join으로 변경 
## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

## 📎 Issue 번호

- closed #605

2023-10-11 10:25 UTC, JJ503 requested changes
경매는 하나만 수정해도 테스트 수정 사항이 엄청나군요...
그런데 말입니다...
제 쪽을 수정해 주시는 과정에서 질문 혹은 필수로 수정해야 할 것 같은 사항이 있어 코멘트 달아두었습니다.
확인해주시면 감사하겠습니다.

2023-10-11 10:25 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/qna/application/QuestionService.java
>                                                   .orElseThrow(() -> new AuctionNotFoundException("해당 경매를 찾을 수 없습니다."));
### 질문 & 필수
지토 수정해 주셔서 정말 감사합니다!
그런데 질문이 있습니다...
저는 create 시 question에 해당 값을 넣어주는 용도로만 사용하고 있어 fetch join을 사용할 필요가 없습니다.
그래서 원래 사용하던 메서드를 사용해야 할 것 같네요.

그래서 지난번에 함께 이야기했던 대로 `findTotalAuctionById`와 `findPureAuctionById`를 사용하면 어떨까요?

2023-10-11 11:21 UTC, kwonyj1022 approved these changes
수고하셨습니다.

2023-10-11 11:24 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/qna/application/QuestionService.java
>                                                   .orElseThrow(() -> new AuctionNotFoundException("해당 경매를 찾을 수 없습니다."));
으아악 수정하겠습닏 ㅏ

2023-10-12 06:15 UTC, JJ503 approved these changes
수정 내용 확인해 approve 합니다.
고생 많으셨습니다!

2023-10-12 16:45 UTC, swonny approved these changes
고생하셨습니다 지토
지토 코드 보니까 어제 나눴던 이야기들이 더 잘 이해가 되는 것 같아요..허허..
감사합니다!

2023-10-13 00:46 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/JpaAuctionRepository.java
> +        WHERE a.deleted = false AND a.id = :id
👍

2023-10-13 01:01 UTC, merged