Q&A 알림 기능 구현
woowacourse-teams/2023-3-ddang pull request #614
Opened 2023-10-11 06:00 UTC by swonny

## 📄 작업 내용 요약
Q&A 알림 기능 구현

Q&A 알림

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

### 기능 관련

- 간단한 메서드 추가 작업이라 어려운 부분은 없습니다.

### 리팩토링 관련

- 기존에는 이벤트 DTO에 도메인 DTO를 저장하고 있었습니다. 코드는 다음과 같습니다.

```java
// 메시지 알림 이벤트 DTO
public record MessageNotificationEvent(MessageDto messageDto) {
}

```

```java
// 메시지 도메인 DTO
public record MessageDto(
        Long id,
        LocalDateTime createdTime,
        ChatRoom chatRoom,
        User writer,
        User receiver,
        String contents,
        String profileImageAbsoluteUrl
) {
    // 정팩메 생략
}

```

도메인을 DTO로 변환하여 이벤트 DTO를 생성했던 이유는 도메인이 그대로 다른 레이어에 노출되는 것을 방지하고자 하는 목적이었다고 생각하고 코드를 짰는데, 필드들을 감싸고 있는 객체만 도메인에서 DTO로 변경되었다는 점 외에는 도메인과 똑같다고 생각했습니다. 따라서 DTO로 한 번 감싸는 것은 불필요한 코드만 길어진다고 생각해 그냥 도메인을 넘기게 되었습니다.

이후에는 이벤트 DTO에서 정팩메를 생성하고, 정팩메 파라미터로 도메인을 받아 이벤트에 필요한 필드만 선별하여 이벤트 리스너로 전송하게 하려는 시도를 했습니다. 그런데 해당 방식은 이벤트 생성을 위해 필요한 필드를 선별하는 과정에서 예기치 못한 예외가 발생할 가능성이 있다고 생각했습니다. 그리고 알림 전송 이벤트 로직을 수행하는 과정에서 예외가 발생할 경우 알림 전송을 위한 비즈니스 로직에도 영향을 미치게 되기 때문에 이벤트 DTO에서는 최대한 전달을 위한 getter와 생성자만 존재하도록 하는 것이 좋을 것 같다고 생각했습니다.

따라서 앞서 말씀드린 것처럼 서비스 레이어에서 생성한 도메인을 이벤트 DTO로 감싸서 그대로 이벤트 리스너에게 전달하고, 이벤트 리스너에서 이벤트 수행을 위한 필드를 선별하는 책임을 가져가도록 구현했습니다. (입찰의 경우만 예외적으로 Bid 도메인에 포함되지 않은 필드(기존 입찰자)가 필요해 BidDto를 생성하게 되었습니다.)

아무튼 해당 부분은 도메인 범위 축소를 이야기하면서 자연스럽게 해결될 수 있을 것 같고, 개선 방안은 조금 더 고민을 해보도록 하겠습니다.
코드를 보면서 의문이 드실 수 있을 것 같아 미리 PR에 작성해둡니다!

## 📎 Issue 번호

- closed #587

2023-10-11 10:14 UTC, apptie approved these changes
고생하셨습니다
말씀해주신대로 도메인 쪽 리펙토링을 하면서 고민을 더 해볼 수 있을 것 같아요 
(chat.application 하위니까 말씀해주신대로 도메인으로 그냥 넘겨도 되는지 등등..?)

질문 하나랑 함께 approve 하도록 하겠습니다

2023-10-11 10:25 UTC, kwonyj1022 requested changes
저번 pr에 있던 리뷰들을 그대로 다시 가져온 겁니다. 추가한 사항은 없어요!

2023-10-11 10:25 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
> +        messageEventPublisher.publishEvent(new MessageNotificationEvent(message, profileImageAbsoluteUrl));
### 선택
옛날에 컨벤션 회의할 때 엔티티를 저장하고 나서는 save()의 반환값을 사용하기로 했던 것 같습니다. 그래서 MessageNotificationEvent 안에 persistMessage를 넣으면 좋을 것 같습니다.

2023-10-11 10:25 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
> +                    question.getContent(),
### 질문
알림 제목을 질문 내용으로 하기로 정한 건가요? 확인차 여쭤봅니다.
또, 질문 내용 같은 경우에는 내용이 많아서 길어질 수 있는데 이런 경우에는 어떻게 되는지 궁금합니다.

2023-10-11 10:25 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/qna/application/AnswerService.java
>                                 .getId();
### 질문
지금은 상관없는 이야기일 수도 있고 제가 트랜잭션이 어떻게 동작하는지 정확하게 몰라서 생기는 의문일 수도 있습니다. 만약에 알림 이벤트에서 answer의 id를 사용해야 한다면 이벤트에 담기는 시점에 id가 없어서 문제가 생길 수도 있지 않을까요? 그렇다면 save를 하고 나서 이벤트를 publish 해야할 것 같습니다.

2023-10-11 10:25 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/qna/application/QuestionService.java
>                                   .getId();
### 질문
이 부분도 위에 AnswerService와 동일한 질문을 드리고 싶습니다.

2023-10-11 10:25 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
> +            );
### 선택
AnswerService에서는 다음과 같은 로직으로 Answer를 생성하고 연관관계를 세팅하고 저장합니다.

```java
final User writer = userRepository.findById(answerDto.userId())
                                  .orElseThrow(() -> new UserNotFoundException("해당 사용자를 찾을 수 없습니다."));
final Question question = questionRepository.findById(answerDto.questionId())
                                            .orElseThrow(() ->
                                                    new QuestionNotFoundException("해당 질문을 찾을 수 없습니다.")
                                            );
checkInvalidAnswerer(question, writer);
checkAlreadyAnswered(question);
final Answer answer = answerDto.toEntity();
question.addAnswer(answer);
```
이때 answer를 저장하기 위해서는 question의 id만 필요하기 때문에 question을 findById로 가져오고 있습니다. (lazy 로딩)
그런데 알림을 전송할 때는 question에 있는 writer, auction, auction의 이미지를 가지고 오고 있어서 n+1이 발생할 것 같습니다.

2023-10-11 10:25 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
> +            );
### 선택
여기도 마찬가지로 QuestionService에서는 Auction 가져올 때 fetch join 없이 id만 가져오기 때문에 여기서도 n+1이 발생할 것 같습니다.

2023-10-11 10:25 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/qna/application/dto/QuestionDto.java
> +        return new QuestionDto(
### 필수
나도 드디어 final 발견!! 여기 final 빠졌어요~
그런데 이거 보니까 사용하지 않는 dto인 것 같습니다. 삭제해 주세요

2023-10-12 08:39 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
> +                    question.getContent(),
해당 기능을 구현할 때는 해당 기능을 만들지 결정되지 않은 상태라 임시로 저장했습니다.
안드로이드분들과 논의해보겠습니다. 감사합니다.

2023-10-12 08:46 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/qna/application/AnswerService.java
>                                 .getId();
제가 이해한 바로는 해당 트랜잭션이 모두 커밋된 이후에 이벤트가 발행됩니다.
따라서 실제로 이벤트 리스너의 메서드 내부에서는 커밋된 아이디를 조회할 수 있습니다.

그런데 레포지토리에 엔티티를 저장한 이후에 저장된 엔티티를 이용하는 것이 좋을 것 같아 레포지토리에 저장하는 로직을 먼저 수행하도록 수정했습니다.

2023-10-13 01:08 UTC, JJ503 approved these changes
메리 고생 많으셨습니다!
저는 수정 사항이 따로 보이지 않아 approve 합니다.
코드 수정 사항에 대한 주의 내용만 코멘트해 두었습니다.

2023-10-13 05:03 UTC, kwonyj1022 approved these changes
수고하셨습니다. 별도의 이슈로 관리하기로 했던 부분에 대해 답변으로 적어주시면 좋을 것 같습니다! (기록을 위해..)

2023-10-13 13:43 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
> +            final ProfileImage profileImage = message.getReceiver().getProfileImage();
감사합니다 제이미

2023-10-13 13:44 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
> +            );
해당 부분 PR 머지 이후 리팩토링 예정이라고 논의되어서 이슈 파서 진행하겠습니다!

2023-10-13 13:46 UTC, merged

2023-10-13 13:51 UTC, swonny commented on backend/ddang/src/test/java/com/ddang/ddang/qna/application/QuestionServiceTest.java
> +@RecordApplicationEvents
이벤트가 발행되면 발행된 이벤트에 해당하는 이벤트 리스너가 이벤트를 전달 받아 메서드를 수행하게 됩니다. 이처럼 이벤트가 발행되는 것을 기록할 수 있는 어노테이션이라고 알고 사용했습니다. 해당 어노테이션과 빈으로 주입받은 `ApplicationEvents`를 함께 사용해서 이벤트에 대한 검증 테스트를 작성할 수 있었습니다.
아까 말씀드린 것처럼 어떻게 동작하는지는 아직 자세히 알아보지 않아서.. 아마..... 디스커션에 남길 때 생각나면 함께 적어두도록 하겠슴다...