Authentication 관련 인프라 리펙토링
woowacourse-teams/2023-3-ddang pull request #647
Opened 2023-10-13 13:00 UTC by apptie

## 📄 작업 내용 요약

- Authentication 관련 인프라 리펙토링
- JpaBlackListToken에서 누락된 테스트 추가 
## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

## 📎 Issue 번호

- closed #645

2023-10-13 16:30 UTC, kwonyj1022 approved these changes
수고하셨습니다!

2023-10-13 16:38 UTC, kwonyj1022 reviewed
질문이 생겨서 추가했습니다.

2023-10-13 16:38 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/persistence/BlackListTokenRepositoryImplTest.java
> +    }
### 질문
다른 pr들도 다 이 부분에 대해 아래처럼 작성하지 않고 BeforeEach에서 직접 생성해 주는 방식으로 한 이유가 궁금합니다.
```java
@Autowired
JpaBlackListTokenRepository blackListTokenRepository;    
```

2023-10-13 16:48 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/persistence/BlackListTokenRepositoryImplTest.java
> +    }
현재 이 테스트는 `infrastructure` 파트로 `@DataJpaTest`를 사용하고 있습니다
이 때 `@DataJpaTest`가 `DI`해주는 영역은 모두 `JpaRepository`을 상속해 구현체를 `JPA`가 만들어줄 수 있는 인터페이스 뿐입니다

저희가 이전에는 `Querydsl` 관련된 부분을 인터페이스와 그 구현체로 만들어서 `extends JpaRepository, QuerydslInterface`와 같이 확장해서 `JPA`가 `Querydsl` 관련 파트까지 합쳐서 그 구현체를 자동으로 만들어줬기 때문에 `@Autowired`로 받은 `JpaRepository`로 테스트할 수 있었던 것이며, 이러한 관계를 끊어줬기 때문에 `@Autowired`로 받지 못한다고 봐 주시면 될 것 같습니다 

사실 지금 테스트 시 `JpaRepository`가 아닌 `QuerydslAuctionAndImageRepository` 인터페이스 자체를 테스트한다면 이것도 지금 코드와 동일하게 `@BeforeEach`에서 `@Autowired`로 `JPAQueryFactory`를 주입받아서 직접 생성을 해주어야 합니다 

아무튼 `BlackListTokenRepository`의 경우 `JpaRepository`를 필드로 갖고 있을 뿐 `JpaRepository`와의 직접적인 연관이 없기 때문에 직접 생성해주어야 하므로 위와 같이 `@BeforeEach`로 생성해줬다고 봐주시면 될 것 같습니다

2023-10-13 16:54 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/persistence/BlackListTokenRepositoryImplTest.java
> +    }
아하 DataJpaTest는 querydsl을 DI 해주지 못하는군요! 답변 감사합니다 👍

2023-10-13 17:20 UTC, swonny approved these changes
첫 작업 고생 많으셨습니다 지토!!
커밋 단위도 깔끔하고 특이사항도 찾지 못해 approve합니다.

2023-10-14 04:53 UTC, JJ503 requested changes
지토 고생 많으셨습니다!
그런데 질문이 하나 있으며, 해당 질문이 맞다면 필수로 변경되게 될 것 같아 일단 rc로 처리해두었습니다.
확인해주시면 감사하겠습니다!

2023-10-14 04:53 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/persistence/fixture/BlackListTokenRepositoryFixture.java
> +    private JpaBlackListTokenRepository blackListTokenRepository;
### 질문 & 필수
해당 Fixture에서도 `JpaBlackListTokenRepository`는 `BlackListTokenRepository`로 변경되게 될까요?
이 질문에 대한 이야기가 맞다면 필수라는 의미입니다..!

2023-10-14 05:01 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/persistence/fixture/BlackListTokenRepositoryFixture.java
> +    private JpaBlackListTokenRepository blackListTokenRepository;
네 맞습니다 
지금 요것도 변경중인데 테스트가 깨지네요

2023-10-14 05:43 UTC, JJ503 approved these changes
수정 내용 확인해 approve 합니다!
고생 많으셨습니다~

2023-10-14 06:05 UTC, kwonyj1022 requested changes
질문이 생겨서 rc로 바꿉니다.

2023-10-14 06:05 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/persistence/fixture/BlackListTokenRepositoryFixture.java
> +
### 필수
여기서 BlackListTokenRepository를 사용하신다고 했는데 수정이 안된 것 같습니다

2023-10-14 06:08 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/persistence/fixture/BlackListTokenRepositoryFixture.java
> +
밑에 25번째 줄에서는 `final BlackListTokenRepository blackListTokenRepository`를 메서드 지역변수로 받아서 `BlackListTokenRepositoryImpl`로 `save`하고 있습니다

저 `@Autowired`는 `BlackListTokenRepositoryImpl`을 생성하기 위해 필요한 의존성이므로 반드시 필요해서 유지했습니다

2023-10-14 06:09 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/persistence/fixture/BlackListTokenRepositoryFixture.java
> +
아아 그렇군요! 감사합니다!

2023-10-14 06:10 UTC, kwonyj1022 approved these changes
답변 감사합니다. 👍

2023-10-14 06:16 UTC, merged