Auction 관련 인프라 리펙토링
woowacourse-teams/2023-3-ddang pull request #651
Opened 2023-10-13 15:49 UTC by apptie

## 📄 작업 내용 요약

Auction 관련 인프라 리펙토링
## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

`AuctionReportService` 파트에서 비즈니스 로직의 변경 사항이 있습니다

```
@Transactional
public Long create(final CreateAuctionReportDto auctionReportDto) {
    final User reporter = userRepository.findById(auctionReportDto.reporterId())
                                        .orElseThrow(() -> new UserNotFoundException("해당 사용자를 찾을 수 없습니다."));
    final Auction auction = auctionRepository.findById(auctionReportDto.auctionId())
                                             .orElseThrow(() -> new AuctionNotFoundException("해당 경매를 찾을 수 없습니다."));
    checkInvalidAuctionReport(reporter, auction);

    final AuctionReport auctionReport = auctionReportDto.toEntity(reporter, auction);

    return auctionReportRepository.save(auctionReport)
                                  .getId();
}

private void checkInvalidAuctionReport(final User reporter, final Auction auction) {
    if (auction.isOwner(reporter)) {
        throw new InvalidReporterToAuctionException("본인 경매글입니다.");
    }
    if (auction.isDeleted()) {
        throw new InvalidReportAuctionException("이미 삭제된 경매입니다.");
    }
    if (auctionReportRepository.existsByAuctionIdAndReporterId(auction.getId(), reporter.getId())) {
        throw new AlreadyReportAuctionException("이미 신고한 경매입니다.");
    }
}
```

기존에는 `JpaRepository`가 기본적으로 제공해주는 `findById()`를 사용하고 있었습니다 
근데 이거를 `AuctionRepository`로 변경하면서 삭제된 경매는 조회하지 않는 메서드로 교체가 되었습니다(`AuctionRepository.findPureAuctionById() / AuctionRepository.findTotalAuctionById()`)

처음에는 `AuctionRepository`에 `findById()`를 정의하는 걸 고려했는데 이전에 회의에서 삭제된 경매는 쿼리에서 조건을 걸어서 조회하지 않도록 하기도 했고, `findById()`는 여기서만 사용되기 때문에 해당 예외 처리 로직을 삭제하는게 낫다고 생각했습니다

```
@Transactional
public Long create(final CreateAuctionReportDto auctionReportDto) {
    final User reporter = userRepository.findById(auctionReportDto.reporterId())
                                        .orElseThrow(() -> new UserNotFoundException("해당 사용자를 찾을 수 없습니다."));
    final Auction auction = auctionRepository.findTotalAuctionById(auctionReportDto.auctionId())
                                             .orElseThrow(() -> new AuctionNotFoundException("해당 경매를 찾을 수 없습니다."));
    checkInvalidAuctionReport(reporter, auction);

    final AuctionReport auctionReport = auctionReportDto.toEntity(reporter, auction);

    return auctionReportRepository.save(auctionReport)
                                  .getId();
}

private void checkInvalidAuctionReport(final User reporter, final Auction auction) {
    if (auction.isOwner(reporter)) {
        throw new InvalidReporterToAuctionException("본인 경매글입니다.");
    }
    if (auctionReportRepository.existsByAuctionIdAndReporterId(auction.getId(), reporter.getId())) {
        throw new AlreadyReportAuctionException("이미 신고한 경매입니다.");
    }
}
```

그래서 `이미 삭제된 경매입니다.`와 관련된 예외 처리 로직을 삭제하게 되었습니다 
관련된 테스트도 변경한 상태입니다 

이렇게 진행해도 괜찮을지 아니면 `AuctionRepository.findById()`를 추가로 정의한 뒤 나중에 삭제하는 방향으로 갈지를 중점적으로 리뷰해주시면 감사하겠습니다 

## 📎 Issue 번호

- closed #649

2023-10-13 18:28 UTC, kwonyj1022 requested changes
필수가 있어서 rc입니다..

2023-10-13 18:28 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/AuctionForListByBidderIdTest.java
> +        querydslAuctionRepository = new QuerydslAuctionRepository(queryFactory);
### 선택
이 부분 변경사항 보다가 생각난 건데, AuctionForList~ Test 들이 테스트 내부를 보지 않고도 Querydsl을 사용한 repository의 테스트임을 알 수 있도록 클래스 이름을 수정하거나 패키지안에 넣는 등의 작업은 굳이인가요?

2023-10-13 18:28 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/fixture/AuctionRepositoryImplFixture.java
> +    private JpaAuctionRepository auctionRepository;
### 질문
이 부분도 그렇고 다른 pr들도 그렇고 픽스처에서 Jpa가 붙은 레포지토리를 사용하시던데 AuctionRepository를 사용해야 하지 않을까요?

2023-10-13 18:28 UTC, kwonyj1022 commented on backend/ddang/src/test/java/com/ddang/ddang/report/application/AuctionReportServiceTest.java
> +                .hasMessage("해당 경매를 찾을 수 없습니다.");
### 질문
이 부분은 테스트코드를 보니까 조금 헷갈려서 질문드립니다. 
사용자 입장에서는 경매 상세페이지 들어가서 경매를 분명히 봤는데 신고를 하니까 해당 경매를 "찾을 수 없다"는 메시지를 받게 되는데 이에 대해 이상하게 생각하지는 않을지 궁금합니다. "찾을 수 없다"라는 말이 "삭제되었다"라는 생각으로 이어질지 궁금합니다. 제 개인적으로는 삭제되었나보다 할 수도 있겠다 싶기는 한데 다른 분들은 어떤지 궁금하네요.

2023-10-14 03:20 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +    private final QuerydslAuctionRepository querydslAuctionRepository;
이부분을 놓쳤군요 수정하겠습니다

2023-10-14 03:22 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java
> +                                         .orElseThrow(() -> new AuctionNotFoundException("해당 경매를 찾을 수 없습니다."));
👍

2023-10-14 03:24 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/report/application/AuctionReportService.java
> +        final Auction auction = auctionRepository.findTotalAuctionById(auctionReportDto.auctionId())
저는 PR의 용도에 따라서 써도 된다고 생각합니다 
AuctionService라는 클래스 하나에 벅가 있어서 수정해야하는 경우라거나 이런건 좀 명확하게 표현해도 괜찮지 않을까 생각합니다
그렇습니다

2023-10-14 03:24 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/AuctionForListByBidderIdTest.java
> +        querydslAuctionRepository = new QuerydslAuctionRepository(queryFactory);
좋은 의견인 것 같습니다 반영하겠습니다

2023-10-14 03:28 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/AuctionForListByBidderIdTest.java
> +        querydslAuctionRepository = new QuerydslAuctionRepository(queryFactory);
querydsl 전용 테스트가 아닌 목록 조회 테스트이니 list라는 패키지로 분리하겠습니다

2023-10-14 03:31 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/fixture/AuctionRepositoryImplFixture.java
> +    private JpaAuctionRepository auctionRepository;
Fixture는 저장만 해도 되니까 어떤걸 사용해도 괜찮다고 생각했었습니다 

예를 들어서 Category의 경우 직접 DB에 값을 저장하기 때문에 save()를 비즈니스 로직에서 호출하지 않습니다 
그래서 Category 관련 Fixture를 만들기 위해서 domain 영역의 repository에 save()를 추가하면 테스트만을 위한 코드가 될 것이므로 그냥 JpaCategory를 쓰는 것이 맞다고 판단했습니다

이런 특이 케이스가 있어서 Fixture에서는 아무튼 저장만 해도 괜찮다고 생각했었습니다

2023-10-14 03:33 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/report/application/AuctionReportServiceTest.java
> +                .hasMessage("해당 경매를 찾을 수 없습니다.");
저는 삭제되서 찾을 수 없다는 의미로 사용하기는 했었습니다 

안드로이드에서도 삭제된 경매의 경우 목록에서 보이지 않게 캐시에서 삭제해주시는 걸로 알고 있어서 사용자가 신고할 수 없다는 메세지를 봤을 때 목록으로 돌아가는 경우 신고하고자 하는 경매가 목록에서 보이지 않을테니 괜찮다고 생각했었습니다

2023-10-14 03:49 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/report/application/AuctionReportService.java
> +        final Auction auction = auctionRepository.findTotalAuctionById(auctionReportDto.auctionId())
커밋에 클래스 이름을 쓰지 않기로 했던거는 나중에 해당 클래스가 없어지거나 이름이 변경되었을 때 혼란을 방지하기 위해서인데 pr도 상위 브랜치에는 커밋으로 쌓이게 되지 않나요? 아니면 머지할 때 이름을 바꾸려고 하신건가요

2023-10-14 04:02 UTC, kwonyj1022 approved these changes
수고하셨습니다!

2023-10-14 04:02 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/report/application/AuctionReportService.java
> +        final Auction auction = auctionRepository.findTotalAuctionById(auctionReportDto.auctionId())
커밋에 클래스 이름을 쓰지 않기로 했던 거는 나중에 해당 클래스가 없어지거나 이름이 변경되었을 때 혼란을 방지하기 위해서인데 pr도 상위 브랜치에는 커밋으로 쌓이게 되지 않나요? 아니면 머지할 때 이름을 바꾸려고 하신 건가요

2023-10-14 04:25 UTC, swonny approved these changes
고생하셨습니다 지토
경매쪽이라 역시 변경된 파일 수가 장난 아니네요.. 
approve하겠습니다!

2023-10-14 04:25 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/report/application/AuctionReportService.java
>          if (auctionReportRepository.existsByAuctionIdAndReporterId(auction.getId(), reporter.getId())) {
### 칭찬

PR에 작성해주신 것처럼 deleted가 false인 경매글만 가져오니 검증 로직은 불필요하겠네요 👍🏻

2023-10-14 04:25 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/report/application/AuctionReportService.java
> +        final Auction auction = auctionRepository.findTotalAuctionById(auctionReportDto.auctionId())
이전 PR에서 logback-spring.xml 설정 변경이라고 명확하게 지정을 한 경우가 있어서 이렇게 말씀드렸었습니다 

혹시 지금 PR 이름이나 커밋에 문제가 있을까요?

2023-10-14 04:38 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/report/application/AuctionReportService.java
> +        final Auction auction = auctionRepository.findTotalAuctionById(auctionReportDto.auctionId())
아 왜 이렇게 말씀하셨는지 이해했습니다 커밋 메세지에 AuctionRepository가 언급되서 그런거였군요
이 부분은 제가 인지하고 못하고 잘못한 부분인 것 같습니다 
반영하겠습니다

2023-10-14 04:44 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/report/application/AuctionReportService.java
> +        final Auction auction = auctionRepository.findTotalAuctionById(auctionReportDto.auctionId())
오잉 저는 pr 이름을 말씀드린거긴 했습니다.. 커밋은 확인을 못했네요

2023-10-14 05:00 UTC, JJ503 requested changes
지토 고생 많으셨습니다!
현재 코드에서 수정 사항은 보이지 않지만, 해당 pr에 대한 질문이 있어 rc로 처리했습니다.

저는 어제 회의에서 `JpaAuctionRepository` 테스트 외의 `JpaAuctionRepository`를 사용하는 곳에서는 새로 만든 `AuctionRepository`을 사용할 것이라고 이해했습니다.
하지만 그러지 않고 경매 레파지토리 관련 테스트 외에서는 `JpaAuctionRepository`를 사용한 이유가 궁금합니다!

2023-10-14 05:12 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/report/application/AuctionReportService.java
> +        final Auction auction = auctionRepository.findTotalAuctionById(auctionReportDto.auctionId())
그럼 모르겠어요! 구체적인 클래스 이름을 pr에 적는게 좀 애매하긴 합니다만 logback-spring.xml과 같이 뭔가 설정파일을 구체적으로 말하지 않으면 너무 장황해질 것 같기도 하고 해서 안쓰는게 나을 것 같기도 하고 모르겠네요

2023-10-14 05:12 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/report/application/AuctionReportService.java
>          if (auctionReportRepository.existsByAuctionIdAndReporterId(auction.getId(), reporter.getId())) {
👍

2023-10-14 05:15 UTC, apptie commented
@JJ503 
Category에서 특이케이스가 발생했기 때문에 Fixture에서는 굳이 지킬 필요가 없겠다고 생각했습니다
근데 지금 리뷰를 받아보니 그래도 최대한 Fixture도 제어하는게 DB 의존성 변경 시 변경의 여지를 줄일 수 있겠네요
반영하도록 하겠습니다

2023-10-14 05:59 UTC, JJ503 approved these changes
수정 사항 확인 완료했습니다!
files changed를 보니 아찔하네요...
리팩터링 첫 타자셨는데 정말 고생 많으셨습니다!
3시까지 모든 approve 받기 성공이시네요 일정 추산 짱!

2023-10-14 06:02 UTC, merged