소셜 로그인할 때 만약 첫 회원가입인 경우, 닉네임 및 프로필 설정페이지를 먼저 보여주기
woowacourse-teams/2023-3-ddang pull request #666
Opened 2023-10-14 14:58 UTC by rhthrhrl0

## 📄 작업 내용 요약
소셜 로그인할 때 만약 첫 회원가입인 경우, 닉네임 및 프로필 설정페이지를 먼저 보여주기
온보딩 액티비티 및 프로필 세팅 프래그먼트 추가 및 로그인 로직 수정

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드
추후 수정 예정

## 📎 Issue 번호
- close: #652

2023-10-15 06:49 UTC, ippnsj requested changes
수고했어요~ 멘델! 👍
프로필 수정이란게 기존 값은 url 형식이고 수정된 값은 uri 형식이라 까다롭네요 😵‍💫

2023-10-15 06:49 UTC, ippnsj commented on android/app/src/main/java/com/ddangddangddang/android/feature/onboarding/profile/ProfileSettingViewModel.kt
> +        if (name == currentProfileName && profile.value?.path == currentProfileUri.path) return setNavigateToNextEvent()
위에서 `takeIf { it.path != currentProfileUri.path }` 로 값을 비교해주고 있으니
name == currentProfileName && profileImageUri == null 일 때 return 해줘도 되지 않을까요?

2023-10-15 06:49 UTC, ippnsj commented on android/app/src/main/java/com/ddangddangddang/android/feature/onboarding/profile/ProfileSettingViewModel.kt
> +    fun submitProfile(context: Context) {
프로필 수정 프래그먼트의 우측 하단 버튼이 마치기가 아닌 다음인 경우에도 프로필 수정이 이루어지겠군요!
그럼 다음 페이지에서 건너뛰기를 누른 사용자는 프로필이 수정되기를 원치 않을수도 있지 않을까요? 🤔

2023-10-15 07:38 UTC, rhthrhrl0 commented on android/app/src/main/java/com/ddangddangddang/android/feature/onboarding/profile/ProfileSettingViewModel.kt
> +    fun submitProfile(context: Context) {
그거 떄문에, 반나절을 고민한 것 같은데, 일단, 건너뛰기를 할 때 그동안 한 모든 내용을 건너뛰려면 애초에 모든 통신 작업을 온보딩뷰모델에서 해야하고, 그렇게 되면 나중에 온보딩 페이지가 수정될 때 유연성도 떨어지고, 온보딩 페이지에서 여러 통신작업을 순차적으로 한다면, 처리 속도또한 집중돼서 사용자가 느끼기에 너무 느리다고 생각할 수 있을 것 같습니다. 
가장 큰 이유는 만약 제가 사용자면 한 페이지가 넘어가면 그 페이지까지는 처리가 돼주기를 원할 것 같습니다. 만약 작업을 다했는데, 한 페이지 내비두고 건너뛰기 했다고 그동안 한 설정들이 다 사라지면, 그건 그거대로 유저에게 안좋은 경험을 주고 시작하는 것 아닐까요???

2023-10-15 07:55 UTC, hyemdooly requested changes
고생하셨습니다! 간단한 리뷰 몇개 남겼어요~

2023-10-15 07:55 UTC, hyemdooly commented on android/app/src/main/java/com/ddangddangddang/android/feature/login/LoginActivity.kt
> +        startActivity(Intent(this, OnBoardingActivity::class.java))
intent를 OnBoardingActivity에서 생성하게끔 하면 어떨까요?

2023-10-15 07:55 UTC, hyemdooly commented on android/app/src/main/java/com/ddangddangddang/android/feature/onboarding/OnBoardingActivity.kt
> +        startActivity(Intent(this, MainActivity::class.java))
여기도 MainActivity가 intent를 생성하게끔 하면 어떨까요?

2023-10-15 08:05 UTC, rhthrhrl0 commented on android/app/src/main/java/com/ddangddangddang/android/feature/login/LoginActivity.kt
> +        startActivity(Intent(this, OnBoardingActivity::class.java))
Main이랑 OnBoadring이랑 추가로 LoginActivity도 캡슐화 진행했습니다

2023-10-15 18:02 UTC, ippnsj commented on android/app/src/main/java/com/ddangddangddang/android/feature/onboarding/profile/ProfileSettingViewModel.kt
> +    fun submitProfile(context: Context) {
그런거라면 나중에 다음 페이지로 이동하는 버튼의 텍스트가 수정사항이 저장된다는 의미를 내포하면 좋을 것 같아요!
만약 `다음`과 같은 텍스트라면 사용자가 저장된다는 것을 인지하지 못할수도 있을 것 같아서요! 😉

2023-10-15 18:05 UTC, ippnsj commented on android/app/src/main/java/com/ddangddangddang/android/feature/onboarding/profile/ProfileSettingViewModel.kt
> +    fun submitProfile(context: Context) {
근데 또 생각해보면 회원가입이 길어지고 서버 통신이 많은게 맞을까 싶기도 하네요!
프로필 수정까지는 괜찮지만 이외에 서버 통신이 추가된다면 회원가입하다가 지루해하는 유저도 있겠는걸요? 😂

2023-10-15 18:07 UTC, ippnsj approved these changes
수고했어요 멘델~!
멘델의 의견도 납득이 가요! 👍
저도 멘델의 의견에 대해 두 가지 의견을 남겼는데 나중에 좀 더 얘기해보아요~! 😉

2023-10-16 04:44 UTC, hyemdooly approved these changes
고생하셨습니다~!

2023-10-16 06:36 UTC, merged