질문 작성/답변 작성 다이얼로그 그리기 및 서버 연동
woowacourse-teams/2023-3-ddang pull request #679
Opened 2023-10-14 17:36 UTC by hyemdooly

## 📄 작업 내용 요약
다이얼로그 그리고 서버 연동까지 했습니다.
파일이 좀 많이 바뀌었을 것 같아요!ㅠㅠ 어려운 부분 있으시면 DM해주세요~

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

```kotlin
private val onClicks = object : QnaAdapter.OnClicks {
        override fun onQuestionClick(questionId: Long) {
            viewModel.selectQna(questionId)
        }

        override fun onSubmitAnswerClick(questionId: Long) {
            activityViewModel.auctionDetailModel.value?.let { model ->
                WriteAnswerDialog.show(parentFragmentManager, model.id, questionId)
            }
        }

        override fun onDeleteQuestionClick(questionId: Long) {
            viewModel.deleteQuestion(questionId)
        }

        override fun onDeleteAnswerClick(answerId: Long) {
            viewModel.deleteAnswer(answerId)
        }

        override fun onReportQuestionClick(questionId: Long) {
            viewModel.reportQuestion(questionId)
        }

        override fun onReportAnswerClick(questionId: Long, answerId: Long) {
            viewModel.reportAnswer(questionId, answerId)
        }
    }
```
QnA 한 아이템에서 onClick이 많이 있어서 interface로 정의해뒀어요.
이 액티비티에서밖에 사용하지않는 코드라서 분리하지 않았습니다.

```kotlin
@HiltViewModel
class WriteAnswerViewModel @Inject constructor(private val repository: AuctionRepository) : ViewModel() {

    //...
    private var _auctionId: Long? = null
    private val auctionId: Long
        get() = _auctionId!!
    private var _questionId: Long? = null
    private val questionId: Long
        get() = _questionId!!
```
변수 한 개만 nullable이면 처리를 하겠는데 두가지가 nullable이라 ?.let 구문이 중첩되는 경우가 많이 생겨서 이렇게 처리했습니다.
```kotlin
object QnaModelMapper {
    fun QnaResponse.toPresentation(isOwner: Boolean): QnaModel {
        return QnaModel(
            qnas.map {
                QnaModel.QuestionAndAnswerModel(
                    it.question.toPresentation(),
                    it.answer?.toPresentation(),
                    isOwner,
                    false,
                    QnaStatusModel.find(it.answer != null),
                )
            },
        )
    }
```
판매자인지아닌지 서버에서 넘겨주고 있지 않고, activityViewModel에서 충분히 가져오는 값이라고 생각해서 요청하지 않았습니다.
다만, Mapper클래스를 상속받으면 toPresentation에서 인자를 받을 수 없어 상속받지 않고 구현했어요~!

```kotlin
sealed class ReportInfo : Serializable {
    data class ArticleReportInfo(val auctionId: Long) : ReportInfo()
    data class MessageRoomReportInfo(val roomId: Long) : ReportInfo()
    data class QuestionReportInfo(val auctionId: Long, val questionId: Long) : ReportInfo()
    data class AnswerReportInfo(val auctionId: Long, val questionId: Long, val answerId: Long) : ReportInfo()
}
```
그동안 신고할 때 어떤 신고든 id 하나만 있으면 됐는데요!
질문과 답변의 경우 이렇게 많은 아이디가 필요합니다. 그래서 ReportInfo라는 sealed class로 감싸주었어요.
이거 때문에 다른 액티비티도 수정되어서 file changed가 더 늘어났습니다.ㅠㅠ
그리고 ReportType도 추가되었는데, ReportInfo가 생김으로서 ReportType이 없어도 될 것 같아요!
내일 서버 연동이 원활하게 잘 되면 이 부분도 리팩터링을 해보겠습니다. 👍 

## 📎 Issue 번호

- closed: #646

2023-10-15 14:06 UTC, hyemdooly commented
## 추가 변경사항
### Barrier
Barrier라는 친구를 한번 사용해봤습니다.
신고하기 버튼 / 답변하기 버튼 / (판매자답변의 경우) 작성하기 버튼 셋 중 하나가 활성화 되는데, 이 경우 위아래 뷰에서 한 버튼만을 연결하기가 애매해서 Barrier로 묶어주었습니다.
말그대로 방어막~같은 의미인데 세 뷰를 묶어서 하나의 아이디로 퉁칠 수 있어요!

### QnaViewModel에서 pickedQuestionId 추가
```kotlin
fun QnaResponse.toPresentation(isOwner: Boolean, pickedQuestionId: Long? = null): QnaModel {
         return QnaModel(
             qnas.map {
                 QnaModel.QuestionAndAnswerModel(
                     it.question.toPresentation(),
                     it.answer?.toPresentation(),
                     isOwner,
                     false,
                     pickedQuestionId != null && it.question.id == pickedQuestionId,
                     QnaStatusModel.find(it.answer != null),
                 )
             },
```
질문 등록, 답변 등록 후 리프레쉬를 하는데 이 경우 사용자가 보고있던 화면이 날아가고 새 리스트뷰가 보일 것을 염려했습니다.
따라서 pickedQuestionId를 추가해서, Qna를 로딩하고 toPresentation으로 매핑할 때 이게 선택됐던 질문인지 확인하여 isPicked의 값을 결정하고있어요!
### ReportType 삭제
ReportInfo를 sealed class로 사용함으로서 type이 필요없어졌습니다. 아예 코드에서 사용하고 있지 않아서 삭제했어요.
### 질문/답변 등록 후 리프레쉬 방법
질문/답변 작성 다이얼로그를 보시면 onDialogResult라는 fun interface를 확인하실 수 있습니다.
```kotlin
fun interface OnDialogResult {
      fun invoke(isNeedRefresh: Boolean)
}
fun setOnDialogResult(onDialogResult: OnDialogResult) {
      this.onDialogResult = onDialogResult
}
```
액티비티에서 onDialogResult를 넘겨주면, 다이얼로그를 종류하기 전에 이 함수를 실행합니다.
```kotlin
    private fun setupBinding() {
         binding.clWriteQuestion.setOnClickListener {
             activityViewModel.auctionDetailModel.value?.let { model ->
                 RegisterQuestionDialog.show(parentFragmentManager, model.id, ::onAfterQnaDialogDismiss)
             }
         }
         // ...
     }

     private fun onAfterQnaDialogDismiss(isNeedRefresh: Boolean) {
         if (isNeedRefresh) viewModel.loadQnas()
     }
```
이렇게 isNeedRefresh가 true면 로딩을 하게끔 수정했어요!!

추가로 어려운 부분이 있으시면 말씀해주세요!

2023-10-15 19:25 UTC, ippnsj requested changes
진짜 진짜 수고했어요 둘리! 👍 👍 👍
내일 Api 수정되면 다시 돌려보고 승인해야 할 것 같아요ㅠㅠ
댓글 삭제 말고 조회도 `isQuestioner`이 없어서 동작을 안하는데 백엔드랑 얘기해봐야 할 것 같아요ㅠㅠ 😭 😭 😭

2023-10-15 19:25 UTC, ippnsj commented on android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepositoryImpl.kt
> +        return remoteDataSource.reportAnswer(reportAnswerRequest)
} 가 빠져있어요~

2023-10-15 19:25 UTC, ippnsj commented on android/app/src/main/java/com/ddangddangddang/android/feature/detail/qna/QnaFragment.kt
ReportType을 모두 지워야합니다~!

2023-10-16 04:00 UTC, hyemdooly commented on android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepositoryImpl.kt
> +        return remoteDataSource.reportAnswer(reportAnswerRequest)
충돌 해결하면서 빠졌네요 흑흑

2023-10-16 06:17 UTC, rhthrhrl0 reviewed
고생하셨습니다. 전반적으로 코드가 잘 짜여져서 리뷰하기 편했습니다

2023-10-16 06:17 UTC, rhthrhrl0 commented on android/app/src/main/java/com/ddangddangddang/android/feature/detail/qna/QnaFragment.kt
> +                    parentFragmentManager,
childFragmentManager를 사용하는게 좀 더 적절할 것 같습니다!

2023-10-16 06:17 UTC, rhthrhrl0 commented on android/app/src/main/java/com/ddangddangddang/android/feature/detail/qna/registerquestion/RegisterQuestionDialog.kt
> +            dialog.setOnDialogResult(onDialogResult)
회전했을떄 다이얼로그 프래그먼트가 복구되면서 번들만 정상적으로 받고, OnDialogResult는 못받을 것 같아요!

2023-10-16 11:52 UTC, ippnsj approved these changes
수고했어요 둘리~
답변 신고 기능이랑 가로 모드에서 글자 잘리는 문제만 해결 부탁해요~
진짜 큰 작업이었고 그래서 테스트도 많았는데 피드백 반영하느라 너무 수고 많았어요ㅠㅠ
덕분에 QnA 기능 걱정 안하고 코드 수정 스프린트에 집중할 수 있었습니다ㅠㅠㅠㅠ 고마워요 둘리!! 🥰

2023-10-17 07:24 UTC, rhthrhrl0 approved these changes
QnA작업 쉽지 않으셨을텐데 정말 고생많으셨어요~~ 👍

2023-10-17 08:13 UTC, merged