경매 상세 페이지 수정(마감기한 시간 정보 뷰 수정 및 최고 입찰자 표시)
woowacourse-teams/2023-3-ddang pull request #699
Opened 2023-10-15 15:59 UTC by rhthrhrl0

## 📄 작업 내용 요약
경매 상세 페이지 수정

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드
![image](https://github.com/woowacourse-teams/2023-3-ddang/assets/67176829/b8952254-0fe4-4dee-8799-276ede175905)
=> 여기서, getRemainHeight에서 Context.resources.displayMetrics.heightPixels 는 상태바 높이 + 액티비티 높이(이 안에 툴바도 포함)를 반환합니다. 이 메소드는 네비게이션 바의 높이를 안주기 때문에 큰 장점이 있습니다. 네비게이션 바는 모드가 기종마다 혹은 회사마다 여러 가지라서 개발자가 신경쓰기 힘든 부분인데 이를 고려대상에서 제외한 사이즈를 주기 때문에 아주 나이스합니다.

또한, 안드로이드에서 상태바의 높이는 24dp입니다. 
그렇다면, 저희는 다음과 같이 빼면 정말 딱 맞는 뷰페이저의 높이를 구할 수 있습니다.

Context.resources.displayMetrics.heightPixels - 상태바 높이 - 툴바 높이 - 탭레이아웃 높이 - 상세페이지의 하단 입찰 버튼 높이
하지만, 여기서 문제가 있습니다. 
갤럭시의 경우, 펀치홀이 상태바에 있는 세로모드의 경우, Context.resources.displayMetrics.heightPixels 에서 상태바 높이가 이미 빠진 상태로 나오게 된다는 결론을 내리게 되었습니다(api28, 33 버전의 픽셀2 휴대폰에서는 세로모드와 가로모드에서 모두 상태바가 포함된 높이가 나왔습니다. 또한, 갤럭시의 가로모드에서도 상태바 높이가 포함된 상태로 나오는 것을 확인했습니다. 오직, 갤럭시의 세로모드에서만 상태바 높이가 빠진 상태로 높이가 나오는 것을 실험 결과로 알게 되었습니다).
그렇다고, 로직을 아래와 같이 수정하기에는 다른 기종이나 갤럭시의 가로모드에서 대응이 안됩니다.
Context.resources.displayMetrics.heightPixels - 툴바 높이 - 탭레이아웃 높이 - 상세페이지의 하단 입찰 버튼 높이

때문에, 그냥 상태바 높이인 24dp도 빼주기로 했습니다.
그나마 다행인 점은 저희가 탭레이아웃의 마진톱을 24dp로 해놔서, 펀치홀이 있는 갤럭시 세로모드에서도 그렇게 부자연스럽지 않습니다. 
실기기 사진은 필요하면, 내일 현장에서 보여드리겠습니다.

 
추가적으로, 경매 상세 페이지에서 바텀 하단 버튼과 뷰페이저 스크롤 영역이 겹치지 않도록 했습니다. marginBottom 값을 주어서 해결했습니다. 이 과정에서 바텀 버튼의 높이가 커지면 안되기 때문에 글자 크기를 고정으로 18dp로 설정했습니다. 

## 📎 Issue 번호
- close: #691

2023-10-16 04:43 UTC, hyemdooly approved these changes
고생하셨습니다!!

2023-10-16 04:43 UTC, hyemdooly commented on android/app/src/main/java/com/ddangddangddang/android/feature/detail/AuctionDetailActivity.kt
> +        val statusBarHeight = convertDpToPx(24f) // 탭 레이아웃의 톱 마진과도 같은 값임.
상수로 빼두는 것은 어떨까용?

2023-10-16 08:13 UTC, ippnsj approved these changes
수고했습니다~!
기종별로 모두 테스트해보시다니 👍 👍 👍
정말 대단해요!!!! 👏

2023-10-16 11:27 UTC, ippnsj requested changes
상태바 사이즈가 포함되지 않은 스크린 높이를 구할 수 있는 api를 찾았는데 확인 부탁드려요ㅎㅎ 😉

2023-10-16 11:27 UTC, ippnsj commented on android/app/src/main/java/com/ddangddangddang/android/feature/detail/AuctionDetailActivity.kt
>      }
```kotlin
private fun getRemainingHeight(context: Context): Int {
    val screenHeight = convertDpToPx(resources.configuration.screenHeightDp.toFloat())
    val actionBarHeight = getActionBarHeight(context)
    val tabLayoutHeight = resources.getDimensionPixelOffset(R.dimen.height_submit_button)
    val bottomButtonHeight = resources.getDimensionPixelOffset(R.dimen.height_submit_button)
    return screenHeight - actionBarHeight - tabLayoutHeight - bottomButtonHeight 
}
```
- `resources.configuration.screenHeightDp` 를 사용하면 화면 orientation, cutout 사이즈를 고려하지 않아도 될 것 같아요!
- [screenHeightDp](https://developer.android.com/reference/android/content/res/Configuration#screenHeightDp)

2023-10-17 01:43 UTC, rhthrhrl0 commented on android/app/src/main/java/com/ddangddangddang/android/feature/detail/AuctionDetailActivity.kt
> +            context.theme.obtainStyledAttributes(intArrayOf(com.google.android.material.R.attr.actionBarSize))
좋습니다!

2023-10-17 01:44 UTC, rhthrhrl0 commented on android/app/src/main/java/com/ddangddangddang/android/feature/detail/AuctionDetailActivity.kt
>      }
찾아주셔서 감사합니다! 테스트 중에 픽셀2 api33 버전에서 상태바가 같이 나오고 있는 것 같아서 확인이 필요할 것 같아요!

2023-10-17 06:28 UTC, rhthrhrl0 commented
기존의 동적 뷰페이저 높이 설정에 문제가 많다고 생각이 들어서, CoordinatorLayout을 사용하도록 수정했습니다. 또한, 가로모드에 대한 대응을 적용한 UI도 추가했습니다.

2023-10-17 07:15 UTC, ippnsj approved these changes
CoordinatorLayout이랑 CollapsingToolbarLayout로 수정하느라 수고했어요! 👍 👍 👍
정말 멋져요!!! 딱 원하던 기능이에요!!! 👏

2023-10-17 07:21 UTC, merged