답변 삭제 시 다시 답변을 달지 못하는 문제 해결
woowacourse-teams/2023-3-ddang pull request #704
Opened 2023-10-16 18:23 UTC by JJ503

## 📄 작업 내용 요약

답변 삭제 시 다시 답변을 달지 못하는 문제 해결

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

크게 없습니다

## 📎 Issue 번호

- closed #701

2023-10-16 22:45 UTC, apptie requested changes
안녕하세요
별이 있습니다
감사합니다

2023-10-16 22:45 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/qna/application/AnswerServiceTest.java
> +import org.assertj.core.api.*;
### 필수 

별이 있습니다 1

2023-10-16 22:45 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/qna/domain/AnswerTest.java
> +import org.assertj.core.api.*;
### 필수

별이 있습니다 2

2023-10-16 22:45 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/qna/domain/Question.java
> +        answer = null;
### 선택

이 null도 상수처리하면 가독성의 향상을 노릴 수 있을 것 같네요

2023-10-16 22:45 UTC, apptie commented on backend/ddang/src/test/java/com/ddang/ddang/notification/application/fixture/NotificationEventListenerFixture.java
> +        final Answer 답변 = new Answer(발신자_겸_판매자, "응답 내용");
### 칭찬

네이밍 좋은데요? 👍

2023-10-16 22:45 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/qna/domain/Answer.java
> +            question = null;
### 선택

이 null도 상수처리..? 가독성..?

2023-10-16 23:01 UTC, kwonyj1022 requested changes
제가 지하철이라 나머지 리뷰는 이따 가서 리뷰하겠습니다. 급하게 보이는거 먼저 리뷰합니다.

2023-10-16 23:01 UTC, kwonyj1022 commented on backend/ddang/src/main/resources/db/migration/V20__alter_user_tables.sql
> +alter table users add constraint fk_answer_writer foreign key (writer_id) references writer (id);
### 필수
user 테이블이 아니라 answer 테이블이 바뀌어야 되는 거 아닌가요? 파일명도 `V20__alter_answer_tables.sql`로 바뀌어야 할 것 같습니다!

2023-10-17 00:17 UTC, swonny approved these changes
고생하셨습니다 제이미!
별과 flyway는 중요한 부분이긴한데 엔초와 지토가 코멘트 남겨주셔서 어프루브 하겠습니다

2023-10-17 00:17 UTC, swonny commented on backend/ddang/src/main/java/com/ddang/ddang/qna/domain/Answer.java
> +            question = null;
### 선택

위에서 상수를 사용했으니 여기서도 통일시켜주면 좋을 것 같습니다

2023-10-17 01:36 UTC, JJ503 commented on backend/ddang/src/test/java/com/ddang/ddang/qna/application/AnswerServiceTest.java
> +import org.assertj.core.api.*;
SoftAssertions 좀 혼내주세요..

2023-10-17 01:37 UTC, JJ503 commented on backend/ddang/src/main/resources/db/migration/V20__alter_user_tables.sql
> +alter table users add constraint fk_answer_writer foreign key (writer_id) references writer (id);
악!!!!!
외래키 신경 쓰다가 테이블 신경을 못 썼군요....
엄청 큰일날뻔 감사합니다!

2023-10-17 03:47 UTC, apptie approved these changes
Approve 하겠습니다

2023-10-17 03:51 UTC, kwonyj1022 approved these changes
수고하셨습니다!

2023-10-17 04:52 UTC, merged