입찰 시 입찰의 대상이 되는 경매에 판매자 정보까지 포함해 조회하도록 변경
woowacourse-teams/2023-3-ddang pull request #742
Opened 2023-11-09 04:09 UTC by apptie

## 📄 작업 내용 요약

입찰 시 입찰의 대상이 되는 경매에 판매자 정보까지 포함해 조회하도록 변경
## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

[이슈](https://github.com/woowacourse-teams/2023-3-ddang/issues/741)에 자세히 적어놨습니다 
## 📎 Issue 번호

- closed #741

2023-11-09 04:18 UTC, JJ503 requested changes
답변을 달기 편하도록 코멘트로 질문 남겼습니다!

2023-11-09 04:18 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionAndImageRepository.java
### 질문
해당 fetch 문이 입찰 외에는 필요 없는 것인지 궁금합니다.
사실 입찰 쪽에서는 이미지가 필요 없기 때문에 `AuctionAndImageDto`를 반환 받을 필요가 없습니다.
그래서 기존에는 그냥 `Auction`을 반환 받았는데, dto로 변경된 것을 pr 리뷰 시 놓친 것 같습니다.
그래서 입찰 외에도 seller를 사용하는 곳이 있다면, 의미가 있어 해두는 것이 좋고 이슈와 pr 내용만 바꾸면 될 것같고
입찰 외에는 없다면 이 부분은 제가 입찰 쪽을 수정해야 한다고 생각합니다.

2023-11-09 04:23 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionAndImageRepository.java
입찰 쪽에는 이미지가 필요 없지만 입찰 시 알림을 보낼 때 이미지가 필요해서 이런 식으로 변경된 것으로 알고 있습니다 
그래서 auctionAndImageRepository.findDtoByAuctionId()은 입찰 등록 시에만 사용되는 것으로 알고 있습니다 

지금 상태 그대로 auctionAndImageRepository.findDtoByAuctionId()를 사용하면서 fetch join으로 seller만 추가하면 된다고 생각합니다 

> 그래서 입찰 외에도 seller를 사용하는 곳이 있다면, 의미가 있어 해두는 것이 좋고 이슈와 pr 내용만 바꾸면 될 것같고
입찰 외에는 없다면 이 부분은 제가 입찰 쪽을 수정해야 한다고 생각합니다.

요 부분은 auctionAndImageRepository.findDtoByAuctionId()이 입찰 외에도 사용되는 경우 + seller를 사용해야 하는 경우를 말씀하신게 맞을까요? 
이해한게 맞다면 그냥 입찰 시에만 사용되는 메서드이고 이미지(알림에 쓸 대표 이미지)도 필요하므로 PR 내용처럼 fetch join을 추가하면 된다고 생각합니다

2023-11-09 04:27 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionAndImageRepository.java
아하 검증쪽만 신경써서 알람을 까먹었네요..!
이해했습니다.

2023-11-09 04:27 UTC, JJ503 approved these changes
의문 해소되어 approve 합니다!

2023-11-12 15:26 UTC, kwonyj1022 approved these changes
감사합니다!

2023-12-04 06:48 UTC, closed without merging