DTO 및 그와 연관된 코드 리펙토링
woowacourse-teams/2023-3-ddang pull request #762
Opened 2023-11-28 02:06 UTC by apptie

## 📄 작업 내용 요약

다른 레포지토리에서 작업한 내용이므로 깨집니다 
이런 느낌이다라고만 확인해주시면 될 것 같습니다

다양한 이유로 DTO와 관련된 코드가 복잡해졌기 때문에 이를 해결하기 위해 코드의 수정이 많아진 상황입니다

---

- 구조
	- dto 필드로 존재하는 dto는 inner record로 변경
- 패키지
	- application layer dto 용도에 따라 request / response 패키지로 분리 
- 가짜 중복 허용
	- 별도의 api에서 호출하는 dto의 경우 필드가 동일하다고 하더라도 다른 용도이므로 별도의 dto로 분리
		- 예시) ReadUserInQnaDto를 QuestionerInfoDto, AnswererInfoDto 와 같이 변경
- 네이밍
	- Dto, Dtos 혹은 Response, Responses의 이름을 각각 Single, Multiple 네이밍으로 변경 
	- 첫 번째 Depth인 DTO에만 CRUD 네이밍 사용 
	- 두 번째 Depth인 DTO에는 Info 네이밍 사용
	- 특정 DTO 내부에 어울리는 네이밍으로 변경
		- 예시) ReadUserInQnaDto -> QuestionerInfoDto, AnswererInfoDto)
- 설정
	- DTO에서 @JsonFormat을 제거하기 위해 Jackson 커스터마이징 직렬화 모듈 추가
		- 이로 인한 테스트 환경 리펙토링
- 이미지
	- 이미지 주소 계산 로직 변경
		- DTO에서 수행하지 않음 
		- 이미지 조회 주소를 외부 설정 파일에서 조회
- 결과물
	- auction
		- application
			- 이전 : 구분없이 9개 
			- 이후 : request 1개 response 4개 
		- presentation 
			- 이전 : request 3개 response 15개 
			- 이후 : request 2개 response 4개
	- authentication
		- application
			- 이전 : 구분없이 3개 
			- 이후 : response 4개
		- presentation
			- 이전 : request 4개 response 3개
			- 이후 : request 4개 response 3개
		- 특이사항
			- RandomNameGenerator 유틸리티 삭제, 도메인으로 변경, 변경하면서 전략 패턴 적용
			- 그...application쪽 dto 옮겻음 나중에 적을것
	- bid
		- application
			- 이전 : 구분없이 3개 
			- 이후 : request 1개 response 1개
		- presentation
			- 이전 : request 2개 response 1개
			- 이후 : request 1개 response 1개
		- 특이사항
			- event에 있는 dto를 단순히 사용하고 있던거를 필드로 그대로 가지도록 설정
	- category
		- application
			- 이전 : 구분없이 1개 
			- 이후 : response 1개 
		- presentation
			- 이전 : response 2개
			- 이후 : response 1개 
	- chat
		- application
			- 이전 : 구분없이 10개 
			- 이후 : request 2개 response 4개 
		- presentation
			- 이전 : request 3개 response 8개 
			- 이후 : request 3개 response 5개
		- 특이사항
			- infra의 DTO 삭제
			- infra 관련 전체적인 네이밍 수정 
	- device
		- application
			- 이전 : 구분없이 1개
			- 이후 : request 1개
		- presentation
			- 이전 : request 1개
			- 이후 : request 1개
	- image
		- 생략
	- notification
		- 생략
	- qna
		- application
			- 이전 : 구분없이 7개
			- 이후 : request 1개 response 2개
		- presentation
			- 이전 : request 2개 
			- 이후 : request 2개 response 1개
		- 특이사항
			- 이전에는 ReadQna, ReadQnas가 있었지만 Auction에 위치하고 있었으며 이를 qna 패키지로 이동시킴 분리함
	- region
		- application
			- 이전 : 구분없이 1개
			- 이후 : response 1개
		- presentation
			- 이전 : response 2개
			- 이후 : response 1개
	- report
		- application
			- 이전 : 구분없이 14개 
			- 이후  : request 4개 response 4개
		- presentation
			- 이전 : request 4개 response 13개 
			- 이후 : request 4개 response 4개
	- review
		- application
			- 이전 : 구분없이 4개 
			- 이후 : request 1개 response 2개
		- presentation
			- 이전 : request 1개 response 3개
			- 이후 : request 1개 response 2개
	- user
		- application
			- 이전 : 구분없이 2개
			- 이후 : request 1개 response 1개
		- presentation
			- 이전 : request 1개 response 10개
			- 이후 : request 1개 response 2개
		- 특이사항
			- 사용자 이름, 신뢰도 관련 유틸리티 삭제
			- 도메인에서 수행

## 🙋🏻 리뷰 시 주의 깊게 확인해야 하는 코드

## 📎 Issue 번호

- closed #758

2023-12-03 13:49 UTC, kwonyj1022 requested changes
질문이 좀 있는데 답을 듣고 싶어서 rc 남겨두겠습니다.

2023-12-03 13:49 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageRelativeUrlFinder.java
> +                                                               .toUriString();
### 선택
find 메서드로 반환되는 이미지 주소는 `https://`부터 시작하는 주소이기 때문에 ImageAbsoluteUrlFinder가 아닐까요?

2023-12-03 13:49 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageRelativeUrlFinder.java
> +    }
### 질문
기존에 enum을 사용하던 방식에서 이 방식으로 바뀐 이유가 궁금합니다. 설정값 데이터를 코드(enum 내부)에 직접적으로 위치시키는게 이상해서인가요?

2023-12-03 13:49 UTC, kwonyj1022 commented on backend/ddang/src/main/resources/application-image-local-upload.yml
> +    profile-image: "/users/images/"
### 선택
upload를 해당 위치에 하는 것이 아닌데 설정파일 이름이 upload인 것이 조금 헷갈리는 것 같습니다.

2023-12-03 13:49 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/authentication/application/AuthenticationService.java
> +                              .build();
### 선택
회원 가입 시에 초기 이름을 부여하는 로직은 service에 있는데, 탈퇴하고 다시 랜덤 이름이 지어지는 곳은 User도메인인 점이 헷갈립니다. 굳이 따지자면 도메인 로직이 아닐까 싶긴 한데.. 한 곳으로 통일하는 게 좋을 것 같습니다.
그리고 UserNameGenerator라는 이름을 봤을 때 처음 보는 사람 입장에서는 회원가입 시 최초 이름 만드는 generator인지 탈퇴 시 랜덤 이름 만드는 generator인지 모르겠어서 이름을 좀 더 명확하게 바꾸면 좋을 것 같습니다.

2023-12-03 13:49 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
> +    private Image thumbnailImage;
### 칭찬
감사합니다! 드디어 염원하던 일이..!!

2023-12-03 13:49 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/domain/repository/AuctionRepository.java
> +    Auction getPureAuctionByIdOrThrow(final Long id);
### 질문
이것 저번에 다른 크루 미션한 거 보고 얘기해보고 싶었어요! 예외처리도 한 곳으로 몰고 메서드를 사용하는 서비스 로직도 간결해져서 좋은 것 같습니다.

그런데 저희가 보내는 예외메시지를 안드로이드에서 그대로 띄워주는 경우가 있는데 사용자 입장에서는 예외 메시지가 명확하지 않아서 불편하지 않을까 하는 생각이 듭니다. 

그리고 저희가 예외코드를 사용하지 않기 때문에 안드로이드측에서 저희가 보내는 예외메시지 문자열로 로직을 달리하는 경우도 있다고 들은 것 같아요.

이 두 부분에 대해 안드로이드와의 회의가 필요하지 않을까 싶습니다.

2023-12-03 13:49 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/response/ReadMultipleAuctionDto.java
> +    public record AuctionInfoDto(
### 칭찬
이너클래스 사용하는 거 안 그래도 제안하려고 했는데! 저는 찬성입니다~ 
(마지막 미션에 적용해보고 싶었는데 시간이 없어서 못해서 아쉬웠었어요..)

2023-12-03 13:49 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/response/ReadMultipleAuctionDto.java
> +    ) {
그나저나 이 많은 필드들도 언젠가.. 정리를 해야겠네요..

2023-12-03 13:49 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/dto/MultipleChatRoomInfoDto.java
>          Long unreadMessageCount
### 질문
필드가 List가 아니라서 Single이어야 하는거 아닌가요?

2023-12-03 13:49 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/configuration/WebConfiguration.java
> +    public Module module() {
### 질문
> DTO에서 @JsonFormat을 제거하기 위해 Jackson 커스터마이징 직렬화 모듈 추가 

이 부분을 위한 코드인 것 같은데 dto에서 `@JsonFormat`을 제거하려는 이유가 무엇인지 궁금합니다.

2023-12-03 13:49 UTC, kwonyj1022 commented on backend/ddang/src/main/java/com/ddang/ddang/image/application/ImageService.java
### 질문
이거 저번에 현재 상태로는 auction image는 null인 경우가 없지만 그럼에도 불구하고 이미지 null 처리를 프로필 이미지처럼 할지 말지에 대해 이야기했을 때 동일하게 가기로 했었던 것 같은데 해당 로직을 없앤 이유가 궁금합니다.

2023-12-04 05:58 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageRelativeUrlFinder.java
> +                                                               .toUriString();
그렇네요 네이밍을 놓쳤습니다
Absolute를 붙이거나 아예 관련된 단어를 빼고 ImageUrlFinder로 하던가 하면 되겠네요

2023-12-04 06:03 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageRelativeUrlFinder.java
> +    }
> 설정값 데이터를 코드(enum 내부)에 직접적으로 위치시키는게 이상해서인가요?

네 요런 느낌인데
정확히는 실행 환경(테스트, 로컬, 개발 서버, 운영 서버)에 따라서 달라질 수 있는 값이기 때문에 enum으로 관리할 수 없다고 생각했기 때문입니다
예를 들어서 테스트 시에는 로컬에 저장한다고 가정하고 테스트를 진행하고, 개발 서버에서는 운영 서버에서 사용하는 S3에 영향을 미치지 않도록 별도의 개발 서버 테스트용 S3를 사용하고, 운영 서버에서는 실제 서비스용 S3를 사용한다면 각 환경에서 사용하는 URL이 모두 다르기 때문에 이를 enum보다는 properties + profile로 관리해야 한다고 생각했습니다

2023-12-04 06:05 UTC, apptie commented on backend/ddang/src/main/resources/application-image-local-upload.yml
> +    profile-image: "/users/images/"
그러네요 요 부분은 말씀해주신대로 upload 말고 다른 네이밍으로 바꾸는게 낫겠네요

2023-12-04 06:21 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/authentication/application/AuthenticationService.java
> +                              .build();
> 회원 가입 시에 초기 이름을 부여하는 로직은 service에 있는데, 탈퇴하고 다시 랜덤 이름이 지어지는 곳은 User도메인인 점이 헷갈립니다.

탈퇴하고 랜덤 이름을 만드는 로직이 있는지를 몰랐네요 
이 부분도 UUID를 내부적으로 직접 사용하면 테스트 시 불편함이 생길 수 있기 때문에 외부로 분리하는게 나을 것 같습니다 

>  굳이 따지자면 도메인 로직이 아닐까 싶긴 한데

이름을 부여하는 로직은 도메인 로직이라는 부분에 대해서는 동의합니다 
그래서 이름을 부여하는 로직이 service에서 호출되기는 하지만 UserNameGenerator 인터페이스와 그 구현체 RandomUuidUserNameGenerator 패키지는 도메인에 위치할 수 있도록 했습니다 

> 그리고 UserNameGenerator라는 이름을 봤을 때 처음 보는 사람 입장에서는 회원가입 시 최초 이름 만드는 generator인지 탈퇴 시 랜덤 이름 만드는 generator인지 모르겠어서 이름을 좀 더 명확하게 바꾸면 좋을 것 같습니다.

이 부분은 탈퇴 시 이름을 변경하는 로직이 User 도메인에 있는지 인지하지 못해서 발생한 이슈인 것 같습니다
그리고 사실 어떤 시점에 이름을 만드는 것이 중요한 것이 아니라 이름을 어떻게 생성하는지가 더 중요하다고 생각합니다 
그래서 탈퇴 시 로직을 User 도메인에서 분리하게 된다면 자연스럽게 해소될 것 같습니다

2023-12-04 06:21 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
> +    private Image thumbnailImage;
굳

2023-12-04 06:25 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/domain/repository/AuctionRepository.java
> +    Auction getPureAuctionByIdOrThrow(final Long id);
해당 부분은 예외 코드를 적용할 것을 베이스로 깔고 가기는 했습니다

처음부터 서버에서 직접 사용자에게 안내하기 위한 예외 문구를 구체적으로 내려주는 것이 잘못된 선택이지 않았나 싶네요 
아무튼 결론은 엔초가 말씀해주신 의견에 동의합니다

2023-12-04 06:26 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/response/ReadMultipleAuctionDto.java
> +    public record AuctionInfoDto(
굳
안에 다 때려박으니 좀 줄기는 하더라고요 
좀 나아진듯 싶습니다

2023-12-04 06:28 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/response/ReadMultipleAuctionDto.java
> +    ) {
저거를 판매자 정보 DTO / 경매 DTO처럼 별도의 DTO로 빼서 묶을까 싶었는데 너무 귀찮더라고요
그래서 일단 패스했습니다

2023-12-04 06:29 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/dto/MultipleChatRoomInfoDto.java
>          Long unreadMessageCount
일단 `List<DTO>` 형태로 반환되는 경우와 DTO 형태로 반환되는 경우를 구분하기 위해서 Multiple이라고 붙였습니다

2023-12-04 06:37 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/configuration/WebConfiguration.java
> +    public Module module() {
다음과 같습니다

1. `@JsonFormat`이 너무 중복되고 코드가 길어지는 현상 방지
2. 날짜와 관련된 경우 무조건 `@JsonFormat`으로 형태를 변경하기 때문에 이를 누락하는 현상 방지
3. 날짜 표시 방식이 변경될 경우 중앙 집중형으로 관리하기 위함

2023-12-04 06:42 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/image/application/ImageService.java
요 부분은 제 개인적인 판단으로 인해 넣은 것이고 실제 프로젝트에 적용할 경우 제외해도 될 것 같습니다

이렇게 한 이유는 경매는 무조건 이미지를 첨부해야 하기 때문에 이미지 조회 시 그 값이 없다면 DB 데이터 정합성 이슈가 발생했거나 이미지를 저장한 공간에서 해당 이미지 파일이 삭제되거나 변조되었다는 상황이라고 판단해서 차라리 예외가 발생하는 편이 이를 추적하기 더 좋다고 판단했기 때문입니다

2023-12-05 06:46 UTC, kwonyj1022 approved these changes

2023-12-06 12:45 UTC, JJ503 requested changes
늦어진 PR 리뷰 죄송합니다..! 🙇‍♀️
궁금한 점들이 있어 몇 가지 질문 코멘트로 남겨보았습니다.
저도 엔초와 동일하게 질문에 대한 답변들을 확인하고 싶어 rc로 두도록 하겠습니다.

그리고 커밋 수와 files changed를 통해 지토가 얼마나 열심히 고민하셨는지가 여실히 느껴지네요..!
네이밍 항상 못한다고 하셨지만, 이제 너무 잘하시는 거 아닌가요..?!
앞으로 네이밍 관련 변명은 통하지 않는 것으로 알겠습니다 ㅎㅎ
고생 많으셨습니다!!

2023-12-06 12:45 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +        final Category subCategory = categoryRepository.getSubCategoryByIdOrThrow(dto.subCategoryId());
### 질문
해당 방식으로 진행하게 된 이유가 궁금합니다!
물론 지금까지 예외 메시지로 인해 코드가 길어진다는 점이 마음에 쓰이긴 했지만, 저희의 컨벤션이 `같은 내용의 예외 메시지라도 다른 예외 메시지다`라는 규칙이 있었던 것으로 기억합니다.
그래서 해당 규칙에는 좀 반하는 수정 사항이 아닌가 하는 의문이 있습니다.

그리고 옛날에 예외와 관련된 회의를 진행할 때 예외를 서비스에 둔 이유는 도메인에서 자세한 예외 메시지가 드러나는 것이 적절하지 않기 때문이었던 것으로 기억합니다.
그런데 Rpository 클래스에서는 예외를 알고 있어도 이상하지 않은 것일까요?
또한, `Throw`라는 메서드 네이밍을 통해서 어떤 예외가 발생활지 예상하기란 어렵지 않은가 라는 의문이 있습니다.

### 선택
메서드 네이밍은 `getByIdOrThrow`보다 `findByIdOrThrow`가 더 적절하지 않을까 라는 생각이 있습니다.

2023-12-06 12:45 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/request/CreateAuctionDto.java
> -            // TODO 3차 데모데이 이후 리펙토링 예정
### 칭찬
해당 주석이 드디어 없어졌군요! 굿굿~

2023-12-06 12:45 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/request/CreateAuctionDto.java
### 칭찬
`application` 패키지에서도 `request`와 `response`로 나눠지니 더 보기 편해졌네요!

2023-12-06 12:45 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/response/ReadFullDirectRegionDto.java
> +    }
### 질문
테스트를 신경 쓰지 않았을 때 inner class는 private인 게 적절한 것이 아닌지 궁금합니다!
어떻게 보면 테스트를 위해 접근 제어자를 public으로 둔 것이 아닌 지에 대한 의문이 있어서요.

물론.. private으로 두었을 때 어떻게 테스트할 수 있을지는 잘 모르겠네요...
그래서 그냥 의문인 상태로만 질문 드립니다..!

2023-12-06 12:45 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/response/ReadMultipleAuctionDto.java
> +public record ReadMultipleAuctionDto(List<AuctionInfoDto> auctionInfoDtos, boolean isLast) {
### 칭찬
`s`로 구분하려면 잘 안 보이고 선언할 때 자꾸 다른 거 선언해 와서 귀찮았는데, 명확히 구분되니 좋네요!

2023-12-06 12:45 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/response/ReadSingleAuctionDto.java
> +                auction.findLastBid().map(lastBid -> lastBid.getPrice().getValue()).orElse(null),
### 칭찬
옹 깔끔해졌네요! 👍

2023-12-06 12:45 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
> +    }
### 질문
`find`와 `get`으로 시작하는 메서드의 차이는 무엇일까요?

2023-12-06 12:45 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/domain/repository/AuctionRepository.java
> +    Auction getPureAuctionByIdOrThrow(final Long id);
저도 예외 처리 방식을 변경하는 것은 좋습니다.
다만, 다른 파트에 의견을 남겨둔 대로 기존의 예외 처리 방식에 대한 저희의 방식을 다시 논의해 보면 좋을 것 같다는 생각을 했습니다.
그리고 예외 코드를 사용하는 방식에 대해선 저도 동의합니다!

2023-12-06 12:45 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/authentication/application/AuthenticationService.java
> +                              .build();
### 질문
탈퇴 시 이름 변경의 경우 당시 두 방식 중 UUID에 대한 처리를 도메인 내부에서 하는 게 더 적절하다는 모두의 의견이 있었습니다. 또한, UUID에 대한 테스트의 불편함이 무엇일지도 의문입니다. 변경되었는지만 확인해도 충분하지 않나요?
당시와 현재의 의견이 바뀐 이유가 궁금합니다!

![image](https://github.com/woowacourse-teams/2023-3-ddang/assets/63184334/f42bea94-44eb-4070-85d0-0a871c715111)

2023-12-06 12:45 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/dto/MultipleChatRoomInfoDto.java
>          Long unreadMessageCount
### 질문
해당 DTO만 봤을 땐 List로 사용될지 여부는 알 수 없지 않나요? Single로 사용될 일이 생길 수도 있고요.
그래서 List로 묶일 운명인지에 대해서는 해당 DTO에서 알 필요는 없다고 생각하기에 저도 Single이 적절하다고 생각하는데 어떻게 생각하시나요?
무조건 List를 바랐더라면 Multi라는 네이밍의 List<DTO>로 다시 묶어주는 게 적절하다고 생각합니다.
또한, 다른 것들과의 규칙이 달라 장기적으로 봤을 때 헷갈리 수 있고, 네이밍만 봤을 때 구분하기 어려울 것이라는 생각이 듭니다.

2023-12-06 12:45 UTC, JJ503 commented on backend/ddang/src/main/resources/application-image-local-upload.yml
> +    profile-image: "/users/images/"
### 질문
이미지 url에 대한 설정을 `application-local.yml`과 분리한 이유가 궁금합니다!

2023-12-06 12:45 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
> +        );
### 질문
이미지 URL에 대해 DTO가 아닌 외부에서 주입받았을 때의 장점은 무엇일까요?

2023-12-07 03:12 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
> +        final Category subCategory = categoryRepository.getSubCategoryByIdOrThrow(dto.subCategoryId());
일단 이 부분은 해당 PR의 내용에 포함되지 않은 부분임을 먼저 말씀드립니다
그래서 PR 내용에서 제외했었는데 그냥 명확하게 적을걸 그랬네요
다음 내용은 팀 컨벤션과는 논외로 제 생각임을 밝힙니다

> 같은 내용의 예외 메시지라도 다른 예외 메시지다라는 규칙

같은 예외라면 예외 메세지도 동일해야 한다고 생각했습니다
같은 예외인데 예외 메세지가 다르다면 이는 예외가 해당 비즈니스 로직 문맥에서 다른 의미를 갖게 된다고 생각하고 이는 하나의 예외가 너무 다양한 환경에서 사용된다고 생각했습니다
이는 예외 처리 시 다른 HTTP Status Code를 내려줘야함에도 불구하고 의미가 다소 맞지 않는 값을 내려줄 수 있다고 생각합니다 

RegionNotFoundException을 예시로 들어보면
첫 번째 모든 지역(시)를 조회하는 readAllFirst()에서는 "등록된 지역이 없습니다."라는 예외 메세지를 사용하고 두 번째, 세 번째는 "지정한 첫 번째 지역에 해당하는 두 번째 지역이 없습니다.", "지정한 첫 번째와 두 번째 지역에 해당하는 세 번째 지역이 없습니다."라는 예외 메세지를 출력합니다
이 때 두 번째나 세 번째의 경우 클라이언트에게 조건을 전달받기 때문에 이 조건이 잘못될 경우도 있기 때문에 지금 400을 내려주는 상태가 적합하다고 볼 수 있습니다
그러나 readAllFirst()는 아무런 조건을 전달받지 않고 있습니다
조건이 없는데도 불구하고 Repository에서 요소를 찾지 못한다면 예외를 발생하고 있고, 이 경우는 애플리케이션 첫 실행 시 DB에 지역을 초기화하지 않았음을 의미합니다
이 경우 클라이언트 책임이 아닌 서버의 책임이라고 생각합니다 
그러나 동일한 예외를 발생시키고 있기 때문에 이 경우에도 400이 발생합니다
이런 경우는 잘못되었다고 생각해서 이렇게 변경했습니다

> Repository 클래스에서는 예외를 알고 있어도 이상하지 않은 것일까요?

Repository 클래스에서 알고 있는 것은 상관 없다고 생각합니다
그리고 이 부분은 persistence layer로 도메인과는 별도의 영역에 존재하기 때문에 `도메인에서 자세한 예외 메시지가 드러나는 것이 적절하지 않기 때문`과는 관련이 없다고 생각합니다
또한 도메인에서 예외는 발생할 수 있다고 생각합니다
도메인에서 예외 메세지를 명시하지는 않지만 예외 자체는 발생할 수 있다고 생각합니다

> Throw라는 메서드 네이밍을 통해서 어떤 예외가 발생활지 예상하기란 어렵지 않은가 라는 의문이 있습니다.

어떤 예외가 발생할지 구체적으로 알 필요는 없다고 생각합니다
Repository.getOrThrow()를 통해서 레포지토리에서 값을 찾을 때, 있으면 꺼내오고 없으면 예외가 발생하겠구나 정도로 이해하기만 해도 된다고 생각합니다 
그리고 이 부분은 Service Layer에서 예외가 발생하는 경우도 동일하다고 생각합니다
AuctionService.create()에서는 지역이 없는 경우 RegionNotFoundException이 발생하는데 이는 메서드 이름만 보고서는 특정한 예외가 발생하는지 알 수 없습니다
그에 비해 예시로 나온 CategoryRepository.getSubCategoryByIdOrThrow()의 경우 id 기반으로 찾고 찾지 못한 경우 예외가 발생할 것을 명확히 드러내고 있다고 생각해서 해주신 말씀은 이 경우에는 어울리지 않다고 생각합니다

> 메서드 네이밍은 getByIdOrThrow보다 findByIdOrThrow가 더 적절하지 않을까 라는 생각이 있습니다.

find는 값을 꺼낼 때 값이 없어도 예외가 발생하지 않겠다는 의미를 가지고 있습니다
그래서 Optional로 반환하는 경우가 대부분입니다
get은 값을 꺼낼 때 값이 없으면 예외가 발생하겠다는 의미를 가지고 있습니다
그래서 findByIdOrThrow의 경우 두 의미가 상충되므로 좋지 않은 네이밍이라고 생각합니다
그래서 getOrThrow와 같은 네이밍이 일반적이라고 볼 수 있습니다

https://grep.app/search?q=getOrThrow&filter[lang][0]=Java&filter[lang][1]=Kotlin
실제로 코틀린에서는 getOrThrow라는 네이밍을 많이 사용하고
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes
스프링 JPA 쪽에서도 값을 꺼낼 때 값이 없을 시 예외가 발생해야 하는 경우에는 getXyzById와 같은 방식으로 사용하고 있음을 확인할 수 있습니다
JpaRepository에서도 값을 찾을 때 없다면 예외가 발생하는 getReference() 메서드가 존재하기도 합니다

2023-12-07 03:13 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/request/CreateAuctionDto.java
> -            // TODO 3차 데모데이 이후 리펙토링 예정
굳

2023-12-07 03:14 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/request/CreateAuctionDto.java
굳

2023-12-07 03:15 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/response/ReadFullDirectRegionDto.java
> +    }
테스트를 제외하면 private로 둘 것 같고 이 경우 리플렉션을 사용해서 직접 만들어줄 수 있을 것 같습니다
그럴 바에는 그냥 public으로 여는게 맞다고 생각하는 편이기는 합니다

2023-12-07 03:15 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/response/ReadMultipleAuctionDto.java
> +public record ReadMultipleAuctionDto(List<AuctionInfoDto> auctionInfoDtos, boolean isLast) {
굳

2023-12-07 03:15 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/response/ReadSingleAuctionDto.java
> +                auction.findLastBid().map(lastBid -> lastBid.getPrice().getValue()).orElse(null),
굳

2023-12-07 03:17 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
> +    }
위에 첫 번째 코멘트를 참고해주세요

2023-12-07 03:19 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
> +        );
1. URL과 같은 부분은 변환해주는 책임은 DTO에서 수행하는 내용이 아닌 컨트롤러에서 수행해야 하는 책임이라고 생각합니다
2. 특정 이슈로 인해서 URL 변환 로직이 변경될 경우 모든 DTO에서 수정 사항이 생길 수 있는 로직을 컨트롤러에 집중시킬 수 있습니다

2023-12-07 03:22 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/authentication/application/AuthenticationService.java
> +                              .build();
UUID로 하는 건 여전히 동일합니다
UUID를 호출하는 행위를 외부로 옮겼을 뿐입니다
그러므로 withdrawal()에서 여전히 UUID 값으로 이름을 변경하는 로직은 변경되지 않았다고 생각합니다

지금은 UUID로 랜덤 값으로 변경하고 있을 뿐이지만 추후 의도한 포맷으로 변경해야 하는 경우와 같이 정확한 값을 테스트 해야 하는 경우에 지금 상태는 테스트하기 어렵다고 생각합니다 
즉 지금 상태는 UUID에 종속적이기 때문에 확장에 닫혀있고 UUID에 도메인 로직이 의존적이라고 생각합니다

추가적으로 이렇게 바꾼 이유는 당시 리뷰할 때 정신이 없어서 별 생각이 없어서 놓쳤다고 생각하기 때문입니다

2023-12-07 03:28 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/dto/MultipleChatRoomInfoDto.java
>          Long unreadMessageCount
> 해당 DTO만 봤을 땐 List로 사용될지 여부는 알 수 없지 않나요?

지금 상태는 Multiple이 붙은 것들만 List로 사용하고 있습니다
Multiple이라는 네이밍이 붙었다면 List로 반환할 수 있는 상황이라고 봐주시면 될 것 같습니다

>  Single로 사용될 일이 생길 수도 있고요.

저는 이런 일이 일어나서는 안 된다고 생각합니다
DTO의 경우 클라이언트에게 전달하는 역할을 수행하고 있기 때문에 그 특징상 빈번하게 변경된다고 생각합니다
이 때 DTO를 재활용하게 된다면 다른 메서드이기 때문에 다른 라이프 사이클을 가지고 있음에도 불구하고 여러 메서드에 의해 영향을 받아 문제가 생길 수 있다고 생각합니다
DTO의 결합도가 높다고 볼 수 있겠네요
이와 관련해서는 가짜중복 진짜중복 관련 키워드로 구글링해보시면 알 수 있을 것 같네요 

> List로 묶일 운명인지에 대해서는 해당 DTO에서 알 필요는 없다고 생각하기에 저도 Single이 적절하다고 생각하는데 어떻게 생각하시나요?

위와 같은 이유로 반대합니다 

> 무조건 List를 바랐더라면 Multi라는 네이밍의 List로 다시 묶어주는 게 적절하다고 생각합니다.

이건 동의합니다
안드로이드 분들의 의견으로 감싼 것을 풀었을 뿐이지 묶는게 맞다고 봅니다 
묶으면 확실히 자연스러워지겠지만 귀찮기도 하고 이 부분은 안드로이드 분들의 동의도 필요한 부분이라 일단 방치했습니다 

> 또한, 다른 것들과의 규칙이 달라 장기적으로 봤을 때 헷갈리 수 있고, 네이밍만 봤을 때 구분하기 어려울 것이라는 생각이 듭니다.

이전 네이밍과는 맞지 않지만 제가 수정한 상황에서는 Multiple은 컬렉션으로 반환되는 상황에만 붙이기 때문에 규칙이 다르다고 생각하지 않습니다
네이밍만 봤을 때에도 Multiple이 붙어 있다면 이건 아무튼 여러 개 반환되는 DTO라는걸 알 수 있기 때문에 더 명확하다고 생각합니다

2023-12-07 03:31 UTC, apptie commented on backend/ddang/src/main/resources/application-image-local-upload.yml
> +    profile-image: "/users/images/"
이미지 저장소를 외부 저장소를 사용하게 된다면 아예 조회하는 URL이 변경되는 상황입니다
저희 프로젝트를 기준으로 생각한다면 cloudfront로 인한 그 복잡한 문자열이 url이 되는 상황입니다

이 경우 기존 코드라면 enum에 하나씩 추가해줘야겠지만 그렇게 하는 경우 실행 환경에 따라 어떤 이미지 저장소를 사용할지 지정할 수 없다는 문제가 생깁니다
S3에 연결했지만 테스트(로컬에 저장), 로컬(로컬에 저장), 개발 서버(운영용 S3가 아닌 테스트용 S3), 운영 서버(운영용 S3)과 같이 각기 다른 이미지 저장소를 가지고 동작할 수 있어야 한다고 생각하며 이는 실행 시 스프링 Profile로 구분해야 한다고 생각합니다

그래서 저렇게 했습니다

2023-12-07 07:39 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/authentication/application/AuthenticationService.java
> +                              .build();
아무래도 제가 저걸 작성했을 때 잘못 작성한 것 같네요..!
2번이 UUID를 외부에서 주입받는 방식으로, 현재 지토가 하는 방식과 비슷했을 것으로 생각합니다.
그런데 그 부분이 제대로 전달이 안 된 듯싶네요!
저도 현재처럼 바뀌는 부분 찬성합니다! (그냥 궁금해서 여쭤봤어요 ㅎㅎ)

2023-12-07 07:47 UTC, JJ503 commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/dto/MultipleChatRoomInfoDto.java
>          Long unreadMessageCount
Single인 상황이 아예 발생하지 않길 원한다면, 네이밍을 변경하는 것이 가장 적절할 것으로 보입니다. (안드로이드 측과의 API 규칙도 있기에)

네이밍만 봤을 때 헷갈릴 것 같다는 이야기는 Multiple이라는 네이밍에 해당하는 방식이 두 가지이기 때문입니다.
1. List<>의 값을 같은 dto
2. List<>로 사용해야 하는 dto

위 두 가지 방식을 네이밍으로만 판단하기란 어려울 것이라 생각이 들며, 계속해 혼돈을 줄 것 같다는 생각이 듭니다.
하지만 이 부분은 개인적인 의견으로, 나머지 분들은 다 괜찮다고 생각하시면 따르도록 하겠습니다!

2023-12-07 08:00 UTC, JJ503 commented on backend/ddang/src/main/resources/application-image-local-upload.yml
> +    profile-image: "/users/images/"
해당 설정의 경우 모든 Profile에서 사용하게 되는 것일까요?

2023-12-08 06:44 UTC, JJ503 approved these changes
질문에 대한 답변들 감사합니다!
충분히 이해가 되어 approve로 수정합니다.
다만, 아직 완벽히 이해가 가지 않은 부분이 두 가지가 있어 해당 부분만 확인해주시면 감사하겠습니다!
([1번](https://github.com/woowacourse-teams/2023-3-ddang/pull/762#discussion_r1418513407), [2번](https://github.com/woowacourse-teams/2023-3-ddang/pull/762#discussion_r1418527001))

2023-12-09 03:04 UTC, apptie commented on backend/ddang/src/main/java/com/ddang/ddang/chat/domain/dto/MultipleChatRoomInfoDto.java
>          Long unreadMessageCount
> List<>의 값을 같은 dto

이건 DTO 내부적으로 List를 가지고 있는 상황을 말씀하신건가요?

아무튼 저는 `List<DTO>`를 그대로 반환하든 저 컬렉션을 감싼 별도의 DTO로 분리하든 특정 도메인에 대한 목록을 조회하는 것이기 때문에 Multiple이라는 네이밍만으로 충분히 구분이 가능하다고 생각합니다
이 형태가 어쨌든 유지보수할때에는 필요한 응답 값들이 바뀔 때 변경해야 하는 경우는 형태에 상관 없이 목록 조회에 사용되는 DTO(Multiple 네이밍이 들어간) 필드를 바꾸면 된다고 생각합니다

오히려 `List<DTO>`를 반환하는 경우와 `List<DTO>`를 감싸서 반환하는 경우를 각각의 네이밍으로 분리하는 경우가 추후 더 헷갈릴 수 있다고 생각합니다

사실 이건 응답 값을 주는 경우가 두 경우 모두 섞여서 그런 것 같습니다 
응답 방식을 하나로 통일했다면 될텐데 이건 안드로이드 분들과의 협의가 필요하니 어쩔 수가 없네요 

> 나머지 분들은 다 괜찮다고 생각하시면 따르도록 하겠습니다!

어처피 해당 PR은 적용은 안될 것 같기 때문에 요 부분은 뭐...그렇습니다

2023-12-09 03:11 UTC, apptie commented on backend/ddang/src/main/resources/application-image-local-upload.yml
> +    profile-image: "/users/images/"
테스트(로컬에 저장), 로컬(로컬에 저장), 개발 서버(운영용 S3가 아닌 테스트용 S3), 운영 서버(운영용 S3)라고 했을 경우

application-image-local-upload.yml : 이미지를 로컬에 저장하는 경우
application-image-dev-s3-upload.yml : 이미지를 개발 서버(테스트 용도) S3에 저장하는 경우
application-image-prod-s3-upload-yml : 이미지를 운영 서버 S3에 저장하는 경우

Profile 별 
test : application-image-local-upload.yml
local : application-image-local-upload.yml
dev : application-image-dev-s3-upload.yml
prod : application-image-prod-s3-upload-yml

> 그래서 application-local.yml와의 구분이 필요하다는 의미가 맞을까요?

이 부분은 이해를 못했습니다

2023-12-09 18:16 UTC, closed without merging